import Link from "next/link";
import { AdminPage, Panel, buttonClass, inputClass, secondaryButtonClass } from "@/components/admin/admin-ui";
import { requirePermission } from "@/domain/auth/session";
import { createManualQuotation } from "@/domain/quotations/actions";

export default async function NewManualQuotation() {
  await requirePermission("quotations.manage");
  return <AdminPage title="Create manual quotation" description="Capture an assisted, email or offline request. Saving creates a tracked draft for review—it does not bypass approval." actions={<Link className={secondaryButtonClass} href="/admin/quotations">Cancel</Link>}>
    <form action={createManualQuotation} className="space-y-4">
      <Panel title="Customer and validity"><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Contact name<input className={`${inputClass} mt-1 w-full`} name="contactName" required/></label><label className="text-sm font-semibold">Email<input className={`${inputClass} mt-1 w-full`} name="email" type="email" required/></label><label className="text-sm font-semibold">Company<input className={`${inputClass} mt-1 w-full`} name="companyName"/></label><label className="text-sm font-semibold">Phone<input className={`${inputClass} mt-1 w-full`} name="phone"/></label><label className="text-sm font-semibold">VAT number<input className={`${inputClass} mt-1 w-full`} name="vatNumber"/></label><label className="text-sm font-semibold">Valid for days<input className={`${inputClass} mt-1 w-full`} name="validDays" type="number" min="1" max="90" defaultValue="7" required/></label><label className="text-sm font-semibold sm:col-span-2">Requirements or customer notes<textarea className={`${inputClass} mt-1 min-h-20 w-full`} name="requirements"/></label></div></Panel>
      <Panel title="Quotation lines" description="Enter customer unit prices including VAT. Tick taxable where the price contains 15% VAT."><div className="space-y-3">{Array.from({length:8},(_,index)=><div className="grid gap-2 border-b border-slate-200 pb-3 sm:grid-cols-[2fr_1fr_90px_130px_100px]" key={index}><input aria-label={`Line ${index+1} description`} className={inputClass} name={`item_${index}_name`} placeholder={`Line ${index+1} description`}/><input aria-label={`Line ${index+1} SKU`} className={inputClass} name={`item_${index}_sku`} placeholder="SKU/reference"/><input aria-label={`Line ${index+1} quantity`} className={inputClass} name={`item_${index}_quantity`} type="number" min="1" defaultValue={index===0?"1":undefined} placeholder="Qty"/><input aria-label={`Line ${index+1} unit price including VAT`} className={inputClass} name={`item_${index}_price`} type="number" min="0.01" step="0.01" placeholder="Unit price"/><label className="flex min-h-10 items-center gap-2 text-sm"><input name={`item_${index}_taxable`} type="checkbox" defaultChecked/>15% VAT</label></div>)}</div></Panel>
      <div className="sticky bottom-0 flex items-center justify-between gap-3 border border-slate-300 bg-white p-4 shadow-lg"><p className="text-sm text-slate-600">The quotation is saved as <strong>Manual · Pending approval</strong>.</p><button className={buttonClass}>Save manual quotation</button></div>
    </form>
  </AdminPage>;
}
