import Link from "next/link";
import { Cpu, Plus, Trophy } from "lucide-react";
import { requireUser } from "@/domain/auth/session";
import { prisma } from "@/lib/prisma";
import { formatZar } from "@/lib/money";

export default async function PcProjectsPage(){
  const ctx=await requireUser(),projects=await prisma.pcProject.findMany({where:{userId:ctx.user.id},include:{items:true},orderBy:{updatedAt:"desc"}});
  return <main className="mx-auto max-w-6xl px-4 py-8 sm:px-6 sm:py-12"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-sky-700">Your machines</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">My PC Projects</h1><p className="mt-2 text-slate-600">Design the dream, then secure it component by component.</p></div><Link href="/build-a-pc" className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-sky-700 px-5 font-bold text-white"><Plus className="size-4"/>Start new project</Link></div>{projects.length?<div className="mt-8 grid gap-5 md:grid-cols-2">{projects.map(project=>{const total=project.items.reduce((sum,item)=>sum+Number(item.configuredPrice),0),purchased=project.items.filter(item=>item.purchasedAt).reduce((sum,item)=>sum+Number(item.purchasedPrice??item.configuredPrice),0),progress=total?Math.round(purchased/total*100):0,configured=["cpu","motherboard","memory","storage","power","case"].filter(key=>project.items.some(item=>item.stepKey===key)).length;return <Link href={`/account/pc-projects/${project.id}`} className="group overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-0.5 hover:shadow-lg" key={project.id}><div className="flex items-start justify-between bg-[#071b33] p-5 text-white"><div><p className="text-[10px] font-bold uppercase tracking-widest text-sky-300">{project.status.replaceAll('_',' ')}</p><h2 className="mt-2 text-2xl font-black">{project.name}</h2></div>{project.status==='COMPLETE'?<Trophy className="size-8 text-amber-300"/>:<Cpu className="size-8 text-sky-300"/>}</div><div className="p-5"><div className="grid grid-cols-2 gap-4 text-sm"><div><p className="text-slate-500">Configuration</p><strong>{Math.round(configured/6*100)}%</strong></div><div><p className="text-slate-500">Purchased</p><strong>{progress}%</strong></div><div><p className="text-slate-500">Build value</p><strong>{formatZar(total)}</strong></div><div><p className="text-slate-500">Components</p><strong>{project.items.filter(item=>item.purchasedAt).length} / {project.items.length}</strong></div></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-emerald-500" style={{width:`${progress}%`}}/></div><p className="mt-4 font-bold text-sky-700">Continue project →</p></div></Link>})}</div>:<div className="mt-10 rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-center"><Cpu className="mx-auto size-12 text-slate-300"/><h2 className="mt-4 text-xl font-bold">Your first machine starts here</h2><p className="mt-2 text-slate-500">Name it, configure it and return whenever you are ready.</p></div>}</main>;
}
