import Link from "next/link";
import { ArrowLeft, Gamepad2, ShoppingCart, UserRound, Wrench } from "lucide-react";
import { BrandLogo } from "@/components/brand-logo";
import { getAuthContext } from "@/domain/auth/session";
import { getCurrentCart } from "@/domain/cart/service";

export async function GamingHeader(){
  const auth=await getAuthContext();let cartCount=0;
  try{const cart=await getCurrentCart();cartCount=cart?cart.items.reduce((sum,item)=>sum+item.quantity,0)+cart.supplierItems.reduce((sum,item)=>sum+item.quantity,0):0}catch{}
  return <header className="sticky top-0 z-50 border-b border-violet-500/20 bg-[#050713]/95 text-white backdrop-blur-xl"><div className="mx-auto flex min-h-16 max-w-7xl items-center gap-3 px-3 sm:px-6 lg:px-8"><Link href="/" className="inline-flex min-h-10 shrink-0 items-center gap-2 rounded-xl border border-slate-700 px-3 text-sm font-bold text-slate-200 hover:border-violet-400"><ArrowLeft className="size-4"/><span className="hidden sm:inline">Back to home</span><span className="sm:hidden">Exit</span></Link><div className="flex min-w-0 flex-1 items-center justify-center gap-3"><BrandLogo variant="footer" priority className="w-28 sm:w-36"/><span className="hidden h-7 border-l border-slate-700 md:block"/><span className="hidden items-center gap-2 text-xs font-black uppercase tracking-[.2em] text-violet-300 md:flex"><Gamepad2 className="size-4"/>Gaming</span></div><nav className="flex shrink-0 items-center gap-1"><Link href="/build-a-pc" aria-label="Build a PC" className="hidden min-h-10 items-center gap-2 rounded-xl px-3 text-sm font-bold text-cyan-300 hover:bg-white/5 sm:flex"><Wrench className="size-4"/><span className="hidden lg:inline">Build a PC</span></Link><Link href={auth?"/account":"/sign-in"} aria-label={auth?"Account":"Sign in"} className="grid size-10 place-items-center rounded-xl text-slate-300 hover:bg-white/5"><UserRound className="size-5"/></Link><Link href={auth?"/cart":"/sign-in"} aria-label={`Cart with ${cartCount} items`} className="relative grid size-10 place-items-center rounded-xl bg-violet-500"><ShoppingCart className="size-5"/>{cartCount?<span className="absolute -right-1 -top-1 grid size-5 place-items-center rounded-full bg-cyan-400 text-[10px] font-black text-slate-950">{cartCount>9?"9+":cartCount}</span>:null}</Link></nav></div></header>;
}
