"use client";
import { Menu, X } from "lucide-react";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";

export function MobileMenu({categories,signedIn}:{categories:string[];signedIn:boolean}) {
  const [open,setOpen]=useState(false); const closeButton=useRef<HTMLButtonElement>(null);
  useEffect(()=>{if(!open)return;const previous=document.body.style.overflow;document.body.style.overflow="hidden";closeButton.current?.focus();const escape=(event:KeyboardEvent)=>{if(event.key==="Escape")setOpen(false)};window.addEventListener("keydown",escape);return()=>{document.body.style.overflow=previous;window.removeEventListener("keydown",escape)}},[open]);
  const item="block min-h-12 rounded-lg px-4 py-3 text-sm font-semibold text-slate-700 hover:bg-slate-50 focus:bg-slate-50";
  return <><button aria-expanded={open} aria-controls="mobile-store-menu" aria-label="Open menu" onClick={()=>setOpen(true)} className="grid size-11 shrink-0 place-items-center rounded-lg border border-slate-300 text-slate-700 lg:hidden"><Menu className="size-5"/></button>{open?<div className="fixed inset-0 z-[100] lg:hidden"><button aria-label="Close menu" className="absolute inset-0 h-full w-full bg-slate-950/55 backdrop-blur-[2px]" onClick={()=>setOpen(false)}/><aside id="mobile-store-menu" role="dialog" aria-modal="true" aria-label="Navigation menu" className="absolute inset-y-0 left-0 flex w-[min(88vw,22rem)] flex-col overflow-y-auto bg-white p-4 shadow-2xl"><div className="flex items-center justify-between border-b border-slate-200 pb-4"><strong className="text-lg text-[#071b33]">Browse Innozanzi</strong><button ref={closeButton} aria-label="Close menu" onClick={()=>setOpen(false)} className="grid size-11 place-items-center rounded-lg bg-slate-100"><X className="size-5"/></button></div><nav className="mt-4 space-y-1" onClick={event=>{if((event.target as HTMLElement).closest("a"))setOpen(false)}}><Link className="block min-h-12 rounded-lg bg-[#071b33] px-4 py-3 font-semibold text-white" href="/shop">All products</Link>{categories.map(category=><Link className={item} href={`/categories/${encodeURIComponent(category)}`} key={category}>{category}</Link>)}<Link className={item} href="/categories">More categories</Link><Link className={`${item}`} href="/gaming">Gaming</Link><Link className={`${item}`} href="/build-a-pc">Build a PC</Link><Link className={`${item}`} href="/blog">Insights</Link><Link className={item} href="/contact">Help</Link><div className="mt-3 border-t border-slate-200 pt-3">{signedIn?<Link className={item} href="/account">My account</Link>:<><Link className={item} href="/sign-in">Log in</Link><Link className="block min-h-12 rounded-lg bg-sky-700 px-4 py-3 text-sm font-bold text-white" href="/register">Create account</Link></>}</div></nav></aside></div>:null}</>;
}
