"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Check, CheckCircle2, Circle, Cpu, Gamepad2, PackagePlus, RotateCcw, Search, ShieldAlert, Sparkles, Wrench } from "lucide-react";
import { addPcBuildToCart } from "@/domain/cart/pc-build-action";
import type { PcBuilderProduct, PcBuildStep, PcBuildStepKey } from "@/domain/catalogue/pc-builder";
import { formatZar } from "@/lib/money";

type BuildType="PC_ONLY"|"COMPLETE_SETUP";
type Selections=Partial<Record<PcBuildStepKey,PcBuilderProduct>>;
const requiredKeys:PcBuildStepKey[]=["cpu","motherboard","memory","storage","power","case"];
const storageKey="innozanzi-pc-builder-v1";

const combined=(product:PcBuilderProduct)=>`${product.name} ${product.categoryPath} ${Object.entries(product.specifications).map(([key,value])=>`${key} ${value}`).join(" ")}`.toLowerCase();
const socket=(product?:PcBuilderProduct)=>product?combined(product).match(/\b(?:lga\s?\d{3,4}|am[45]|tr4|strx4)\b/i)?.[0]?.replace(/\s/g,"").toUpperCase():undefined;
const memoryType=(product?:PcBuilderProduct)=>product?combined(product).match(/\bddr[345]\b/i)?.[0]?.toUpperCase():undefined;

function compatibility(step:PcBuildStepKey,candidate:PcBuilderProduct,selections:Selections){
  if(step==="motherboard"&&selections.cpu){const a=socket(selections.cpu),b=socket(candidate);if(a&&b)return a===b?{kind:"ok",text:`CPU socket ${a} matches`}:{kind:"bad",text:`Requires ${b}; your CPU uses ${a}`};}
  if(step==="cpu"&&selections.motherboard){const a=socket(candidate),b=socket(selections.motherboard);if(a&&b)return a===b?{kind:"ok",text:`Motherboard socket ${b} matches`}:{kind:"bad",text:`Uses ${a}; motherboard requires ${b}`};}
  if(step==="memory"&&selections.motherboard){const a=memoryType(candidate),b=memoryType(selections.motherboard);if(a&&b)return a===b?{kind:"ok",text:`${a} matches motherboard`}:{kind:"bad",text:`This is ${a}; motherboard uses ${b}`};}
  if(step==="motherboard"&&selections.memory){const a=memoryType(candidate),b=memoryType(selections.memory);if(a&&b)return a===b?{kind:"ok",text:`${a} memory matches`}:{kind:"bad",text:`Board uses ${a}; selected memory is ${b}`};}
  if(step==="cooling"&&(selections.cpu||selections.motherboard)){const needed=socket(selections.cpu??selections.motherboard),text=combined(candidate);if(needed&&text.includes(needed.toLowerCase()))return{kind:"ok",text:`Lists ${needed} support`};}
  return{kind:"unknown",text:"Compatibility not confirmed by supplier data"};
}

export function PcBuilder({steps,error}:{steps:PcBuildStep[];error?:string}){
  const[buildType,setBuildType]=useState<BuildType|null>(null);const[current,setCurrent]=useState(0);const[selections,setSelections]=useState<Selections>({});const[search,setSearch]=useState("");const[brand,setBrand]=useState("");const[maxPrice,setMaxPrice]=useState("");const[ready,setReady]=useState(false);
  useEffect(()=>{queueMicrotask(()=>{try{const saved=JSON.parse(localStorage.getItem(storageKey)??"null");if(saved){setBuildType(saved.buildType??null);setSelections(saved.selections??{});setCurrent(saved.current??0)}}catch{}setReady(true)})},[]);
  useEffect(()=>{if(ready)localStorage.setItem(storageKey,JSON.stringify({buildType,selections,current}))},[buildType,selections,current,ready]);
  const activeSteps=useMemo(()=>steps.filter(step=>buildType==="COMPLETE_SETUP"||!step.setupOnly),[steps,buildType]);const step=activeSteps[current];
  const completedRequired=requiredKeys.filter(key=>selections[key]).length;const pcPercent=Math.round(completedRequired/requiredKeys.length*100);const total=Object.values(selections).reduce((sum,product)=>sum+Number(product?.price??0),0);const pcComplete=completedRequired===requiredKeys.length;
  const brands=useMemo(()=>step?[...new Set(step.products.map(product=>product.brand).filter((value):value is string=>Boolean(value)))].sort():[],[step]);
  const products=useMemo(()=>step?step.products.filter(product=>(!search||combined(product).includes(search.toLowerCase()))&&(!brand||product.brand===brand)&&(!maxPrice||Number(product.price)<=Number(maxPrice))):[],[step,search,brand,maxPrice]);
  const go=(index:number)=>{setCurrent(Math.max(0,Math.min(activeSteps.length-1,index)));setSearch("");setBrand("");setMaxPrice("");window.scrollTo({top:0,behavior:"smooth"})};
  const select=(product:PcBuilderProduct)=>{if(!step)return;setSelections(previous=>({...previous,[step.key]:product}));setTimeout(()=>{if(current<activeSteps.length-1)go(current+1)},380)};
  const reset=()=>{setBuildType(null);setSelections({});setCurrent(0);localStorage.removeItem(storageKey)};
  if(!ready)return <div className="grid min-h-[60vh] place-items-center bg-[#06172b] text-sky-200">Preparing your builder…</div>;

  if(!buildType)return <section className="relative overflow-hidden bg-[#06172b] text-white"><div className="absolute inset-0 opacity-30 [background-image:radial-gradient(circle_at_20%_20%,#0ea5e9_0,transparent_28%),radial-gradient(circle_at_80%_70%,#2563eb_0,transparent_25%)]"/><div className="relative mx-auto max-w-7xl px-4 py-16 sm:px-6 sm:py-24 lg:px-8"><div className="mx-auto max-w-3xl text-center"><span className="inline-flex items-center gap-2 rounded-full border border-sky-400/30 bg-sky-400/10 px-4 py-2 text-sm font-bold text-sky-200"><Sparkles className="size-4"/>Interactive PC Builder</span><h1 className="mt-6 text-4xl font-black tracking-tight sm:text-6xl">You’re about to build your own PC.</h1><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-slate-300">Choose real components from live distributor stock, watch your build take shape and check out as one complete order.</p></div><div className="mx-auto mt-12 grid max-w-5xl gap-5 md:grid-cols-2"><button onClick={()=>setBuildType("PC_ONLY")} className="group rounded-3xl border border-slate-700 bg-white/5 p-7 text-left transition hover:-translate-y-1 hover:border-sky-400 hover:bg-white/10"><span className="grid size-14 place-items-center rounded-2xl bg-sky-500 text-white transition group-hover:scale-105"><Cpu className="size-7"/></span><h2 className="mt-6 text-2xl font-bold">Build the PC</h2><p className="mt-2 leading-7 text-slate-300">Assemble the computer itself: processor, motherboard, memory, storage, power supply, case and optional performance parts.</p><span className="mt-6 inline-flex items-center gap-2 font-bold text-sky-300">Start PC build <ArrowRight className="size-4"/></span></button><button onClick={()=>setBuildType("COMPLETE_SETUP")} className="group rounded-3xl border border-slate-700 bg-white/5 p-7 text-left transition hover:-translate-y-1 hover:border-violet-400 hover:bg-white/10"><span className="grid size-14 place-items-center rounded-2xl bg-violet-500 text-white transition group-hover:scale-105"><Gamepad2 className="size-7"/></span><h2 className="mt-6 text-2xl font-bold">Build a complete setup</h2><p className="mt-2 leading-7 text-slate-300">Build the PC, then finish your desk with a monitor, keyboard, mouse and audio products.</p><span className="mt-6 inline-flex items-center gap-2 font-bold text-violet-300">Build everything <ArrowRight className="size-4"/></span></button></div><div className="mt-10 text-center"><Link className="text-sm text-slate-400 underline hover:text-white" href="/shop?category=Computers">Prefer a ready-built computer?</Link></div></div></section>;

  if(!step)return null;
  return <div className="min-h-screen bg-slate-100">
    <header className="sticky top-0 z-30 border-b border-slate-800 bg-[#06172b] text-white shadow-xl"><div className="mx-auto max-w-[1500px] px-4 py-4 sm:px-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-sky-300">Your custom PC</p><p className="mt-1 font-bold">{pcPercent}% complete · {formatZar(total)}</p></div><div className="min-w-[220px] flex-1 sm:max-w-xl"><div className="h-2 overflow-hidden rounded-full bg-slate-700"><div className="h-full rounded-full bg-gradient-to-r from-sky-400 to-emerald-400 transition-all duration-500" style={{width:`${pcPercent}%`}}/></div></div><button className="inline-flex items-center gap-2 text-sm text-slate-300 hover:text-white" onClick={reset}><RotateCcw className="size-4"/>Start over</button></div></div></header>
    {error?<div className="mx-auto max-w-[1500px] px-4 pt-5 sm:px-6"><p className="rounded-xl bg-red-50 p-4 text-red-800">One of your selected components is no longer in stock. Replace the affected item and try again.</p></div>:null}
    <div className="mx-auto grid max-w-[1500px] items-start gap-6 px-4 py-7 sm:px-6 xl:grid-cols-[250px_minmax(0,1fr)_330px]">
      <nav className="hidden rounded-2xl border bg-white p-3 shadow-sm xl:block"><p className="px-3 py-2 text-xs font-bold uppercase tracking-wider text-slate-500">Build stages</p>{activeSteps.map((item,index)=>{const selected=selections[item.key];return <button onClick={()=>go(index)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm transition ${index===current?"bg-sky-50 text-sky-900":"hover:bg-slate-50"}`} key={item.key}>{selected?<CheckCircle2 className="size-5 shrink-0 text-emerald-600"/>:<Circle className={`size-5 shrink-0 ${item.required?"text-slate-400":"text-slate-300"}`}/>}<span className="min-w-0"><strong className="block truncate">{item.shortTitle}</strong><small className="text-slate-500">{selected?"Selected":item.required?"Required":"Optional"}</small></span></button>})}</nav>
      <main className="min-w-0"><div className="rounded-2xl border bg-white p-5 shadow-sm sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-sky-700">Stage {current+1} of {activeSteps.length}</p><h2 className="mt-2 text-3xl font-black tracking-tight text-slate-950">{step.title}</h2><p className="mt-2 max-w-2xl text-slate-600">{step.description}</p></div>{!step.required?<button className="rounded-lg border px-4 py-2 text-sm font-semibold text-slate-600" onClick={()=>go(current+1)}>Skip for now</button>:null}</div><div className="mt-5 flex flex-wrap gap-2">{step.filterHints.map(hint=><span className="rounded-full bg-slate-100 px-3 py-1 text-xs text-slate-600" key={hint}>{hint}</span>)}</div><div className="mt-6 grid gap-3 sm:grid-cols-[1fr_180px_150px]"><label className="relative"><Search className="absolute left-3 top-3.5 size-4 text-slate-400"/><input className="h-11 w-full rounded-lg border pl-9 pr-3" value={search} onChange={event=>setSearch(event.target.value)} placeholder={`Search ${step.shortTitle.toLowerCase()} products`}/></label><select className="h-11 rounded-lg border px-3" value={brand} onChange={event=>setBrand(event.target.value)}><option value="">All brands</option>{brands.map(value=><option key={value}>{value}</option>)}</select><input className="h-11 rounded-lg border px-3" type="number" min="0" value={maxPrice} onChange={event=>setMaxPrice(event.target.value)} placeholder="Max price"/></div></div>
        <div className="mt-5 grid gap-4 sm:grid-cols-2 2xl:grid-cols-3">{products.map(product=>{const state=compatibility(step.key,product,selections);const selected=selections[step.key]?.id===product.id;return <article className={`group flex flex-col overflow-hidden rounded-2xl border bg-white transition ${selected?"border-emerald-500 ring-2 ring-emerald-200":"border-slate-200 hover:-translate-y-0.5 hover:shadow-lg"}`} key={product.id}><div className="relative aspect-[4/3] bg-white">{product.image?<Image src={product.image} alt={product.name} fill sizes="(max-width:640px) 100vw, 33vw" className="object-contain p-5"/>:null}{selected?<span className="absolute right-3 top-3 rounded-full bg-emerald-600 px-3 py-1 text-xs font-bold text-white">✓ Added</span>:null}</div><div className="flex flex-1 flex-col border-t p-4"><p className="text-xs font-bold uppercase tracking-wide text-sky-700">{product.brand??step.shortTitle}</p><h3 className="mt-1 line-clamp-3 font-bold leading-6 text-slate-950">{product.name}</h3><p className="mt-2 text-xs text-slate-500">{product.stock} in stock · {product.sku}</p><p className={`mt-3 text-xs font-semibold ${state.kind==="ok"?"text-emerald-700":state.kind==="bad"?"text-red-700":"text-amber-700"}`}>{state.kind==="bad"?<ShieldAlert className="mr-1 inline size-3.5"/>:null}{state.text}</p><div className="mt-auto flex items-end justify-between gap-3 pt-5"><strong className="text-xl text-slate-950">{formatZar(product.price)}</strong><button disabled={state.kind==="bad"} onClick={()=>select(product)} className="rounded-lg bg-sky-700 px-4 py-2 text-sm font-bold text-white disabled:cursor-not-allowed disabled:bg-slate-300">{selected?"Selected":"Add"}</button></div></div></article>})}</div>{!products.length?<div className="mt-5 rounded-2xl border border-dashed bg-white p-12 text-center text-slate-500">No in-stock products match these filters.</div>:null}
        <div className="mt-6 flex justify-between"><button disabled={!current} onClick={()=>go(current-1)} className="inline-flex items-center gap-2 rounded-lg border bg-white px-5 py-3 font-bold disabled:opacity-40"><ArrowLeft className="size-4"/>Previous</button><button disabled={current===activeSteps.length-1} onClick={()=>go(current+1)} className="inline-flex items-center gap-2 rounded-lg border bg-white px-5 py-3 font-bold disabled:opacity-40">Next<ArrowRight className="size-4"/></button></div>
      </main>
      <aside className="rounded-2xl border bg-white shadow-sm xl:sticky xl:top-28"><div className="border-b p-5"><div className="flex items-center justify-between"><h2 className="text-xl font-black">Your Build</h2><Wrench className="size-5 text-sky-700"/></div><p className="mt-1 text-sm text-slate-500">{buildType==="COMPLETE_SETUP"?"Complete PC setup":"PC only"}</p></div><div className="max-h-[50vh] divide-y overflow-auto">{activeSteps.map((item,index)=>{const product=selections[item.key];return <button className="flex w-full gap-3 p-4 text-left hover:bg-slate-50" onClick={()=>go(index)} key={item.key}><span className={`mt-0.5 grid size-6 shrink-0 place-items-center rounded-full ${product?"bg-emerald-100 text-emerald-700":"bg-slate-100 text-slate-400"}`}>{product?<Check className="size-4"/>:<span className="text-xs">{index+1}</span>}</span><span className="min-w-0 flex-1"><strong className="block text-sm">{item.shortTitle}</strong><small className={`mt-0.5 block truncate ${product?"text-slate-600":"text-slate-400"}`}>{product?.name??(item.required?"Required":"Optional")}</small></span>{product?<small className="shrink-0 font-semibold">{formatZar(product.price)}</small>:null}</button>})}</div><div className="border-t bg-slate-50 p-5"><div className="flex justify-between"><span className="text-sm text-slate-600">PC completion</span><strong>{pcPercent}%</strong></div><div className="mt-2 flex items-end justify-between"><span className="font-bold">Build total</span><strong className="text-2xl">{formatZar(total)}</strong></div>{pcComplete?<div className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-800"><Sparkles className="mr-1 inline size-4"/>Your PC is complete!</div>:<p className="mt-3 text-xs leading-5 text-slate-500">Select {requiredKeys.length-completedRequired} more required {requiredKeys.length-completedRequired===1?"component":"components"} before checkout.</p>}<form action={addPcBuildToCart} className="mt-4"><input type="hidden" name="productIds" value={JSON.stringify(Object.values(selections).map(product=>product?.id).filter(Boolean))}/><button disabled={!pcComplete} className="flex min-h-12 w-full items-center justify-center gap-2 rounded-lg bg-emerald-600 px-5 font-black text-white transition hover:bg-emerald-700 disabled:bg-slate-300"><PackagePlus className="size-5"/>Buy this build</button></form><p className="mt-2 text-center text-xs text-slate-500">Adds all selected parts to one cart and checkout.</p></div></aside>
    </div>
  </div>;
}
