"use client";

import Image from "next/image";
import NextLink from "next/link";
import type { ComponentProps } from "react";
import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Check, CheckCircle2, ChevronRight, Cpu, Gamepad2, HardDrive, Headphones, Keyboard, LogIn, MemoryStick, Monitor, Mouse, PackagePlus, Power, RotateCcw, Search, ShieldAlert, Snowflake, SquareDashed, UserPlus, Wrench, X } from "lucide-react";
import type { PcBuilderProduct, PcBuildStep, PcBuildStepKey } from "@/domain/catalogue/pc-builder";
import { formatZar } from "@/lib/money";
import { BrandLogo } from "@/components/brand-logo";
import { addPcProjectPartsToCart, analysePcProject, continuePcProjectAuthentication, createPcProject, savePcProjectPart } from "@/domain/pc-projects/actions";
import { normalizeBuildAnalysis, record } from "@/domain/pc-projects/analysis";
import { PC_PROJECT_MINIMUM_PROGRESSIVE_PURCHASE } from "@/domain/pc-projects/policy";
import { pcPartCompatibility } from "@/domain/pc-projects/compatibility";

function Link(props:ComponentProps<typeof NextLink>){return <NextLink {...props} href={props.href==="/shop"?"/":props.href}/>}

type BuildType="PC_ONLY"|"COMPLETE_SETUP";type Selections=Partial<Record<PcBuildStepKey,PcBuilderProduct>>;
const required:PcBuildStepKey[]=["cpu","motherboard","memory","storage","power","case"];
const text=(product:PcBuilderProduct)=>`${product.name} ${product.categoryPath} ${Object.entries(product.specifications).flat().join(" ")}`.toLowerCase();
const icons:Record<PcBuildStepKey,typeof Cpu>={cpu:Cpu,motherboard:SquareDashed,memory:MemoryStick,storage:HardDrive,graphics:Monitor,power:Power,case:SquareDashed,cooling:Snowflake,monitor:Monitor,keyboard:Keyboard,mouse:Mouse,audio:Headphones};

function WorkshopBar({progress,total,reset,title}:{progress?:number;total?:number;reset?:()=>void;title?:string}){
  return <header className="sticky top-0 z-50 border-b border-slate-200 bg-white/95 backdrop-blur"><div className="mx-auto flex min-h-16 max-w-[1500px] items-center gap-3 px-4 sm:px-6"><Link href="/shop" className="inline-flex min-h-10 shrink-0 items-center gap-2 rounded-xl border border-slate-200 px-3 text-sm font-bold text-slate-700 transition hover:border-sky-500 hover:text-slate-950"><ArrowLeft className="size-4"/><span className="hidden sm:inline">Back to shop</span><span className="sm:hidden">Exit</span></Link><div className="flex min-w-0 flex-1 items-center justify-center gap-3"><BrandLogo priority className="w-28 sm:w-36"/><span className="hidden h-7 border-l border-slate-200 sm:block"/><span className="hidden max-w-52 truncate text-xs font-black uppercase tracking-[.18em] text-sky-700 sm:block">{title??"PC Workshop"}</span></div>{progress===undefined?<span className="w-[68px] sm:w-[130px]"/>:<div className="flex shrink-0 items-center gap-2"><div className="hidden text-right md:block"><p className="text-[10px] font-bold uppercase tracking-widest text-slate-500">{progress}% assembled</p><strong className="text-sm text-slate-950">{formatZar(total??0)}</strong></div>{reset?<button onClick={reset} className="rounded-lg border border-slate-200 p-2.5 text-slate-600 hover:border-slate-500 hover:text-slate-950" title="Start over"><RotateCcw className="size-4"/></button>:null}</div>}</div>{progress!==undefined?<div className="h-1 bg-slate-100"><div className="h-full bg-sky-700 transition-all duration-700" style={{width:`${progress}%`}}/></div>:null}</header>;
}

type ProjectIntent={name:string;buildType:BuildType;intendedUse:"GAMING"|"WORK"|"CREATION"|"BALANCED";performanceTarget:"EASY"|"SMOOTH"|"HIGH_PERFORMANCE";gamePreferences:string[]};
const gameChoices=["Competitive shooters","Football & sports","Racing","Open-world adventures","Strategy & simulation","Creative sandbox"];

function ProjectStart({authenticated,draftName,draftType,draftUse,draftTarget,draftGames=[]}:{authenticated:boolean;draftName?:string;draftType?:BuildType;draftUse?:string;draftTarget?:string;draftGames?:string[]}){
  const[intent,setIntent]=useState<ProjectIntent|null>(null);
  const[buildType,setBuildType]=useState<BuildType>(draftType??"PC_ONLY");
  const submit=(event:React.FormEvent<HTMLFormElement>)=>{
    if(authenticated)return;
    event.preventDefault();
    const data=new FormData(event.currentTarget),name=String(data.get("name")??"").trim();
    if(name.length>=3)setIntent({name,buildType:String(data.get("buildType")) as BuildType,intendedUse:String(data.get("intendedUse")) as ProjectIntent["intendedUse"],performanceTarget:String(data.get("performanceTarget")) as ProjectIntent["performanceTarget"],gamePreferences:data.getAll("gamePreferences").map(String)});
  };
  const hiddenIntent=(value:ProjectIntent)=><><input type="hidden" name="name" value={value.name}/><input type="hidden" name="buildType" value={value.buildType}/><input type="hidden" name="intendedUse" value={value.intendedUse}/><input type="hidden" name="performanceTarget" value={value.performanceTarget}/>{value.gamePreferences.map(game=><input key={game} type="hidden" name="gamePreferences" value={game}/>)}</>;
  return <main className="min-h-dvh bg-[#f7f9fb] text-slate-950"><WorkshopBar/><div className="mx-auto max-w-4xl px-4 py-10 sm:py-16">
    <div className="text-center"><p className="text-xs font-bold uppercase tracking-[.18em] text-sky-700">New PC project</p><h1 className="mt-3 text-4xl font-black sm:text-6xl">What are you building?</h1><p className="mx-auto mt-4 max-w-xl leading-7 text-slate-600">Set the goal once. We use it throughout component selection and performance review.</p>{authenticated&&draftName?<p className="mx-auto mt-5 max-w-xl rounded-xl border border-emerald-400/30 bg-emerald-400/10 p-3 text-sm font-bold text-emerald-700">Welcome back. Your project details are ready.</p>:null}</div>
    <form action={authenticated?createPcProject:undefined} onSubmit={submit} className="mt-9 space-y-7 rounded-xl border border-slate-200 bg-white p-5 sm:p-8">
      <fieldset><legend className="font-black">1. Choose the build</legend><div className="mt-3 grid gap-3 sm:grid-cols-2">{([["PC_ONLY","PC only","The computer itself."],["COMPLETE_SETUP","Full setup","PC, monitor and desk peripherals."]] as const).map(([value,label,description])=><label key={value} className={`cursor-pointer rounded-xl border p-4 ${buildType===value?"border-sky-400 bg-sky-700/10":"border-slate-200 bg-slate-50"}`}><input className="sr-only" type="radio" name="buildType" value={value} checked={buildType===value} onChange={()=>setBuildType(value)}/><strong>{label}</strong><span className="mt-1 block text-sm text-slate-500">{description}</span></label>)}</div></fieldset>
      <fieldset><legend className="font-black">2. Main purpose</legend><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4">{([["GAMING","Gaming"],["WORK","Work"],["CREATION","Creation"],["BALANCED","Mixed use"]] as const).map(([value,label])=><label className="cursor-pointer rounded-xl border border-slate-200 bg-slate-50 p-3 text-center text-sm font-bold has-[:checked]:border-sky-400 has-[:checked]:bg-sky-700 has-[:checked]:text-white" key={value}><input className="sr-only" type="radio" name="intendedUse" value={value} defaultChecked={(draftUse??"GAMING")===value}/>{label}</label>)}</div></fieldset>
      <fieldset><legend className="font-black">3. Performance feel</legend><div className="mt-3 grid gap-2 sm:grid-cols-3">{([["EASY","Everyday","Reliable essentials"],["SMOOTH","Smooth","Comfortable performance"],["HIGH_PERFORMANCE","High performance","Demanding games and workloads"]] as const).map(([value,label,description])=><label className="cursor-pointer rounded-xl border border-slate-200 bg-slate-50 p-3 text-sm has-[:checked]:border-sky-400" key={value}><input className="mr-2 accent-sky-700" type="radio" name="performanceTarget" value={value} defaultChecked={(draftTarget??"SMOOTH")===value}/><strong>{label}</strong><span className="mt-1 block pl-6 text-xs text-slate-500">{description}</span></label>)}</div></fieldset>
      <fieldset><legend className="font-black">4. Games you care about <span className="font-normal text-slate-500">(optional)</span></legend><p className="mt-1 text-sm text-slate-500">Choose styles, not titles that will become outdated.</p><div className="mt-3 flex flex-wrap gap-2">{gameChoices.map(game=><label className="cursor-pointer rounded-full border border-slate-200 bg-slate-50 px-3 py-2 text-sm has-[:checked]:border-sky-400 has-[:checked]:text-sky-700" key={game}><input className="mr-2 accent-sky-700" type="checkbox" name="gamePreferences" value={game} defaultChecked={draftGames.includes(game)}/>{game}</label>)}</div></fieldset>
      <label className="block font-black">5. Project name<input name="name" required minLength={3} maxLength={80} defaultValue={draftName} placeholder="My gaming PC" className="mt-2 h-12 w-full rounded-xl border border-slate-300 bg-slate-50 px-4 text-base font-normal text-slate-950 outline-none focus:border-sky-600"/></label>
      <button className="inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-sky-700 font-black text-white">{authenticated?"Create project":"Continue"}<ArrowRight className="size-4"/></button>
    </form><p className="mt-5 text-center text-xs text-slate-500">Projects are saved only to an authenticated account.</p>
  </div>{intent?<div className="fixed inset-0 z-[70] grid place-items-center bg-slate-950/45 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="project-auth-title"><div className="relative w-full max-w-lg rounded-xl border border-slate-200 bg-white p-6 sm:p-8"><button onClick={()=>setIntent(null)} aria-label="Close" className="absolute right-4 top-4 rounded-lg p-2 text-slate-500 hover:bg-slate-100"><X className="size-5"/></button><p className="text-xs font-bold uppercase tracking-widest text-sky-700">Save {intent.name}</p><h2 id="project-auth-title" className="mt-3 text-3xl font-black">Sign in to save this project</h2><p className="mt-3 text-slate-600">Use your account or create one. Your choices will return with you.</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{([["login","Sign in",LogIn],["register","Register",UserPlus]] as const).map(([mode,label,Icon])=><form action={continuePcProjectAuthentication} key={mode}>{hiddenIntent(intent)}<input type="hidden" name="mode" value={mode}/><button className={`inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-xl px-4 font-black ${mode==="login"?"bg-sky-700 text-white":"border border-slate-300 bg-slate-100 text-slate-950"}`}><Icon className="size-4"/>{label}</button></form>)}</div></div></div>:null}</main>;
}

function Slot({part,label,icon:Icon,className,active,onClick}:{part?:PcBuilderProduct;label:string;icon:typeof Cpu;className:string;active:boolean;onClick:()=>void}){
  return <button onClick={onClick} className={`absolute overflow-hidden rounded-xl border text-left transition-colors ${className} ${part?"border-slate-500 bg-slate-100":"border-dashed border-slate-300 bg-white"} ${active?"ring-2 ring-sky-400 ring-offset-2 ring-offset-white":""}`}><span className="absolute left-2 top-2 z-10 rounded-md bg-slate-50/80 px-2 py-1 text-[10px] font-bold uppercase tracking-wide text-slate-700">{label}</span>{part?.image?<Image src={part.image} alt="" fill sizes="180px" className="object-contain p-5 opacity-90"/>:<span className="grid h-full place-items-center"><Icon className="size-7 text-slate-500"/></span>}{part?<span className="absolute bottom-1.5 left-2 right-2 truncate text-[10px] font-semibold text-emerald-700">Installed</span>:null}</button>;
}

function Assembly({selected,active,onStage,setup}:{selected:Selections;active:PcBuildStepKey;onStage:(key:PcBuildStepKey)=>void;setup:boolean}){
  return <section className="relative overflow-hidden rounded-xl border border-slate-200 bg-white "><div className="relative flex items-center justify-between border-b border-slate-200 px-5 py-4 text-slate-950"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-sky-700">Assembly view</p><h2 className="mt-1 text-lg font-bold">Your machine takes shape here</h2></div><Wrench className="size-5 text-sky-700"/></div><div className="relative mx-auto aspect-[4/3] max-h-[610px] w-full p-6"><div className="absolute inset-[7%_10%_8%_10%] rounded-[2rem] border-4 border-slate-300 bg-slate-100"><div className="absolute -right-3 top-10 h-20 w-3 rounded-r bg-slate-500"/><div className="absolute bottom-5 right-5 flex gap-2">{[1,2,3].map(value=><span className="size-9 rounded-full border-2 border-sky-500/40" key={value}/>)}</div></div>
    <Slot part={selected.motherboard} label="Motherboard" icon={SquareDashed} active={active==="motherboard"} onClick={()=>onStage("motherboard")} className="left-[17%] top-[18%] h-[52%] w-[45%]"/>
    <Slot part={selected.cpu} label="CPU" icon={Cpu} active={active==="cpu"} onClick={()=>onStage("cpu")} className="left-[31%] top-[32%] h-[18%] w-[17%]"/>
    <Slot part={selected.memory} label="Memory" icon={MemoryStick} active={active==="memory"} onClick={()=>onStage("memory")} className="left-[50%] top-[25%] h-[34%] w-[10%]"/>
    <Slot part={selected.graphics} label="Graphics" icon={Monitor} active={active==="graphics"} onClick={()=>onStage("graphics")} className="left-[25%] top-[57%] h-[14%] w-[45%]"/>
    <Slot part={selected.storage} label="Storage" icon={HardDrive} active={active==="storage"} onClick={()=>onStage("storage")} className="right-[16%] top-[21%] h-[20%] w-[17%]"/>
    <Slot part={selected.cooling} label="Cooling" icon={Snowflake} active={active==="cooling"} onClick={()=>onStage("cooling")} className="right-[16%] top-[45%] h-[20%] w-[17%]"/>
    <Slot part={selected.power} label="Power" icon={Power} active={active==="power"} onClick={()=>onStage("power")} className="right-[16%] bottom-[12%] h-[15%] w-[25%]"/>
    <Slot part={selected.case} label="Case" icon={SquareDashed} active={active==="case"} onClick={()=>onStage("case")} className="left-[12%] bottom-[3%] h-[10%] w-[22%]"/>
    {setup?<div className="absolute bottom-3 left-1/2 flex -translate-x-1/2 gap-2 rounded-xl border border-sky-400/30 bg-sky-700/10 p-2">{(["monitor","keyboard","mouse","audio"] as PcBuildStepKey[]).map(key=>{const Icon=icons[key];return <button title={key} onClick={()=>onStage(key)} className={`grid size-10 place-items-center rounded-lg ${selected[key]?"bg-sky-700 text-white":"bg-slate-100 text-slate-500"}`} key={key}><Icon className="size-4"/></button>})}</div>:null}</div></section>;
}

type ProjectData={id:string;name:string;buildType:string;intendedUse:string;performanceTarget:string;gamePreferences:string[];analysis?:unknown;items:{id:string;stepKey:string;productId:string;purchased:boolean;name:string;sku:string;image:string|null;price:string;specifications:unknown}[]};

function BuildReview({project,selected,total,onBack}:{project:ProjectData;selected:Selections;total:number;onBack:()=>void}){
  const analysis=normalizeBuildAnalysis(project.analysis),products=Object.values(selected).filter((item):item is PcBuilderProduct=>Boolean(item)),remaining=project.items.filter(item=>!item.purchased);
  return <main className="min-h-dvh bg-[#f7f9fb] text-slate-950"><WorkshopBar progress={100} total={total} title={project.name}/><div className="mx-auto max-w-6xl px-4 py-8 sm:px-6 sm:py-12">
    <button onClick={onBack} className="inline-flex min-h-11 items-center gap-2 text-sm font-bold text-slate-600 hover:text-slate-950"><ArrowLeft className="size-4"/>Back to components</button>
    <div className="mt-5 flex flex-wrap items-end justify-between gap-5 border-b border-slate-200 pb-7"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-sky-700">Build review</p><h1 className="mt-2 text-3xl font-black sm:text-5xl">{project.name}</h1><div className="mt-3 flex flex-wrap gap-2 text-xs text-slate-600"><span className="rounded-full border border-slate-200 px-3 py-1.5">{project.intendedUse.toLowerCase()}</span><span className="rounded-full border border-slate-200 px-3 py-1.5">{project.performanceTarget.replaceAll("_"," ").toLowerCase()}</span>{project.gamePreferences.map(game=><span className="rounded-full border border-slate-200 px-3 py-1.5" key={game}>{game}</span>)}</div></div><div><p className="text-sm text-slate-500">Project value</p><strong className="text-3xl">{formatZar(total)}</strong></div></div>
    <section className="mt-8"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-2xl font-black">Choose what to secure now</h2><p className="mt-1 text-sm text-slate-500">Purchased parts stay attached to this project. Return later for the rest.</p></div><Link className="text-sm font-bold text-sky-700" href={`/account/pc-projects/${project.id}`}>View project progress</Link></div>
      <form action={addPcProjectPartsToCart} className="mt-5"><input type="hidden" name="projectId" value={project.id}/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{project.items.map(item=>{const product=products.find(entry=>entry.id===item.productId);return <label className={`flex min-w-0 gap-3 rounded-xl border p-3 ${item.purchased?"border-emerald-500/40 bg-emerald-500/10":"border-slate-200 bg-white"}`} key={item.id}>{item.purchased?<span className="grid size-5 shrink-0 place-items-center rounded-full bg-emerald-500 text-slate-950"><Check className="size-3.5"/></span>:<input className="mt-0.5 size-5 shrink-0 accent-sky-700" type="checkbox" name="itemId" value={item.id} defaultChecked/>}<span className="relative size-12 shrink-0 overflow-hidden rounded-lg bg-white">{product?.image?<Image src={product.image} alt="" fill sizes="48px" className="object-contain p-1"/>:null}</span><span className="min-w-0"><strong className="line-clamp-2 text-sm">{item.name}</strong><span className="mt-1 block text-sm text-slate-600">{formatZar(item.price)}</span><small className={item.purchased?"text-emerald-700":"text-slate-500"}>{item.purchased?"Purchased":"Selected for checkout"}</small></span></label>})}</div>
        {analysis&&remaining.length?<div className="mt-5 flex flex-col items-start gap-3 sm:flex-row sm:items-center"><button className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-sky-700 px-6 font-black text-white"><PackagePlus className="size-5"/>Checkout selected parts</button><p className="text-xs text-slate-500">Minimum checkout: {formatZar(PC_PROJECT_MINIMUM_PROGRESSIVE_PURCHASE)}. Live prices and stock are checked before cart.</p></div>:null}
      </form>
    </section>
    <section className="mt-10 border-t border-slate-200 pt-8"><p className="text-xs font-bold uppercase tracking-[.18em] text-sky-700">Performance estimate</p><h2 className="mt-2 text-2xl font-black">What can this PC handle?</h2>{analysis?<><p className="mt-3 max-w-3xl leading-7 text-slate-600">{analysis.personality}</p><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{analysis.gaming?.map(item=><div className="rounded-xl border border-slate-200 bg-white p-4" key={item.label}><p className="text-xs text-slate-500">{item.label}</p><strong className="mt-2 block text-sky-700">{item.rating}</strong></div>)}</div>{analysis.games?.length?<div className="mt-7 grid gap-3 md:grid-cols-3">{analysis.games.map(group=><article className="rounded-xl border border-slate-200 bg-white p-4" key={group.tier}><h3 className="font-black">{group.tier}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{group.titles.join(" · ")}</p></article>)}</div>:null}<p className="mt-5 text-xs text-slate-500">Performance is an estimate based on available supplier specifications, not a frame-rate guarantee.</p></>:<form action={analysePcProject} className="mt-6"><input type="hidden" name="projectId" value={project.id}/><button className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-sky-700 px-6 font-black text-white"><Cpu className="size-4"/>Analyse this build</button><p className="mt-3 text-xs text-slate-500">Analysis unlocks checkout and is refreshed whenever a component changes.</p></form>}</section>
  </div></main>;
}

export function PcBuilderWorkspace({steps,error,project,authenticated=false,draftName,draftType,draftUse,draftTarget,draftGames,startInReview=false}:{steps:PcBuildStep[];error?:string;authenticated?:boolean;draftName?:string;draftType?:BuildType;draftUse?:string;draftTarget?:string;draftGames?:string[];startInReview?:boolean;project?:ProjectData}){
  const liveProducts=steps.flatMap(step=>step.products);
  const initialSelected=Object.fromEntries((project?.items??[]).map(item=>{const live=liveProducts.find(product=>product.id===item.productId);const snapshot:PcBuilderProduct={id:item.productId,name:item.name,slug:"",sku:item.sku,brand:null,image:item.image,price:item.price,stock:0,categoryPath:"",specifications:record(item.specifications)?Object.fromEntries(Object.entries(item.specifications).map(([key,value])=>[key,String(value)])): {}};return[item.stepKey,live??snapshot]})) as Selections;
  const[type,setType]=useState<BuildType|null>(project?.buildType as BuildType??null),[index,setIndex]=useState(0),[selected,setSelected]=useState<Selections>(initialSelected),[search,setSearch]=useState(""),[brand,setBrand]=useState(""),[price,setPrice]=useState(""),[installed,setInstalled]=useState<string|null>(null),[saveError,setSaveError]=useState<string|null>(null),[reviewing,setReviewing]=useState(startInReview);
  const active=useMemo(()=>steps.filter(step=>type==="COMPLETE_SETUP"||!step.setupOnly),[steps,type]),step=active[index];const done=required.filter(key=>selected[key]).length,percent=Math.round(done/required.length*100),complete=done===required.length,total=Object.values(selected).reduce((sum,item)=>sum+Number(item?.price??0),0);
  const brands=useMemo(()=>step?[...new Set(step.products.map(item=>item.brand).filter((item):item is string=>Boolean(item)))].sort():[],[step]);const products=useMemo(()=>step?step.products.filter(item=>(!search||text(item).includes(search.toLowerCase()))&&(!brand||item.brand===brand)&&(!price||Number(item.price)<=Number(price))):[],[step,search,brand,price]);
  const go=(target:number)=>{setIndex(Math.max(0,Math.min(active.length-1,target)));setSearch("");setBrand("");setPrice("");window.scrollTo({top:0,behavior:"smooth"})};const goKey=(key:PcBuildStepKey)=>{const target=active.findIndex(item=>item.key===key);if(target>=0)go(target)};
  const install=async(product:PcBuilderProduct)=>{if(!step||!project)return;setSaveError(null);try{await savePcProjectPart({projectId:project.id,stepKey:step.key,productId:product.id});setSelected(current=>({...current,[step.key]:product}));setInstalled(step.key);setTimeout(()=>setInstalled(null),1100)}catch(cause){setSaveError(cause instanceof Error?cause.message:"This component could not be saved.")}};
  if(!project)return <ProjectStart authenticated={authenticated} draftName={draftName} draftType={draftType} draftUse={draftUse} draftTarget={draftTarget} draftGames={draftGames}/>;
  if(!type)return <section className="relative min-h-dvh overflow-hidden bg-[#f7f9fb] text-slate-950"><WorkshopBar/><div className="relative mx-auto max-w-7xl px-4 py-12 sm:px-6 sm:py-20 lg:px-8"><div className="mx-auto max-w-3xl text-center"><span className="inline-flex items-center gap-2 rounded-full border border-sky-400/30 bg-sky-700/10 px-4 py-2 text-sm font-bold text-sky-800"><Cpu className="size-4"/>Welcome to your build workshop</span><h1 className="mt-6 text-4xl font-black tracking-tight sm:text-7xl">Build it. See it. Make it yours.</h1><p className="mx-auto mt-5 max-w-2xl text-base leading-7 text-slate-600 sm:text-lg sm:leading-8">Install real in-stock components into your virtual machine, check compatibility and purchase the finished build in one checkout.</p></div><div className="mx-auto mt-10 grid max-w-5xl gap-4 md:mt-14 md:grid-cols-2 md:gap-5"><button onClick={()=>setType("PC_ONLY")} className="group rounded-xl border border-slate-200 bg-white p-6 text-left transition hover:-translate-y-1 hover:border-sky-500 hover:bg-sky-700/10 sm:p-8"><Cpu className="size-10 text-sky-700 sm:size-11"/><h2 className="mt-5 text-2xl font-black sm:mt-7 sm:text-3xl">Build a PC</h2><p className="mt-3 leading-7 text-slate-600">Assemble the machine itself, from processor and motherboard to case and power.</p><span className="mt-6 inline-flex items-center gap-2 font-bold text-sky-700 sm:mt-8">Enter the workshop <ArrowRight className="size-4"/></span></button><button onClick={()=>setType("COMPLETE_SETUP")} className="group rounded-xl border border-slate-200 bg-white p-6 text-left transition hover:-translate-y-1 hover:border-sky-500 hover:bg-sky-700/10 sm:p-8"><Gamepad2 className="size-10 text-sky-700 sm:size-11"/><h2 className="mt-5 text-2xl font-black sm:mt-7 sm:text-3xl">Build a full setup</h2><p className="mt-3 leading-7 text-slate-600">Assemble the PC, then place the monitor, keyboard, mouse and audio around it.</p><span className="mt-6 inline-flex items-center gap-2 font-bold text-sky-700 sm:mt-8">Build the whole desk <ArrowRight className="size-4"/></span></button></div><div className="mt-8 text-center sm:mt-10"><Link href="/shop?category=Computers" className="text-sm text-slate-500 underline">Shop ready-built computers instead</Link></div></div></section>;
  if(!step)return null;
  if(reviewing&&complete)return <BuildReview project={project} selected={selected} total={total} onBack={()=>setReviewing(false)}/>;
  return <main className="min-h-dvh bg-[#f7f9fb] pb-20 text-slate-950 sm:pb-28"><WorkshopBar progress={percent} total={total} title={project.name}/>
    {error||saveError?<div className="mx-auto max-w-[1500px] px-4 pt-5 sm:px-6"><p className="rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-red-700">{saveError??"A selected component is no longer available. Replace it before checkout."}</p></div>:null}
    <div className="mx-auto max-w-[1500px] px-4 py-6 sm:px-6"><nav className="flex gap-2 overflow-x-auto pb-3">{active.map((item,itemIndex)=>{const Icon=icons[item.key],has=selected[item.key];return <button onClick={()=>go(itemIndex)} className={`flex shrink-0 items-center gap-2 rounded-full border px-4 py-2 text-sm font-semibold transition ${itemIndex===index?"border-sky-400 bg-sky-700 text-white":has?"border-emerald-500/50 bg-emerald-500/10 text-emerald-700":"border-slate-200 bg-white text-slate-500"}`} key={item.key}>{has?<Check className="size-4"/>:<Icon className="size-4"/>}{item.shortTitle}</button>})}</nav>
      <div className="mt-3 grid items-start gap-6 xl:grid-cols-[minmax(0,1.12fr)_minmax(430px,.88fr)]"><Assembly selected={selected} active={step.key} onStage={goKey} setup={type==="COMPLETE_SETUP"}/><section className="overflow-hidden rounded-xl border border-slate-200 bg-white "><div className="border-b border-slate-200 p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-sky-700">Install step {index+1}</p><h1 className="mt-2 text-3xl font-black">{step.title}</h1><p className="mt-2 text-sm leading-6 text-slate-500">{step.description}</p></div>{!step.required?<button onClick={()=>go(index+1)} className="shrink-0 rounded-lg border border-slate-300 px-3 py-2 text-xs font-bold text-slate-600">Skip</button>:null}</div>{installed===step.key?<div className="mt-4 flex items-center gap-2 rounded-xl bg-emerald-500/15 p-3 font-bold text-emerald-700"><CheckCircle2 className="size-5"/>{step.shortTitle} installed into your build</div>:null}<div className="mt-5 grid gap-2 sm:grid-cols-[1fr_145px_120px]"><label className="relative"><Search className="absolute left-3 top-3 size-4 text-slate-500"/><input value={search} onChange={event=>setSearch(event.target.value)} className="h-10 w-full rounded-lg border border-slate-200 bg-slate-50 pl-9 pr-3 text-sm outline-none focus:border-sky-600" placeholder="Search products or specifications"/></label><select value={brand} onChange={event=>setBrand(event.target.value)} className="h-10 rounded-lg border border-slate-200 bg-slate-50 px-3 text-sm"><option value="">All brands</option>{brands.map(item=><option key={item}>{item}</option>)}</select><input value={price} onChange={event=>setPrice(event.target.value)} className="h-10 rounded-lg border border-slate-200 bg-slate-50 px-3 text-sm" type="number" min="0" placeholder="Max price"/></div></div>
        <div className="max-h-[600px] space-y-2 overflow-y-auto p-3 sm:p-4">{products.map(product=>{const state=pcPartCompatibility(step.key,product,selected),isSelected=selected[step.key]?.id===product.id;return <article className={`grid grid-cols-[64px_minmax(0,1fr)] items-center gap-3 rounded-xl border p-3 transition sm:grid-cols-[84px_minmax(0,1fr)_auto] ${isSelected?"border-emerald-400 bg-emerald-400/10":"border-slate-200 bg-slate-50 hover:border-slate-500"}`} key={product.id}><div className="relative aspect-square overflow-hidden rounded-xl bg-white">{product.image?<Image src={product.image} alt={product.name} fill sizes="84px" className="object-contain p-2"/>:null}</div><div className="min-w-0"><p className="text-[10px] font-bold uppercase tracking-wide text-sky-700">{product.brand??step.shortTitle} · {product.stock} in stock</p><h2 className="mt-1 line-clamp-2 text-sm font-bold leading-5">{product.name}</h2><p className={`mt-1 text-[11px] ${state.kind==="ok"?"text-emerald-700":state.kind==="bad"?"text-red-700":"text-amber-700"}`}>{state.kind==="bad"?<ShieldAlert className="mr-1 inline size-3"/>:null}{state.label}</p></div><div className="col-span-2 flex items-center justify-between border-t border-slate-200 pt-2 text-right sm:col-span-1 sm:block sm:border-0 sm:pt-0"><strong className="block text-sm">{formatZar(product.price)}</strong><button disabled={state.kind==="bad"} onClick={()=>install(product)} className={`rounded-lg px-3 py-2 text-xs font-black sm:mt-2 ${isSelected?"bg-emerald-500 text-slate-950":"bg-sky-700 text-white"} disabled:bg-slate-700 disabled:text-slate-500`}>{isSelected?"Installed":"Install"}</button></div></article>})}{!products.length?<p className="p-10 text-center text-slate-500">No products match these filters.</p>:null}</div><div className="flex justify-between border-t border-slate-200 p-4"><button disabled={!index} onClick={()=>go(index-1)} className="inline-flex items-center gap-2 text-sm font-bold disabled:opacity-30"><ArrowLeft className="size-4"/>Previous</button><button disabled={index===active.length-1} onClick={()=>go(index+1)} className="inline-flex items-center gap-2 text-sm font-bold disabled:opacity-30">Next<ArrowRight className="size-4"/></button></div></section></div>
      <section className="mt-6 overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-200 p-5"><div><p className="text-xs font-bold uppercase tracking-widest text-sky-700">Build tray</p><h2 className="mt-1 text-xl font-black">{complete?"Your PC is assembled":"Parts waiting to be installed"}</h2></div><div className="text-right"><p className="text-xs text-slate-500">Current build total</p><strong className="text-2xl">{formatZar(total)}</strong></div></div><div className="grid gap-px bg-slate-200 sm:grid-cols-2 lg:grid-cols-4">{active.map((item,itemIndex)=>{const product=selected[item.key],Icon=icons[item.key];return <button onClick={()=>go(itemIndex)} className="flex min-h-24 items-center gap-3 bg-white p-4 text-left hover:bg-slate-100" key={item.key}><span className={`grid size-10 shrink-0 place-items-center rounded-xl ${product?"bg-emerald-500 text-slate-950":"bg-slate-100 text-slate-500"}`}>{product?<Check className="size-5"/>:<Icon className="size-5"/>}</span><span className="min-w-0"><strong className="block text-sm">{item.shortTitle}</strong><small className="mt-1 block truncate text-slate-500">{product?.name??(item.required?"Not installed":"Optional")}</small></span></button>})}</div><div className="flex flex-col items-center justify-between gap-4 p-5 sm:flex-row">{complete?<div className="flex items-center gap-3 text-emerald-700"><CheckCircle2 className="size-7"/><div><strong className="block text-lg">Assembly complete</strong><span className="text-sm">Review performance before checkout.</span></div></div>:<p className="text-sm text-slate-500">Install {required.length-done} more required {required.length-done===1?"part":"parts"} to complete the PC.</p>}<button disabled={!complete} onClick={()=>setReviewing(true)} className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-sky-700 px-7 font-black text-white hover:bg-sky-800 disabled:bg-slate-700 disabled:text-slate-500">Review build<ChevronRight className="size-4"/></button></div></section>
    </div>
  </main>;
}
