"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Check, CheckCircle2, ChevronRight, Cpu, Gamepad2, HardDrive, Headphones, Keyboard, MemoryStick, Monitor, Mouse, PackagePlus, Power, RotateCcw, Search, ShieldAlert, Snowflake, Sparkles, SquareDashed, Wrench } from "lucide-react";
import { addPcBuildToCart } from "@/domain/cart/pc-build-action";
import type { PcBuilderProduct, PcBuildStep, PcBuildStepKey } from "@/domain/catalogue/pc-builder";
import { formatZar } from "@/lib/money";

type BuildType="PC_ONLY"|"COMPLETE_SETUP";type Selections=Partial<Record<PcBuildStepKey,PcBuilderProduct>>;
const required:PcBuildStepKey[]=["cpu","motherboard","memory","storage","power","case"],storageKey="innozanzi-pc-workspace-v2";
const text=(product:PcBuilderProduct)=>`${product.name} ${product.categoryPath} ${Object.entries(product.specifications).flat().join(" ")}`.toLowerCase();
const socket=(product?:PcBuilderProduct)=>product?text(product).match(/\b(?:lga\s?\d{3,4}|am[45]|tr4|strx4)\b/i)?.[0]?.replace(/\s/g,"").toUpperCase():undefined;
const ram=(product?:PcBuilderProduct)=>product?text(product).match(/\bddr[345]\b/i)?.[0]?.toUpperCase():undefined;
const icons:Record<PcBuildStepKey,typeof Cpu>={cpu:Cpu,motherboard:SquareDashed,memory:MemoryStick,storage:HardDrive,graphics:Monitor,power:Power,case:SquareDashed,cooling:Snowflake,monitor:Monitor,keyboard:Keyboard,mouse:Mouse,audio:Headphones};

function compatibility(key:PcBuildStepKey,candidate:PcBuilderProduct,selected:Selections){
  if(key==="motherboard"&&selected.cpu){const a=socket(selected.cpu),b=socket(candidate);if(a&&b)return a===b?{kind:"ok",label:`${a} socket match`}:{kind:"bad",label:`${b} board does not match ${a} CPU`};}
  if(key==="cpu"&&selected.motherboard){const a=socket(candidate),b=socket(selected.motherboard);if(a&&b)return a===b?{kind:"ok",label:`${b} socket match`}:{kind:"bad",label:`${a} CPU does not match ${b} board`};}
  if(key==="memory"&&selected.motherboard){const a=ram(candidate),b=ram(selected.motherboard);if(a&&b)return a===b?{kind:"ok",label:`${a} memory match`}:{kind:"bad",label:`${a} memory does not match ${b} board`};}
  if(key==="motherboard"&&selected.memory){const a=ram(candidate),b=ram(selected.memory);if(a&&b)return a===b?{kind:"ok",label:`${a} memory match`}:{kind:"bad",label:`${a} board does not match ${b} memory`};}
  return{kind:"unknown",label:"Compatibility needs final verification"};
}

function Slot({part,label,icon:Icon,className,active,onClick}:{part?:PcBuilderProduct;label:string;icon:typeof Cpu;className:string;active:boolean;onClick:()=>void}){
  return <button onClick={onClick} className={`absolute overflow-hidden rounded-xl border text-left transition-all duration-500 ${className} ${part?"border-emerald-400/70 bg-emerald-400/10 shadow-[0_0_25px_rgba(52,211,153,.16)]":"border-dashed border-slate-600 bg-slate-900/70"} ${active?"animate-pulse ring-2 ring-sky-400 ring-offset-2 ring-offset-[#07111f]":""}`}><span className="absolute left-2 top-2 z-10 rounded-md bg-slate-950/80 px-2 py-1 text-[10px] font-bold uppercase tracking-wide text-slate-200">{label}</span>{part?.image?<Image src={part.image} alt="" fill sizes="180px" className="object-contain p-5 opacity-90"/>:<span className="grid h-full place-items-center"><Icon className="size-7 text-slate-500"/></span>}{part?<span className="absolute bottom-1.5 left-2 right-2 truncate text-[10px] font-semibold text-emerald-200">Installed</span>:null}</button>;
}

function Assembly({selected,active,onStage,setup}:{selected:Selections;active:PcBuildStepKey;onStage:(key:PcBuildStepKey)=>void;setup:boolean}){
  return <section className="relative overflow-hidden rounded-3xl border border-slate-700 bg-[#07111f] shadow-2xl"><div className="absolute inset-0 opacity-20 [background-image:linear-gradient(rgba(56,189,248,.12)_1px,transparent_1px),linear-gradient(90deg,rgba(56,189,248,.12)_1px,transparent_1px)] [background-size:28px_28px]"/><div className="relative flex items-center justify-between border-b border-slate-700 px-5 py-4 text-white"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-sky-300">Assembly view</p><h2 className="mt-1 text-lg font-bold">Your machine takes shape here</h2></div><Wrench className="size-5 text-sky-300"/></div><div className="relative mx-auto aspect-[4/3] max-h-[610px] w-full p-6"><div className="absolute inset-[7%_10%_8%_10%] rounded-[2rem] border-4 border-slate-600 bg-slate-950/70 shadow-[inset_0_0_50px_rgba(14,165,233,.08)]"><div className="absolute -right-3 top-10 h-20 w-3 rounded-r bg-slate-500"/><div className="absolute bottom-5 right-5 flex gap-2">{[1,2,3].map(value=><span className="size-9 rounded-full border-2 border-sky-500/40" key={value}/>)}</div></div>
    <Slot part={selected.motherboard} label="Motherboard" icon={SquareDashed} active={active==="motherboard"} onClick={()=>onStage("motherboard")} className="left-[17%] top-[18%] h-[52%] w-[45%]"/>
    <Slot part={selected.cpu} label="CPU" icon={Cpu} active={active==="cpu"} onClick={()=>onStage("cpu")} className="left-[31%] top-[32%] h-[18%] w-[17%]"/>
    <Slot part={selected.memory} label="Memory" icon={MemoryStick} active={active==="memory"} onClick={()=>onStage("memory")} className="left-[50%] top-[25%] h-[34%] w-[10%]"/>
    <Slot part={selected.graphics} label="Graphics" icon={Monitor} active={active==="graphics"} onClick={()=>onStage("graphics")} className="left-[25%] top-[57%] h-[14%] w-[45%]"/>
    <Slot part={selected.storage} label="Storage" icon={HardDrive} active={active==="storage"} onClick={()=>onStage("storage")} className="right-[16%] top-[21%] h-[20%] w-[17%]"/>
    <Slot part={selected.cooling} label="Cooling" icon={Snowflake} active={active==="cooling"} onClick={()=>onStage("cooling")} className="right-[16%] top-[45%] h-[20%] w-[17%]"/>
    <Slot part={selected.power} label="Power" icon={Power} active={active==="power"} onClick={()=>onStage("power")} className="right-[16%] bottom-[12%] h-[15%] w-[25%]"/>
    <Slot part={selected.case} label="Case" icon={SquareDashed} active={active==="case"} onClick={()=>onStage("case")} className="left-[12%] bottom-[3%] h-[10%] w-[22%]"/>
    {setup?<div className="absolute bottom-3 left-1/2 flex -translate-x-1/2 gap-2 rounded-xl border border-violet-400/30 bg-violet-400/10 p-2">{(["monitor","keyboard","mouse","audio"] as PcBuildStepKey[]).map(key=>{const Icon=icons[key];return <button title={key} onClick={()=>onStage(key)} className={`grid size-10 place-items-center rounded-lg ${selected[key]?"bg-violet-500 text-white":"bg-slate-800 text-slate-400"}`} key={key}><Icon className="size-4"/></button>})}</div>:null}</div></section>;
}

export function PcBuilderWorkspace({steps,error}:{steps:PcBuildStep[];error?:string}){
  const[type,setType]=useState<BuildType|null>(null),[index,setIndex]=useState(0),[selected,setSelected]=useState<Selections>({}),[search,setSearch]=useState(""),[brand,setBrand]=useState(""),[price,setPrice]=useState(""),[installed,setInstalled]=useState<string|null>(null),[ready,setReady]=useState(false);
  useEffect(()=>{queueMicrotask(()=>{try{const saved=JSON.parse(localStorage.getItem(storageKey)??"null");if(saved){setType(saved.type??null);setSelected(saved.selected??{});setIndex(saved.index??0)}}catch{}setReady(true)})},[]);
  useEffect(()=>{if(ready)localStorage.setItem(storageKey,JSON.stringify({type,selected,index}))},[type,selected,index,ready]);
  const active=useMemo(()=>steps.filter(step=>type==="COMPLETE_SETUP"||!step.setupOnly),[steps,type]),step=active[index];const done=required.filter(key=>selected[key]).length,percent=Math.round(done/required.length*100),complete=done===required.length,total=Object.values(selected).reduce((sum,item)=>sum+Number(item?.price??0),0);
  const brands=useMemo(()=>step?[...new Set(step.products.map(item=>item.brand).filter((item):item is string=>Boolean(item)))].sort():[],[step]);const products=useMemo(()=>step?step.products.filter(item=>(!search||text(item).includes(search.toLowerCase()))&&(!brand||item.brand===brand)&&(!price||Number(item.price)<=Number(price))):[],[step,search,brand,price]);
  const go=(target:number)=>{setIndex(Math.max(0,Math.min(active.length-1,target)));setSearch("");setBrand("");setPrice("");window.scrollTo({top:0,behavior:"smooth"})};const goKey=(key:PcBuildStepKey)=>{const target=active.findIndex(item=>item.key===key);if(target>=0)go(target)};
  const install=(product:PcBuilderProduct)=>{if(!step)return;setSelected(current=>({...current,[step.key]:product}));setInstalled(step.key);setTimeout(()=>setInstalled(null),1100)};const reset=()=>{setType(null);setSelected({});setIndex(0);localStorage.removeItem(storageKey)};
  if(!ready)return <div className="grid min-h-[70vh] place-items-center bg-[#050b14] text-sky-300">Loading your workshop…</div>;
  if(!type)return <section className="relative overflow-hidden bg-[#050b14] text-white"><div className="absolute inset-0 opacity-30 [background-image:radial-gradient(circle_at_15%_25%,#0284c7_0,transparent_30%),radial-gradient(circle_at_85%_70%,#7c3aed_0,transparent_28%)]"/><div className="relative mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><div className="mx-auto max-w-3xl text-center"><span className="inline-flex items-center gap-2 rounded-full border border-sky-400/30 bg-sky-400/10 px-4 py-2 text-sm font-bold text-sky-200"><Sparkles className="size-4"/>Welcome to your build workshop</span><h1 className="mt-6 text-5xl font-black tracking-tight sm:text-7xl">Build it. See it. Make it yours.</h1><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-slate-300">Install real in-stock components into your virtual machine, check compatibility and purchase the finished build in one checkout.</p></div><div className="mx-auto mt-14 grid max-w-5xl gap-5 md:grid-cols-2"><button onClick={()=>setType("PC_ONLY")} className="group rounded-3xl border border-slate-700 bg-white/5 p-8 text-left transition hover:-translate-y-1 hover:border-sky-400 hover:bg-sky-400/10"><Cpu className="size-11 text-sky-300"/><h2 className="mt-7 text-3xl font-black">Build a PC</h2><p className="mt-3 leading-7 text-slate-300">Assemble the machine itself, from processor and motherboard to case and power.</p><span className="mt-8 inline-flex items-center gap-2 font-bold text-sky-300">Enter the workshop <ArrowRight className="size-4"/></span></button><button onClick={()=>setType("COMPLETE_SETUP")} className="group rounded-3xl border border-slate-700 bg-white/5 p-8 text-left transition hover:-translate-y-1 hover:border-violet-400 hover:bg-violet-400/10"><Gamepad2 className="size-11 text-violet-300"/><h2 className="mt-7 text-3xl font-black">Build a full setup</h2><p className="mt-3 leading-7 text-slate-300">Assemble the PC, then place the monitor, keyboard, mouse and audio around it.</p><span className="mt-8 inline-flex items-center gap-2 font-bold text-violet-300">Build the whole desk <ArrowRight className="size-4"/></span></button></div><div className="mt-10 text-center"><Link href="/shop?category=Computers" className="text-sm text-slate-400 underline">Shop ready-built computers instead</Link></div></div></section>;
  if(!step)return null;
  return <main className="min-h-screen bg-[#0a101b] pb-28 text-white"><header className="sticky top-0 z-40 border-b border-slate-800 bg-[#050b14]/95 backdrop-blur"><div className="mx-auto max-w-[1500px] px-4 py-4 sm:px-6"><div className="flex items-center gap-5"><div className="hidden sm:block"><p className="text-xs font-bold uppercase tracking-[.18em] text-sky-300">PC Workshop</p><p className="font-bold">{percent}% assembled</p></div><div className="h-2 flex-1 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-gradient-to-r from-sky-400 via-cyan-300 to-emerald-400 transition-all duration-700" style={{width:`${percent}%`}}/></div><strong className="text-lg">{formatZar(total)}</strong><button onClick={reset} className="rounded-lg border border-slate-700 p-2 text-slate-300 hover:text-white" title="Start over"><RotateCcw className="size-4"/></button></div></div></header>
    {error?<div className="mx-auto max-w-[1500px] px-4 pt-5 sm:px-6"><p className="rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-red-200">A selected component is no longer available. Replace it before checkout.</p></div>:null}
    <div className="mx-auto max-w-[1500px] px-4 py-6 sm:px-6"><nav className="flex gap-2 overflow-x-auto pb-3">{active.map((item,itemIndex)=>{const Icon=icons[item.key],has=selected[item.key];return <button onClick={()=>go(itemIndex)} className={`flex shrink-0 items-center gap-2 rounded-full border px-4 py-2 text-sm font-semibold transition ${itemIndex===index?"border-sky-400 bg-sky-400 text-slate-950":has?"border-emerald-500/50 bg-emerald-500/10 text-emerald-200":"border-slate-700 bg-slate-900 text-slate-400"}`} key={item.key}>{has?<Check className="size-4"/>:<Icon className="size-4"/>}{item.shortTitle}</button>})}</nav>
      <div className="mt-3 grid items-start gap-6 xl:grid-cols-[minmax(0,1.12fr)_minmax(430px,.88fr)]"><Assembly selected={selected} active={step.key} onStage={goKey} setup={type==="COMPLETE_SETUP"}/><section className="overflow-hidden rounded-3xl border border-slate-700 bg-slate-900 shadow-2xl"><div className="border-b border-slate-700 p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-sky-300">Install step {index+1}</p><h1 className="mt-2 text-3xl font-black">{step.title}</h1><p className="mt-2 text-sm leading-6 text-slate-400">{step.description}</p></div>{!step.required?<button onClick={()=>go(index+1)} className="shrink-0 rounded-lg border border-slate-600 px-3 py-2 text-xs font-bold text-slate-300">Skip</button>:null}</div>{installed===step.key?<div className="mt-4 flex items-center gap-2 rounded-xl bg-emerald-500/15 p-3 font-bold text-emerald-300"><CheckCircle2 className="size-5"/>{step.shortTitle} installed into your build</div>:null}<div className="mt-5 grid gap-2 sm:grid-cols-[1fr_145px_120px]"><label className="relative"><Search className="absolute left-3 top-3 size-4 text-slate-500"/><input value={search} onChange={event=>setSearch(event.target.value)} className="h-10 w-full rounded-lg border border-slate-700 bg-slate-950 pl-9 pr-3 text-sm outline-none focus:border-sky-400" placeholder="Search products or specifications"/></label><select value={brand} onChange={event=>setBrand(event.target.value)} className="h-10 rounded-lg border border-slate-700 bg-slate-950 px-3 text-sm"><option value="">All brands</option>{brands.map(item=><option key={item}>{item}</option>)}</select><input value={price} onChange={event=>setPrice(event.target.value)} className="h-10 rounded-lg border border-slate-700 bg-slate-950 px-3 text-sm" type="number" min="0" placeholder="Max price"/></div></div>
        <div className="max-h-[600px] space-y-2 overflow-y-auto p-3 sm:p-4">{products.map(product=>{const state=compatibility(step.key,product,selected),isSelected=selected[step.key]?.id===product.id;return <article className={`grid grid-cols-[84px_minmax(0,1fr)_auto] items-center gap-3 rounded-2xl border p-3 transition ${isSelected?"border-emerald-400 bg-emerald-400/10":"border-slate-700 bg-slate-950/60 hover:border-slate-500"}`} key={product.id}><div className="relative aspect-square overflow-hidden rounded-xl bg-white">{product.image?<Image src={product.image} alt={product.name} fill sizes="84px" className="object-contain p-2"/>:null}</div><div className="min-w-0"><p className="text-[10px] font-bold uppercase tracking-wide text-sky-300">{product.brand??step.shortTitle} · {product.stock} in stock</p><h2 className="mt-1 line-clamp-2 text-sm font-bold leading-5">{product.name}</h2><p className={`mt-1 text-[11px] ${state.kind==="ok"?"text-emerald-300":state.kind==="bad"?"text-red-300":"text-amber-300"}`}>{state.kind==="bad"?<ShieldAlert className="mr-1 inline size-3"/>:null}{state.label}</p></div><div className="text-right"><strong className="block text-sm">{formatZar(product.price)}</strong><button disabled={state.kind==="bad"} onClick={()=>install(product)} className={`mt-2 rounded-lg px-3 py-2 text-xs font-black ${isSelected?"bg-emerald-500 text-white":"bg-sky-400 text-slate-950"} disabled:bg-slate-700 disabled:text-slate-500`}>{isSelected?"Installed":"Install"}</button></div></article>})}{!products.length?<p className="p-10 text-center text-slate-500">No products match these filters.</p>:null}</div><div className="flex justify-between border-t border-slate-700 p-4"><button disabled={!index} onClick={()=>go(index-1)} className="inline-flex items-center gap-2 text-sm font-bold disabled:opacity-30"><ArrowLeft className="size-4"/>Previous</button><button disabled={index===active.length-1} onClick={()=>go(index+1)} className="inline-flex items-center gap-2 text-sm font-bold disabled:opacity-30">Next<ArrowRight className="size-4"/></button></div></section></div>
      <section className="mt-6 overflow-hidden rounded-2xl border border-slate-700 bg-slate-900"><div className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-700 p-5"><div><p className="text-xs font-bold uppercase tracking-widest text-sky-300">Build tray</p><h2 className="mt-1 text-xl font-black">{complete?"Your PC is assembled":"Parts waiting to be installed"}</h2></div><div className="text-right"><p className="text-xs text-slate-400">Current build total</p><strong className="text-2xl">{formatZar(total)}</strong></div></div><div className="grid gap-px bg-slate-700 sm:grid-cols-2 lg:grid-cols-4">{active.map((item,itemIndex)=>{const product=selected[item.key],Icon=icons[item.key];return <button onClick={()=>go(itemIndex)} className="flex min-h-24 items-center gap-3 bg-slate-900 p-4 text-left hover:bg-slate-800" key={item.key}><span className={`grid size-10 shrink-0 place-items-center rounded-xl ${product?"bg-emerald-500 text-white":"bg-slate-800 text-slate-500"}`}>{product?<Check className="size-5"/>:<Icon className="size-5"/>}</span><span className="min-w-0"><strong className="block text-sm">{item.shortTitle}</strong><small className="mt-1 block truncate text-slate-400">{product?.name??(item.required?"Not installed":"Optional")}</small></span></button>})}</div><div className="flex flex-col items-center justify-between gap-4 p-5 sm:flex-row">{complete?<div className="flex items-center gap-3 text-emerald-300"><Sparkles className="size-7"/><div><strong className="block text-lg">Your PC is built!</strong><span className="text-sm">Review your installed parts, then continue to your cart.</span></div></div>:<p className="text-sm text-slate-400">Install {required.length-done} more required {required.length-done===1?"part":"parts"} to complete the PC.</p>}<form action={addPcBuildToCart}><input type="hidden" name="productIds" value={JSON.stringify(Object.values(selected).map(item=>item?.id).filter(Boolean))}/><button disabled={!complete} className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-emerald-500 px-7 font-black text-white hover:bg-emerald-600 disabled:bg-slate-700 disabled:text-slate-500"><PackagePlus className="size-5"/>Buy this build<ChevronRight className="size-4"/></button></form></div></section>
    </div>
  </main>;
}
