import Link from "next/link";
import { CheckCircle2, LockKeyhole, MessageSquare, Star, UserRound } from "lucide-react";
import { submitProductReview } from "@/domain/catalogue/review-actions";

type PublicReview = { id: string; rating: number; title: string | null; body: string | null; isVerifiedPurchase: boolean; createdAt: Date; user: { name: string | null } };

function Stars({ rating, size = "size-4" }: { rating: number; size?: string }) {
  return <div aria-label={`${rating} out of 5 stars`} className="flex gap-0.5 text-amber-500">{[1, 2, 3, 4, 5].map(star => <Star aria-hidden="true" className={`${size} ${star <= rating ? "fill-current" : "text-slate-300"}`} key={star}/>)}</div>;
}

export function ProductReviews({ productId, sourceType, path, reviews, signedIn, submitted }: { productId: string; sourceType: "LOCAL" | "SUPPLIER"; path: string; reviews: PublicReview[]; signedIn: boolean; submitted?: boolean }) {
  const average = reviews.length ? reviews.reduce((sum, review) => sum + review.rating, 0) / reviews.length : 0;
  const distribution = [5, 4, 3, 2, 1].map(rating => ({ rating, count: reviews.filter(review => review.rating === rating).length }));
  return <section id="reviews" className="scroll-mt-32 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-8 lg:p-10">
    <div className="flex flex-col justify-between gap-3 border-b border-slate-100 pb-6 sm:flex-row sm:items-end"><div><p className="text-xs font-black uppercase tracking-[.18em] text-sky-700">Customer feedback</p><h2 className="mt-2 text-2xl font-black tracking-tight text-slate-950 sm:text-3xl">Reviews &amp; comments</h2></div><p className="text-sm text-slate-500">Real feedback from signed-in Innozanzi customers</p></div>
    {submitted ? <div className="mt-6 flex items-start gap-3 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-900"><CheckCircle2 className="mt-0.5 size-5 shrink-0"/><div><strong className="block">Your review is live</strong><span>Thank you for helping other customers make a more informed choice.</span></div></div> : null}
    <div className="mt-7 grid items-start gap-8 lg:grid-cols-[minmax(280px,.72fr)_minmax(0,1.28fr)] lg:gap-12">
      <aside className="space-y-5 lg:sticky lg:top-32">
        {reviews.length ? <div className="rounded-2xl bg-slate-950 p-6 text-white"><div className="flex items-center gap-4"><strong className="text-5xl font-black">{average.toFixed(1)}</strong><div><Stars rating={Math.round(average)} size="size-5"/><p className="mt-1 text-sm text-slate-300">Based on {reviews.length} customer {reviews.length === 1 ? "review" : "reviews"}</p></div></div><div className="mt-6 space-y-2.5">{distribution.map(item => <div className="grid grid-cols-[28px_1fr_24px] items-center gap-2 text-xs text-slate-300" key={item.rating}><span>{item.rating}★</span><span className="h-2 overflow-hidden rounded-full bg-white/15"><span className="block h-full rounded-full bg-amber-400" style={{ width: `${reviews.length ? item.count / reviews.length * 100 : 0}%` }}/></span><span className="text-right">{item.count}</span></div>)}</div></div> : <div className="rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-6"><MessageSquare className="size-7 text-sky-700"/><p className="mt-4 font-bold text-slate-950">No reviews yet</p><p className="mt-1 text-sm leading-6 text-slate-600">Be the first customer to share useful product feedback.</p></div>}
        {signedIn ? <form action={submitProductReview} className="space-y-4 rounded-2xl border border-slate-200 bg-slate-50 p-5 sm:p-6">
          <input type="hidden" name="productId" value={productId}/><input type="hidden" name="sourceType" value={sourceType}/><input type="hidden" name="returnPath" value={path}/>
          <div><h3 className="text-lg font-black text-slate-950">Share your experience</h3><p className="mt-1 text-xs leading-5 text-slate-500">Your review publishes immediately and can be updated by submitting again.</p></div>
          <fieldset><legend className="text-sm font-semibold text-slate-800">Your rating</legend><div className="mt-2 grid grid-cols-5 gap-1.5">{[1, 2, 3, 4, 5].map(rating => <label className="cursor-pointer" key={rating}><input className="peer sr-only" type="radio" name="rating" value={rating} required/><span className="grid min-h-11 place-items-center rounded-lg border border-slate-300 bg-white text-sm font-bold peer-checked:border-amber-500 peer-checked:bg-amber-50 peer-checked:text-amber-800">{rating} ★</span></label>)}</div></fieldset>
          <label className="block text-sm font-semibold text-slate-800">Review title<input className="mt-2 h-12 w-full rounded-xl border border-slate-300 bg-white px-3 outline-none focus:border-sky-600 focus:ring-1 focus:ring-sky-600" name="title" minLength={3} maxLength={120} placeholder="Summarise your experience" required/></label>
          <label className="block text-sm font-semibold text-slate-800">Your comments<textarea className="mt-2 min-h-32 w-full rounded-xl border border-slate-300 bg-white p-3 outline-none focus:border-sky-600 focus:ring-1 focus:ring-sky-600" name="body" minLength={10} maxLength={2000} placeholder="What worked well, and what should another customer know?" required/></label>
          <button className="min-h-12 w-full rounded-xl bg-sky-700 px-5 font-black text-white transition hover:bg-sky-800">Publish review</button><p className="flex gap-2 text-xs leading-5 text-slate-500"><CheckCircle2 className="mt-0.5 size-3.5 shrink-0 text-emerald-600"/>Paid-order reviews automatically receive a verified-purchase badge.</p>
        </form> : <div className="rounded-2xl border border-sky-100 bg-sky-50 p-6"><span className="grid size-10 place-items-center rounded-full bg-white text-sky-700"><LockKeyhole className="size-5"/></span><p className="mt-4 font-bold text-slate-950">Sign in to join the conversation</p><p className="mt-1 text-sm leading-6 text-slate-600">Only signed-in customers can publish ratings and comments.</p><Link className="mt-4 inline-flex min-h-11 items-center rounded-xl bg-sky-700 px-5 text-sm font-bold text-white" href={`/sign-in?callbackUrl=${encodeURIComponent(`${path}#reviews`)}`}>Sign in to review</Link></div>}
      </aside>
      <div className="space-y-4">
        {reviews.map(review => <article className="rounded-2xl border border-slate-200 bg-white p-5 transition hover:border-slate-300 hover:shadow-sm sm:p-6" key={review.id}><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex min-w-0 items-center gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-slate-100 text-slate-600"><UserRound className="size-5"/></span><div className="min-w-0"><p className="truncate text-sm font-bold text-slate-950">{review.user.name ?? "Innozanzi customer"}</p><time className="text-xs text-slate-500">{review.createdAt.toLocaleDateString("en-ZA", { day: "numeric", month: "short", year: "numeric" })}</time></div></div><Stars rating={review.rating}/></div><h3 className="mt-5 text-lg font-black text-slate-950">{review.title ?? "Customer review"}</h3>{review.body ? <p className="mt-2 whitespace-pre-line text-sm leading-7 text-slate-700">{review.body}</p> : null}{review.isVerifiedPurchase ? <div className="mt-5 border-t border-slate-100 pt-4"><span className="inline-flex items-center gap-1.5 rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-bold text-emerald-700"><CheckCircle2 className="size-3.5"/>Verified purchase</span></div> : null}</article>)}
        {!reviews.length ? <div className="grid min-h-72 place-items-center rounded-2xl border border-dashed border-slate-300 bg-slate-50/70 px-6 text-center"><div><MessageSquare className="mx-auto size-8 text-slate-400"/><p className="mt-3 font-semibold text-slate-700">Customer reviews will appear here.</p><p className="mt-1 text-sm text-slate-500">Sign in and be the first to share your experience.</p></div></div> : null}
      </div>
    </div>
  </section>;
}
