"use server";
import {randomUUID} from"node:crypto";
import Decimal from"decimal.js";
import{redirect}from"next/navigation";
import{revalidatePath}from"next/cache";
import{z}from"zod";
import{requirePermission,requireUser}from"@/domain/auth/session";
import{prisma}from"@/lib/prisma";
import{createSupabaseAdmin}from"@/lib/supabase";
import{enqueueEmail}from"@/integrations/email/outbox";
import{emailTemplates}from"@/integrations/email/templates";

const allowedTypes=new Set(["image/jpeg","image/png","image/webp","application/pdf","video/mp4","video/quicktime"]);
const MAX=25*1024*1024;
const optionalDate=z.preprocess(value=>value===""||value===null||value===undefined?undefined:value,z.coerce.date().optional());
const reference=(prefix:string)=>`${prefix}-${Date.now().toString(36).toUpperCase()}`;
async function uploadFiles(files:File[],folder:string){
  const supabase=createSupabaseAdmin(),bucket=process.env.SUPABASE_PRIVATE_BUCKET??"private-documents";
  if(!(await supabase.storage.getBucket(bucket)).data){const made=await supabase.storage.createBucket(bucket,{public:false,fileSizeLimit:MAX});if(made.error)throw made.error}
  const uploaded:Array<{bucket:string;path:string;file:File}>=[];
  try{for(const file of files){if(!file.size)continue;if(file.size>MAX||!allowedTypes.has(file.type))throw new Error("Evidence must be a JPG, PNG, WebP, PDF, MP4 or MOV smaller than 25 MB.");const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"-");const path=`returns/${folder}/${randomUUID()}-${safe}`;const result=await supabase.storage.from(bucket).upload(path,file,{contentType:file.type,upsert:false});if(result.error)throw result.error;uploaded.push({bucket,path,file})}return uploaded}catch(error){if(uploaded.length)await supabase.storage.from(bucket).remove(uploaded.map(item=>item.path));throw error}
}
async function removeUploads(items:Array<{bucket:string;path:string}>){if(items.length)await createSupabaseAdmin().storage.from(items[0].bucket).remove(items.map(item=>item.path))}

const preferred=z.enum(["GUIDANCE","REPAIR","REPLACEMENT","EXCHANGE","FULL_REFUND","PARTIAL_REFUND","STORE_CREDIT","RETURN_TO_CUSTOMER"]);
export async function submitCustomerReturn(formData:FormData){
  const ctx=await requireUser();const data=z.object({orderItemId:z.string().uuid(),reasonId:z.string().uuid(),quantityAffected:z.coerce.number().int().positive(),customerDescription:z.string().trim().min(20).max(5000),problemStartedAt:optionalDate,usageDescription:z.string().trim().max(3000).optional(),troubleshooting:z.string().trim().max(3000).optional(),preferredResolution:preferred,serialNumber:z.string().trim().max(120).optional()}).parse(Object.fromEntries(formData));
  const item=await prisma.orderItem.findFirst({where:{id:data.orderItemId,order:{userId:ctx.user.id,paymentStatus:"PAID"}},include:{order:{include:{shipments:{orderBy:{deliveredAt:"desc"},take:1}}},product:true}});if(!item)throw new Error("Eligible paid order item not found.");if(data.quantityAffected>item.quantity)throw new Error("Affected quantity cannot exceed the ordered quantity.");
  const [reason,policy]=await Promise.all([prisma.complaintReason.findFirst({where:{id:data.reasonId,isActive:true}}),prisma.returnPolicyVersion.findFirst({where:{isCurrent:true,publishedAt:{not:null}},orderBy:{version:"desc"}})]);if(!reason)throw new Error("Select an active complaint reason.");
  const files=formData.getAll("evidence").filter((value):value is File=>value instanceof File&&value.size>0);if(reason.requiresProductPhoto&&!files.some(file=>file.type.startsWith("image/")))throw new Error("Please include at least one clear product photograph.");
  const number=reference("RET"),uploads=await uploadFiles(files,number);
  let createdReference="";
  try{
    await Promise.all([enqueueEmail(emailTemplates.returnAcknowledged(ctx.user.email,ctx.user.name??"Customer",number,item.productName),ctx.user.id),enqueueEmail(emailTemplates.returnInternalAlert(number,ctx.user.name??ctx.user.email,item.productName))]);
    const created=await prisma.$transaction(async tx=>{const row=await tx.returnCase.create({data:{referenceNumber:number,customerId:ctx.user.id,orderId:item.orderId,orderItemId:item.id,productId:item.productId,reasonId:reason.id,policyVersionId:policy?.id,createdById:ctx.user.id,source:"CUSTOMER_PORTAL",status:"SUBMITTED",assessmentStatus:reason.requiresInspection?"AWAITING_ASSIGNMENT":"NOT_REQUIRED",quantityAffected:data.quantityAffected,productNameSnapshot:item.productName,skuSnapshot:item.sku,unitPriceSnapshot:item.unitPrice,warrantySnapshot:item.product?.warranty,serialNumber:data.serialNumber||null,customerDescription:data.customerDescription,problemStartedAt:data.problemStartedAt,usageDescription:data.usageDescription||null,troubleshooting:data.troubleshooting||null,preferredResolution:data.preferredResolution,submittedAt:new Date(),isTestData:item.order.isTestData}});for(const upload of uploads){const document=await tx.uploadedDocument.create({data:{bucket:upload.bucket,path:upload.path,originalName:upload.file.name,mimeType:upload.file.type,size:upload.file.size,isPrivate:true,isTestData:item.order.isTestData}});await tx.returnEvidence.create({data:{returnCaseId:row.id,documentId:document.id,type:upload.file.type.startsWith("video/")?"CUSTOMER_VIDEO":"CUSTOMER_EVIDENCE",uploadedById:ctx.user.id}})}await tx.returnCaseEvent.create({data:{returnCaseId:row.id,actorId:ctx.user.id,type:"COMPLAINT_SUBMITTED",customerVisible:true,message:"Request received. Assessment is required before a resolution can be confirmed."}});await tx.auditLog.create({data:{actorId:ctx.user.id,action:"return.submit",entityType:"ReturnCase",entityId:row.id,after:{referenceNumber:number,orderId:item.orderId,orderItemId:item.id,reason:reason.name,source:"CUSTOMER_PORTAL"}}});return row});
    createdReference=created.referenceNumber;
  }catch(error){await removeUploads(uploads);throw error}
  redirect(`/account/returns/${createdReference}`);
}

export async function createManualReturn(formData:FormData){
  const ctx=await requirePermission("returns.create");const data=z.object({orderItemId:z.string().uuid(),reasonId:z.string().uuid(),quantityAffected:z.coerce.number().int().positive(),customerDescription:z.string().trim().min(10).max(5000),preferredResolution:preferred,source:z.enum(["ADMIN_MANUAL","EMAIL","WHATSAPP","TELEPHONE","IMPORTED","API"]),serialNumber:z.string().trim().max(120).optional()}).parse(Object.fromEntries(formData));
  const item=await prisma.orderItem.findUnique({where:{id:data.orderItemId},include:{order:{include:{user:true}},product:true}});if(!item||data.quantityAffected>item.quantity)throw new Error("Valid order item required.");const reason=await prisma.complaintReason.findFirstOrThrow({where:{id:data.reasonId,isActive:true}});const policy=await prisma.returnPolicyVersion.findFirst({where:{isCurrent:true}});
  const number=reference("RET");await enqueueEmail(emailTemplates.returnAcknowledged(item.order.email,item.order.user?.name??"Customer",number,item.productName),item.order.userId??undefined);
  const row=await prisma.$transaction(async tx=>{const saved=await tx.returnCase.create({data:{referenceNumber:number,customerId:item.order.userId,orderId:item.orderId,orderItemId:item.id,productId:item.productId,reasonId:reason.id,policyVersionId:policy?.id,createdById:ctx.user.id,source:data.source,status:"SUBMITTED",assessmentStatus:reason.requiresInspection?"AWAITING_ASSIGNMENT":"NOT_REQUIRED",quantityAffected:data.quantityAffected,productNameSnapshot:item.productName,skuSnapshot:item.sku,unitPriceSnapshot:item.unitPrice,warrantySnapshot:item.product?.warranty,serialNumber:data.serialNumber||null,customerDescription:data.customerDescription,preferredResolution:data.preferredResolution,submittedAt:new Date(),isTestData:item.order.isTestData}});await tx.returnCaseEvent.create({data:{returnCaseId:saved.id,actorId:ctx.user.id,type:"MANUAL_COMPLAINT_CREATED",customerVisible:true,message:`Request captured from ${data.source.replaceAll("_"," ").toLowerCase()}.`}});return saved});redirect(`/admin/returns/${row.id}`)
}

export async function assignReturnInspection(formData:FormData){
  const ctx=await requirePermission("returns.assign-technician");const data=z.object({returnCaseId:z.string().uuid(),technicianId:z.string().uuid(),appointmentAt:optionalDate,expectedCompletionAt:optionalDate,location:z.string().trim().max(500).optional(),instructions:z.string().trim().max(3000).optional()}).parse(Object.fromEntries(formData));const [row,technician]=await Promise.all([prisma.returnCase.findUniqueOrThrow({where:{id:data.returnCaseId}}),prisma.user.findUniqueOrThrow({where:{id:data.technicianId}})]);await enqueueEmail(emailTemplates.technicianReturnAssignment(technician.email,row.referenceNumber,row.productNameSnapshot,data.expectedCompletionAt),technician.id);await prisma.$transaction([prisma.returnInspection.create({data:{returnCaseId:row.id,technicianId:technician.id,status:data.appointmentAt?"APPOINTMENT_SCHEDULED":"ASSIGNED",appointmentAt:data.appointmentAt,expectedCompletionAt:data.expectedCompletionAt,location:data.location||null,instructions:data.instructions||null}}),prisma.returnCase.update({where:{id:row.id},data:{assignedTechnicianId:technician.id,status:"AWAITING_ASSESSMENT",assessmentStatus:data.appointmentAt?"APPOINTMENT_SCHEDULED":"ASSIGNED"}}),prisma.returnCaseEvent.create({data:{returnCaseId:row.id,actorId:ctx.user.id,type:"TECHNICIAN_ASSIGNED",customerVisible:true,message:data.appointmentAt?`Assessment appointment scheduled for ${data.appointmentAt.toLocaleString("en-ZA")}.`:"A technician has been assigned to assess the product."}})]);revalidatePath(`/admin/returns/${row.id}`)
}

export async function submitReturnInspection(formData:FormData){
  const ctx=await requirePermission("returns.inspections.perform");const data=z.object({inspectionId:z.string().uuid(),serialNumberConfirmed:z.string().trim().max(120).optional(),barcode:z.string().trim().max(160).optional(),testResults:z.string().trim().min(10).max(5000),finding:z.string().trim().min(2).max(160),findingExplanation:z.string().trim().min(10).max(5000),recommendation:preferred,technicianCost:z.coerce.number().min(0).default(0)}).parse(Object.fromEntries(formData));const inspection=await prisma.returnInspection.findFirst({where:{id:data.inspectionId,technicianId:ctx.user.id},include:{returnCase:{include:{customer:true}}}});if(!inspection&&!ctx.isSuperAdministrator)throw new Error("You may only submit inspections assigned to you.");const record=inspection??await prisma.returnInspection.findUniqueOrThrow({where:{id:data.inspectionId},include:{returnCase:{include:{customer:true}}}});
  const checklist={correctProduct:formData.get("correctProduct")==="on",physicalDamage:formData.get("physicalDamage")==="on",packagingDamaged:formData.get("packagingDamaged")==="on",accessoriesPresent:formData.get("accessoriesPresent")==="on",powersOn:formData.get("powersOn")==="on",liquidDamage:formData.get("liquidDamage")==="on",impactDamage:formData.get("impactDamage")==="on",tampering:formData.get("tampering")==="on",unsafe:formData.get("unsafe")==="on"};
  const files=formData.getAll("evidence").filter((value):value is File=>value instanceof File&&value.size>0);if(["Manufacturing defect","Delivery damage","Physical damage","Non-repairable fault"].includes(data.finding)&&!files.some(file=>file.type.startsWith("image/")))throw new Error("Photographic evidence is required for confirmed damage or defects.");const uploads=await uploadFiles(files,`${record.returnCase.referenceNumber}/inspection`);
  try{await prisma.$transaction(async tx=>{await tx.returnInspection.update({where:{id:record.id},data:{status:"SUBMITTED",serialNumberConfirmed:data.serialNumberConfirmed||null,barcode:data.barcode||null,checklist,testResults:data.testResults,finding:data.finding,findingExplanation:data.findingExplanation,recommendation:data.recommendation,technicianCost:new Decimal(data.technicianCost),submittedAt:new Date()}});for(const upload of uploads){const doc=await tx.uploadedDocument.create({data:{bucket:upload.bucket,path:upload.path,originalName:upload.file.name,mimeType:upload.file.type,size:upload.file.size,isPrivate:true,isTestData:record.returnCase.isTestData}});await tx.returnEvidence.create({data:{returnCaseId:record.returnCaseId,inspectionId:record.id,documentId:doc.id,type:"INSPECTION_EVIDENCE",uploadedById:ctx.user.id,customerVisible:false}})}await tx.returnCase.update({where:{id:record.returnCaseId},data:{status:"DECISION_PENDING",assessmentStatus:"SUBMITTED"}});await tx.returnCaseEvent.create({data:{returnCaseId:record.returnCaseId,actorId:ctx.user.id,type:"INSPECTION_SUBMITTED",customerVisible:true,message:"The product assessment is complete and the resolution is under internal review.",newValue:{finding:data.finding,recommendation:data.recommendation}}})});await enqueueEmail(emailTemplates.returnInternalAlert(record.returnCase.referenceNumber,record.returnCase.customer?.name??record.returnCase.customer?.email??"Customer",record.returnCase.productNameSnapshot));}catch(error){await removeUploads(uploads);throw error}revalidatePath(`/admin/returns/${record.returnCaseId}`)
}

export async function decideReturnResolution(formData:FormData){
  const data=z.object({returnCaseId:z.string().uuid(),type:z.enum(["GUIDANCE","REPAIR","REPLACEMENT","EXCHANGE","FULL_REFUND","PARTIAL_REFUND","STORE_CREDIT","REJECTED","RETURN_TO_CUSTOMER","ESCALATE_TO_DISTRIBUTOR"]),customerExplanation:z.string().trim().min(10).max(5000),internalExplanation:z.string().trim().max(5000).optional(),approvedAmount:z.coerce.number().min(0).default(0),deductionAmount:z.coerce.number().min(0).default(0),deductionReason:z.string().trim().max(1000).optional()}).parse(Object.fromEntries(formData));
  const permission=data.type==="FULL_REFUND"||data.type==="PARTIAL_REFUND"?"returns.refund.approve":data.type==="REPAIR"?"returns.repair.approve":data.type==="REPLACEMENT"||data.type==="EXCHANGE"?"returns.replacement.approve":data.type==="REJECTED"?"returns.reject":"returns.review";
  const ctx=await requirePermission(permission);
  const row=await prisma.returnCase.findUniqueOrThrow({where:{id:data.returnCaseId},include:{customer:true,reason:true,order:{include:{payments:{where:{status:"PAID"},take:1}}},inspections:{where:{status:{in:["SUBMITTED","COMPLETED"]}},orderBy:{submittedAt:"desc"},take:1}}});
  if(row.resolutionType!=="PENDING"||row.resolutionStatus!=="PENDING")throw new Error("This case already has a recorded resolution.");
  if(row.reason.requiresInspection&&!row.inspections[0])throw new Error("The required technical inspection must be submitted before a resolution can be approved.");
  const max=Number(row.unitPriceSnapshot)*row.quantityAffected;if(data.approvedAmount>max)throw new Error("Approved amount cannot exceed the affected item value.");
  await enqueueEmail(emailTemplates.returnUpdate(row.customer?.email??row.order.email,row.customer?.name??"Customer",row.referenceNumber,data.type,data.customerExplanation),row.customerId??undefined);
  await prisma.$transaction(async tx=>{
    const resolution=await tx.returnResolution.create({data:{returnCaseId:row.id,inspectionId:row.inspections[0]?.id,decidedById:ctx.user.id,type:data.type,status:data.type==="REJECTED"?"REJECTED":"APPROVED",customerExplanation:data.customerExplanation,internalExplanation:data.internalExplanation||null,approvedAmount:new Decimal(data.approvedAmount),deductionAmount:new Decimal(data.deductionAmount),deductionReason:data.deductionReason||null}});
    const refund=data.type==="FULL_REFUND"||data.type==="PARTIAL_REFUND";
    if(refund)await tx.returnRefund.create({data:{refundNumber:reference("RFD"),returnCaseId:row.id,resolutionId:resolution.id,originalPaymentId:row.order.payments[0]?.id,approvedById:ctx.user.id,status:"AWAITING_PAYMENT",originalAmount:new Decimal(max),refundableAmount:new Decimal(max),approvedAmount:new Decimal(data.approvedAmount),deductions:new Decimal(data.deductionAmount),deductionReason:data.deductionReason||null,method:"EFT",isTestData:row.isTestData}});
    if(data.type==="REPAIR")await tx.returnRepair.create({data:{repairNumber:reference("RPR"),returnCaseId:row.id,resolutionId:resolution.id,status:"APPROVED"}});
    if(data.type==="REPLACEMENT"||data.type==="EXCHANGE")await tx.returnReplacement.create({data:{replacementNumber:reference("RPL"),returnCaseId:row.id,resolutionId:resolution.id,status:"APPROVED",productNameSnapshot:row.productNameSnapshot,quantity:row.quantityAffected,serialNumbers:[]}});
    const operational=["REPAIR","REPLACEMENT","EXCHANGE"].includes(data.type);
    await tx.returnCase.update({where:{id:row.id},data:{status:data.type==="REJECTED"?"REJECTED":"RESOLVED",resolutionType:data.type,resolutionStatus:data.type==="REJECTED"?"REJECTED":operational?"IN_PROGRESS":"APPROVED",refundStatus:refund?"AWAITING_PAYMENT":"NOT_REQUIRED",resolvedAt:operational?null:new Date()}});
    await tx.returnCaseEvent.create({data:{returnCaseId:row.id,actorId:ctx.user.id,type:"RESOLUTION_DECIDED",customerVisible:true,message:data.customerExplanation,newValue:{type:data.type,approvedAmount:data.approvedAmount}}});
    await tx.auditLog.create({data:{actorId:ctx.user.id,action:"return.resolve",entityType:"ReturnCase",entityId:row.id,after:{type:data.type,approvedAmount:data.approvedAmount}}});
  });revalidatePath(`/admin/returns/${row.id}`)
}

export async function recordRefundPayment(formData:FormData){
  const ctx=await requirePermission("returns.refund.confirm");const data=z.object({refundId:z.string().uuid(),amount:z.coerce.number().positive(),paidAt:z.coerce.date(),method:z.string().trim().min(2).max(80),bankReference:z.string().trim().max(160).optional(),transactionReference:z.string().trim().min(3).max(160),notes:z.string().trim().max(2000).optional()}).parse(Object.fromEntries(formData));const refund=await prisma.returnRefund.findUniqueOrThrow({where:{id:data.refundId},include:{returnCase:{include:{customer:true,order:true}}}});if(refund.approvedById===ctx.user.id)throw new Error("The refund approver cannot also confirm payment.");if(refund.status!=="AWAITING_PAYMENT"&&refund.status!=="FAILED")throw new Error("This refund is not awaiting payment.");if(data.amount!==Number(refund.approvedAmount))throw new Error("Confirmed payment must equal the approved refund amount.");const file=formData.get("proof");const uploads=file instanceof File&&file.size?await uploadFiles([file],`${refund.returnCase.referenceNumber}/refund`):[];
  await enqueueEmail(emailTemplates.returnUpdate(refund.returnCase.customer?.email??refund.returnCase.order.email,refund.returnCase.customer?.name??"Customer",refund.returnCase.referenceNumber,"REFUND_COMPLETED",`Your refund of R ${data.amount.toFixed(2)} has been processed using ${data.method}. Reference: ${data.transactionReference}.`),refund.returnCase.customerId??undefined);
  try{await prisma.$transaction(async tx=>{
    let documentId:string|undefined;
    if(uploads[0]){const doc=await tx.uploadedDocument.create({data:{bucket:uploads[0].bucket,path:uploads[0].path,originalName:uploads[0].file.name,mimeType:uploads[0].file.type,size:uploads[0].file.size,isPrivate:true,isTestData:refund.isTestData}});documentId=doc.id}
    await tx.returnRefundPayment.create({data:{refundId:refund.id,processedById:ctx.user.id,proofDocumentId:documentId,amount:new Decimal(data.amount),method:data.method,bankReference:data.bankReference||null,transactionReference:data.transactionReference,paidAt:data.paidAt,notes:data.notes||null}});
    await tx.returnRefund.update({where:{id:refund.id},data:{status:"COMPLETED",completedAt:new Date()}});
    await tx.returnCase.update({where:{id:refund.returnCaseId},data:{refundStatus:"COMPLETED",resolutionStatus:"COMPLETED"}});
    await tx.returnCaseEvent.create({data:{returnCaseId:refund.returnCaseId,actorId:ctx.user.id,type:"REFUND_PAID",customerVisible:true,message:`Refund payment completed. Reference: ${data.transactionReference}.`,newValue:{amount:data.amount,method:data.method}}});
    await tx.auditLog.create({data:{actorId:ctx.user.id,action:"return.refund.confirm-payment",entityType:"ReturnRefund",entityId:refund.id,after:{amount:data.amount,transactionReference:data.transactionReference}}});
  })}catch(error){await removeUploads(uploads);throw error}revalidatePath("/admin/returns");revalidatePath("/admin/payments")
}

export async function createDistributorClaim(formData:FormData){const ctx=await requirePermission("returns.claims.manage");const data=z.object({returnCaseId:z.string().uuid(),supplierId:z.string().uuid().optional().or(z.literal("")),faultDescription:z.string().trim().min(10).max(5000),requestedResolution:z.string().trim().min(2).max(200),claimAmount:z.coerce.number().min(0),followUpAt:optionalDate}).parse(Object.fromEntries(formData));const row=await prisma.returnCase.findUniqueOrThrow({where:{id:data.returnCaseId},include:{inspections:{where:{status:{in:["SUBMITTED","COMPLETED"]}},orderBy:{submittedAt:"desc"},take:1}}});await prisma.$transaction(async tx=>{const claim=await tx.distributorClaim.create({data:{claimNumber:reference("DCL"),returnCaseId:row.id,supplierId:data.supplierId||null,status:"DRAFT",productName:row.productNameSnapshot,productCode:row.skuSnapshot,serialNumber:row.serialNumber,faultDescription:data.faultDescription,technicianFinding:row.inspections[0]?.findingExplanation,requestedResolution:data.requestedResolution,claimAmount:new Decimal(data.claimAmount),followUpAt:data.followUpAt}});await tx.distributorClaimEvent.create({data:{distributorClaimId:claim.id,actorId:ctx.user.id,toStatus:"DRAFT",internalNote:"Distributor recovery claim created."}});await tx.returnCase.update({where:{id:row.id},data:{distributorClaimStatus:"DRAFT",resolutionType:row.resolutionType==="PENDING"?"ESCALATE_TO_DISTRIBUTOR":row.resolutionType}});await tx.returnCaseEvent.create({data:{returnCaseId:row.id,actorId:ctx.user.id,type:"DISTRIBUTOR_CLAIM_CREATED",message:"A separate distributor recovery claim was created."}})});revalidatePath(`/admin/returns/${row.id}`)}

export async function classifyReturnedUnit(formData:FormData){const ctx=await requirePermission("returns.inventory.classify");const data=z.object({returnCaseId:z.string().uuid(),serialNumber:z.string().trim().max(120).optional(),condition:z.enum(["AWAITING_ASSESSMENT","NEW_UNOPENED","OPEN_BOX","CUSTOMER_RETURN","TESTED_WORKING","REFURBISHED","REPAIRED","USED","COSMETIC_DAMAGE","FUNCTIONAL_DAMAGE","PARTIALLY_WORKING","NON_FUNCTIONAL","SPARE_PARTS","SCRAP"]),outcome:z.enum(["PENDING","RETURN_TO_CUSTOMER","RETURN_TO_DISTRIBUTOR","REPAIR","REPLACEMENT_RECEIVED","OPEN_BOX","REFURBISHED","USED","DAMAGED_STOCK","SPARE_PARTS","WRITE_OFF","DISPOSED","RESALE"]),receivedAt:optionalDate,returnMethod:z.string().trim().max(160).optional(),receivedBy:z.string().trim().max(160).optional(),conditionNotes:z.string().trim().max(5000).optional(),packagingCondition:z.string().trim().max(500).optional(),accessories:z.string().trim().max(1000).optional(),storageLocation:z.string().trim().max(200).optional(),costValue:z.coerce.number().min(0).default(0),recoveryTarget:z.coerce.number().min(0).default(0),approvedResalePrice:z.coerce.number().min(0).optional()}).parse(Object.fromEntries(formData));const row=await prisma.returnCase.findUniqueOrThrow({where:{id:data.returnCaseId}});await prisma.$transaction([prisma.returnedInventoryUnit.create({data:{returnCaseId:row.id,originalProductId:row.productId,serialNumber:data.serialNumber||row.serialNumber,condition:data.condition,outcome:data.outcome,status:data.outcome==="RESALE"?"RESALE_APPROVED":"CONDITION_CONFIRMED",receivedAt:data.receivedAt,returnMethod:data.returnMethod||null,receivedBy:data.receivedBy||null,conditionNotes:data.conditionNotes||null,packagingCondition:data.packagingCondition||null,accessories:data.accessories?.split(",").map(x=>x.trim()).filter(Boolean)??[],storageLocation:data.storageLocation||null,costValue:new Decimal(data.costValue),recoveryTarget:new Decimal(data.recoveryTarget),approvedResalePrice:data.approvedResalePrice===undefined?null:new Decimal(data.approvedResalePrice),approvedById:ctx.user.id}}),prisma.returnCase.update({where:{id:row.id},data:{inventoryOutcome:data.outcome}}),prisma.returnCaseEvent.create({data:{returnCaseId:row.id,actorId:ctx.user.id,type:"RETURNED_UNIT_CLASSIFIED",message:`Returned unit classified as ${data.condition.replaceAll("_"," ")} with outcome ${data.outcome.replaceAll("_"," ")}.`}})]);revalidatePath(`/admin/returns/${row.id}`)}
