import type { RfqStatus } from "@/generated/prisma/enums";

export const RFQ_TRANSITIONS: Record<RfqStatus, readonly RfqStatus[]> = {
  DRAFT: ["ANALYSING", "UNDER_REVIEW", "CANCELLED"],
  ANALYSING: ["READY_FOR_REVIEW", "ANALYSIS_FAILED", "CANCELLED"],
  ANALYSIS_FAILED: ["ANALYSING", "UNDER_REVIEW", "CANCELLED"],
  READY_FOR_REVIEW: ["UNDER_REVIEW", "ACCEPTED_FOR_PROCESSING", "DECLINED_INTERNAL", "CANCELLED"],
  UNDER_REVIEW: ["ACCEPTED_FOR_PROCESSING", "DECLINED_INTERNAL", "CANCELLED"],
  ACCEPTED_FOR_PROCESSING: ["PRICING_IN_PROGRESS", "CANCELLED"],
  DECLINED_INTERNAL: [],
  PRICING_IN_PROGRESS: ["AWAITING_APPROVAL", "CANCELLED"],
  AWAITING_APPROVAL: ["APPROVED", "REJECTED"],
  APPROVED: ["SUBMITTED", "CANCELLED"],
  REJECTED: ["PRICING_IN_PROGRESS", "CANCELLED"],
  SUBMITTED: ["WON", "LOST", "EXPIRED", "CANCELLED"],
  WON: ["COMPLETED", "CANCELLED"],
  LOST: [],
  CANCELLED: [],
  EXPIRED: [],
  COMPLETED: [],
};

export function assertRfqTransition(from: RfqStatus, to: RfqStatus) {
  if (!RFQ_TRANSITIONS[from].includes(to)) throw new Error(`RFQ cannot move from ${from} to ${to}.`);
}
