import Link from "next/link";
import { Search, ShoppingBag } from "lucide-react";
import { requireClientPortal } from "@/domain/client-portal/session";
import { prisma } from "@/lib/prisma";

export default async function PortalProductsPage({searchParams}:{searchParams:Promise<{q?:string}>}){
  await requireClientPortal();
  const{q=""}=await searchParams;
  const products=await prisma.product.findMany({where:{status:"PUBLISHED",deletedAt:null,...(q?{OR:[{name:{contains:q,mode:"insensitive"}},{sku:{contains:q,mode:"insensitive"}},{shortDescription:{contains:q,mode:"insensitive"}}]}:{})},include:{brand:true,category:true},orderBy:[{isFeatured:"desc"},{name:"asc"}],take:60});
  return <div className="mx-auto max-w-7xl"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-sky-700">Business catalogue</p><h1 className="mt-1 text-3xl font-semibold">Products for your organisation</h1><p className="mt-2 max-w-2xl text-sm text-slate-600">Browse our published range. You can request business pricing even when an item is out of stock—or ask us to source something not listed.</p></div><Link className="rounded-md bg-sky-700 px-4 py-3 text-sm font-bold text-white hover:bg-sky-800" href="/portal/requests/new">Request unlisted products</Link></header>
    <form className="mt-6 flex max-w-2xl gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-3.5 size-4 text-slate-400"/><input className="w-full rounded-md border border-slate-300 bg-white py-3 pl-10 pr-3 text-sm" defaultValue={q} name="q" placeholder="Search by product, brand or SKU"/></div><button className="rounded-md border border-slate-300 bg-white px-5 text-sm font-semibold">Search</button></form>
    <div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{products.map(product=><article className="flex flex-col rounded-xl border border-slate-200 bg-white p-5 shadow-sm" key={product.id}><div className="grid size-11 place-items-center rounded-lg bg-sky-50 text-sky-700"><ShoppingBag className="size-5"/></div><p className="mt-4 text-xs font-semibold uppercase tracking-wide text-slate-500">{product.brand?.name??product.category.name} · {product.sku}</p><h2 className="mt-1 text-lg font-semibold">{product.name}</h2><p className="mt-2 line-clamp-2 min-h-10 text-sm text-slate-600">{product.shortDescription??"Contact us for specifications and business pricing."}</p><div className="mt-4 flex items-center justify-between"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${product.stockStatus==="IN_STOCK"?"bg-emerald-100 text-emerald-800":product.stockStatus==="OUT_OF_STOCK"?"bg-amber-100 text-amber-800":"bg-sky-100 text-sky-800"}`}>{product.stockStatus.replaceAll("_"," ")}</span><span className="text-sm font-bold">R {Number(product.salePrice??product.regularPrice).toLocaleString("en-ZA",{minimumFractionDigits:2})}</span></div><Link className="mt-5 rounded-md bg-[#0b2745] px-4 py-2.5 text-center text-sm font-bold text-white hover:bg-sky-800" href={`/portal/requests/new?product=${product.id}`}>Add to quote request</Link></article>)}</div>
    {!products.length?<div className="mt-6 rounded-xl border border-dashed border-slate-300 bg-white p-10 text-center"><p className="font-semibold">No matching catalogue products</p><Link className="mt-2 inline-block text-sm font-bold text-sky-700" href="/portal/requests/new">Ask us to source it →</Link></div>:null}
  </div>;
}
