import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { MobilePushControl } from "@/components/mobile-admin/mobile-push-control";
import { Row, Section, Stat, card, money } from "@/components/mobile-admin/ui";

export default async function MobileAdminHome() {
  const now=new Date(),today=new Date(now);today.setHours(0,0,0,0);const activeSince=new Date(now.getTime()-15*60_000);
  const [orders,paidAction,awaitingPayment,pendingProof,openSupport,openReturns,openQuotes,activeUsers,socialToday,inventory,feedProblems]=await Promise.all([
    prisma.order.findMany({where:{isTestData:false},orderBy:{createdAt:"desc"},take:6,select:{id:true,orderNumber:true,email:true,grandTotal:true,status:true,createdAt:true}}),
    prisma.order.count({where:{isTestData:false,status:{in:["PAID","PAYMENT_VERIFIED"]}}}),prisma.order.count({where:{isTestData:false,status:"AWAITING_PAYMENT"}}),prisma.paymentProof.count({where:{status:"PENDING"}}),prisma.helpDeskTicket.count({where:{status:{in:["OPEN","IN_PROGRESS"]}}}),prisma.returnCase.count({where:{isTestData:false,status:{notIn:["DRAFT","RESOLVED","REJECTED","CLOSED"]}}}),prisma.quotationRequest.count({where:{isTestData:false,status:{in:["OPEN","IN_REVIEW"]}}}),prisma.session.findMany({where:{lastSeenAt:{gte:activeSince},expires:{gt:now},user:{status:"ACTIVE",deletedAt:null}},distinct:["userId"],select:{userId:true}}),prisma.socialContent.count({where:{createdAt:{gte:today}}}),prisma.inventory.findMany({select:{onHand:true,reserved:true,reorderLevel:true}}),prisma.supplierFeed.count({where:{enabled:true,OR:[{lastError:{not:null}},{nextSyncAt:{lt:now}}]}})
  ]);
  const lowStock=inventory.filter(item=>item.onHand-item.reserved<=item.reorderLevel).length;
  return <><div className="flex items-end justify-between"><div><h1 className="text-3xl font-black tracking-tight text-[#071b33]">Today</h1><p className="mt-1 text-sm text-slate-500">What needs attention right now.</p></div><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-emerald-800">Live</span></div><div className="mt-5 grid grid-cols-2 gap-3"><Stat label="Orders to accept" value={paidAction} tone={paidAction?"rose":"green"}/><Stat label="Awaiting payment" value={awaitingPayment} tone="amber"/><Stat label="Customer inbox" value={openSupport+openReturns+openQuotes} tone="blue"/><Stat label="Low stock" value={lowStock} tone={lowStock?"amber":"green"}/></div><div className="mt-5"><MobilePushControl/></div><Section title="Quick actions"><div className="grid grid-cols-2 gap-3"><Link href="/mobile-admin/orders" className="min-h-20 rounded-2xl bg-white p-4 text-sm font-black text-[#071b33] shadow-sm">Process orders<br/><span className="text-xs font-medium text-slate-500">{pendingProof} payment proof pending</span></Link><Link href="/mobile-admin/marketing" className="min-h-20 rounded-2xl bg-white p-4 text-sm font-black text-[#071b33] shadow-sm">Create content<br/><span className="text-xs font-medium text-slate-500">{socialToday} posts today</span></Link><Link href="/mobile-admin/stock" className="min-h-20 rounded-2xl bg-white p-4 text-sm font-black text-[#071b33] shadow-sm">Check suppliers<br/><span className="text-xs font-medium text-slate-500">{feedProblems} feed issues</span></Link><Link href="/mobile-admin/activity" className="min-h-20 rounded-2xl bg-white p-4 text-sm font-black text-[#071b33] shadow-sm">Signed in now<br/><span className="text-xs font-medium text-slate-500">{activeUsers.length} registered users</span></Link></div></Section><Section title="Latest orders" href="/mobile-admin/orders"><div className={card}>{orders.length?orders.map(order=><Row key={order.id} href={`/admin/orders/${order.id}`} title={order.orderNumber} meta={`${order.email} · ${money(order.grandTotal)}`} badge={order.status}/>):<p className="p-5 text-sm text-slate-500">No orders yet.</p>}</div></Section><p className="mt-6 text-center text-xs text-slate-400">Anonymous website traffic remains available in Google Analytics.</p></>;
}
