import Link from "next/link";
import { AdminPage, EmptyState, MetricCard, Panel, StatusBadge, buttonClass, inputClass, secondaryButtonClass, tableClass } from "@/components/admin/admin-ui";
import { requirePermission } from "@/domain/auth/session";
import { createAdminHelpDeskTicket } from "@/domain/communications/actions";
import { prisma } from "@/lib/prisma";

export default async function HelpDeskPage({searchParams}:{searchParams:Promise<{department?:string;status?:string}>}) {
  await requirePermission("customers.manage");
  const params=await searchParams;
  const [departments,tasks]=await Promise.all([prisma.department.findMany({where:{isActive:true},orderBy:{name:"asc"}}),prisma.serviceTask.count({where:{status:{in:["OPEN","IN_PROGRESS","BLOCKED"]}}})]);
  const selectedDepartment=departments.find(x=>x.name===params.department);
  const rows=await prisma.helpDeskTicket.findMany({where:{...(selectedDepartment?{departmentId:selectedDepartment.id}:{}),...(params.status?{status:params.status as never}:{})},include:{department:true,assignee:{select:{name:true,email:true}},_count:{select:{tasks:true}}},orderBy:[{priority:"desc"},{createdAt:"desc"}],take:150});
  return <AdminPage title="Ticketing centre" description="Every web, email, WhatsApp, phone and internal request becomes a routed, owned and measurable ticket." actions={<div className="flex gap-2"><a className={buttonClass} href="#new-ticket">Create ticket</a><Link className={secondaryButtonClass} href="/admin/calendar">Calendar</Link></div>}>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Open tickets" value={rows.filter(x=>x.status==="OPEN").length}/><MetricCard label="In progress" value={rows.filter(x=>x.status==="IN_PROGRESS").length}/><MetricCard label="Waiting for customer" value={rows.filter(x=>x.status==="WAITING_CUSTOMER").length}/><MetricCard label="Open to-dos" value={tasks} detail="Across all departments"/></div>
    <Panel title="Department queues" description="Filter the shared service queue by responsible team. Super administrators retain visibility across every queue."><div className="flex flex-wrap gap-2"><Link className={!selectedDepartment?"rounded-full bg-slate-900 px-3 py-1.5 text-xs font-bold text-white":"rounded-full border px-3 py-1.5 text-xs font-bold"} href="/admin/help-desk">All</Link>{departments.map(d=><Link className={selectedDepartment?.id===d.id?"rounded-full bg-sky-700 px-3 py-1.5 text-xs font-bold text-white":"rounded-full border px-3 py-1.5 text-xs font-bold text-slate-600"} href={`/admin/help-desk?department=${encodeURIComponent(d.name)}`} key={d.id}>{d.name}</Link>)}</div></Panel>
    <Panel title="Support queue" description="Open a ticket to route it, assign ownership, reply to the client and manage its to-do list."><div className="-mx-4 overflow-x-auto">{rows.length?<table className={tableClass}><thead><tr><th>Ticket</th><th>Customer</th><th>Request</th><th>Department / owner</th><th>Due</th><th>Status</th><th></th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><strong>{x.ticketNumber}</strong><br/><span className="text-xs text-slate-500">{x.sourceChannel} · {x.priority}</span></td><td>{x.name}<br/><span className="text-xs text-slate-500">{x.email}</span></td><td className="max-w-xs"><strong>{x.subject}</strong><p className="line-clamp-1 text-xs text-slate-500">{x.message}</p></td><td>{x.department?.name??"Unrouted"}<br/><span className="text-xs text-slate-500">{x.assignee?.name??x.assignee?.email??"Unassigned"} · {x._count.tasks} to-do(s)</span></td><td>{x.dueAt?.toLocaleString("en-ZA")??"Not set"}</td><td><StatusBadge value={x.status}/></td><td><Link className="font-semibold text-sky-700" href={`/admin/help-desk/${x.id}`}>Open</Link></td></tr>)}</tbody></table>:<EmptyState title="No support tickets" description="New customer and staff-captured requests will appear here automatically."/>}</div></Panel>
    <details id="new-ticket" className="scroll-mt-20 border border-slate-300 bg-white shadow-sm"><summary className="cursor-pointer list-none px-4 py-3 font-semibold [&::-webkit-details-marker]:hidden">Capture a phone, email, WhatsApp or internal request <span className="float-right text-sky-700">＋</span></summary><form action={createAdminHelpDeskTicket} className="grid gap-3 border-t p-4 sm:grid-cols-2 lg:grid-cols-4"><input className={inputClass} name="name" placeholder="Customer name" required/><input className={inputClass} name="email" type="email" placeholder="Customer email" required/><input className={inputClass} name="phone" placeholder="Phone"/><input className={inputClass} name="companyName" placeholder="Company"/><select className={inputClass} name="sourceChannel" defaultValue="PHONE">{["PHONE","EMAIL","WHATSAPP","WALK_IN","INTERNAL"].map(x=><option key={x}>{x}</option>)}</select><select className={inputClass} name="departmentId" required><option value="">Select department</option>{departments.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select><select className={inputClass} name="category" defaultValue="OTHER">{["QUOTATION","ORDER","PAYMENT","PRODUCT","TECHNICAL","ACCOUNT","OTHER"].map(x=><option key={x}>{x}</option>)}</select><select className={inputClass} name="priority" defaultValue="NORMAL">{["LOW","NORMAL","HIGH","URGENT"].map(x=><option key={x}>{x}</option>)}</select><input className={`${inputClass} sm:col-span-2`} name="subject" placeholder="Short subject" required/><textarea className={`${inputClass} min-h-20 sm:col-span-2`} name="message" placeholder="What was requested?" required/><div className="text-right sm:col-span-2 lg:col-span-4"><button className={buttonClass}>Create, route and notify</button></div></form></details>
  </AdminPage>;
}
