import Link from "next/link";
import { AdminPage,Panel,StatusBadge,buttonClass,tableClass } from "@/components/admin/admin-ui";
import { requirePermission } from "@/domain/auth/session";
import { createDeliveryNoteFromOrder } from "@/domain/documents/actions";
import { prisma } from "@/lib/prisma";

export default async function DeliveryNotesPage(){
  await requirePermission("orders.view");const [notes,orders]=await Promise.all([prisma.deliveryNote.findMany({include:{order:{select:{orderNumber:true}},responsibleStaff:{select:{name:true,email:true}}},orderBy:{createdAt:"desc"},take:100}),prisma.order.findMany({where:{status:{notIn:["DRAFT","CANCELLED","COMPLETED"]},deliveryNotes:{none:{status:{not:"CANCELLED"}}}},select:{id:true,orderNumber:true,companyName:true,email:true},orderBy:{createdAt:"desc"},take:50})]);
  return <AdminPage title="Delivery notes" description="One register for system-generated and manually captured delivery documents." actions={<Link className={buttonClass} href="/admin/delivery-notes/new">New manual delivery note</Link>}><div className="grid gap-3 sm:grid-cols-3"><Summary label="Documents" value={notes.length}/><Summary label="Ready" value={notes.filter(x=>x.status==="READY_FOR_DELIVERY").length}/><Summary label="Awaiting acknowledgement" value={notes.filter(x=>x.status==="DELIVERED").length}/></div>{orders.length?<Panel title="Generate from an order" description="Customer, delivery address and order items are copied automatically."><form action={createDeliveryNoteFromOrder} className="flex gap-2"><select className="min-h-11 min-w-0 flex-1 border border-slate-300 bg-white px-3" name="orderId" required><option value="">Select eligible order</option>{orders.map(x=><option key={x.id} value={x.id}>{x.orderNumber} · {x.companyName??x.email}</option>)}</select><button className={buttonClass}>Generate</button></form></Panel>:null}<Panel><div className="-mx-4 overflow-x-auto"><table className={tableClass}><thead><tr><th>Delivery note</th><th>Customer</th><th>Origin</th><th>Source</th><th>Delivery</th><th>Responsible</th><th>Status</th></tr></thead><tbody>{notes.map(x=><tr key={x.id}><td><Link className="font-bold text-sky-700" href={`/admin/delivery-notes/${x.id}`}>{x.deliveryNoteNumber}</Link></td><td>{x.companyName??x.customerName}</td><td>{x.origin}</td><td>{x.order?.orderNumber??x.reference??"Standalone"}</td><td>{x.deliveryDate?.toLocaleDateString("en-ZA")??"Not planned"}</td><td>{x.responsibleStaff?.name??x.responsibleStaff?.email??"Unassigned"}</td><td><StatusBadge value={x.status}/></td></tr>)}{!notes.length?<tr><td colSpan={7} className="py-10 text-center text-slate-500">No delivery notes recorded.</td></tr>:null}</tbody></table></div></Panel></AdminPage>;
}
function Summary({label,value}:{label:string;value:number}){return <div className="border border-slate-300 bg-white p-4"><p className="text-xs font-bold uppercase text-slate-500">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>}
