import { createPortalSupportRequest } from "@/domain/client-portal/actions";
import { requireClientPortal } from "@/domain/client-portal/session";
import { prisma } from "@/lib/prisma";

const field="mt-1 w-full rounded-md border border-slate-300 px-3 py-2.5 text-sm";
export default async function PortalSupportPage({searchParams}:{searchParams:Promise<{submitted?:string}>}){
  const{context}=await requireClientPortal();const{submitted}=await searchParams;
  const tickets=await prisma.helpDeskTicket.findMany({where:{customerId:context.user.id},orderBy:{createdAt:"desc"}});
  return <div className="mx-auto max-w-6xl"><p className="text-xs font-bold uppercase tracking-widest text-sky-700">Client service</p><h1 className="mt-1 text-3xl font-semibold">Support centre</h1><p className="mt-2 text-sm text-slate-600">Ask for product, order, delivery, technical or account assistance.</p>{submitted?<div className="mt-5 rounded-lg border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-800">Support request {submitted} was submitted.</div>:null}<div className="mt-6 grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><form action={createPortalSupportRequest} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-semibold">Open a request</h2><label className="mt-4 block text-sm font-semibold">Category<select className={field} name="category"><option>Product assistance</option><option>Quotation</option><option>Order or delivery</option><option>Technical support</option><option>Account or documents</option></select></label><label className="mt-4 block text-sm font-semibold">Subject<input className={field} name="subject" required/></label><label className="mt-4 block text-sm font-semibold">How can we help?<textarea className={field} name="message" required rows={6}/></label><button className="mt-4 rounded-md bg-sky-700 px-5 py-3 text-sm font-bold text-white">Submit request</button></form><section className="rounded-xl border border-slate-200 bg-white shadow-sm"><h2 className="border-b p-5 text-lg font-semibold">Your support history</h2><div className="divide-y">{tickets.map(ticket=><div className="p-5" key={ticket.id}><div className="flex flex-wrap justify-between gap-2"><strong>{ticket.ticketNumber} · {ticket.subject}</strong><span className="rounded-full bg-rose-50 px-3 py-1 text-xs font-bold text-rose-800">{ticket.status.replaceAll("_"," ")}</span></div><p className="mt-2 line-clamp-2 text-sm text-slate-600">{ticket.message}</p><p className="mt-2 text-xs text-slate-400">{ticket.createdAt.toLocaleString("en-ZA")}</p></div>)}{!tickets.length?<p className="p-8 text-center text-sm text-slate-500">No support requests yet.</p>:null}</div></section></div></div>;
}
