import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { requirePermission } from "@/domain/auth/session";
import { setOrderStatus } from "@/domain/admin/actions";
import { allowedOrderTransitions, currentOperationalTime, orderStageContext } from "@/domain/orders/lifecycle";
import { AdminPage, Panel, StatusBadge, inputClass, tableClass } from "@/components/admin/admin-ui";
import { OrderProgress } from "@/components/orders/order-progress";
import { DocumentActions } from "@/components/admin/document-actions";

export default async function AdminOrderDetail({ params }: { params: Promise<{ id: string }> }) {
  await requirePermission("orders.view");
  const order = await prisma.order.findUnique({ where: { id: (await params).id }, include: { items: true, payments: true, shipments: { orderBy: { createdAt: "desc" } }, transports: { orderBy: { createdAt: "desc" }, include: { provider: { select: { name: true } }, responsibleUser: { select: { name: true, email: true } } } }, returnCases: { orderBy: { createdAt: "desc" }, select: { id: true, referenceNumber: true, status: true, resolutionType: true } }, statusHistory: { orderBy: { createdAt: "desc" }, include: { actor: { select: { name: true, email: true } } } }, deliveryEvents: { orderBy: { occurredAt: "desc" } }, convertedQuotation: { select: { quotationNumber: true } } } });
  if (!order) notFound();
  const hasSupplierItems = order.items.some(item => item.sourceType === "SUPPLIER" || Boolean(item.supplierId));
  const transitions = allowedOrderTransitions(order.status).filter(status => !(order.status === "PROCESSING" && status === "ITEMS_RECEIVED" && hasSupplierItems) && !(order.status === "PROCESSING" && status === "SOURCING_ITEMS" && !hasSupplierItems) && !(["DISPATCHED", "IN_TRANSIT", "DELIVERED"].includes(status) && order.shipments.length === 0));
  const stage = orderStageContext(order.status);
  const acceptanceMinutes=Math.floor((currentOperationalTime()-(order.payments.find(payment=>payment.status==="PAID")?.paidAt??order.updatedAt).getTime())/60_000),acceptanceOverdue=order.status==="PAYMENT_VERIFIED"&&acceptanceMinutes>=30;
  const health = acceptanceOverdue?"Acceptance overdue":order.returnCases.some(item=>!["RESOLVED","REJECTED","CLOSED"].includes(item.status)) ? "Attention required" : order.status === "SOURCING_ITEMS" ? "Waiting on supplier" : "On track";
  return <AdminPage title={order.orderNumber} description={`${order.companyName ?? order.email} · paid order fulfilment`} actions={<><a className="font-semibold text-sky-700" href={`/admin/orders/${order.id}/delivery`}>Plan delivery</a><DocumentActions type="ORDER" id={order.id} label="order confirmation"/><a className="font-semibold text-sky-700" href={`/api/orders/${order.orderNumber}/delivery-note`} target="_blank">Delivery note</a><StatusBadge value={order.status}/></>}>
    {order.status==="PAYMENT_VERIFIED"?<div className={`border-l-4 p-4 ${acceptanceOverdue?"border-red-600 bg-red-50 text-red-900":"border-amber-500 bg-amber-50 text-amber-900"}`}><strong>{acceptanceOverdue?"Paid order acceptance is overdue":"Paid order requires acceptance"}</strong><p className="mt-1 text-sm">Payment is verified. Confirm supplier or local availability and move this order to Processing now. Target: within 30 minutes of purchase.</p></div>:null}
    <Panel title="End-to-end order tracking" description="One controlled lifecycle from verified payment through delivery and after-sales."><OrderProgress status={order.status}/></Panel>
    <div className="grid gap-px border border-slate-200 bg-slate-200 sm:grid-cols-2 xl:grid-cols-5">
      {[['Current phase',stage.phase],['Why it is here',stage.reason],['Next action',stage.next],['Owner',stage.owner],['Health',health]].map(([label,value])=><div className="bg-white p-4" key={label}><p className="text-[10px] font-bold uppercase tracking-wider text-slate-500">{label}</p><p className={`mt-2 text-sm font-semibold ${label==='Health'&&health!=='On track'?'text-amber-700':'text-slate-900'}`}>{value}</p></div>)}
    </div>
    <div className="grid gap-4 xl:grid-cols-[1.4fr_.8fr]"><div className="space-y-4">
      <Panel><div className="flex flex-wrap justify-between gap-4"><div><h2 className="font-bold">Customer and payment</h2><p className="mt-2 text-sm">{order.email}<br/>{order.phone ?? "No phone supplied"}{order.convertedQuotation ? <><br/>Quotation {order.convertedQuotation.quotationNumber}</> : null}</p></div><div className="text-right"><StatusBadge value={order.paymentStatus}/><p className="mt-2 text-2xl font-bold">R {Number(order.grandTotal).toLocaleString("en-ZA", { minimumFractionDigits: 2 })}</p></div></div></Panel>
      <Panel><h2 className="font-bold">Immutable order snapshot</h2><table className={`${tableClass} mt-4`}><thead><tr><th>Product</th><th>SKU</th><th>Quantity</th><th>Unit</th><th>Total</th></tr></thead><tbody>{order.items.map((item) => <tr key={item.id}><td>{item.productName}</td><td>{item.sku}</td><td>{item.quantity}</td><td>R {item.unitPrice.toString()}</td><td>R {item.lineTotal.toString()}</td></tr>)}</tbody></table></Panel>
      {hasSupplierItems ? <Panel title="Supplier procurement" description="Supplier-sourced lines remain visible separately from local inventory."><table className={tableClass}><thead><tr><th>Product</th><th>Supplier SKU</th><th>Source</th><th>Readiness</th></tr></thead><tbody>{order.items.filter(item=>item.sourceType==="SUPPLIER"||item.supplierId).map(item=><tr key={item.id}><td>{item.productName}</td><td>{item.supplierSku??item.sku}</td><td>{item.sourceType.replaceAll('_',' ')}</td><td>{["ITEMS_RECEIVED","PACKING","READY_FOR_DELIVERY","DISPATCHED","IN_TRANSIT","DELIVERED","COMPLETED"].includes(order.status)?"Received":"Awaiting procurement confirmation"}</td></tr>)}</tbody></table></Panel> : null}
      {transitions.length ? <Panel><h2 className="font-bold">Publish fulfilment update</h2><p className="mt-1 text-sm text-slate-600">Only valid next stages are available. Customer-facing notes appear in tracking and email.</p><form action={setOrderStatus} className="mt-4 grid gap-3"><input type="hidden" name="id" value={order.id}/><label>Next stage<select className={`${inputClass} mt-1 w-full`} name="status" required>{transitions.map((status) => <option key={status} value={status}>{status.replaceAll("_", " ")}</option>)}</select></label><label>Customer-facing update<textarea className={`${inputClass} mt-1 min-h-20 w-full`} name="note" required/></label><label>Private operations note<textarea className={`${inputClass} mt-1 min-h-20 w-full`} name="internalNote"/></label>{transitions.includes("CANCELLED") ? <label className="rounded border border-red-200 bg-red-50 p-3 text-sm text-red-900"><input className="mr-2" type="checkbox" name="refundConfirmed"/>I confirm the paid amount was refunded. Cancellation releases reserved stock and is finance-controlled.</label> : null}<button className="min-h-11 bg-sky-700 px-4 font-bold text-white">Record and notify customer</button></form></Panel> : <Panel><p className="text-sm text-slate-600">This order is in a terminal state and has no further fulfilment transitions.</p></Panel>}
    </div><aside className="space-y-4"><Panel><h2 className="font-bold">Customer tracking</h2><p className="mt-2 text-xs text-slate-500">Customers see five simple milestones and public updates only. Private supplier, cost and exception notes stay internal.</p></Panel>{order.transports.length?<Panel title="Transport and delivery">{order.transports.map(record=><div className="border-b py-3 last:border-0" key={record.id}><div className="flex justify-between gap-3"><strong className="text-sm">{record.referenceNumber}</strong><StatusBadge value={record.status}/></div><p className="mt-1 text-xs text-slate-500">{record.provider?.name??record.driverName??"Provider not assigned"} · Owner: {record.responsibleUser?.name??record.responsibleUser?.email??"Unassigned"}</p></div>)}</Panel>:null}{order.returnCases.length?<Panel title="After-sales cases">{order.returnCases.map(item=><a className="block border-b py-3 text-sm last:border-0" href={`/admin/returns/${item.id}`} key={item.id}><strong>{item.referenceNumber}</strong><span className="ml-2 text-slate-500">{item.status.replaceAll('_',' ')} · {item.resolutionType.replaceAll('_',' ')}</span></a>)}</Panel>:null}<Panel><h2 className="font-bold">Activity timeline</h2><div className="mt-4 space-y-4">{order.deliveryEvents.map((event) => <div className="border-l-2 border-sky-500 pl-3" key={event.id}><p className="text-sm font-semibold">{event.status.replaceAll("_", " ")}</p><p className="text-xs text-slate-500">{event.occurredAt.toLocaleString("en-ZA")}</p>{event.publicNote ? <p className="mt-1 text-sm">Customer: {event.publicNote}</p> : null}{event.internalNote ? <p className="mt-1 text-xs text-red-700">Internal: {event.internalNote}</p> : null}</div>)}</div></Panel></aside></div>
  </AdminPage>;
}
