import Image from "next/image";
import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { generateMobileSocialContent } from "@/domain/mobile-admin/actions";
import { DAILY_SOCIAL_TYPES } from "@/domain/marketing/social-content";
import { Section, Stat, card } from "@/components/mobile-admin/ui";

const labels:Record<string,string>={ALL:"All",PRODUCT:"Products",PC_BUILDER:"PC Builder",GAMING:"Gaming"};
export default async function MobileMarketing({searchParams}:{searchParams:Promise<{result?:string;type?:string}>}) {
  const {result,type}=await searchParams;
  const selected=type&&["ALL",...DAILY_SOCIAL_TYPES].includes(type)?type:"ALL";
  const today=new Date();today.setHours(0,0,0,0);
  const content=await prisma.socialContent.findMany({where:{createdAt:{gte:today},contentType:selected==="ALL"?{in:[...DAILY_SOCIAL_TYPES]}:selected},orderBy:{createdAt:"desc"},take:6});
  return <><h1 className="text-3xl font-black text-[#071b33]">Daily marketing</h1><p className="mt-1 text-sm text-slate-500">Three product and feature posts for South African customers.</p>{result?<p className={`mt-4 rounded-xl p-3 text-sm font-bold ${result==="failed"?"bg-rose-50 text-rose-800":"bg-emerald-50 text-emerald-800"}`}>{result==="failed"?"Content generation failed. Open the full workspace for details.":`Generation: ${result.replaceAll("-"," ")}.`}</p>:null}<div className="mt-5 grid grid-cols-2 gap-3"><Stat label="Posts today" value={content.length} tone="blue"/><Stat label="Daily target" value="3" tone={content.length>=3?"green":"amber"}/></div><form action={generateMobileSocialContent} className="mt-4"><button className="min-h-12 w-full rounded-xl bg-[#0a6ed1] px-4 text-sm font-black text-white">Generate today’s three posts</button></form><div className="mt-5 flex gap-2 overflow-x-auto pb-1">{Object.entries(labels).map(([value,label])=><Link key={value} href={value==="ALL"?"/mobile-admin/marketing":`/mobile-admin/marketing?type=${value}`} className={`shrink-0 rounded-full px-4 py-2 text-xs font-bold ${selected===value?"bg-[#071b33] text-white":"border border-slate-300 bg-white text-slate-600"}`}>{label}</Link>)}</div><Section title="Today’s posts"><div className={card}>{content.length?content.map(item=><article key={item.id} className="border-b border-slate-100 p-4 last:border-0"><div className="grid grid-cols-[88px_1fr] gap-3"><a href={item.imageUrl} target="_blank" rel="noreferrer" className="relative aspect-[4/5] overflow-hidden rounded-lg bg-slate-100"><Image src={item.imageUrl} alt={item.imageAlt} fill sizes="88px" className="object-cover"/></a><div className="min-w-0"><span className="text-[10px] font-black uppercase text-sky-700">{labels[item.contentType]??item.contentType}</span><h2 className="mt-1 text-sm font-black text-slate-900">{item.title}</h2><p className="mt-1 line-clamp-4 whitespace-pre-wrap text-xs leading-5 text-slate-600">{item.caption}</p></div></div><div className="mt-3 flex justify-end"><a href={item.imageUrl} target="_blank" rel="noreferrer" download className="min-h-10 px-3 py-2 text-xs font-bold text-sky-700">Download full-size image</a></div></article>):<p className="p-5 text-sm text-slate-500">No matching post generated today.</p>}</div></Section><Link href="/admin/marketing/social" className="mt-5 block min-h-11 rounded-xl border border-slate-300 bg-white px-4 py-3 text-center text-sm font-bold text-slate-700">Open content library and filters</Link></>;
}
