import Link from "next/link";
import { AdminPage,Panel,buttonClass,inputClass,secondaryButtonClass } from "@/components/admin/admin-ui";
import { requirePermission } from "@/domain/auth/session";
import { createManualDeliveryNote } from "@/domain/documents/actions";
import { prisma } from "@/lib/prisma";

export default async function NewDeliveryNote(){
  await requirePermission("orders.update");const staff=await prisma.user.findMany({where:{status:"ACTIVE",accountType:"INTERNAL_EMPLOYEE"},select:{id:true,name:true,email:true},orderBy:{name:"asc"}});
  return <AdminPage title="Manual delivery note" description="Capture an external or offline delivery without creating a duplicate order." actions={<Link className={secondaryButtonClass} href="/admin/delivery-notes">Back</Link>}><Panel><form action={createManualDeliveryNote} className="grid gap-4 sm:grid-cols-2"><label>Customer name<input className={inputClass} name="customerName" required/></label><label>Company<input className={inputClass} name="companyName"/></label><label>Email<input className={inputClass} name="customerEmail" type="email"/></label><label>Phone<input className={inputClass} name="customerPhone"/></label><label className="sm:col-span-2">Delivery address<textarea className={`${inputClass} min-h-20`} name="deliveryAddress" required/></label><label>Planned delivery<input className={inputClass} name="deliveryDate" type="datetime-local"/></label><label>Delivery method<input className={inputClass} name="deliveryMethod" placeholder="Courier, own driver, collection…"/></label><label>Reference<input className={inputClass} name="reference" placeholder="PO, quotation or external reference"/></label><label>Responsible staff<select className={inputClass} name="responsibleStaffId"><option value="">Unassigned</option>{staff.map(x=><option key={x.id} value={x.id}>{x.name??x.email}</option>)}</select></label><label className="sm:col-span-2">Instructions<textarea className={`${inputClass} min-h-20`} name="instructions"/></label><div className="sm:col-span-2"><h2 className="font-bold">Items to deliver</h2></div>{Array.from({length:8},(_,i)=><div className="grid gap-2 border border-slate-200 p-3 sm:col-span-2 sm:grid-cols-[1fr_120px]" key={i}><input className={inputClass} name={`description_${i}`} placeholder={`Item ${i+1} description`} required={i===0}/><input className={inputClass} name={`quantity_${i}`} type="number" min="1" defaultValue={i===0?1:undefined} placeholder="Quantity"/></div>)}<button className={`${buttonClass} sm:col-span-2`}>Save delivery note</button></form></Panel></AdminPage>;
}
