import Link from "next/link";
import { AdminPage,Panel,buttonClass,inputClass,secondaryButtonClass } from "@/components/admin/admin-ui";
import { requirePermission } from "@/domain/auth/session";
import { createManualDeliveryNote } from "@/domain/documents/actions";
import { prisma } from "@/lib/prisma";
import { DynamicLineItems } from "@/components/admin/dynamic-line-items";

export default async function NewDeliveryNote(){
  await requirePermission("orders.update");const staff=await prisma.user.findMany({where:{status:"ACTIVE",accountType:"INTERNAL_EMPLOYEE"},select:{id:true,name:true,email:true},orderBy:{name:"asc"}});
  return <AdminPage title="Manual delivery note" description="Capture an external or offline delivery without creating a duplicate order." actions={<Link className={secondaryButtonClass} href="/admin/delivery-notes">Back</Link>}><Panel><form action={createManualDeliveryNote} className="grid gap-4 sm:grid-cols-2"><label>Customer name<input className={inputClass} name="customerName" required/></label><label>Company<input className={inputClass} name="companyName"/></label><label>Email<input className={inputClass} name="customerEmail" type="email"/></label><label>Phone<input className={inputClass} name="customerPhone"/></label><label className="sm:col-span-2">Delivery address<textarea className={`${inputClass} min-h-20`} name="deliveryAddress" required/></label><label>Planned delivery<input className={inputClass} name="deliveryDate" type="datetime-local"/></label><label>Delivery method<input className={inputClass} name="deliveryMethod" placeholder="Courier, own driver, collection…"/></label><label>Reference<input className={inputClass} name="reference" placeholder="PO, quotation or external reference"/></label><label>Responsible staff<select className={inputClass} name="responsibleStaffId"><option value="">Unassigned</option>{staff.map(x=><option key={x.id} value={x.id}>{x.name??x.email}</option>)}</select></label><label className="sm:col-span-2">Instructions<textarea className={`${inputClass} min-h-20`} name="instructions"/></label><div className="sm:col-span-2"><h2 className="font-bold">Items to deliver</h2><p className="text-sm text-slate-500">Start with one item and add or remove lines as required.</p></div><div className="sm:col-span-2"><DynamicLineItems kind="delivery"/></div><button className={`${buttonClass} sm:col-span-2`}>Save delivery note</button></form></Panel></AdminPage>;
}
