import Link from "next/link";
import { AdminPage,Panel,buttonClass,inputClass,secondaryButtonClass } from "@/components/admin/admin-ui";
import { requirePermission } from "@/domain/auth/session";
import { createManualDeliveryNote } from "@/domain/documents/actions";
import { prisma } from "@/lib/prisma";
import { DynamicLineItems } from "@/components/admin/dynamic-line-items";

export default async function NewDeliveryNote(){
  await requirePermission("orders.update");const staff=await prisma.user.findMany({where:{status:"ACTIVE",accountType:"INTERNAL_EMPLOYEE"},select:{id:true,name:true,email:true},orderBy:{name:"asc"}});
  const field="block text-sm font-semibold text-slate-700";
  return <AdminPage title="Manual delivery note" description="Capture an external or offline delivery without creating a duplicate order." actions={<Link className={secondaryButtonClass} href="/admin/delivery-notes">Back</Link>}><form action={createManualDeliveryNote} className="mx-auto w-full max-w-6xl space-y-4"><Panel title="Customer and destination"><div className="grid gap-4 md:grid-cols-2"><label className={field}>Customer name<span className="ml-1 text-rose-600">*</span><input className={`${inputClass} mt-1.5 w-full`} name="customerName" required/></label><label className={field}>Company <span className="font-normal text-slate-400">(optional)</span><input className={`${inputClass} mt-1.5 w-full`} name="companyName"/></label><label className={field}>Email address<input className={`${inputClass} mt-1.5 w-full`} name="customerEmail" type="email"/></label><label className={field}>Phone number<input className={`${inputClass} mt-1.5 w-full`} name="customerPhone"/></label><label className={`${field} md:col-span-2`}>Delivery address<span className="ml-1 text-rose-600">*</span><textarea className={`${inputClass} mt-1.5 min-h-24 w-full resize-y`} name="deliveryAddress" required/></label></div></Panel><Panel title="Delivery planning"><div className="grid gap-4 md:grid-cols-2"><label className={field}>Planned delivery<input className={`${inputClass} mt-1.5 w-full`} name="deliveryDate" type="datetime-local"/></label><label className={field}>Delivery method<input className={`${inputClass} mt-1.5 w-full`} name="deliveryMethod" placeholder="Courier, own driver or collection"/></label><label className={field}>Reference<input className={`${inputClass} mt-1.5 w-full`} name="reference" placeholder="PO, quotation or external reference"/></label><label className={field}>Responsible staff<select className={`${inputClass} mt-1.5 w-full`} name="responsibleStaffId"><option value="">Unassigned</option>{staff.map(x=><option key={x.id} value={x.id}>{x.name??x.email}</option>)}</select></label><label className={`${field} md:col-span-2`}>Delivery instructions<textarea className={`${inputClass} mt-1.5 min-h-20 w-full resize-y`} name="instructions"/></label></div></Panel><Panel title="Items to deliver" description="Start with one item and add or remove lines as required."><DynamicLineItems kind="delivery"/></Panel><div className="sticky bottom-3 z-10 flex flex-col gap-3 border border-slate-300 bg-white/95 p-3 shadow-lg backdrop-blur sm:flex-row sm:items-center sm:justify-between"><p className="text-sm text-slate-600">Save the document as a draft, then update its delivery status.</p><button className={`${buttonClass} w-full sm:w-auto`}>Save delivery note</button></div></form></AdminPage>;
}
