import Decimal from "decimal.js";
import {prisma} from "@/lib/prisma";
import {getCommerceSettings} from "@/domain/commerce/settings";
import {innozanziPrice} from "@/domain/commerce/engine";

export async function approveDecision(input:{id:string;actorId:string;expiresAt?:Date|null}){
  return prisma.$transaction(async tx=>{await tx.$queryRaw`SELECT pg_advisory_xact_lock(hashtextextended(${`trading:${input.id}`},0))::text AS locked`;const decision=await tx.tradingDecision.findUniqueOrThrow({where:{id:input.id},include:{product:true,session:true}});if(decision.status!=="PROPOSED"||!decision.proposedPrice)throw new Error("This recommendation is no longer awaiting review.");const benchmark=await tx.marketBenchmark.findFirst({where:{productKey:decision.productKey},orderBy:{observedAt:"desc"}});if(!benchmark||benchmark.confidence!=="HIGH"||!benchmark.normalMedian)throw new Error("High-confidence current market evidence is required.");if(benchmark.observedAt<new Date(Date.now()-35*86400000))throw new Error("Market evidence is stale. Run a new review.");const offer=decision.product.sourceType==="SUPPLIER"?await tx.supplierCatalogueProduct.findUnique({where:{id:decision.product.sourceId},select:{costPrice:true,feed:{select:{lastSuccessAt:true,enabled:true}}}}):null;if(!offer?.costPrice||!offer.feed.enabled||!offer.feed.lastSuccessAt)throw new Error("Current supplier cost and feed evidence are required.");const economics=innozanziPrice(offer.costPrice,await getCommerceSettings()),proposed=new Decimal(decision.proposedPrice);if(proposed.lt(economics.floor.gross))throw new Error("The recommendation is below the current protected floor.");const snapshot=decision.snapshot as Record<string,unknown>;if(String(snapshot.cost)!==offer.costPrice.toString()||String(snapshot.floor)!==economics.floor.gross.toString())throw new Error("Cost or floor changed after review. Generate a new recommendation.");const before=await tx.tradingPriceOverride.findUnique({where:{productKey:decision.productKey}});await tx.tradingPriceOverride.upsert({where:{productKey:decision.productKey},update:{price:proposed,source:"APPROVED_RECOMMENDATION",reason:decision.reason,createdById:input.actorId,expiresAt:input.expiresAt??null,version:crypto.randomUUID()},create:{productKey:decision.productKey,price:proposed,source:"APPROVED_RECOMMENDATION",reason:decision.reason,createdById:input.actorId,expiresAt:input.expiresAt??null}});await tx.tradingDecision.update({where:{id:decision.id},data:{status:"APPLIED",approvedById:input.actorId,approvedAt:new Date(),appliedAt:new Date()}});await tx.auditLog.create({data:{actorId:input.actorId,action:"trading.price.apply",entityType:"MarketProduct",entityId:decision.productKey,before:before?{price:before.price.toString(),version:before.version}:undefined,after:{price:proposed.toString(),decisionId:decision.id,cost:offer.costPrice.toString(),floor:economics.floor.gross.toString()}}});return {price:proposed.toFixed(2)};});
}
export async function rejectDecision(input:{id:string;actorId:string;reason:string}){await prisma.$transaction([prisma.tradingDecision.update({where:{id:input.id,status:"PROPOSED"},data:{status:"REJECTED",approvedById:input.actorId,approvedAt:new Date(),reason:input.reason}}),prisma.auditLog.create({data:{actorId:input.actorId,action:"trading.price.reject",entityType:"TradingDecision",entityId:input.id,after:{reason:input.reason}}})]);}
