import {getOpenAIClient} from "@/lib/openai";
import {marketIdentitySchema,observationSchema,validateObservation,type Observation,type MarketIdentity} from "./analysis";

const responseSchema={type:"object",additionalProperties:false,properties:{observations:{type:"array",maxItems:12,items:{type:"object",additionalProperties:false,properties:{retailer:{type:"string"},sourceUrl:{type:"string"},country:{type:"string",enum:["ZA"]},currency:{type:"string",enum:["ZAR"]},advertisedPrice:{type:"number"},regularPrice:{type:["number","null"]},promotionPrice:{type:["number","null"]},promotionDetected:{type:"boolean"},promotionType:{type:["string","null"]},stockState:{type:"string",enum:["IN_STOCK","OUT_OF_STOCK","UNKNOWN"]},condition:{type:"string",enum:["NEW","USED","REFURBISHED","UNKNOWN"]},brand:{type:["string","null"]},mpn:{type:["string","null"]},gtin:{type:["string","null"]},variant:{type:"object",additionalProperties:{type:"string"}},matchExplanation:{type:"string"}},required:Object.keys(observationSchema.shape)}}},required:["observations"]} as const;
function citationUrls(value:unknown,urls=new Set<string>()){if(!value||typeof value!=="object")return urls;if(Array.isArray(value)){for(const item of value)citationUrls(item,urls);return urls;}const row=value as Record<string,unknown>;if(row.type==="url_citation"&&typeof row.url==="string")urls.add(row.url);for(const item of Object.values(row))citationUrls(item,urls);return urls;}
export async function researchMarketProduct(rawIdentity:unknown):Promise<Observation[]>{
  const identity:MarketIdentity=marketIdentitySchema.parse(rawIdentity);
  const response=await getOpenAIClient().responses.create({model:process.env.OPENAI_MARKET_RESEARCH_MODEL??process.env.OPENAI_MODEL??"gpt-5.6-terra",store:false,tools:[{type:"web_search"}],include:["web_search_call.action.sources"],input:`Find current public South African retailer listings for this exact new product. Search using GTIN or brand plus manufacturer part number. Reject different RAM, storage, generation, model or other variant. Do not estimate prices. Return only in-stock ZAR evidence. Product identity: ${JSON.stringify(identity)}`,text:{format:{type:"json_schema",name:"market_observations",strict:true,schema:responseSchema}}},{timeout:60000});
  const parsed=JSON.parse(response.output_text||'{"observations":[]}') as {observations?:unknown[]},cited=citationUrls(response.output);
  return (parsed.observations??[]).flatMap(item=>{const valid=validateObservation(item,identity,cited);return valid?[valid]:[];});
}
