import {prisma} from "@/lib/prisma";
import {marketBenchmark,tradingPosition} from "./analysis";
import {claimMarketScanJobs,completeMarketScanJob,failMarketScanJob,finaliseTradingSession} from "./jobs";
import {researchMarketProduct} from "./research";
import {getTradingRules} from "./settings";
import {getCommerceSettings} from "@/domain/commerce/settings";
import {innozanziPrice} from "@/domain/commerce/engine";

export async function runTradingBatch(){const rules=await getTradingRules(),commerce=await getCommerceSettings(),jobs=await claimMarketScanJobs(rules.batchSize),results=[];for(const job of jobs){try{const identity={name:job.product.name,brand:job.product.brand,mpn:job.product.mpn,gtin:job.product.gtin,variant:job.product.variant},observations=await researchMarketProduct(identity),benchmark=marketBenchmark(observations,rules.minimumRetailers);const offer=job.product.sourceType==="SUPPLIER"?await prisma.supplierCatalogueProduct.findUnique({where:{id:job.product.sourceId},select:{costPrice:true}}):null;if(!offer?.costPrice)throw new Error("MISSING_CURRENT_COST");const cost=offer.costPrice,price=innozanziPrice(cost,commerce),position=tradingPosition({effectivePrice:price.gross,floor:price.floor.gross,benchmark,rules});await prisma.$transaction(async tx=>{for(const row of observations)await tx.marketObservation.upsert({where:{jobId_sourceUrl:{jobId:job.id,sourceUrl:row.sourceUrl}},update:{},create:{jobId:job.id,productKey:job.productKey,retailer:row.retailer,sourceUrl:row.sourceUrl,retailerDomain:new URL(row.sourceUrl).hostname,advertisedPrice:row.advertisedPrice,regularPrice:row.regularPrice,promotionPrice:row.promotionPrice,promotionDetected:row.promotionDetected,promotionType:row.promotionType,stockState:row.stockState,condition:row.condition,matchEvidence:{brand:row.brand,mpn:row.mpn,gtin:row.gtin,variant:row.variant,explanation:row.matchExplanation}}});await tx.marketBenchmark.upsert({where:{jobId:job.id},update:{},create:{jobId:job.id,productKey:job.productKey,...benchmark}});if(position.recommendedPrice)await tx.tradingDecision.create({data:{productKey:job.productKey,sessionId:job.sessionId,action:"SET_PRICE",source:"SMART_TRADING",proposedPrice:position.recommendedPrice,beforePrice:price.gross,snapshot:{cost:cost.toString(),floor:price.floor.gross.toString(),benchmarkObservedAt:new Date().toISOString(),signals:position.signals},reason:position.reason,createdById:job.session.createdById??"00000000-0000-0000-0000-000000000000"}})});await completeMarketScanJob(job.id,job.leaseToken!,position);results.push({id:job.id,status:"COMPLETED"});}catch(error){const code=error instanceof Error?error.message:"MARKET_RESEARCH_FAILED";await failMarketScanJob(job.id,job.leaseToken!,code,rules.maxAttempts);results.push({id:job.id,status:"FAILED"});}await finaliseTradingSession(job.sessionId);}return results;}
