"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { headers } from "next/headers";
import { z } from "zod";
import Decimal from "decimal.js";
import { prisma } from "@/lib/prisma";
import { requirePermission, getAuthContext } from "@/domain/auth/session";
import { enqueueEmail } from "@/integrations/email/outbox";
import { consumeRateLimit } from "@/domain/auth/rate-limit";

const requestSchema=z.object({contactName:z.string().trim().min(2),email:z.string().email(),phone:z.string().max(40).optional(),companyName:z.string().max(200).optional(),requirements:z.string().trim().min(10).max(5000),productName:z.string().trim().min(2),quantity:z.coerce.number().int().positive().max(10000)});
export async function submitQuotationRequest(formData:FormData){const data=requestSchema.parse(Object.fromEntries(formData));const auth=await getAuthContext();const requestHeaders=await headers();const client=requestHeaders.get("x-forwarded-for")?.split(",")[0]?.trim()||"unknown";const rate=consumeRateLimit(`quotation:${client}:${data.email.toLowerCase()}`,5,60*60_000);if(!rate.allowed)throw new Error(`Too many quotation requests. Try again in ${rate.retryAfterSeconds} seconds.`);const requestNumber=`QR-${Date.now().toString(36).toUpperCase()}`;const request=await prisma.quotationRequest.create({data:{requestNumber,userId:auth?.user.id,contactName:data.contactName,email:data.email,phone:data.phone||null,companyName:data.companyName||null,requirements:data.requirements,items:{create:{productName:data.productName,requestedQuantity:data.quantity}}}});await enqueueEmail({to:data.email,subject:`Quotation request ${requestNumber} received`,text:`We received your quotation request ${requestNumber}.`,html:`<p>We received your quotation request <strong>${requestNumber}</strong>.</p>`,idempotencyKey:`quotation-request:${request.id}`},auth?.user.id);redirect(`/quotations/request?submitted=${requestNumber}`)}

export async function createQuotation(formData:FormData){const ctx=await requirePermission("quotations.manage");const requestId=z.string().uuid().parse(formData.get("requestId"));const req=await prisma.quotationRequest.findUniqueOrThrow({where:{id:requestId},include:{items:{include:{product:true,variant:true}}}});const version=(await prisma.quotation.count({where:{quotationRequestId:requestId}}))+1;const items=req.items.map((item)=>{const price=new Decimal(item.variant?.regularPrice?.toString()??item.product?.regularPrice?.toString()??"0");const line=price.mul(item.requestedQuantity).toDecimalPlaces(2);const vat=line.mul(new Decimal(15).div(115)).toDecimalPlaces(2);return{productId:item.productId,variantId:item.variantId,productName:item.productName??item.product?.name??"Requested item",sku:item.variant?.sku??item.product?.sku,quantity:item.requestedQuantity,unitPrice:price,vatRate:new Decimal("0.15"),vatTotal:vat,lineTotal:line}});const subtotal=items.reduce((n,x)=>n.plus(x.lineTotal),new Decimal(0));const vat=items.reduce((n,x)=>n.plus(x.vatTotal),new Decimal(0));const quotation=await prisma.$transaction(async(tx)=>{const q=await tx.quotation.create({data:{quotationNumber:`QUO-${Date.now().toString(36).toUpperCase()}`,quotationRequestId:requestId,customerId:req.userId,version,subtotal,vatTotal:vat,grandTotal:subtotal,validUntil:new Date(Date.now()+30*86400000),items:{create:items}}});await tx.quotationRequest.update({where:{id:requestId},data:{status:"QUOTED"}});await tx.auditLog.create({data:{actorId:ctx.user.id,action:"quotation.create",entityType:"Quotation",entityId:q.id,after:{quotationNumber:q.quotationNumber,version}}});return q});revalidatePath("/admin/quotations");redirect(`/admin/quotations/${quotation.id}`)}

export async function setQuotationStatus(formData:FormData){const ctx=await requirePermission("quotations.manage");const{id,status}=z.object({id:z.string().uuid(),status:z.enum(["ISSUED","ACCEPTED","REJECTED","EXPIRED","CANCELLED"])}).parse(Object.fromEntries(formData));await prisma.$transaction(async(tx)=>{const before=await tx.quotation.findUniqueOrThrow({where:{id},select:{status:true}});await tx.quotation.update({where:{id},data:{status,issuedAt:status==="ISSUED"?new Date():undefined,acceptedAt:status==="ACCEPTED"?new Date():undefined}});await tx.quotationStatusHistory.create({data:{quotationId:id,fromStatus:before.status,toStatus:status,actorId:ctx.user.id}});await tx.auditLog.create({data:{actorId:ctx.user.id,action:"quotation.status",entityType:"Quotation",entityId:id,before,after:{status}}})});revalidatePath("/admin/quotations")}
