"use server";
import { redirect } from "next/navigation";
import { z } from "zod";
import { getCurrentCart } from "@/domain/cart/service";
import { resolveQuotationCart } from "@/domain/catalogue/product-source";
import { requireUser } from "@/domain/auth/session";
import { prisma } from "@/lib/prisma";
import { supportEmail } from "@/lib/support";
import { enqueueEmail } from "@/integrations/email/outbox";
import { emailTemplates } from "@/integrations/email/templates";
import { configuredMarkup, quoteExpiry, quoteTotals, quotationNumber } from "./lifecycle";
import { quotationPdf } from "./pdf";

const schema=z.object({contactName:z.string().trim().min(2).max(120),phone:z.string().trim().max(40).optional(),companyName:z.string().trim().max(200).optional(),vatNumber:z.string().trim().max(50).optional(),deliveryRequired:z.enum(["yes","no"]),deliveryAddress:z.string().trim().max(500).optional(),customerNotes:z.string().trim().max(5000).optional()});

export async function submitUnifiedCartQuotationRequest(formData:FormData){
  const{user}=await requireUser();const data=schema.parse(Object.fromEntries(formData));const cart=await getCurrentCart();if(!cart||(!cart.items.length&&!cart.supplierItems.length))throw new Error("Your quotation list is empty.");
  const markup=await configuredMarkup();const lines=await resolveQuotationCart(cart,markup);const totals=quoteTotals(lines);const number=quotationNumber();const requestNumber=`QR-${Date.now().toString(36).toUpperCase()}`;const expires=quoteExpiry();const notes=data.customerNotes||"Customer requested the listed products and quantities.";
  const pdf=quotationPdf({quotationNumber:number,kind:"PROVISIONAL",validUntil:expires,subtotal:totals.subtotal,vatTotal:totals.vatTotal,grandTotal:totals.grandTotal,terms:"Provisional and subject to business review. Valid for seven days. Do not make payment until a final quotation is issued.",notes,quotationRequest:{contactName:data.contactName,companyName:data.companyName,email:user.email},items:lines.map(line=>({productName:line.productName,sku:line.sku,quantity:line.quantity,unitPrice:line.grossUnit,lineTotal:line.grossUnit.mul(line.quantity)}))});
  const message=emailTemplates.provisionalQuotation(user.email,data.contactName,number,totals.grandTotal.toString(),expires,pdf);await Promise.all([enqueueEmail(message,user.id),enqueueEmail({...message,to:supportEmail,subject:`Customer provisional quotation ${number} · ${requestNumber}`,idempotencyKey:`quotation-provisional-support:${number}`})]);
  await prisma.$transaction(async tx=>{const request=await tx.quotationRequest.create({data:{requestNumber,userId:user.id,status:"QUOTED",contactName:data.contactName,email:user.email,phone:data.phone||null,companyName:data.companyName||null,vatNumber:data.vatNumber||null,deliveryAddress:data.deliveryRequired==="yes"?{address:data.deliveryAddress||"To be confirmed"}:undefined,requirements:notes,customerNotes:data.customerNotes||null,markupPercent:markup,items:{create:lines.map(line=>({productId:line.productId,variantId:line.variantId,productName:line.productName,requestedQuantity:line.quantity,supplierId:line.supplierId,supplierProductId:line.supplierProductId,supplierSku:line.supplierSku,productSnapshot:line.sourceSnapshot}))}}});const quote=await tx.quotation.create({data:{quotationNumber:number,quotationRequestId:request.id,customerId:user.id,status:"PROVISIONAL_GENERATED",kind:"PROVISIONAL",version:1,markupPercent:markup,subtotal:totals.subtotal,vatTotal:totals.vatTotal,grandTotal:totals.grandTotal,validUntil:expires,terms:"Provisional and subject to business review. Valid for seven days.",notes,aiGenerated:false,items:{create:lines.map(line=>({productId:line.productId,variantId:line.variantId,productName:line.productName,sku:line.sku,quantity:line.quantity,costPrice:line.costPrice,unitPrice:line.grossUnit,vatRate:line.vatRate,vatTotal:line.vatUnit.mul(line.quantity),lineTotal:line.grossUnit.mul(line.quantity),sourceType:line.sourceType,sourceId:line.sourceId,supplierId:line.supplierId,supplierSku:line.supplierSku,sourceSnapshot:line.sourceSnapshot,pricingRule:line.pricingRule,markupPercent:markup,stockSnapshot:line.available}))}}});await tx.quotationVersion.create({data:{quotationId:quote.id,version:1,kind:"PROVISIONAL",snapshot:{quotationNumber:number,requestNumber,kind:"PROVISIONAL",markupPercent:markup.toString(),totals:{subtotal:totals.subtotal.toString(),vat:totals.vatTotal.toString(),grand:totals.grandTotal.toString()},items:lines.map(line=>({...line.sourceSnapshot,quantity:line.quantity,unitPrice:line.grossUnit.toString(),lineTotal:line.grossUnit.mul(line.quantity).toString(),pricingRule:line.pricingRule})),capturedAt:new Date().toISOString()}}});await tx.cart.update({where:{id:cart.id},data:{status:"CONVERTED"}});await tx.auditLog.create({data:{actorId:user.id,action:"quotation.provisional.create",entityType:"Quotation",entityId:quote.id,after:{requestNumber,quotationNumber:number,sourceTypes:[...new Set(lines.map(line=>line.sourceType))],grandTotal:totals.grandTotal.toString()}}})});redirect(`/account/quotations?submitted=${requestNumber}`);
}
