"use server";

import { Decimal } from "@prisma/client/runtime/client";
import { randomUUID } from "crypto";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { requirePermission } from "@/domain/auth/session";
import { prisma } from "@/lib/prisma";
import { createSupabaseAdmin } from "@/lib/supabase";

const lineSchema=z.object({description:z.string().trim().min(2).max(500),quantity:z.coerce.number().int().positive().max(100000),unitPrice:z.coerce.number().nonnegative().max(100000000),vatRate:z.coerce.number().min(0).max(100)});
const number=(prefix:string)=>`${prefix}-${new Date().toISOString().slice(0,10).replaceAll("-","")}-${Date.now().toString(36).toUpperCase()}`;
const linesFromForm=(formData:FormData,withPrice=true)=>Array.from({length:12},(_,i)=>{const description=String(formData.get(`description_${i}`)??"").trim();if(!description)return null;return lineSchema.parse({description,quantity:formData.get(`quantity_${i}`),unitPrice:withPrice?formData.get(`unitPrice_${i}`):0,vatRate:withPrice?formData.get(`vatRate_${i}`):0})}).filter((x):x is z.infer<typeof lineSchema>=>Boolean(x));
const invoiceLines=(lines:z.infer<typeof lineSchema>[])=>lines.map((line,sortOrder)=>{const quantity=new Decimal(line.quantity);const unitPrice=new Decimal(line.unitPrice);const net=unitPrice.mul(quantity);const vatTotal=net.mul(new Decimal(line.vatRate).div(100)).toDecimalPlaces(2);return{description:line.description,quantity:line.quantity,unitPrice,vatRate:new Decimal(line.vatRate),vatTotal,lineTotal:net.plus(vatTotal).toDecimalPlaces(2),sortOrder}});

export async function createManualInvoice(formData:FormData){
  const ctx=await requirePermission("quotations.manage");
  const customer=z.object({customerName:z.string().trim().min(2),customerEmail:z.string().email(),companyName:z.string().trim().optional(),billingAddress:z.string().trim().min(5),dueAt:z.coerce.date(),notes:z.string().trim().max(3000).optional()}).parse(Object.fromEntries(formData));
  const items=invoiceLines(linesFromForm(formData));if(!items.length)throw new Error("Add at least one invoice line.");
  const subtotal=items.reduce((n,x)=>n.plus(x.unitPrice.mul(x.quantity)),new Decimal(0));const vatTotal=items.reduce((n,x)=>n.plus(x.vatTotal),new Decimal(0));const grandTotal=subtotal.plus(vatTotal);
  const invoice=await prisma.$transaction(async tx=>{const created=await tx.invoice.create({data:{invoiceNumber:number("INV"),origin:"MANUAL",status:"DRAFT",createdById:ctx.user.id,updatedById:ctx.user.id,...customer,companyName:customer.companyName||null,notes:customer.notes||null,subtotal,vatTotal,grandTotal,balanceDue:grandTotal,items:{create:items}}});await tx.auditLog.create({data:{actorId:ctx.user.id,action:"invoice.manual.create",entityType:"Invoice",entityId:created.id,after:{invoiceNumber:created.invoiceNumber,total:grandTotal.toString()}}});return created});
  redirect(`/admin/invoices/${invoice.id}`);
}

export async function createInvoiceFromOrder(formData:FormData){
  const ctx=await requirePermission("quotations.manage");const orderId=z.string().uuid().parse(formData.get("orderId"));
  const order=await prisma.order.findUniqueOrThrow({where:{id:orderId},include:{items:true,addresses:true,invoices:{where:{status:{notIn:["VOID","CANCELLED"]}}}}});if(order.invoices.length)throw new Error("This order already has an active invoice.");
  const items=order.items.map((x,sortOrder)=>({description:x.productName,quantity:x.quantity,unitPrice:x.unitPrice,discountTotal:x.discountTotal,vatRate:x.vatRate.mul(100),vatTotal:x.vatTotal,lineTotal:x.lineTotal,sortOrder}));
  const address=order.addresses.find(x=>x.type==="BILLING"||x.type==="BOTH");const billingAddress=address?[address.line1,address.line2,address.suburb,address.city,address.province,address.postalCode].filter(Boolean).join(", "):null;
  const invoice=await prisma.$transaction(async tx=>{const created=await tx.invoice.create({data:{invoiceNumber:number("INV"),orderId:order.id,origin:"AUTOMATED",status:"DRAFT",createdById:ctx.user.id,updatedById:ctx.user.id,customerName:address?.recipient??order.email,customerEmail:order.email,companyName:order.companyName,billingAddress,currency:order.currency,subtotal:order.subtotal,discountTotal:order.discountTotal,vatTotal:order.vatTotal,grandTotal:order.grandTotal,balanceDue:order.grandTotal,dueAt:new Date(Date.now()+30*86400000),notes:`Generated from order ${order.orderNumber}`,items:{create:items}}});await tx.auditLog.create({data:{actorId:ctx.user.id,action:"invoice.order.create",entityType:"Invoice",entityId:created.id,after:{invoiceNumber:created.invoiceNumber,orderNumber:order.orderNumber}}});return created});redirect(`/admin/invoices/${invoice.id}`);
}

export async function recordInvoicePayment(formData:FormData){
  const ctx=await requirePermission("payments.approve");const data=z.object({invoiceId:z.string().uuid(),amount:z.coerce.number().positive(),paidAt:z.coerce.date(),method:z.enum(["EFT","MANUAL","PAYSTACK","YOCO"]),reference:z.string().trim().max(150).optional(),note:z.string().trim().max(1000).optional()}).parse(Object.fromEntries(formData));
  await prisma.$transaction(async tx=>{const invoice=await tx.invoice.findUniqueOrThrow({where:{id:data.invoiceId},include:{payments:true}});if(["VOID","CANCELLED","CREDITED"].includes(invoice.status))throw new Error("Payments cannot be recorded against this invoice.");const paid=invoice.payments.reduce((n,x)=>n.plus(x.amount),new Decimal(0)).plus(data.amount);if(paid.gt(invoice.grandTotal))throw new Error("Payment exceeds the invoice balance.");const balance=new Decimal(invoice.grandTotal).minus(paid);await tx.invoicePayment.create({data:{invoiceId:invoice.id,amount:data.amount,paidAt:data.paidAt,method:data.method,reference:data.reference||null,note:data.note||null,recordedById:ctx.user.id}});await tx.invoice.update({where:{id:invoice.id},data:{amountPaid:paid,balanceDue:balance,status:balance.isZero()?"PAID":"PARTIALLY_PAID",paidAt:balance.isZero()?data.paidAt:null,updatedById:ctx.user.id}});await tx.auditLog.create({data:{actorId:ctx.user.id,action:"invoice.payment.record",entityType:"Invoice",entityId:invoice.id,after:{amount:String(data.amount),balance:balance.toString(),reference:data.reference}}})});revalidatePath(`/admin/invoices/${data.invoiceId}`);revalidatePath("/admin/invoices");
}

export async function updateInvoiceStatus(formData:FormData){
  const ctx=await requirePermission("quotations.manage");const data=z.object({invoiceId:z.string().uuid(),status:z.enum(["DRAFT","ISSUED","SENT","OVERDUE","VOID","CANCELLED","CREDITED"])}).parse(Object.fromEntries(formData));const before=await prisma.invoice.findUniqueOrThrow({where:{id:data.invoiceId},select:{status:true}});await prisma.$transaction([prisma.invoice.update({where:{id:data.invoiceId},data:{status:data.status,issuedAt:data.status==="ISSUED"?new Date():undefined,sentAt:data.status==="SENT"?new Date():undefined,updatedById:ctx.user.id}}),prisma.auditLog.create({data:{actorId:ctx.user.id,action:"invoice.status",entityType:"Invoice",entityId:data.invoiceId,before,after:{status:data.status}}})]);revalidatePath(`/admin/invoices/${data.invoiceId}`);revalidatePath("/admin/invoices");
}

export async function createDeliveryNoteFromOrder(formData:FormData){
  const ctx=await requirePermission("orders.update");const orderId=z.string().uuid().parse(formData.get("orderId"));const order=await prisma.order.findUniqueOrThrow({where:{id:orderId},include:{items:true,addresses:true,invoices:{orderBy:{createdAt:"desc"},take:1},deliveryNotes:{where:{status:{not:"CANCELLED"}}}}});if(order.deliveryNotes.length)throw new Error("This order already has an active delivery note.");const address=order.addresses.find(x=>x.type==="DELIVERY"||x.type==="BOTH");if(!address)throw new Error("The order does not have a delivery address.");
  const deliveryAddress=[address.line1,address.line2,address.suburb,address.city,address.province,address.postalCode].filter(Boolean).join(", ");const note=await prisma.$transaction(async tx=>{const created=await tx.deliveryNote.create({data:{deliveryNoteNumber:number("DN"),orderId:order.id,invoiceId:order.invoices[0]?.id,origin:"AUTOMATED",status:"DRAFT",createdById:ctx.user.id,updatedById:ctx.user.id,customerName:address.recipient,customerEmail:order.email,customerPhone:address.phone??order.phone,companyName:order.companyName,deliveryAddress,reference:order.orderNumber,items:{create:order.items.map((x,sortOrder)=>({description:x.productName,quantity:x.quantity,sortOrder}))},history:{create:{toStatus:"DRAFT",actorId:ctx.user.id,note:"Generated from order"}}}});await tx.auditLog.create({data:{actorId:ctx.user.id,action:"delivery-note.order.create",entityType:"DeliveryNote",entityId:created.id,after:{deliveryNoteNumber:created.deliveryNoteNumber,orderNumber:order.orderNumber}}});return created});redirect(`/admin/delivery-notes/${note.id}`);
}

export async function createManualDeliveryNote(formData:FormData){
  const ctx=await requirePermission("orders.update");const data=z.object({customerName:z.string().trim().min(2),customerEmail:z.string().email().optional().or(z.literal("")),customerPhone:z.string().trim().optional(),companyName:z.string().trim().optional(),deliveryAddress:z.string().trim().min(5),deliveryDate:z.coerce.date().optional(),deliveryMethod:z.string().trim().optional(),reference:z.string().trim().optional(),instructions:z.string().trim().max(3000).optional(),responsibleStaffId:z.string().uuid().optional().or(z.literal(""))}).parse(Object.fromEntries(formData));const items=linesFromForm(formData,false);if(!items.length)throw new Error("Add at least one delivery item.");
  const note=await prisma.$transaction(async tx=>{const created=await tx.deliveryNote.create({data:{deliveryNoteNumber:number("DN"),origin:"MANUAL",status:"DRAFT",createdById:ctx.user.id,updatedById:ctx.user.id,responsibleStaffId:data.responsibleStaffId||null,customerName:data.customerName,customerEmail:data.customerEmail||null,customerPhone:data.customerPhone||null,companyName:data.companyName||null,deliveryAddress:data.deliveryAddress,deliveryDate:data.deliveryDate,deliveryMethod:data.deliveryMethod||null,reference:data.reference||null,instructions:data.instructions||null,items:{create:items.map((x,sortOrder)=>({description:x.description,quantity:x.quantity,sortOrder}))},history:{create:{toStatus:"DRAFT",actorId:ctx.user.id,note:"Manual delivery note created"}}}});await tx.auditLog.create({data:{actorId:ctx.user.id,action:"delivery-note.manual.create",entityType:"DeliveryNote",entityId:created.id,after:{deliveryNoteNumber:created.deliveryNoteNumber}}});return created});redirect(`/admin/delivery-notes/${note.id}`);
}

export async function updateDeliveryNote(formData:FormData){
  const ctx=await requirePermission("orders.update");const data=z.object({deliveryNoteId:z.string().uuid(),status:z.enum(["DRAFT","READY_FOR_DELIVERY","PARTIALLY_DELIVERED","DELIVERED","ACKNOWLEDGED","CANCELLED"]),deliveryDate:z.coerce.date().optional(),deliveryMethod:z.string().trim().optional(),responsibleStaffId:z.string().uuid().optional().or(z.literal("")),customerNote:z.string().trim().max(2000).optional(),internalNote:z.string().trim().max(2000).optional(),confirmationName:z.string().trim().optional(),confirmationNote:z.string().trim().max(1000).optional()}).parse(Object.fromEntries(formData));await prisma.$transaction(async tx=>{const before=await tx.deliveryNote.findUniqueOrThrow({where:{id:data.deliveryNoteId},include:{items:true}});if(before.status==="CANCELLED")throw new Error("A cancelled delivery note cannot be changed.");const now=new Date();await tx.deliveryNote.update({where:{id:before.id},data:{status:data.status,deliveryDate:data.deliveryDate,deliveryMethod:data.deliveryMethod||null,responsibleStaffId:data.responsibleStaffId||null,customerNote:data.customerNote||null,internalNote:data.internalNote||null,confirmationName:data.confirmationName||null,confirmationNote:data.confirmationNote||null,deliveredAt:data.status==="DELIVERED"||data.status==="ACKNOWLEDGED"?now:undefined,customerConfirmedAt:data.status==="ACKNOWLEDGED"?now:undefined,confirmedById:data.status==="ACKNOWLEDGED"?ctx.user.id:undefined,cancelledAt:data.status==="CANCELLED"?now:undefined,updatedById:ctx.user.id}});if(data.status==="DELIVERED"||data.status==="ACKNOWLEDGED")await tx.deliveryNoteItem.updateMany({where:{deliveryNoteId:before.id},data:{deliveredQty:{set:0}}}).then(async()=>{for(const item of before.items)await tx.deliveryNoteItem.update({where:{id:item.id},data:{deliveredQty:item.quantity}})});await tx.deliveryNoteHistory.create({data:{deliveryNoteId:before.id,fromStatus:before.status,toStatus:data.status,actorId:ctx.user.id,note:data.customerNote||undefined}});await tx.auditLog.create({data:{actorId:ctx.user.id,action:"delivery-note.status",entityType:"DeliveryNote",entityId:before.id,before:{status:before.status},after:{status:data.status}}})});revalidatePath(`/admin/delivery-notes/${data.deliveryNoteId}`);revalidatePath("/admin/delivery-notes");
}

export async function uploadDeliveryEvidence(formData:FormData){
  const ctx=await requirePermission("orders.update");const deliveryNoteId=z.string().uuid().parse(formData.get("deliveryNoteId"));const type=z.enum(["PROOF_OF_DELIVERY","SIGNATURE","PHOTO","OTHER"]).parse(formData.get("type"));const file=formData.get("file");if(!(file instanceof File)||!file.size||file.size>10*1024*1024||!["application/pdf","image/jpeg","image/png","image/webp"].includes(file.type))throw new Error("Upload a PDF, JPG, PNG or WebP smaller than 10 MB.");const note=await prisma.deliveryNote.findUniqueOrThrow({where:{id:deliveryNoteId}});const bucket=process.env.SUPABASE_PRIVATE_BUCKET??"private-documents";const supabase=createSupabaseAdmin();if(!(await supabase.storage.getBucket(bucket)).data){const created=await supabase.storage.createBucket(bucket,{public:false,fileSizeLimit:10*1024*1024});if(created.error)throw created.error}const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"-");const path=`delivery-notes/${note.deliveryNoteNumber}/${randomUUID()}-${safe}`;const uploaded=await supabase.storage.from(bucket).upload(path,file,{contentType:file.type,upsert:false});if(uploaded.error)throw uploaded.error;try{await prisma.$transaction(async tx=>{const document=await tx.uploadedDocument.create({data:{bucket,path,originalName:file.name,mimeType:file.type,size:file.size,isPrivate:true,isTestData:note.isTestData}});await tx.deliveryNoteAttachment.create({data:{deliveryNoteId,documentId:document.id,type,isTestData:note.isTestData}});await tx.auditLog.create({data:{actorId:ctx.user.id,action:"delivery-note.evidence.upload",entityType:"DeliveryNote",entityId:deliveryNoteId,after:{type,originalName:file.name}}})})}catch(error){await supabase.storage.from(bucket).remove([path]);throw error}revalidatePath(`/admin/delivery-notes/${deliveryNoteId}`);
}
