import { defaultDocumentBranding,type DocumentBranding } from "./branding";
type DocumentLine = { description: string; quantity: number; unitPrice?: string; total?: string };
const escapePdf = (value: string) => value.replace(/([\\()])/g, "\\$1").replace(/[^\x20-\x7E]/g, "?");

export function commercialPdf(input: { title: string; number: string; customer: string; email: string; issueDate: Date; dueDate?: Date; reference?: string; lines: DocumentLine[]; subtotal?: string; vat?: string; total?: string; notes?: string | null },branding:DocumentBranding=defaultDocumentBranding) {
  const company=[branding.companyName.toUpperCase(),branding.tagline.toUpperCase(),[branding.companyName,branding.registration,branding.email,branding.phone].filter(Boolean).join(" | "),branding.address,branding.website];
  const rows = [...company, "", input.title, `Number: ${input.number}`, `Issue date: ${input.issueDate.toISOString().slice(0,10)}`, input.dueDate?`Due date: ${input.dueDate.toISOString().slice(0,10)}`:"", `Customer: ${input.customer}`, `Email: ${input.email}`, input.reference?`Reference: ${input.reference}`:"", "", "Description | Quantity | Unit price | Total", ...input.lines.map(line=>`${line.description} | ${line.quantity} | ${line.unitPrice??"-"} | ${line.total??"-"}`), "", input.subtotal?`Subtotal: ${input.subtotal}`:"", input.vat?`VAT: ${input.vat}`:"", input.total?`TOTAL: ${input.total}`:"", input.notes?`Notes: ${input.notes}`:""].filter(Boolean);
  const content=rows.slice(0,40).map((line,index)=>`BT /F1 ${index===0?20:index===6?16:9} Tf 38 ${810-index*19} Td (${escapePdf(line)}) Tj ET`).join("\n");
  const objects=["<< /Type /Catalog /Pages 2 0 R >>","<< /Type /Pages /Kids [3 0 R] /Count 1 >>","<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>","<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",`<< /Length ${Buffer.byteLength(content)} >>\nstream\n${content}\nendstream`];
  let pdf="%PDF-1.4\n";const offsets=[0];objects.forEach((object,index)=>{offsets.push(Buffer.byteLength(pdf));pdf+=`${index+1} 0 obj\n${object}\nendobj\n`});const xref=Buffer.byteLength(pdf);pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(offset=>`${String(offset).padStart(10,"0")} 00000 n `).join("\n")}\ntrailer << /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return Buffer.from(pdf);
}
