import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminPage,Panel,StatusBadge,buttonClass,inputClass,secondaryButtonClass,tableClass } from "@/components/admin/admin-ui";
import { requirePermission } from "@/domain/auth/session";
import { assertBusinessDocumentAccess,businessDocumentTypes,getOrCreateBusinessDocument } from "@/domain/documents/business-documents";
import { sendBusinessDocument } from "@/domain/documents/send-actions";

export default async function SendDocumentPage({searchParams}:{searchParams:Promise<{type?:string;id?:string;sent?:string}>}){
  const context=await requirePermission("documents.send");const query=await searchParams;
  if(!query.type||!businessDocumentTypes.includes(query.type as never)||!query.id)notFound();
  const type=query.type as (typeof businessDocumentTypes)[number];await assertBusinessDocumentAccess(context,type,query.id);
  const {artifact,descriptor}=await getOrCreateBusinessDocument(type,query.id,context.user.id);
  return <AdminPage title={`Send ${descriptor.label}`} description="Review the recipient, message and exact stored PDF before sending. Nothing is sent until you confirm." actions={<><Link className={secondaryButtonClass} href={`/api/business-documents/${descriptor.type.toLowerCase().replaceAll("_","-")}/${descriptor.recordId}/download`}>Download PDF</Link><StatusBadge value={artifact.state}/></>}>
    {query.sent==="1"?<div className="mb-4 border border-emerald-300 bg-emerald-50 p-4 text-sm font-semibold text-emerald-900">The document was accepted by the configured email provider and the send history was recorded.</div>:null}
    <div className="grid gap-4 xl:grid-cols-[1fr_.65fr]"><Panel title="Email review"><form action={sendBusinessDocument} className="space-y-4"><input type="hidden" name="type" value={descriptor.type}/><input type="hidden" name="recordId" value={descriptor.recordId}/><label className="block text-sm font-semibold">Recipient<input className={`${inputClass} mt-1 w-full`} name="to" type="email" defaultValue={descriptor.recipientEmail??""} required/></label><p className="text-xs text-slate-500">Stored contact: {descriptor.recipientEmail??"No email is stored for this record."} A different address requires explicit confirmation.</p><label className="block text-sm font-semibold">CC recipients<input className={`${inputClass} mt-1 w-full`} name="cc" placeholder="name@example.com, another@example.com"/></label><label className="block text-sm font-semibold">Subject<input className={`${inputClass} mt-1 w-full`} name="subject" defaultValue={descriptor.subject} required/></label><label className="block text-sm font-semibold">Message<textarea className={`${inputClass} mt-1 min-h-56 w-full`} name="message" defaultValue={descriptor.message} required/></label><label className="flex items-start gap-2 border border-amber-200 bg-amber-50 p-3 text-sm"><input className="mt-1" name="confirmExternal" type="checkbox"/>I confirm that any changed recipient is authorised to receive this document.</label><div className="flex flex-wrap gap-2"><button className={buttonClass}>Confirm and send</button><Link className={secondaryButtonClass} href={`/admin/${descriptor.type==="DELIVERY_NOTE"?"delivery-notes":descriptor.type==="RFQ"?"rfqs":descriptor.type.toLowerCase()+"s"}/${descriptor.recordId}`}>Cancel</Link></div></form></Panel>
    <aside className="space-y-4"><Panel title="Attached document"><dl className="space-y-2 text-sm"><div><dt className="font-bold">File</dt><dd className="break-all">{artifact.filename}</dd></div><div><dt className="font-bold">Reference</dt><dd>{artifact.documentNumber}</dd></div><div><dt className="font-bold">Version</dt><dd>{artifact.version}</dd></div><div><dt className="font-bold">Status</dt><dd>{artifact.state}</dd></div><div><dt className="font-bold">Size</dt><dd>{Math.ceil(artifact.size/1024)} KB</dd></div></dl></Panel><Panel title="Send history">{artifact.dispatches.length?<div className="overflow-x-auto"><table className={tableClass}><thead><tr><th>Date</th><th>Recipient</th><th>Status</th></tr></thead><tbody>{artifact.dispatches.map(item=><tr key={item.id}><td>{item.createdAt.toLocaleString("en-ZA")}</td><td>{item.toRecipients.join(", ")}{item.isResend?<small className="block">Resent</small>:null}</td><td><StatusBadge value={item.status}/>{item.failureReason?<p className="mt-1 max-w-xs text-xs text-rose-700">{item.failureReason}</p>:null}</td></tr>)}</tbody></table></div>:<p className="text-sm text-slate-500">This document has not been sent from the shared document centre.</p>}</Panel></aside></div>
  </AdminPage>;
}
