import Link from "next/link";
import { requirePartnerSalesContext } from "@/domain/partner-sales/access";
import { prisma } from "@/lib/prisma";
import { formatZar } from "@/lib/money";

export const dynamic = "force-dynamic";

export default async function PartnerPayoutStatementsPage() {
  const { partnership } = await requirePartnerSalesContext();
  const batches = await prisma.partnerPayoutBatch.findMany({ where: { partnershipId: partnership.id, status: { in: ["APPROVED", "PAID"] } }, orderBy: { periodEnd: "desc" }, take: 100, select: { id: true, batchNumber: true, status: true, total: true, currency: true, periodStart: true, periodEnd: true, paymentReference: true, paymentDate: true } });
  return <main className="mx-auto min-w-0 max-w-6xl px-4 py-7 sm:px-6 sm:py-10"><p className="text-xs font-black uppercase tracking-[.18em] text-sky-700">Partner sales</p><div className="mt-2 flex min-w-0 flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div className="min-w-0"><h1 className="text-3xl font-black tracking-tight text-slate-950">Payout statements</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">View finance-approved commission settlements and EFT references. Statements contain only your partnership’s cases and payout totals.</p></div><Link className="inline-flex min-h-11 items-center justify-center rounded-lg border px-4 text-sm font-bold text-sky-700" href="/account/partner/orders">Order tracking</Link></div><section className="mt-7 grid gap-3">{batches.map((batch) => <article key={batch.id} className="grid min-w-0 gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:grid-cols-[minmax(0,1fr)_auto_auto] sm:items-center sm:p-5"><div className="min-w-0"><strong className="break-all text-slate-950 sm:break-words">{batch.batchNumber}</strong><p className="mt-1 text-xs text-slate-500">{batch.periodStart.toLocaleDateString("en-ZA")} – {batch.periodEnd.toLocaleDateString("en-ZA")}</p></div><div><p className="text-sm font-black text-slate-900">{formatZar(batch.total)}</p><p className="text-xs uppercase tracking-wide text-slate-500">{batch.status}</p></div><div className="text-left text-xs text-slate-500 sm:text-right">{batch.status === "PAID" ? <><span className="block">EFT {batch.paymentReference ?? "recorded"}{batch.paymentDate ? ` · ${batch.paymentDate.toLocaleDateString("en-ZA")}` : ""}</span><Link className="mt-1 inline-block font-bold text-sky-700 underline" href={`/api/account/partner/payouts/${batch.id}/statement`}>Download statement</Link></> : "Approved for payment"}</div></article>)}{!batches.length ? <p className="rounded-2xl border border-slate-200 bg-white px-5 py-12 text-center text-sm text-slate-500">No approved payout statements are available yet.</p> : null}</section></main>;
}
