import Link from "next/link";
import { AdminPage, MetricCard, Panel, buttonClass, inputClass, tableClass } from "@/components/admin/admin-ui";
import { assistantSettings } from "@/domain/ai-shopping/service";
import { saveAISettings } from "@/domain/ai-shopping/admin-actions";
import { requirePermission } from "@/domain/auth/session";
import { prisma } from "@/lib/prisma";

const start=(value:string|undefined,fallback:Date)=>{const date=value?new Date(`${value}T00:00:00`):fallback;return Number.isNaN(date.getTime())?fallback:date};
export default async function AIAdminPage({searchParams}:{searchParams:Promise<{from?:string;to?:string;saved?:string}>}){await requirePermission("marketing.analytics.view");const query=await searchParams,now=new Date(),from=start(query.from,new Date(now.getFullYear(),now.getMonth(),1)),to=start(query.to,now);to.setHours(23,59,59,999);const today=new Date();today.setHours(0,0,0,0);const[rows,range,todayCount,monthCount,settings]=await Promise.all([prisma.aIUsage.findMany({where:{createdAt:{gte:from,lte:to}},orderBy:{createdAt:"desc"},take:50}),prisma.aIUsage.aggregate({where:{createdAt:{gte:from,lte:to}},_count:true,_sum:{inputTokens:true,outputTokens:true,totalTokens:true,estimatedCost:true,responseTimeMs:true}}),prisma.aIUsage.count({where:{createdAt:{gte:today}}}),prisma.aIUsage.count({where:{createdAt:{gte:new Date(now.getFullYear(),now.getMonth(),1)}}}),assistantSettings()]);const success=rows.filter(item=>item.requestStatus==="SUCCESS").length,anonymous=rows.filter(item=>item.anonymousSessionId).length,carts=rows.filter(item=>item.cartCreated).length,orders=rows.filter(item=>item.orderId).length,spend=Number(range._sum.estimatedCost??0),avg=range._count?Math.round((range._sum.responseTimeMs??0)/range._count):0;return <AdminPage title="AI" description="Operational usage, cost and sales visibility for the Innozanzi AI Shopping Assistant." actions={<Link className={buttonClass} href="https://platform.openai.com/settings/organization/billing" target="_blank" rel="noreferrer">Manage OpenAI billing</Link>}>
  {query.saved?<p className="bg-emerald-50 p-3 text-sm text-emerald-800">AI settings saved.</p>:null}{spend>=settings.monthlyWarning&&settings.monthlyWarning>0?<p className="border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900">Application estimated spend has reached the configured warning for this date range.</p>:null}
  <form className="flex flex-wrap items-end gap-3 border border-slate-300 bg-white p-4"><label className="text-xs font-bold">From<input className={`${inputClass} mt-1`} type="date" name="from" defaultValue={from.toISOString().slice(0,10)}/></label><label className="text-xs font-bold">To<input className={`${inputClass} mt-1`} type="date" name="to" defaultValue={to.toISOString().slice(0,10)}/></label><button className={buttonClass}>Apply dates</button></form>
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Requests today" value={todayCount}/><MetricCard label="Requests this month" value={monthCount}/><MetricCard label="Successful" value={success}/><MetricCard label="Failed" value={rows.length-success}/><MetricCard label="Anonymous usage" value={anonymous}/><MetricCard label="Logged-in usage" value={rows.length-anonymous}/><MetricCard label="Input tokens" value={(range._sum.inputTokens??0).toLocaleString()}/><MetricCard label="Output tokens" value={(range._sum.outputTokens??0).toLocaleString()}/><MetricCard label="Total tokens" value={(range._sum.totalTokens??0).toLocaleString()}/><MetricCard label="Estimated spend" value={`$${spend.toFixed(4)}`} detail="Application estimate; not OpenAI account balance"/><MetricCard label="Average tokens" value={range._count?Math.round((range._sum.totalTokens??0)/range._count):0}/><MetricCard label="Average response" value={`${avg} ms`}/><MetricCard label="Carts generated" value={carts}/><MetricCard label="AI PC builds" value={rows.filter(item=>item.pcBuildGenerated).length}/><MetricCard label="AI conversions" value={orders}/></div>
  <Panel title="Assistant controls" description="Spend warnings use application telemetry and do not claim to be the OpenAI prepaid balance."><form action={saveAISettings} className="grid max-w-3xl gap-4 sm:grid-cols-3"><label className="text-sm font-semibold">Daily spend warning ($)<input className={`${inputClass} mt-1`} name="dailyWarning" type="number" step="0.01" defaultValue={settings.dailyWarning}/></label><label className="text-sm font-semibold">Monthly spend warning ($)<input className={`${inputClass} mt-1`} name="monthlyWarning" type="number" step="0.01" defaultValue={settings.monthlyWarning}/></label><label className="text-sm font-semibold">Tokens/request warning<input className={`${inputClass} mt-1`} name="tokenWarning" type="number" defaultValue={settings.tokenWarning}/></label><label className="flex items-center gap-2 text-sm font-semibold sm:col-span-3"><input type="checkbox" name="enabled" defaultChecked={settings.enabled}/> AI Shopping Assistant enabled</label><button className={`${buttonClass} sm:col-span-3 sm:w-fit`}>Save controls</button></form></Panel>
  <Panel title="Recent requests"><table className={tableClass}><thead><tr><th>Time</th><th>Status</th><th>Audience</th><th>Intent</th><th>Tokens</th><th>Cost</th><th>Response</th><th>Outcome</th></tr></thead><tbody>{rows.map(item=><tr key={item.id}><td>{item.createdAt.toLocaleString("en-ZA")}</td><td>{item.requestStatus}</td><td>{item.userId?"Signed in":"Anonymous"}</td><td>{item.intentType??"—"}</td><td>{item.totalTokens.toLocaleString()}</td><td>${Number(item.estimatedCost).toFixed(5)}</td><td>{item.responseTimeMs??0} ms</td><td>{item.orderId?"Order":item.cartCreated?"Cart":item.pcBuildGenerated?"Build":"Recommendation"}</td></tr>)}{!rows.length?<tr><td colSpan={8}>No AI usage in this date range.</td></tr>:null}</tbody></table></Panel>
  </AdminPage>}
