import Link from "next/link";
import { ArrowRight, Boxes, CircleCheck, ClipboardList, FileText, Headphones, PackageCheck, RotateCcw, Sparkles } from "lucide-react";
import { requireClientPortal } from "@/domain/client-portal/session";
import { prisma } from "@/lib/prisma";

export default async function ClientPortalDashboard(){
  const{context,portal}=await requireClientPortal();
  const[requests,quotes,orders,returns,tickets,recentOrders,recentQuotes]=await Promise.all([
    prisma.quotationRequest.count({where:{userId:context.user.id,status:{notIn:["CANCELLED","CLOSED"]}}}),
    prisma.quotation.count({where:{customerId:context.user.id,status:{in:["DRAFT","PENDING_APPROVAL","FINAL_APPROVED","SENT","ISSUED"]}}}),
    prisma.order.count({where:{userId:context.user.id,status:{notIn:["DELIVERED","CANCELLED","REFUNDED"]}}}),
    prisma.returnCase.count({where:{customerId:context.user.id,status:{notIn:["CLOSED","REJECTED"]}}}),
    prisma.helpDeskTicket.count({where:{customerId:context.user.id,status:{notIn:["RESOLVED","CLOSED"]}}}),
    prisma.order.findMany({where:{userId:context.user.id},select:{id:true,orderNumber:true,status:true,grandTotal:true,createdAt:true},orderBy:{createdAt:"desc"},take:4}),
    prisma.quotation.findMany({where:{customerId:context.user.id},select:{id:true,quotationNumber:true,status:true,grandTotal:true,createdAt:true},orderBy:{createdAt:"desc"},take:4}),
  ]);
  const metrics=[
    {label:"Open requests",value:requests,detail:"Awaiting review or quotation",href:"/account/quotations",icon:ClipboardList,tone:"border-sky-200 bg-sky-50 text-sky-700"},
    {label:"Active quotations",value:quotes,detail:"Review and respond",href:"/account/quotations",icon:FileText,tone:"border-violet-200 bg-violet-50 text-violet-700"},
    {label:"Current orders",value:orders,detail:"In progress or delivery",href:"/account/orders",icon:Boxes,tone:"border-amber-200 bg-amber-50 text-amber-700"},
    {label:"Open support",value:tickets,detail:"Requests needing attention",href:"/account/support",icon:Headphones,tone:"border-rose-200 bg-rose-50 text-rose-700"},
    {label:"Returns",value:returns,detail:"Active assistance cases",href:"/account/returns",icon:RotateCcw,tone:"border-emerald-200 bg-emerald-50 text-emerald-700"},
  ];
  return <div className="mx-auto max-w-[1500px]">
    <section className="relative overflow-hidden rounded-xl bg-gradient-to-br from-[#07566a] via-[#087b83] to-[#0a9aa0] p-6 text-white shadow-lg sm:p-8"><div className="absolute -right-16 -top-24 size-64 rounded-full border-[45px] border-white/[.06]"/><div className="relative"><div className="flex flex-wrap items-center gap-2"><span className="inline-flex items-center gap-1.5 rounded-full bg-white/10 px-3 py-1 text-[11px] font-bold uppercase tracking-wider text-cyan-100"><Sparkles className="size-3.5"/>{portal.tier} client service</span><span className="inline-flex items-center gap-1.5 rounded-full bg-emerald-300/15 px-3 py-1 text-[11px] font-bold text-emerald-100"><CircleCheck className="size-3.5"/>Portal active</span></div><h1 className="mt-5 text-3xl font-semibold tracking-tight sm:text-4xl">Good day, {context.user.name?.split(" ")[0]??"Client"}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-cyan-50 sm:text-base">Manage your organisation’s quotations, orders, deliveries and support services from one dedicated Innozanzi workspace.</p><div className="mt-6 flex flex-wrap gap-3"><Link className="inline-flex min-h-11 items-center gap-2 rounded-md bg-white px-4 text-sm font-bold text-[#07566a] shadow-sm hover:bg-cyan-50" href="/quotations/request">Request a quotation <ArrowRight className="size-4"/></Link><Link className="inline-flex min-h-11 items-center gap-2 rounded-md border border-white/30 bg-white/5 px-4 text-sm font-semibold text-white hover:bg-white/10" href="/account/support">Get support</Link></div></div></section>
    <section className="mt-6"><div className="mb-3 flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.17em] text-cyan-700">Account snapshot</p><h2 className="mt-1 text-xl font-semibold">What needs your attention</h2></div><p className="hidden text-xs text-slate-500 sm:block">Live information from your account</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{metrics.map(metric=>{const Icon=metric.icon;return <Link className="group rounded-lg border border-slate-200 bg-white p-4 shadow-sm transition hover:-translate-y-0.5 hover:border-cyan-400 hover:shadow-md" href={metric.href} key={metric.label}><div className={`grid size-10 place-items-center rounded-lg border ${metric.tone}`}><Icon className="size-5"/></div><p className="mt-4 text-3xl font-semibold tabular-nums text-slate-950">{metric.value}</p><p className="mt-1 text-sm font-semibold text-slate-800">{metric.label}</p><p className="mt-1 text-xs leading-5 text-slate-500">{metric.detail}</p></Link>})}</div></section>
    <div className="mt-6 grid gap-5 xl:grid-cols-[1.15fr_.85fr]">
      <section className="rounded-lg border border-slate-200 bg-white shadow-sm"><header className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><div><h2 className="font-semibold">Recent activity</h2><p className="mt-0.5 text-xs text-slate-500">Latest quotations and orders</p></div><PackageCheck className="size-5 text-cyan-700"/></header><div className="divide-y divide-slate-100">{[...recentQuotes.map(x=>({key:`q-${x.id}`,label:x.quotationNumber,status:x.status,total:x.grandTotal,date:x.createdAt,href:"/account/quotations",kind:"Quotation"})),...recentOrders.map(x=>({key:`o-${x.id}`,label:x.orderNumber,status:x.status,total:x.grandTotal,date:x.createdAt,href:`/account/orders/${x.orderNumber}`,kind:"Order"}))].sort((a,b)=>b.date.getTime()-a.date.getTime()).slice(0,6).map(row=><Link className="flex items-center gap-4 px-5 py-3.5 hover:bg-cyan-50/50" href={row.href} key={row.key}><span className={`size-2 rounded-full ${row.kind==="Order"?"bg-amber-400":"bg-violet-400"}`}/><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{row.label}</p><p className="text-xs text-slate-500">{row.kind} · {row.status.replaceAll("_"," ")}</p></div><div className="text-right"><p className="text-sm font-semibold">R {Number(row.total).toLocaleString("en-ZA",{minimumFractionDigits:2})}</p><p className="text-xs text-slate-400">{row.date.toLocaleDateString("en-ZA")}</p></div></Link>)}{!recentOrders.length&&!recentQuotes.length?<div className="px-5 py-10 text-center"><p className="font-semibold text-slate-700">No activity yet</p><p className="mt-1 text-sm text-slate-500">Your quotations and orders will appear here.</p></div>:null}</div></section>
      <section className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm"><p className="text-[10px] font-bold uppercase tracking-[.17em] text-cyan-700">Quick actions</p><h2 className="mt-1 text-lg font-semibold">How can we help?</h2><div className="mt-5 grid gap-3">{[{label:"Request products or pricing",detail:"Tell us what your organisation needs",href:"/quotations/request",icon:ClipboardList},{label:"Track an order or delivery",detail:"View fulfilment and delivery progress",href:"/account/orders",icon:PackageCheck},{label:"Open a support request",detail:"Get product, technical or account help",href:"/account/support",icon:Headphones},{label:"Access account documents",detail:"Find quotations, invoices and records",href:"/account",icon:FileText}].map(action=>{const Icon=action.icon;return <Link className="group flex items-center gap-3 rounded-lg border border-slate-200 p-3.5 hover:border-cyan-400 hover:bg-cyan-50/60" href={action.href} key={action.label}><span className="grid size-10 place-items-center rounded-lg bg-[#e3f7f7] text-[#087b83]"><Icon className="size-5"/></span><span className="min-w-0 flex-1"><strong className="block text-sm text-slate-900">{action.label}</strong><span className="block text-xs leading-5 text-slate-500">{action.detail}</span></span><ArrowRight className="size-4 text-slate-300 group-hover:text-cyan-700"/></Link>})}</div></section>
    </div>
  </div>;
}
