import { notFound } from "next/navigation";
import { AdminPage, Panel, StatusBadge, buttonClass, inputClass } from "@/components/admin/admin-ui";
import { createServiceTask, updateHelpDeskTicket, updateServiceTask } from "@/domain/communications/actions";
import { requirePermission } from "@/domain/auth/session";
import { prisma } from "@/lib/prisma";

export default async function TicketPage({ params }: { params: Promise<{ id: string }> }) {
  await requirePermission("customers.manage");
  const id = (await params).id;
  const [ticket, staff] = await Promise.all([
    prisma.helpDeskTicket.findUnique({ where: { id }, include: { assignee: true, tasks: { include: { assignedTo: true }, orderBy: [{ dueAt: "asc" }, { createdAt: "desc" }] }, activities: { include: { actor: { select: { name: true, email: true } } }, orderBy: { createdAt: "desc" } } } }),
    prisma.user.findMany({ where: { status: "ACTIVE", accountType: "INTERNAL_EMPLOYEE", deletedAt: null }, select: { id: true, name: true, email: true }, orderBy: { name: "asc" } }),
  ]);
  if (!ticket) notFound();
  return <AdminPage title={ticket.ticketNumber} description={`${ticket.name} · ${ticket.email}`} actions={<StatusBadge value={ticket.status}/>}>
    <div className="grid gap-4 xl:grid-cols-[1.4fr_.8fr]"><div className="space-y-4">
      <Panel title={ticket.subject} description={`${ticket.category} · Opened ${ticket.createdAt.toLocaleString("en-ZA")}`}><p className="whitespace-pre-wrap text-sm leading-6">{ticket.message}</p></Panel>
      <Panel title="Update and reply" description="Customer replies are emailed and added to the visible conversation. Internal notes remain private."><form action={updateHelpDeskTicket} className="grid gap-3 sm:grid-cols-2"><input type="hidden" name="id" value={ticket.id}/><label className="text-sm font-semibold">Status<select className={`${inputClass} mt-1 w-full`} name="status" defaultValue={ticket.status}>{["OPEN","IN_PROGRESS","WAITING_CUSTOMER","RESOLVED","CLOSED"].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm font-semibold">Priority<select className={`${inputClass} mt-1 w-full`} name="priority" defaultValue={ticket.priority}>{["LOW","NORMAL","HIGH","URGENT"].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm font-semibold">Owner<select className={`${inputClass} mt-1 w-full`} name="assignedToId" defaultValue={ticket.assignedToId??""}><option value="">Unassigned</option>{staff.map(x=><option key={x.id} value={x.id}>{x.name??x.email}</option>)}</select></label><label className="text-sm font-semibold">Due date<input className={`${inputClass} mt-1 w-full`} name="dueAt" type="datetime-local" defaultValue={ticket.dueAt?.toISOString().slice(0,16)}/></label><label className="text-sm font-semibold sm:col-span-2">Message to customer<textarea className={`${inputClass} mt-1 min-h-24 w-full`} name="customerMessage" placeholder="Progress update or next step"/></label><label className="text-sm font-semibold sm:col-span-2">Private internal note<textarea className={`${inputClass} mt-1 min-h-20 w-full`} name="internalNote" placeholder="Supplier, technical or operational context"/></label><label className="text-sm font-semibold sm:col-span-2">Resolution summary<textarea className={`${inputClass} mt-1 min-h-20 w-full`} name="resolution" defaultValue={ticket.resolution??""}/></label><button className={`${buttonClass} sm:col-span-2`}>Save ticket update</button></form></Panel>
      <Panel title="Conversation and activity"><div className="space-y-3">{ticket.activities.map(a=><article className={`border-l-2 pl-3 ${a.isInternal?"border-amber-500 bg-amber-50/50 py-2":"border-sky-500"}`} key={a.id}><div className="flex justify-between gap-2"><strong className="text-sm">{a.isInternal?"Internal note":a.type.replaceAll("_"," ")}</strong><span className="text-xs text-slate-500">{a.createdAt.toLocaleString("en-ZA")}</span></div><p className="mt-1 whitespace-pre-wrap text-sm">{a.message}</p><p className="mt-1 text-xs text-slate-500">{a.actor?.name??a.actor?.email??"Customer"}</p></article>)}</div></Panel>
    </div><aside className="space-y-4">
      <Panel title="Create to-do" description="Assigned staff receive an email immediately."><form action={createServiceTask} className="grid gap-3"><input type="hidden" name="ticketId" value={ticket.id}/><input className={inputClass} name="title" placeholder="What needs to be done?" required/><textarea className={`${inputClass} min-h-20`} name="description" placeholder="Instructions or expected outcome"/><select className={inputClass} name="priority" defaultValue="NORMAL">{["LOW","NORMAL","HIGH","URGENT"].map(x=><option key={x}>{x}</option>)}</select><select className={inputClass} name="assignedToId"><option value="">Unassigned</option>{staff.map(x=><option key={x.id} value={x.id}>{x.name??x.email}</option>)}</select><input className={inputClass} name="dueAt" type="datetime-local"/><button className={buttonClass}>Create task</button></form></Panel>
      <Panel title="Ticket to-dos"><div className="space-y-3">{ticket.tasks.map(task=><article className="border border-slate-200 p-3" key={task.id}><div className="flex justify-between gap-2"><strong className="text-sm">{task.title}</strong><StatusBadge value={task.status}/></div><p className="mt-1 text-xs text-slate-500">{task.assignedTo?.name??task.assignedTo?.email??"Unassigned"} · {task.dueAt?.toLocaleString("en-ZA")??"No due date"}</p><form action={updateServiceTask} className="mt-2 flex gap-2"><input type="hidden" name="id" value={task.id}/><select className={`${inputClass} min-h-9 flex-1 py-1`} name="status" defaultValue={task.status}>{["OPEN","IN_PROGRESS","BLOCKED","COMPLETED","CANCELLED"].map(x=><option key={x}>{x}</option>)}</select><button className="text-sm font-semibold text-sky-700">Update</button></form></article>)}{!ticket.tasks.length?<p className="text-sm text-slate-500">No tasks yet.</p>:null}</div></Panel>
    </aside></div>
  </AdminPage>;
}
