import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Gamepad2, Search, ShieldCheck, Truck, Wrench } from "lucide-react";
import { ProductCard } from "@/components/store/product-card";
import { getGamingCatalogue } from "@/domain/catalogue/queries";

export const dynamic="force-dynamic";
export const metadata:Metadata={title:"Gaming PCs, Components & Gear",description:"Shop gaming PCs, laptops, graphics cards, monitors, peripherals and streaming gear with live South African availability.",alternates:{canonical:"/gaming"}};
const href=(params:Record<string,string|undefined>)=>`/gaming?${new URLSearchParams(Object.entries(params).filter((entry):entry is [string,string]=>Boolean(entry[1]))).toString()}`;

export default async function GamingPage({searchParams}:{searchParams:Promise<{search?:string;group?:string;brand?:string;page?:string}>}){
  const query=await searchParams,data=await getGamingCatalogue({...query,page:Number(query.page)||1});
  return <main className="min-h-screen bg-[#f7f9fb] text-slate-950">
    <section className="border-b border-slate-200 bg-white"><div className="mx-auto grid max-w-7xl gap-8 px-4 py-10 sm:px-6 sm:py-14 lg:grid-cols-[minmax(0,1fr)_22rem] lg:items-end lg:px-8">
      <div><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.16em] text-sky-700"><Gamepad2 className="size-4"/>Innozanzi Gaming</p><h1 className="mt-4 max-w-3xl text-4xl font-black tracking-tight sm:text-5xl lg:text-6xl">Serious gaming technology, chosen clearly.</h1><p className="mt-5 max-w-2xl text-base leading-7 text-slate-600 sm:text-lg">Browse gaming PCs, laptops, components and accessories from our live online catalogue—with practical product information and nationwide South African delivery.</p>
        <form className="mt-7 flex max-w-2xl overflow-hidden rounded-xl border border-slate-300 bg-white shadow-sm focus-within:border-sky-600 focus-within:ring-2 focus-within:ring-sky-100" action="/gaming"><Search className="ml-4 mt-3.5 size-5 text-slate-400"/><input name="search" defaultValue={query.search} placeholder="Search gaming PCs, GPUs, monitors and gear" className="h-12 min-w-0 flex-1 px-3 text-base outline-none"/><button className="m-1 rounded-lg bg-sky-700 px-5 text-sm font-bold text-white hover:bg-sky-800">Search</button></form>
        <div className="mt-6 flex flex-wrap gap-x-6 gap-y-2 text-sm text-slate-600"><span className="flex items-center gap-2"><ShieldCheck className="size-4 text-sky-700"/>Verified catalogue details</span><span className="flex items-center gap-2"><Truck className="size-4 text-sky-700"/>National delivery</span></div>
      </div>
      <Link href="/build-a-pc" className="group rounded-xl border border-slate-200 bg-slate-50 p-6 transition hover:border-sky-300 hover:bg-white hover:shadow-sm"><Wrench className="size-7 text-sky-700"/><p className="mt-5 text-xs font-bold uppercase tracking-wider text-slate-500">Professional configurator</p><h2 className="mt-2 text-2xl font-black">Build your gaming PC</h2><p className="mt-2 text-sm leading-6 text-slate-600">Choose compatible components step by step and keep the complete build in one place.</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-sky-700">Open PC Builder<ArrowRight className="size-4 transition-transform group-hover:translate-x-1"/></span></Link>
    </div></section>
    <section className="mx-auto max-w-7xl px-4 py-8 sm:px-6 sm:py-12 lg:px-8">
      <div><p className="text-xs font-bold uppercase tracking-wider text-sky-700">Browse by category</p><nav aria-label="Gaming categories" className="mt-3 flex snap-x gap-2 overflow-x-auto pb-2 [scrollbar-width:none]"><Link href={href({search:query.search,brand:query.brand})} className={`min-h-11 shrink-0 rounded-full border px-4 py-2.5 text-sm font-bold ${!query.group?'border-sky-700 bg-sky-700 text-white':'border-slate-300 bg-white text-slate-700 hover:border-sky-400'}`}>All gaming <span className="ml-1 opacity-70">{data.total}</span></Link>{data.groups.map(group=><Link href={href({group:group.slug,search:query.search,brand:query.brand})} key={group.slug} className={`min-h-11 shrink-0 rounded-full border px-4 py-2.5 text-sm font-semibold ${query.group===group.slug?'border-sky-700 bg-sky-700 text-white':'border-slate-300 bg-white text-slate-700 hover:border-sky-400'}`}>{group.name}<span className="ml-2 text-xs opacity-60">{group.count}</span></Link>)}</nav></div>
      <div className="mt-8 flex flex-col gap-4 border-b border-slate-200 pb-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-sky-700">Gaming catalogue</p><h2 className="mt-1 text-2xl font-black sm:text-3xl">{data.total.toLocaleString("en-ZA")} products</h2><p className="mt-1 text-sm text-slate-500">Current catalogue products matching your selection.</p></div><form action="/gaming" className="grid grid-cols-[minmax(0,1fr)_auto] gap-2 sm:flex"><input type="hidden" name="group" value={query.group??""}/><input type="hidden" name="search" value={query.search??""}/><select name="brand" defaultValue={query.brand??""} className="h-11 min-w-0 rounded-lg border border-slate-300 bg-white px-3 text-sm" aria-label="Gaming brand"><option value="">All brands</option>{data.brands.map(brand=><option key={brand}>{brand}</option>)}</select><button className="rounded-lg border border-slate-300 bg-white px-4 text-sm font-bold text-slate-800 hover:border-sky-500">Apply</button></form></div>
      {data.products.length?<div className="mt-6 grid gap-4 min-[480px]:grid-cols-2 lg:grid-cols-4">{data.products.map(product=><ProductCard product={product} key={product.id}/>)}</div>:<div className="mt-8 rounded-xl border border-dashed border-slate-300 bg-white p-10 text-center text-slate-500"><h2 className="font-bold text-slate-800">No matching gaming products</h2><p className="mt-2 text-sm">Try another category, brand or search term.</p></div>}
      {data.pages>1?<nav className="mt-10 flex flex-wrap justify-center gap-2" aria-label="Gaming catalogue pages">{Array.from({length:data.pages},(_,index)=>index+1).slice(Math.max(0,data.page-3),data.page+2).map(page=><Link className={`grid size-11 place-items-center rounded-lg border text-sm font-bold ${page===data.page?'border-sky-700 bg-sky-700 text-white':'border-slate-300 bg-white text-slate-700'}`} href={href({...query,page:String(page)})} key={page}>{page}</Link>)}</nav>:null}
    </section>
  </main>;
}
