"use client";

import { useActionState, useRef, useState } from "react";
import { loadDraftCommerceSettings, previewCommerceSettings, saveCommerceSettings, saveDraftCommerceSettings } from "@/domain/commerce/actions";
import { commerceSchema, type CommerceSettings } from "@/domain/commerce/config";
import type { PricingDraft } from "@/domain/commerce/draft";
import { innozanziPrice, protectedPrice } from "@/domain/commerce/engine";
import { buttonClass, inputClass } from "@/components/admin/admin-ui";

const labels: Record<string, string> = {
  vatPercent:"Supplier / output VAT (%)", reservePercent:"Returns and risk reserve (%)",
  accessoryMargin:"Accessory target margin (%)", hardwareMargin:"Hardware target margin (%)", premiumMargin:"Premium target margin (%)",
  accessoryMinimum:"Accessory minimum contribution (R)", hardwareMinimum:"Hardware minimum contribution (R)", premiumMinimum:"Premium minimum contribution (R)",
  accessoryLimit:"Accessory cost ceiling, excl. supplier VAT (R)", premiumLimit:"Premium cost starts above (R)",
  supplierDelivery:"Supplier delivery allocation per unit, excl. VAT (R)", surcharge:"Fuel / remote / split-delivery allowance per unit, excl. VAT (R)", handling:"Handling allocation per unit, excl. VAT (R)",
  payfastPercent:"PayFast card fee (%)", payfastFixed:"PayFast fixed fee, excl. VAT (R)", payfastMinimum:"PayFast minimum fee, excl. VAT (R)",
  ozowPercent:"Ozow bank payment fee (%)", ozowFixed:"Ozow fixed fee, excl. VAT (R)", ozowMinimum:"Ozow minimum fee, excl. VAT (R)",
  feeVatPercent:"VAT on gateway fees (%)", payoutAllocation:"Payout allocation per unit, excl. VAT (R)", customerDelivery:"Customer delivery charge (R)",
  freeDeliveryThreshold:"Free customer delivery from (R)", freshnessHours:"Maximum supplier offer age (hours)", platformMonthly:"Monthly platform expense (R)",
  expectedMonthlyUnits:"Expected units sold per month", competitiveAdjustment:"Competitive adjustment (%)",
};
type Preview = Extract<Awaited<ReturnType<typeof previewCommerceSettings>>, {ok:true}>["impact"];

export function PricingEditor({initial,initialDraft}:{initial:CommerceSettings;initialDraft:PricingDraft|null}) {
  const [values,setValues]=useState(initial),[draft,setDraft]=useState(initialDraft);
  const [cost,setCost]=useState(800),[rrp,setRrp]=useState(0),[preview,setPreview]=useState<Preview|null>(null);
  const [feedback,setFeedback]=useState<{tone:"success"|"error";text:string}|null>(null);
  const [operation,setOperation]=useState<"save"|"load"|"preview"|null>(null);
  const [publishState,publishAction,publishing]=useActionState(saveCommerceSettings,{error:"",success:""});
  const revision=useRef(0);
  const parsed=commerceSchema.safeParse(values),settingsError=parsed.success?"":"Check the entered settings.";
  const calculationError=settingsError||(!Number.isFinite(cost)||cost<=0?"Enter a positive supplier cost to calculate a preview.":"");
  const protectedResults=parsed.success&&!calculationError?(["OZOW","PAYFAST"] as const).map(gateway=>protectedPrice(cost,parsed.data,gateway)):[];
  function changed(next:CommerceSettings){revision.current++;setValues(next);setPreview(null);}
  async function save(form:HTMLFormElement){setOperation("save");setFeedback(null);try{const result=await saveDraftCommerceSettings(new FormData(form));if(result.error)setFeedback({tone:"error",text:`Unable to save draft: ${result.error}`});else if(result.draft){setDraft(result.draft);setFeedback({tone:"success",text:`Draft saved successfully. Version ${result.draft.version}, ${new Date(result.draft.savedAt).toLocaleString("en-ZA")}.`});}}catch{setFeedback({tone:"error",text:"Unable to save draft. Check the server log and try again."});}finally{setOperation(null);}}
  async function load(){setOperation("load");setFeedback(null);try{const result=await loadDraftCommerceSettings();if(!result.ok)setFeedback({tone:"error",text:`Unable to load draft: ${result.error}`});else{setDraft(result.draft);changed(result.draft.settings);setFeedback({tone:"success",text:`Draft loaded. Version ${result.draft.version}, saved ${new Date(result.draft.savedAt).toLocaleString("en-ZA")}.`});}}catch{setFeedback({tone:"error",text:"Unable to load draft. Check the server log and try again."});}finally{setOperation(null);}}
  async function generatePreview(form:HTMLFormElement){const requestedRevision=revision.current;setOperation("preview");setFeedback(null);try{const result=await previewCommerceSettings(new FormData(form));if(requestedRevision!==revision.current){setFeedback({tone:"error",text:"Settings changed while the preview was calculating. Preview the catalogue again."});return;}if(!result.ok)setFeedback({tone:"error",text:`Preview failed: ${result.error}`});else{setPreview(result.impact);setFeedback({tone:"success",text:"Preview ready. Review the catalogue impact below."});}}catch{setFeedback({tone:"error",text:"Preview failed. Check the server log and try again."});}finally{setOperation(null);}}

  return <form action={publishAction} className="space-y-6">
    <section className="grid gap-3 rounded border border-slate-300 bg-slate-50 p-4 text-sm md:grid-cols-3"><div><strong>Draft</strong><p>{draft?"Saved":"None"}</p></div><div><strong>Draft version</strong><p className="break-all">{draft?.version??"—"}</p></div><div><strong>Saved</strong><p>{draft?`${new Date(draft.savedAt).toLocaleString("en-ZA")} by ${draft.savedBy}`:"—"}</p></div></section>
    {feedback?<p role={feedback.tone==="error"?"alert":"status"} className={`rounded border p-4 ${feedback.tone==="error"?"border-red-300 bg-red-50 text-red-800":"border-emerald-300 bg-emerald-50 text-emerald-800"}`}>{feedback.text}</p>:null}
    {publishState.error?<p role="alert" className="rounded border border-red-300 bg-red-50 p-4 text-red-800">Publishing failed: {publishState.error}</p>:null}
    {publishState.success?<p role="status" className="rounded border border-emerald-300 bg-emerald-50 p-4 text-emerald-800">{publishState.success}</p>:null}
    <p className="text-sm text-slate-600">The public price protects the higher configured payment cost. Save the exact draft, load it when required, preview catalogue impact, then approve publication.</p>
    <div className="grid gap-4 md:grid-cols-3"><label className="text-sm">VAT registration<select name="vatRegistered" className={inputClass} value={String(values.vatRegistered)} onChange={e=>changed({...values,vatRegistered:e.target.value==="true"})}><option value="false">Not VAT registered</option><option value="true">VAT registered</option></select></label>{Object.entries(labels).map(([key,label])=><label key={key} className="text-sm">{label}<input name={key} type="number" min={key==="competitiveAdjustment"?"-50":"0"} step="0.01" required className={inputClass} value={values[key as keyof CommerceSettings] as number} onChange={e=>changed({...values,[key]:Number(e.target.value)})}/></label>)}<label className="text-sm">Monthly platform allocation<select className={inputClass} name="overheadAllocation" value={values.overheadAllocation} onChange={e=>changed({...values,overheadAllocation:e.target.value as CommerceSettings["overheadAllocation"]})}><option value="NONE">Reporting only</option><option value="PER_UNIT">Divide by expected monthly units</option></select></label><label className="text-sm">Round upward to<select className={inputClass} name="rounding" value={values.rounding} onChange={e=>changed({...values,rounding:e.target.value as CommerceSettings["rounding"]})}><option value="CENT">Nearest cent</option><option value="RAND">Whole rand</option><option value="99">R .99</option></select></label></div>
    <section className="space-y-3 rounded border p-4"><h2 className="font-bold">Additional pricing costs</h2><p className="text-sm text-slate-600">Economic costs after tax recovery. Monthly components divide by expected units and percentage components apply to net revenue.</p><input type="hidden" name="customCosts" value={JSON.stringify(values.customCosts)}/>{values.customCosts.map((component,index)=><div key={index} className="grid gap-2 rounded border p-3 sm:grid-cols-2"><input aria-label="Cost name" className={inputClass} value={component.name} onChange={e=>changed({...values,customCosts:values.customCosts.map((c,i)=>i===index?{...c,name:e.target.value}:c)})}/><select aria-label="Cost basis" className={inputClass} value={component.basis} onChange={e=>changed({...values,customCosts:values.customCosts.map((c,i)=>i===index?{...c,basis:e.target.value as typeof c.basis}:c)})}><option value="PER_ITEM">Rand per item</option><option value="PER_ORDER">Rand per order</option><option value="MONTHLY">Monthly allocation</option><option value="PERCENT_NET">Percentage of net revenue</option></select><input aria-label="Cost amount" className={inputClass} type="number" min="0" step="0.01" value={component.amount} onChange={e=>changed({...values,customCosts:values.customCosts.map((c,i)=>i===index?{...c,amount:Number(e.target.value)}:c)})}/><label><input type="checkbox" checked={component.active} onChange={e=>changed({...values,customCosts:values.customCosts.map((c,i)=>i===index?{...c,active:e.target.checked}:c)})}/> Active</label><input aria-label="Cost description" placeholder="Description" className={inputClass} value={component.description} onChange={e=>changed({...values,customCosts:values.customCosts.map((c,i)=>i===index?{...c,description:e.target.value}:c)})}/><button type="button" onClick={()=>changed({...values,customCosts:values.customCosts.filter((_,i)=>i!==index)})}>Remove cost</button></div>)}<button type="button" className={buttonClass} onClick={()=>changed({...values,customCosts:[...values.customCosts,{name:"New cost",description:"",basis:"PER_ITEM",amount:0,active:true}]})}>Add pricing cost</button></section>
    <section className="space-y-3 rounded border p-4"><h2 className="font-bold">Price simulator</h2><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Supplier cost excluding VAT<input className={inputClass} type="number" min="0.01" step="0.01" value={cost} onChange={e=>setCost(Number(e.target.value))}/></label><label className="text-sm">Supplier RRP benchmark (optional)<input className={inputClass} type="number" min="0" step="0.01" value={rrp} onChange={e=>setRrp(Number(e.target.value))}/></label></div>{calculationError?<p role="alert" className="text-red-700">{calculationError}</p>:<div className="grid gap-4 sm:grid-cols-2">{protectedResults.map(result=><div key={result.gateway} className="rounded border bg-slate-50 p-4 text-sm"><strong>{result.gateway}</strong><p>Protected customer price: R {result.gross.toFixed(2)}</p><p>Landed cost: R {result.landed.toFixed(2)}</p><p>Gateway estimate: R {result.fees.toFixed(2)}</p><p>Operating allocation: R {result.operating.toFixed(2)}</p><p>Other configured costs: R {result.otherCosts.toFixed(2)}</p><p>Reserve: R {result.reserve.toFixed(2)}</p><p>Contribution: R {result.contribution.toFixed(2)} ({result.margin.toFixed(2)}%)</p></div>)}</div>}{parsed.success&&!calculationError?<p className="font-semibold">Innozanzi RRP: R {innozanziPrice(cost,parsed.data).gross.toFixed(2)}{rrp>0?` · Difference from supplier RRP: R ${innozanziPrice(cost,parsed.data).gross.minus(rrp).toFixed(2)}`:" · Supplier RRP not supplied"}</p>:null}</section>
    <label className="block text-sm">Reason for publication<textarea className={inputClass} name="reason" required minLength={8} maxLength={500}/></label>
    <section className="space-y-4 rounded border p-4"><div className="flex flex-wrap gap-3"><button type="button" className={buttonClass} disabled={Boolean(operation)||publishing||Boolean(settingsError)} onClick={e=>void save(e.currentTarget.form!)}>{operation==="save"?"Saving...":"Save draft"}</button><button type="button" className={buttonClass} disabled={Boolean(operation)||publishing||!draft} onClick={()=>void load()}>{operation==="load"?"Loading...":"Load draft"}</button><button type="button" className={buttonClass} disabled={Boolean(operation)||publishing||Boolean(settingsError)} onClick={e=>void generatePreview(e.currentTarget.form!)}>{operation==="preview"?"Generating preview...":"Preview catalogue"}</button></div>
      {preview?<div className="space-y-2 rounded border border-sky-200 bg-sky-50 p-4 text-sm"><h3 className="font-bold">Catalogue preview</h3><div className="grid gap-2 sm:grid-cols-3"><p>Evaluated: <strong>{preview.evaluated}</strong></p><p>Priced successfully: <strong>{preview.pricedSuccessfully}</strong></p><p>Excluded: <strong>{preview.excluded}</strong></p><p>Invalid/blocking: <strong>{preview.blockingErrors}</strong></p><p>Warnings: <strong>{preview.warnings}</strong></p><p>Without supplier RRP: <strong>{preview.withoutRrp}</strong></p><p>Cost-only pricing: <strong>{preview.costOnly}</strong></p><p>Increasing: <strong>{preview.increasing}</strong></p><p>Decreasing: <strong>{preview.decreasing}</strong></p></div><p>Unchanged: {preview.unchanged} · Average change R {preview.averageChange} · Local products below floor: {preview.localBelowFloor}</p><input type="hidden" name="impactToken" value={preview.token}/><label className="block font-semibold"><input name="confirmImpact" type="checkbox" required onChange={e=>e.stopPropagation()}/> I reviewed this impact and approve publication.</label><button className={buttonClass} disabled={publishing||Boolean(operation)}>{publishing?"Publishing...":"Approve & publish pricing"}</button></div>:null}
    </section>
  </form>;
}
