"use client";
import { useState } from "react";
import { saveCommerceSettings } from "@/domain/commerce/actions";
import { commerceSchema, type CommerceSettings } from "@/domain/commerce/config";
import { protectedPrice } from "@/domain/commerce/engine";
import { inputClass, buttonClass } from "@/components/admin/admin-ui";
const labels:Record<string,string>={vatPercent:"Supplier / output VAT (%)",reservePercent:"Returns and risk reserve (%)",accessoryMargin:"Accessory target margin (%)",hardwareMargin:"Hardware target margin (%)",premiumMargin:"Premium target margin (%)",accessoryMinimum:"Accessory minimum contribution (R)",hardwareMinimum:"Hardware minimum contribution (R)",premiumMinimum:"Premium minimum contribution (R)",accessoryLimit:"Accessory cost ceiling, excl. supplier VAT (R)",premiumLimit:"Premium cost starts above (R)",supplierDelivery:"Supplier delivery allocation per unit, excl. VAT (R)",surcharge:"Fuel / remote / split-delivery allowance per unit, excl. VAT (R)",handling:"Handling allocation per unit, excl. VAT (R)",payfastPercent:"PayFast card fee (%)",payfastFixed:"PayFast fixed fee, excl. VAT (R)",payfastMinimum:"PayFast minimum fee, excl. VAT (R)",ozowPercent:"Ozow bank payment fee (%)",ozowFixed:"Ozow fixed fee, excl. VAT (R)",ozowMinimum:"Ozow minimum fee, excl. VAT (R)",feeVatPercent:"VAT on gateway fees (%)",payoutAllocation:"Payout allocation per unit, excl. VAT (R)",customerDelivery:"Customer delivery charge (R)",freeDeliveryThreshold:"Free customer delivery from (R)",freshnessHours:"Maximum supplier offer age (hours)",platformMonthly:"Monthly platform expense (R)"};
export function PricingEditor({initial}:{initial:CommerceSettings}){
 const [values,setValues]=useState(initial),[cost,setCost]=useState(800);
 const parsed=commerceSchema.safeParse(values);let results:ReturnType<typeof protectedPrice>[]=[];let error="";
 try {if(!parsed.success)throw new Error("Check the entered settings.");results=(["OZOW","PAYFAST"] as const).map(g=>protectedPrice(cost,parsed.data,g));}catch(e){error=e instanceof Error?e.message:"Invalid settings";}
 const preview=error?<p className="text-red-700">{error}</p>:<div className="grid gap-4 sm:grid-cols-2">{results.map(p=><div key={p.gateway} className="rounded-lg border bg-slate-50 p-4 text-sm"><strong>{p.gateway}</strong><p>Protected customer price: R {p.gross.toFixed(2)}</p><p>Landed cost: R {p.landed.toFixed(2)}</p><p>Gateway estimate: R {p.fees.toFixed(2)}</p><p>Reserve: R {p.reserve.toFixed(2)}</p><p>Contribution: R {p.contribution.toFixed(2)} ({p.margin.toFixed(2)}%)</p><p>Output VAT: R {p.vat.toFixed(2)}</p></div>)}</div>;
 return <form action={saveCommerceSettings} className="space-y-6"><p className="text-sm text-slate-600">The public price protects the higher of the two configured payment costs. Delivery, handling and fixed fees are conservatively allocated per unit; this avoids underpricing split deliveries. Preview changes before saving. Changes apply immediately to new price calculations; completed orders keep their snapshots.</p><div className="grid gap-4 md:grid-cols-3"><label className="text-sm">VAT registration<select name="vatRegistered" className={inputClass} value={String(values.vatRegistered)} onChange={e=>setValues({...values,vatRegistered:e.target.value==="true"})}><option value="false">Not VAT registered</option><option value="true">VAT registered</option></select></label>{Object.entries(labels).map(([key,label])=><label key={key} className="text-sm">{label}<input name={key} type="number" min="0" step="0.01" required className={inputClass} value={values[key as keyof CommerceSettings] as number} onChange={e=>setValues({...values,[key]:Number(e.target.value)})}/></label>)}<label className="text-sm">Round upward to<select className={inputClass} name="rounding" value={values.rounding} onChange={e=>setValues({...values,rounding:e.target.value as CommerceSettings["rounding"]})}><option value="CENT">Nearest cent</option><option value="RAND">Whole rand</option><option value="99">R .99</option></select></label></div><section className="space-y-3 rounded-lg border p-4"><h2 className="font-bold">Price simulator</h2><label className="text-sm">Supplier cost excluding VAT<input className={inputClass} type="number" min="0.01" step="0.01" value={cost} onChange={e=>setCost(Number(e.target.value))}/></label>{preview}</section><label className="block text-sm">Reason for change<textarea className={inputClass} name="reason" required minLength={8} maxLength={500}/></label><button className={buttonClass}>Publish pricing settings</button></form>;
}
