import Link from "next/link";
import { requireUser } from "@/domain/auth/session";
import { prisma } from "@/lib/prisma";

export default async function SupportTicketsPage() {
  const { user } = await requireUser();
  const tickets = await prisma.helpDeskTicket.findMany({ where: { OR: [{ customerId: user.id }, { customerId: null, email: { equals: user.email, mode: "insensitive" } }] }, orderBy: { createdAt: "desc" } });
  return <main className="mx-auto min-w-0 max-w-5xl px-4 py-6 sm:px-6 sm:py-10"><p className="text-xs font-bold uppercase tracking-wider text-sky-700">Support</p><div className="flex min-w-0 flex-col items-start gap-3 sm:flex-row sm:items-end sm:justify-between"><div className="min-w-0"><h1 className="mt-1 text-3xl font-black">Your support tickets</h1><p className="mt-2 text-slate-600">Track questions, progress updates and resolutions in one place.</p></div><Link className="inline-flex min-h-12 w-full items-center justify-center rounded-lg bg-sky-600 px-4 py-3 text-center font-bold text-white sm:w-auto" href="/contact">Start a conversation</Link></div><div className="mt-6 space-y-3 sm:mt-7">{tickets.map(ticket=><Link className="grid min-w-0 gap-3 rounded-xl border border-slate-200 bg-white p-4 shadow-sm hover:border-sky-400 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center" href={`/account/support/${ticket.id}`} key={ticket.id}><div className="min-w-0"><p className="break-all text-xs font-bold text-sky-700 sm:break-words">{ticket.ticketNumber}</p><h2 className="mt-1 break-words font-bold">{ticket.subject}</h2><p className="mt-1 text-sm text-slate-500">{ticket.category} · Opened {ticket.createdAt.toLocaleDateString("en-ZA")}</p></div><span className="text-sm font-semibold">{ticket.status.replaceAll("_"," ")}</span></Link>)}{!tickets.length?<div className="rounded-xl border border-dashed p-6 text-center sm:p-10"><h2 className="font-bold">No support tickets yet</h2><p className="mt-1 text-sm text-slate-500">When you contact our help desk, your tracked conversation will appear here.</p></div>:null}</div></main>;
}
