import { notFound } from "next/navigation";
import Link from "next/link";
import { AdminPage, Panel, buttonClass, inputClass, secondaryButtonClass } from "@/components/admin/admin-ui";
import { saveShipmentDetails } from "@/domain/admin/actions";
import { requirePermission } from "@/domain/auth/session";
import { prisma } from "@/lib/prisma";

export default async function DeliveryPlanPage({params}:{params:Promise<{id:string}>}) {
  await requirePermission("orders.update");const order=await prisma.order.findUnique({where:{id:(await params).id},include:{shipments:{orderBy:{createdAt:"desc"},take:1}}});if(!order)notFound();const shipment=order.shipments[0];
  return <AdminPage title={`Plan delivery · ${order.orderNumber}`} description="Record the delivery provider and planned date. Saving emails the customer and adds a tracking event." actions={<Link className={secondaryButtonClass} href={`/admin/orders/${order.id}`}>Back to order</Link>}><Panel><form action={saveShipmentDetails} className="grid gap-3 sm:grid-cols-2"><input type="hidden" name="orderId" value={order.id}/><label className="text-sm font-semibold">Delivery company<input className={`${inputClass} mt-1 w-full`} name="deliveryCompany" defaultValue={shipment?.deliveryCompany??""} required/></label><label className="text-sm font-semibold">Planned delivery<input className={`${inputClass} mt-1 w-full`} name="estimatedDeliveryAt" type="datetime-local" defaultValue={shipment?.estimatedDeliveryAt?.toISOString().slice(0,16)} required/></label><label className="text-sm font-semibold">Driver/contact name<input className={`${inputClass} mt-1 w-full`} name="contactName" defaultValue={shipment?.contactName??""}/></label><label className="text-sm font-semibold">Contact phone<input className={`${inputClass} mt-1 w-full`} name="contactPhone" defaultValue={shipment?.contactPhone??""}/></label><label className="text-sm font-semibold">Tracking number<input className={`${inputClass} mt-1 w-full`} name="trackingNumber" defaultValue={shipment?.trackingNumber??""}/></label><label className="text-sm font-semibold">Tracking URL<input className={`${inputClass} mt-1 w-full`} name="trackingUrl" type="url" defaultValue={shipment?.trackingUrl??""}/></label><label className="text-sm font-semibold sm:col-span-2">Delivery instructions<textarea className={`${inputClass} mt-1 min-h-24 w-full`} name="deliveryInstructions" defaultValue={shipment?.deliveryInstructions??""}/></label><button className={`${buttonClass} sm:col-span-2`}>Save plan and notify customer</button></form></Panel></AdminPage>;
}
