import Link from "next/link";
import Decimal from "decimal.js";
import {z} from "zod";
import {requirePermission} from "@/domain/auth/session";
import {getTradingData} from "@/domain/commerce/trading-data";
import {AdminPage,MetricCard,Panel,inputClass,buttonClass,tableClass} from "@/components/admin/admin-ui";
import {formatZar} from "@/lib/money";

export default async function TradingPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
  await requirePermission("reports.view");
  const query=z.object({days:z.enum(["30","90"]).catch("30"),q:z.string().max(100).catch(""),supplier:z.string().max(150).catch(""),category:z.string().max(150).catch(""),view:z.enum(["revenue","velocity","low-velocity","margin","low-margin","cost-increase","price-movement","near-floor","exceptions"]).catch("revenue"),page:z.coerce.number().int().min(1).max(100000).catch(1)}).parse(await searchParams);
  const data=await getTradingData(Number(query.days));
  const suppliers=[...new Set(data.rows.map(r=>r.supplier))].sort(),categories=[...new Set(data.rows.map(r=>r.category))].sort();
  const selected=data.rows.filter(row=>(!query.q||`${row.name} ${row.sku}`.toLowerCase().includes(query.q.toLowerCase()))&&(!query.supplier||row.supplier===query.supplier)&&(!query.category||row.category===query.category));
  const sum=(key:"revenue"|"knownContribution")=>selected.reduce((total,row)=>total.plus(row.summary?.[key]??0),new Decimal(0));
  const units=selected.reduce((n,row)=>n+(row.summary?.units??0),0),missing=selected.reduce((n,row)=>n+(row.summary?.unknownLines??0),0);
  const filtered=selected.filter(row=>query.view==="cost-increase"?row.costMovement!==null&&new Decimal(row.costMovement).gt(0):query.view==="price-movement"?row.priceMovement!==null&&!new Decimal(row.priceMovement).isZero():query.view==="near-floor"?row.headroom!==null&&new Decimal(row.headroom).lte(5):query.view==="exceptions"?Boolean(row.reason):query.view==="margin"||query.view==="low-margin"?row.margin!==null:true);
  filtered.sort((a,b)=>{
    if(query.view==="velocity"||query.view==="low-velocity")return ((b.summary?.units??0)-(a.summary?.units??0))*(query.view==="low-velocity"?-1:1)||a.name.localeCompare(b.name);
    if(query.view==="margin"||query.view==="low-margin")return new Decimal(b.margin??0).comparedTo(a.margin??0)*(query.view==="low-margin"?-1:1)||a.name.localeCompare(b.name);
    if(query.view==="cost-increase")return new Decimal(b.costMovement??0).comparedTo(a.costMovement??0);
    return new Decimal(b.summary?.revenue??0).comparedTo(a.summary?.revenue??0)||a.name.localeCompare(b.name);
  });
  const pages=Math.max(1,Math.ceil(filtered.length/50)),page=Math.min(query.page,pages),rows=filtered.slice((page-1)*50,page*50);
  const pageUrl=(n:number)=>"/admin/trading?"+new URLSearchParams({...query,page:String(n)} as Record<string,string>);
  const money=(value:string|null|undefined)=>value==null?"Unknown":formatZar(value);
  return <AdminPage title="Trading desk" eyebrow="Commerce" description="Review product performance, current margin and commercial changes before deciding whether to adjust pricing." actions={<Link className={buttonClass} href="/admin/pricing">Open pricing review</Link>}>
    <Panel><form className="grid gap-3 sm:grid-cols-3 lg:grid-cols-6" method="get"><label className="text-xs font-bold">Period<select className={inputClass} name="days" defaultValue={query.days}><option value="30">Last 30 days</option><option value="90">Last 90 days</option></select></label><label className="text-xs font-bold">Product / SKU<input className={inputClass} name="q" defaultValue={query.q}/></label><label className="text-xs font-bold">Supplier<select className={inputClass} name="supplier" defaultValue={query.supplier}><option value="">All suppliers</option>{suppliers.map(s=><option key={s}>{s}</option>)}</select></label><label className="text-xs font-bold">Category<select className={inputClass} name="category" defaultValue={query.category}><option value="">All categories</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label className="text-xs font-bold">Commercial view<select className={inputClass} name="view" defaultValue={query.view}>{[["revenue","Top revenue"],["velocity","Strong sales velocity"],["low-velocity","Low / no sales"],["margin","High current margin"],["low-margin","Low current margin"],["cost-increase","Supplier cost increased"],["price-movement","Price changed"],["near-floor","Near / below safe floor"],["exceptions","Pricing exceptions"]].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><button className={buttonClass+" self-end"}>Apply filters</button></form></Panel>
    <div className="grid gap-3 sm:grid-cols-4"><MetricCard label="Units sold" value={units} detail={`Selected products · ${data.days} days`}/><MetricCard label="Product revenue" value={formatZar(sum("revenue").toFixed(2))} detail="Excludes output VAT and delivery"/><MetricCard label={missing?"Known contribution only":"Expected contribution"} value={formatZar(sum("knownContribution").toFixed(2))} detail={missing?`${missing} sale lines lack exact economics` :"Saved sale economics, not actual profit"}/><MetricCard label="Products / offers" value={selected.length} detail={`${filtered.length} match commercial view`}/></div>
    <p className="text-sm text-slate-600">Sales use paid, non-test orders placed in the selected period. {data.refundCount} refunded or partially refunded orders across the comparison periods are excluded; refund profitability remains in <Link className="underline" href="/admin/returns/profitability">Returns</Link>. Each distributor offer is shown separately. Current margin uses the active pricing policy; movements compare with the latest recorded sale in the two periods, not a continuous market-price history. Missing comparisons mean no evidence.</p>
    {data.orderCount>data.loadedOrders?<p role="alert" className="rounded bg-amber-50 p-3 text-sm font-bold">Report limited to the latest {data.loadedOrders} of {data.orderCount} orders. Totals and comparisons are incomplete; narrow the reporting period.</p>:null}
    <Panel title="Product performance" description="Review cost increases, declining sales and floor headroom. Trading does not change prices automatically.">
      <table className={tableClass}><thead><tr><th>Product / source</th><th>Sales</th><th>Saved contribution</th><th>Current economics</th><th>Movement / next action</th></tr></thead><tbody>{rows.map(row=><tr key={row.key}><td><strong>{row.name}</strong><br/><span className="text-xs">{row.sku}<br/>{row.supplier} · {row.category}<br/>Stock: {row.stock??"See inventory"}</span></td><td>{row.summary?.units??0} units<br/>{money(row.summary?.revenue??"0")} net revenue<br/><span className="text-xs">Previous: {row.summary?.previousUnits??0} units<br/>Change: {row.summary?.unitsChange??0} units<br/>{((row.summary?.units??0)/data.days).toFixed(2)} units/day</span></td><td>{row.summary?.units?money(row.summary.expectedContribution):"No sales"}<br/>{row.summary?.margin!=null?`${row.summary.margin}% margin`:"Margin unknown"}</td><td className="text-xs">Cost: {money(row.cost)}<br/>Supplier RRP: {row.rrp?money(row.rrp):"Not supplied"}<br/>Innozanzi price: {money(row.price)}<br/>Safe floor: {money(row.floor)}<br/>Contribution margin: {row.margin??"Unknown"}{row.margin?"%":""}<br/>Floor headroom: {row.headroom??"Unknown"}{row.headroom?"%":""}</td><td className="text-xs">Cost change: {money(row.costMovement)}<br/>Price change: {money(row.priceMovement)}<br/>{row.comparisonDate?`Since sale ${row.comparisonDate.toISOString().slice(0,10)}`:"No recorded comparison"}{row.reason?<p className="mt-2 font-bold text-amber-800">{row.reason}</p>:null}<Link className="mt-2 inline-block font-bold text-sky-800 underline" href={row.reason?"/admin/risk":"/admin/pricing"}>{row.reason?"Review exception":"Review pricing"}</Link></td></tr>)}{!rows.length?<tr><td colSpan={5}>No products match these filters.</td></tr>:null}</tbody></table>
      <div className="mt-4 flex justify-between text-sm">{page>1?<Link className="underline" href={pageUrl(page-1)}>Previous</Link>:<span/>}<span>Page {page} of {pages}</span>{page<pages?<Link className="underline" href={pageUrl(page+1)}>Next</Link>:<span/>}</div>
    </Panel>
    <Panel title="Actual reconciled order profit" description="Latest finance reconciliation for paid orders in this period. Actual order costs are not arbitrarily allocated to products."><table className={tableClass}><thead><tr><th>Order</th><th>Actual profit</th><th>Margin</th><th>Reconciled (UTC)</th></tr></thead><tbody>{data.actual.map(order=><tr key={order.id}><td><Link className="underline" href={`/admin/orders/${order.id}`}>{order.number}</Link></td><td>{money(order.profit)}</td><td>{order.margin}%</td><td>{order.reconciledAt.toISOString()}</td></tr>)}{!data.actual.length?<tr><td colSpan={4}>No reconciled order costs in this period. Actual profit is unknown.</td></tr>:null}</tbody></table></Panel>
  </AdminPage>;
}
