import { Building2, CircleAlert, Landmark } from "lucide-react";
import { uploadOrderPaymentProof } from "@/domain/checkout/proof-actions";
import { retryOrderPayment } from "@/domain/payments/customer-actions";
import type { RetailPaymentSettings } from "@/domain/payments/settings";
import { formatZar } from "@/lib/money";

type PaymentOrder = { id: string; orderNumber: string; grandTotal: { toString(): string }; paymentMethod: string; paymentStatus: string };

export function OrderPaymentPanel({ order, notice, ozowAvailable, eftSettings }: { order: PaymentOrder; notice?: string; ozowAvailable: boolean; eftSettings: RetailPaymentSettings }) {
  if (order.paymentStatus === "AWAITING_REVIEW") return <section className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-5 sm:p-6"><h2 className="text-xl font-black text-amber-950">EFT proof under review</h2><p className="mt-2 text-sm leading-6 text-amber-900">Your order has not entered fulfilment yet. We’ll notify you after finance verifies the payment in the company bank account.</p></section>;
  const eftAvailable = eftSettings.eftEnabled && Boolean(eftSettings.bankName && eftSettings.accountHolder && eftSettings.accountNumber && eftSettings.branchCode);
  const isEft = order.paymentMethod === "EFT" && order.paymentStatus === "PENDING" && eftAvailable;
  const title = notice === "cancelled" || order.paymentStatus === "CANCELLED" ? "Payment cancelled — your order is still unpaid" : notice === "error" || order.paymentStatus === "FAILED" ? "Payment was not completed" : notice === "processing" ? "Waiting for Ozow confirmation" : isEft ? "Complete your EFT payment" : "Payment required";
  return <section className="mt-6 rounded-2xl border border-amber-200 bg-white p-5 shadow-sm sm:p-6">
    <div className="flex gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-full bg-amber-100 text-amber-800"><CircleAlert className="size-5"/></span><div><h2 className="text-xl font-black text-slate-950">{title}</h2><p className="mt-1 text-sm leading-6 text-slate-600">{notice === "processing" ? "Your bank response is being verified. If the status does not update shortly, you can safely return here and try again." : "Nothing is being packed or delivered until payment is confirmed."}</p></div></div>
    {isEft ? <div className="mt-5 rounded-xl bg-slate-900 p-5 text-sm text-white">
      <div className="flex items-center gap-2"><Building2 className="size-5 text-sky-300"/><h3 className="font-bold">Innozanzi EFT details</h3></div>
      <dl className="mt-4 grid gap-3 sm:grid-cols-2"><div><dt className="text-xs text-slate-400">Bank</dt><dd className="font-semibold">{eftSettings.bankName}</dd></div><div><dt className="text-xs text-slate-400">Account holder</dt><dd className="font-semibold">{eftSettings.accountHolder}</dd></div><div><dt className="text-xs text-slate-400">Account number</dt><dd className="font-semibold">{eftSettings.accountNumber}</dd></div><div><dt className="text-xs text-slate-400">Branch code</dt><dd className="font-semibold">{eftSettings.branchCode}</dd></div>{eftSettings.accountType ? <div><dt className="text-xs text-slate-400">Account type</dt><dd className="font-semibold">{eftSettings.accountType}</dd></div> : null}<div><dt className="text-xs text-slate-400">Payment reference</dt><dd className="font-semibold">{order.orderNumber}</dd></div></dl>
      <p className="mt-4 border-t border-slate-700 pt-4 text-slate-300">{eftSettings.instructions || "Use the order number exactly as your payment reference."}</p>
      <p className="mt-2 font-bold">Amount: {formatZar(order.grandTotal.toString())}</p>
    </div> : null}
    {isEft ? <form action={uploadOrderPaymentProof} className="mt-5 rounded-xl border border-slate-200 p-4"><input type="hidden" name="orderId" value={order.id}/><label className="text-sm font-bold text-slate-900">Upload proof of payment<input className="mt-2 block w-full rounded-lg border border-slate-300 p-2 text-sm" name="proof" type="file" accept=".pdf,image/jpeg,image/png,image/webp" required/></label><p className="mt-2 text-xs text-slate-500">PDF, JPG, PNG or WebP; maximum 10 MB. Uploading proof does not confirm payment automatically.</p><button className="mt-4 min-h-11 rounded-lg bg-sky-700 px-5 text-sm font-bold text-white">Submit proof for verification</button></form> : null}
    {(ozowAvailable || eftAvailable) ? <form action={retryOrderPayment} className="mt-5 border-t border-slate-200 pt-5"><input type="hidden" name="orderId" value={order.id}/><label className="text-sm font-bold text-slate-900">{isEft ? "Or choose another payment method" : "Choose how to pay"}<select className="mt-2 min-h-12 w-full rounded-lg border border-slate-300 bg-white px-3" name="paymentMethod" defaultValue={ozowAvailable ? "OZOW" : "EFT"}>{ozowAvailable ? <option value="OZOW">Ozow instant bank payment</option> : null}{eftAvailable ? <option value="EFT">Manual EFT and proof upload</option> : null}</select></label><button className="mt-3 flex min-h-12 w-full items-center justify-center gap-2 rounded-lg bg-emerald-700 px-5 font-bold text-white hover:bg-emerald-800">{ozowAvailable ? <Landmark className="size-5"/> : <Building2 className="size-5"/>}Continue to payment</button></form> : <p className="mt-5 rounded-lg bg-amber-50 p-3 text-sm text-amber-900">Payment options are temporarily unavailable. Please contact support.</p>}
  </section>;
}
