import Link from "next/link";
import { AdminPage, Panel, StatusBadge, inputClass, secondaryButtonClass, tableClass } from "@/components/admin/admin-ui";
import { setProductStatus } from "@/domain/admin/actions";
import { requirePermission } from "@/domain/auth/session";
import { sellableSupplierWhere } from "@/integrations/suppliers/availability";
import { prisma } from "@/lib/prisma";

const money=(value:{toString():string}|null|undefined)=>value?`R ${Number(value.toString()).toLocaleString("en-ZA",{minimumFractionDigits:2,maximumFractionDigits:2})}`:"—";
const identityLabel=(key:string|null)=>key?.startsWith("gtin:")?"Matched by barcode":key?.startsWith("mpn:")?"Matched by brand + MPN":"Supplier-only offer";

export default async function ProductsPage({searchParams}:{searchParams:Promise<{search?:string;supplier?:string;visibility?:string}>}) {
  await requirePermission("products.view");
  const params=await searchParams,search=params.search?.trim(),visibility=params.visibility??"all",publicWhere=await sellableSupplierWhere();
  const suppliers=await prisma.supplier.findMany({where:{deletedAt:null,isActive:true},select:{id:true,companyName:true},orderBy:{companyName:"asc"}});
  const manualWhere={deletedAt:null,...(search?{OR:[{name:{contains:search,mode:"insensitive" as const}},{sku:{contains:search,mode:"insensitive" as const}},{barcode:{contains:search,mode:"insensitive" as const}},{brand:{name:{contains:search,mode:"insensitive" as const}}},{category:{name:{contains:search,mode:"insensitive" as const}}}]}:{})};
  const visibilityWhere=visibility==="sellable"?publicWhere:visibility==="unavailable"?{OR:[{availability:{not:"IN_STOCK"}},{stock:{lte:0}}]}:visibility==="no-image"?{images:{isEmpty:true}}:visibility==="alternate"?{displayPreferred:false}:{};
  const supplierWhere={active:true,...(params.supplier?{supplierId:params.supplier}:{}),...visibilityWhere,...(search?{OR:[{name:{contains:search,mode:"insensitive" as const}},{supplierSku:{contains:search,mode:"insensitive" as const}},{manufacturerSku:{contains:search,mode:"insensitive" as const}},{barcode:{contains:search,mode:"insensitive" as const}},{brand:{contains:search,mode:"insensitive" as const}},{category:{contains:search,mode:"insensitive" as const}}]}:{})};
  const[manualProducts,supplierProducts,manualTotal,supplierTotal,allOffers,publicOffers,alternateOffers,supplierStats]=await Promise.all([
    prisma.product.findMany({where:manualWhere,include:{category:true,brand:true,inventory:true},orderBy:{updatedAt:"desc"},take:search?200:100}),
    prisma.supplierCatalogueProduct.findMany({where:supplierWhere,include:{supplier:{select:{companyName:true}}},orderBy:{sourceUpdatedAt:"desc"},take:search?200:100}),
    prisma.product.count({where:manualWhere}),prisma.supplierCatalogueProduct.count({where:supplierWhere}),
    prisma.supplierCatalogueProduct.count({where:{active:true}}),prisma.supplierCatalogueProduct.count({where:publicWhere}),prisma.supplierCatalogueProduct.count({where:{active:true,displayPreferred:false}}),
    Promise.all(suppliers.map(async supplier=>{const [total,inStock,visible,noImage]=await Promise.all([prisma.supplierCatalogueProduct.count({where:{active:true,supplierId:supplier.id}}),prisma.supplierCatalogueProduct.count({where:{active:true,supplierId:supplier.id,availability:"IN_STOCK",stock:{gt:0}}}),prisma.supplierCatalogueProduct.count({where:{supplierId:supplier.id,...publicWhere}}),prisma.supplierCatalogueProduct.count({where:{active:true,supplierId:supplier.id,images:{isEmpty:true}}})]);return{supplier,total,inStock,visible,noImage};})),
  ]);
  const total=manualTotal+supplierTotal;
  return <AdminPage title="Products" description="One catalogue across every approved distributor, with the selected fulfilment source retained on every offer and order.">
    <div className="grid gap-3 md:grid-cols-3"><Panel><p className="text-xs font-bold uppercase text-slate-500">All distributor offers</p><p className="mt-2 text-3xl font-bold">{allOffers.toLocaleString("en-ZA")}</p></Panel><Panel><p className="text-xs font-bold uppercase text-slate-500">Unified storefront products</p><p className="mt-2 text-3xl font-bold text-emerald-700">{publicOffers.toLocaleString("en-ZA")}</p></Panel><Panel><p className="text-xs font-bold uppercase text-slate-500">Hidden duplicate alternatives</p><p className="mt-2 text-3xl font-bold text-amber-700">{alternateOffers.toLocaleString("en-ZA")}</p></Panel></div>
    <div className="grid gap-3 md:grid-cols-2">{supplierStats.map(({supplier,total:count,inStock,visible,noImage})=><Panel key={supplier.id}><div className="flex items-center justify-between gap-3"><h2 className="font-bold">{supplier.companyName}</h2><Link className="text-sm font-semibold text-sky-700" href={`/admin/products?supplier=${supplier.id}`}>View products</Link></div><p className="mt-3 text-sm text-slate-600">{count.toLocaleString("en-ZA")} total · {inStock.toLocaleString("en-ZA")} in stock · {visible.toLocaleString("en-ZA")} selected for storefront · {noImage.toLocaleString("en-ZA")} without images</p></Panel>)}</div>
    <Panel>
      <form className="grid gap-2 md:grid-cols-[minmax(16rem,1fr)_14rem_14rem_auto]"><input className={inputClass} name="search" defaultValue={search} placeholder="Product name, SKU, MPN or barcode"/><select className={inputClass} name="supplier" defaultValue={params.supplier}><option value="">All distributors</option>{suppliers.map(supplier=><option key={supplier.id} value={supplier.id}>{supplier.companyName}</option>)}</select><select className={inputClass} name="visibility" defaultValue={visibility}><option value="all">All feed records</option><option value="sellable">Shown on storefront</option><option value="alternate">Duplicate alternatives</option><option value="unavailable">Unavailable / no stock</option><option value="no-image">Missing image</option></select><button className={secondaryButtonClass}>Apply filters</button></form>
      <p className="mt-3 text-xs text-slate-500">{total.toLocaleString("en-ZA")} matching products · {manualTotal.toLocaleString("en-ZA")} managed internally · {supplierTotal.toLocaleString("en-ZA")} distributor offers</p>
    </Panel>
    <Panel title="Distributor-feed products" description="The storefront shows only the best currently sellable offer for a matched product. Every alternative remains here for audit and supplier switching.">
      <table className={tableClass}><thead><tr><th>Product / identifiers</th><th>Distributor</th><th>Catalogue role</th><th>Supplier cost</th><th>Customer reference</th><th>Stock</th><th></th></tr></thead><tbody>{supplierProducts.map(p=><tr key={p.id}><td><strong>{p.name}</strong><small className="block text-slate-500">SKU {p.supplierSku}{p.manufacturerSku?` · MPN ${p.manufacturerSku}`:""}{p.barcode?` · Barcode ${p.barcode}`:""}</small></td><td className="font-semibold">{p.supplier.companyName}</td><td><StatusBadge value={p.displayPreferred?"STOREFRONT":"ALTERNATE"}/><small className="mt-1 block text-slate-500">{identityLabel(p.identityKey)}</small></td><td className="text-rose-800">{money(p.costPrice)}<small className="block">Private</small></td><td>{money(p.promotionalPrice??p.recommendedRetail)}</td><td>{p.stock}<small className="block"><StatusBadge value={p.availability}/>{p.images.length?null:<span className="ml-1 text-rose-700">No image</span>}</small></td><td><Link className={secondaryButtonClass} href={`/admin/syntech/products/${p.id}`}>Inspect</Link></td></tr>)}</tbody></table>
      {!supplierProducts.length?<p className="py-8 text-center text-sm text-slate-500">No distributor products match these filters.</p>:null}{supplierTotal>supplierProducts.length?<p className="mt-3 text-xs text-slate-500">Showing {supplierProducts.length.toLocaleString("en-ZA")} of {supplierTotal.toLocaleString("en-ZA")} matches. Search by SKU or product name to locate an exact item.</p>:null}
    </Panel>
    {!params.supplier&&visibility==="all"?<Panel title="Internally managed products" description="Products created and controlled directly in Innozanzi.">
      <table className={tableClass}><thead><tr><th>Product / identifiers</th><th>Category</th><th>Cost</th><th>Customer price</th><th>Available</th><th>Status</th><th>Manage</th></tr></thead><tbody>{manualProducts.map(p=><tr key={p.id}><td><strong>{p.name}</strong><small className="block text-slate-500">SKU {p.sku}{p.barcode?` · Barcode ${p.barcode}`:""}</small></td><td>{p.category.name}</td><td className="text-rose-800">{money(p.costPrice)}<small className="block">Private</small></td><td>{money(p.salePrice??p.regularPrice)}</td><td>{p.inventory.reduce((n,i)=>n+i.onHand-i.reserved,0)}</td><td><StatusBadge value={p.status}/></td><td><form action={setProductStatus} className="flex gap-2"><input type="hidden" name="id" value={p.id}/><select name="status" defaultValue={p.status} className="rounded border px-2 py-1"><option>DRAFT</option><option>PUBLISHED</option><option>ARCHIVED</option></select><button className="text-sky-800 underline">Save</button></form></td></tr>)}</tbody></table>
    </Panel>:null}
  </AdminPage>;
}
