import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminPage, Panel, StatusBadge, buttonClass, inputClass, secondaryButtonClass, tableClass } from "@/components/admin/admin-ui";
import { requirePermission } from "@/domain/auth/session";
import { quotePartnerCase } from "@/domain/partner-sales/cases";

export default async function SalesCaseDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const actor = await requirePermission("partner_sales.pricing.approve");
  const { id } = await params;
  let preview;
  try { preview = await quotePartnerCase(id, actor); } catch (error) { if (error instanceof Error && error.message === "Partner quote case not found.") notFound(); throw error; }
  const pricing = preview.pricing;
  return <AdminPage title={`Partner case ${preview.caseNumber}`} description="Review live cost, stock, protected floor, gateway economics, commission and client totals before issuing an immutable quotation version." actions={<><StatusBadge value={preview.status} /><Link className={secondaryButtonClass} href="/admin/partnerships/sales-cases">Back to queue</Link></>}>
    <div className="grid gap-4 xl:grid-cols-[1.35fr_.65fr]">
      <Panel title="Commercial editor" description="Prices below the protected floor, stale cost/stock evidence and negative post-commission contribution are rejected by the approval transaction.">
        <form action={`/api/admin/partner-sales/cases/${preview.caseId}/approve`} className="space-y-4" method="post">
          <input name="caseId" type="hidden" value={preview.caseId} />
          <input name="items" type="hidden" value={JSON.stringify(pricing.items.map((item) => ({ id: item.id, unitPrice: item.approvedGrossUnit.toFixed(2) })))} />
          <div className="overflow-x-auto"><table className={tableClass}><thead><tr><th>Item</th><th>Qty</th><th>Cost (internal)</th><th>Protected floor</th><th>Client unit price</th><th>Contribution</th></tr></thead><tbody>{pricing.items.map((item) => <tr key={item.id}><td>{item.title}<br /><span className="text-xs text-slate-500">{item.sourceType ?? "source"} · {item.availabilityFingerprint ?? "live"}</span></td><td>{item.quantity}</td><td>R {item.cost.toString()}</td><td>R {item.protectedGrossUnit.toFixed(2)}</td><td><input aria-label={`${item.title} client unit price`} className={`${inputClass} w-32`} defaultValue={item.approvedGrossUnit.toFixed(2)} name={`price-${item.id}`} /></td><td>R {item.contribution.toFixed(2)}</td></tr>)}</tbody></table></div>
          <div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Delivery (gross)<input className={`${inputClass} mt-1`} defaultValue={pricing.deliveryTotal.toFixed(2)} min="0" name="deliveryTotal" step="0.01" type="number" /></label><label className="text-sm font-semibold">Discount (gross)<input className={`${inputClass} mt-1`} defaultValue={pricing.discountTotal.toFixed(2)} min="0" name="discountTotal" step="0.01" type="number" /></label><label className="text-sm font-semibold">Gateway<select className={`${inputClass} mt-1`} defaultValue={pricing.gateway} name="gateway"><option>PAYFAST</option><option>OZOW</option><option>EFT</option></select></label><label className="text-sm font-semibold">Expiry override (optional)<input className={`${inputClass} mt-1`} min={new Date().toISOString().slice(0, 16)} name="validUntil" type="datetime-local" /></label></div>
          <fieldset className="grid gap-3 border border-slate-200 p-3 sm:grid-cols-2"><legend className="px-1 text-sm font-semibold">Commission approval</legend><label className="text-sm font-semibold">Method<select className={`${inputClass} mt-1`} defaultValue={pricing.commissionMethod} name="commissionMethod"><option value="PERCENTAGE">Percentage</option><option value="FIXED_AMOUNT">Fixed amount</option></select></label><label className="text-sm font-semibold">Value<input className={`${inputClass} mt-1`} defaultValue={pricing.commissionValue.toFixed(2)} min="0" name="commissionValue" step="0.01" type="number" /></label><label className="text-sm font-semibold sm:col-span-2">Override reason (required when changing the approved default)<textarea className={`${inputClass} mt-1`} maxLength={2000} name="commissionOverrideReason" rows={2} /></label></fieldset>
          <button className={buttonClass} type="submit">Approve immutable quotation version</button>
        </form>
      </Panel>
      <div className="space-y-4"><Panel title="Internal economics"><dl className="grid gap-2 text-sm"><div className="flex justify-between gap-3"><dt>Net sale</dt><dd className="font-semibold">R {pricing.netSale.toFixed(2)}</dd></div><div className="flex justify-between gap-3"><dt>VAT</dt><dd>R {pricing.vatTotal.toFixed(2)}</dd></div><div className="flex justify-between gap-3"><dt>Gateway fees</dt><dd>R {pricing.fees.toFixed(2)}</dd></div><div className="flex justify-between gap-3"><dt>Reserve</dt><dd>R {pricing.reserve.toFixed(2)}</dd></div><div className="flex justify-between gap-3"><dt>Commission</dt><dd>R {pricing.commissionAmount.toFixed(2)}</dd></div><div className="flex justify-between gap-3 border-t pt-2"><dt className="font-semibold">Expected contribution</dt><dd className="font-bold">R {pricing.expectedContribution.toFixed(2)}</dd></div></dl></Panel><Panel title="Client total" description="Only approved selling values are included in the client projection."><p className="text-3xl font-bold">R {pricing.grandTotal.toFixed(2)}</p><p className="mt-1 text-sm text-slate-600">Valid until {pricing.validUntil.toLocaleString("en-ZA")}</p><p className="mt-3 text-xs text-slate-600">Issued by Innozanzi on behalf of the partner. Payment and fulfilment are managed by Innozanzi.</p></Panel></div>
    </div>
  </AdminPage>;
}
