import Link from "next/link";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { requirePermission } from "@/domain/auth/session";
import { analyseRfqSource, confirmRfqAnalysis, decideRfqApproval, saveRfqLineItem, submitRfqForApproval } from "@/domain/rfq/actions";
import { AdminPage, Panel, StatusBadge, buttonClass, inputClass, tableClass } from "@/components/admin/admin-ui";
import { RfqSourcePicker } from "@/components/admin/rfq-source-picker";
import { DocumentActions } from "@/components/admin/document-actions";

export default async function RfqDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const context = await requirePermission("rfq.view");
  const { id } = await params;
  const rfq = await prisma.rfqOpportunity.findUnique({ where: { id }, include: { sources: { orderBy: { createdAt: "desc" } }, analyses: { orderBy: { createdAt: "desc" } }, requirements: true, lineItems: true, approvals: { orderBy: { createdAt: "desc" } }, statusHistory: { orderBy: { createdAt: "desc" } } } });
  if (!rfq || (!context.isSuperAdministrator && context.user.companyId && rfq.companyId !== context.user.companyId)) notFound();
  const latestAnalysis = rfq.analyses[0];
  const latestApproval = rfq.approvals[0];
  const nextAction = rfq.status === "DRAFT" ? "Attach and analyse the client source" : rfq.status === "AWAITING_APPROVAL" ? "Review the pricing decision" : rfq.status === "PRICING_IN_PROGRESS" ? "Complete pricing and submit it for approval" : rfq.status === "SUBMITTED" ? "Record the client outcome when received" : "Review the workspace and complete the next valid action";
  return <AdminPage title={rfq.title} description={`${rfq.referenceNumber} · ${rfq.issuingOrganisation}`} actions={<><Link className="text-sm font-semibold text-sky-700 hover:underline" href="/admin/rfqs">Back to RFQs</Link><DocumentActions type="RFQ" id={rfq.id} label={rfq.type}/><StatusBadge value={rfq.status}/></>}>
    <div className="grid gap-3 border border-slate-300 bg-white px-4 py-3 shadow-sm sm:grid-cols-[1fr_auto] sm:items-center"><div><p className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Next action</p><p className="mt-1 text-sm font-semibold text-slate-900">{nextAction}</p></div><span className="text-xs text-slate-600">Closing: {rfq.closingAt?.toLocaleString("en-ZA") ?? "No date set"}</span></div>
    <div className="grid gap-4 xl:grid-cols-[1.15fr_.85fr]">
      <Panel title="Source documents" description="Choose how the client supplied the opportunity. Only one compact intake form opens at a time."><RfqSourcePicker rfqId={rfq.id}/>
        <div className="border-t border-slate-200 pt-4"><p className="text-[11px] font-bold uppercase tracking-[.14em] text-slate-500">Attached sources</p><div className="mt-3 space-y-2">{rfq.sources.map((source) => <div className="flex flex-wrap items-center justify-between gap-3 border border-slate-200 p-3" key={source.id}><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><strong className="text-sm">{source.label}</strong><span className="text-[10px] font-bold uppercase tracking-wider text-slate-500">{source.type}</span></div><p className="mt-1 text-xs text-slate-500">{source.originalFilename ?? source.sourceUrl ?? source.processingStatus}</p>{source.analysisError ? <p className="text-xs text-red-700">{source.analysisError}</p> : null}</div><div className="flex items-center gap-2">{source.documentId ? <Link className="text-xs font-semibold text-sky-700 hover:underline" href={`/api/documents/${source.documentId}`}>Open PDF</Link> : null}<form action={analyseRfqSource}><input type="hidden" name="sourceId" value={source.id}/><button className={buttonClass}>Analyse</button></form></div></div>)}{!rfq.sources.length ? <p className="text-sm text-slate-500">No sources attached yet.</p> : null}</div></div>
      </Panel>
      <Panel><h2 className="mb-4 text-lg font-semibold">Human review</h2>
        {latestAnalysis ? <><p className="text-sm text-slate-600">AI confidence: {Math.round(Number(latestAnalysis.confidence ?? 0) * 100)}% — extraction is never accepted automatically.</p><details className="mt-3 border border-slate-300"><summary className="cursor-pointer px-3 py-2 text-sm font-semibold">Review extracted details</summary><pre className="max-h-72 overflow-auto whitespace-pre-wrap border-t border-slate-300 bg-slate-950 p-3 text-xs text-slate-100">{JSON.stringify(latestAnalysis.rawOutput, null, 2)}</pre></details>{!latestAnalysis.reviewedAt ? <form action={confirmRfqAnalysis} className="mt-3"><input type="hidden" name="analysisId" value={latestAnalysis.id}/><button className={buttonClass}>Confirm extraction</button></form> : <p className="mt-3 text-sm font-semibold text-emerald-700">Confirmed by a reviewer</p>}</> : <p className="text-sm text-slate-500">Add and analyse a source. A person must confirm all extracted data.</p>}
      </Panel>
    </div>
    <Panel><h2 className="mb-4 text-lg font-semibold">Pricing workspace</h2>
      <form action={saveRfqLineItem} className="grid gap-3 md:grid-cols-6"><input type="hidden" name="rfqId" value={rfq.id}/><input className={`${inputClass} md:col-span-2`} name="description" placeholder="Product or service" required/><input className={inputClass} name="quantity" type="number" min="0.01" step="0.01" placeholder="Qty" required/><input className={inputClass} name="unitCost" type="number" min="0" step="0.01" placeholder="Unit cost" required/><select className={inputClass} name="pricingMethod"><option value="MARKUP">Markup</option><option value="MARGIN">Margin</option></select><input className={inputClass} name="pricingPercent" type="number" min="0" max="99.99" step="0.01" placeholder="%" required/><label className="flex items-center gap-2 text-sm"><input name="isService" type="checkbox"/>Service cost</label><button className={buttonClass}>Add pricing line</button></form>
      <div className="mt-5 overflow-x-auto"><table className={tableClass}><thead><tr><th>Description</th><th>Qty</th><th>Cost</th><th>Selling</th><th>Profit</th></tr></thead><tbody>{rfq.lineItems.map((item) => <tr key={item.id}><td>{item.description}</td><td>{Number(item.quantity)}</td><td>R {Number(item.costSubtotal).toFixed(2)}</td><td>R {Number(item.sellingSubtotal).toFixed(2)}</td><td>R {Number(item.profit).toFixed(2)}</td></tr>)}</tbody></table></div>
      <div className="mt-4 grid gap-3 sm:grid-cols-4">{[["Cost",rfq.totalCostBeforeVat],["Selling incl. VAT",rfq.sellingIncludingVat],["Gross profit",rfq.grossProfit],["Expected profit",rfq.expectedProfit]].map(([label,value]) => <div className="border p-3" key={String(label)}><p className="text-xs font-bold uppercase text-slate-500">{String(label)}</p><p className="text-xl font-semibold">R {Number(value).toFixed(2)}</p></div>)}</div>
      {rfq.status === "PRICING_IN_PROGRESS" ? <form action={submitRfqForApproval} className="mt-4"><input type="hidden" name="rfqId" value={rfq.id}/><button className={buttonClass}>Submit pricing for approval</button></form> : null}
      {rfq.status === "AWAITING_APPROVAL" && latestApproval ? <div className="mt-4 grid gap-3 sm:grid-cols-2">{["APPROVED","REJECTED"].map((decision) => <form action={decideRfqApproval} className="border p-3" key={decision}><input type="hidden" name="rfqId" value={rfq.id}/><input type="hidden" name="approvalId" value={latestApproval.id}/><input type="hidden" name="decision" value={decision}/><textarea className={`${inputClass} mb-2`} name="comments" placeholder="Approval comments"/><button className={buttonClass}>{decision === "APPROVED" ? "Approve" : "Reject"}</button></form>)}</div> : null}
    </Panel>
    <Panel><h2 className="mb-4 text-lg font-semibold">Activity timeline</h2><ol className="space-y-3">{rfq.statusHistory.map((event) => <li className="border-l-2 border-sky-600 pl-3 text-sm" key={event.id}><StatusBadge value={event.toStatus}/><span className="ml-2 text-xs text-slate-500">{event.createdAt.toLocaleString("en-ZA")}</span>{event.note ? <p className="mt-1 text-slate-700">{event.note}</p> : null}</li>)}</ol></Panel>
  </AdminPage>;
}
