import { AdminPage, Panel, StatusBadge, tableClass } from "@/components/admin/admin-ui";
import { requirePermission } from "@/domain/auth/session";
import { createInvoiceFromQuotation } from "@/domain/quotations/actions";
import { prisma } from "@/lib/prisma";

export default async function InvoicesPage({searchParams}:{searchParams:Promise<{created?:string}>}) {
  await requirePermission("quotations.manage");const{created}=await searchParams;const [rows,readyQuotes]=await Promise.all([prisma.invoice.findMany({include:{quotation:{select:{quotationNumber:true}}},orderBy:{createdAt:"desc"},take:100}),prisma.quotation.findMany({where:{status:{in:["ACCEPTED","PAYMENT_VERIFIED","CONVERTED"]},invoices:{none:{status:{not:"VOID"}}}},include:{quotationRequest:true},orderBy:{updatedAt:"desc"},take:50})]);const outstanding=rows.filter(i=>!["PAID","VOID"].includes(i.status)).reduce((n,i)=>n+Number(i.grandTotal),0);
  return <AdminPage title="Invoices" description="Numbered customer billing documents generated from accepted or payment-verified quotations.">{created?<div className="border border-emerald-300 bg-emerald-50 p-3 text-sm">Invoice <strong>{created}</strong> created and emailed.</div>:null}<div className="grid gap-3 sm:grid-cols-3"><Summary label="Documents" value={rows.length.toString()}/><Summary label="Outstanding" value={`R ${outstanding.toLocaleString("en-ZA",{minimumFractionDigits:2})}`}/><Summary label="Overdue" value={rows.filter(i=>i.status==="OVERDUE").length.toString()}/></div>{readyQuotes.length?<Panel title="Create an invoice" description="Choose an accepted or payment-verified quotation. Customer and agreed totals are copied into the invoice."><form action={createInvoiceFromQuotation} className="flex flex-col gap-3 sm:flex-row"><select className="min-h-11 flex-1 border border-slate-300 bg-white px-3" name="id" required><option value="">Select quotation</option>{readyQuotes.map(q=><option value={q.id} key={q.id}>{q.quotationNumber} — {q.quotationRequest?.companyName??q.quotationRequest?.contactName??"Customer"} — R {Number(q.grandTotal).toFixed(2)}</option>)}</select><button className="min-h-11 bg-sky-700 px-5 font-bold text-white" type="submit">Generate invoice</button></form></Panel>:null}<Panel><div className="-mx-4 overflow-x-auto"><table className={tableClass}><thead><tr><th>Invoice</th><th>Account</th><th>Source quote</th><th>Due</th><th>Total</th><th>Status</th><th></th></tr></thead><tbody>{rows.map(i=><tr key={i.id}><td><strong>{i.invoiceNumber}</strong></td><td>{i.companyName??i.customerName}<br/><span className="text-xs text-slate-500">{i.customerEmail}</span></td><td>{i.quotation?.quotationNumber??"Manual"}</td><td>{i.dueAt.toLocaleDateString("en-ZA")}</td><td className="font-semibold">R {Number(i.grandTotal).toLocaleString("en-ZA",{minimumFractionDigits:2})}</td><td><StatusBadge value={i.status}/></td><td><a className="font-semibold text-sky-700" href={`/api/invoices/${i.invoiceNumber}/pdf`} target="_blank">Open PDF</a></td></tr>)}{!rows.length?<tr><td colSpan={7} className="py-10 text-center text-slate-500">No invoices yet. Create one after a quotation is accepted.</td></tr>:null}</tbody></table></div></Panel></AdminPage>;
}
function Summary({label,value}:{label:string;value:string}){return <div className="border border-slate-300 bg-white p-4"><p className="text-xs font-bold uppercase text-slate-500">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>}
