export const brand = {
  name: "Innozanzi",
  legalName: "Innozanzi (Pty) Ltd",
  shopName: "Innozanzi Shop",
  siteUrl: process.env.NEXT_PUBLIC_SITE_URL ?? "https://shop.innozanzi.co.za",
  tagline: "Technology, made easier.",
  promise: "We help you make the right technology decision, communicate honestly and stay involved until your order reaches you.",
  description: "A South African technology company combining specialist products, intelligent software and hands-on service to make technology easier to choose, buy and receive.",
  positioning: "We understand technology, build technology and sell technology—using that combination to create a clearer, more helpful purchasing experience.",
  founder: { name: "Simukelo Ntshaba", title: "Founder, CEO and Director" },
  contact: { email: "support@innozanzi.co.za", phone: "+27 71 238 4185" },
  experiences: { gaming: "Innozanzi Gaming", pcBuilder: "Innozanzi PC Workshop" },
  assets: { headerLogo: "/brand/innozanzi-shop-logo-header-v2.png", lightLogo: "/brand/innozanzi-shop-logo-white.png", schemaLogo: "/brand/innozanzi-shop-logo.png", socialImage: "/social/innozanzi-share.png" },
} as const;

export const companyIdentity = {
  purpose: "Make technology easier to understand, easier to choose and easier to access.",
  mission: "Help people and businesses choose and obtain the right technology through intelligent software, practical guidance, dependable products and service built around what they actually need.",
  vision: "Build one of South Africa’s most trusted and intelligent technology purchasing experiences, then take that standard beyond our borders.",
  customerPromise: "We will help you make the right technology decision, communicate honestly, treat your order as important and stay involved until the technology reaches you.",
  values: [
    { name: "Every Order Matters", summary: "Every order represents someone trusting us with their money.", detail: "Whether a customer spends R300 or R300,000, we pay attention, communicate and follow through until they receive what was promised." },
    { name: "Solve Before You Sell", summary: "Understand the outcome before recommending the product.", detail: "Good advice may mean recommending a simpler or less expensive option. Long-term trust matters more than maximising one transaction." },
    { name: "Build What Should Exist", summary: "Use software to remove avoidable difficulty.", detail: "When an industry process is confusing or repetitive, we ask whether a clearer tool or better workflow can be built." },
    { name: "Own the Outcome", summary: "A customer should never need to navigate our internal structure.", detail: "We find the right person, escalate when necessary, follow up and make sure the issue keeps moving toward resolution." },
    { name: "Be Clear and Honest", summary: "Trust grows through accurate, timely communication.", detail: "We communicate delays, uncertainty and problems early. We never make promises merely because they sound reassuring." },
    { name: "Never Stop Improving", summary: "The platform and the business are never finished.", detail: "Every question, complaint, failed process and abandoned journey is evidence we can use to make the next experience better." },
  ],
  beliefs: [
    "Buying technology should not require you to be a technology expert.",
    "Software can make purchasing technology smarter and clearer.",
    "Good advice creates stronger relationships than aggressive selling.",
    "An order is complete when the customer receives what was promised—not when payment clears.",
    "Technology should solve problems rather than create new ones.",
    "Trust is earned one interaction and one order at a time.",
    "The strongest technology businesses combine good products, intelligent software and exceptional human service.",
  ],
  workingPrinciples: [
    "Take ownership and never walk past a customer problem.",
    "Think from the customer’s side, not only from the internal process.",
    "Communicate early, especially when the news is difficult.",
    "Understand the real problem before acting.",
    "Automate repetitive work without automating away genuine human help.",
    "Protect long-term trust ahead of a short-term sale.",
    "Question unnecessary complexity and finish what we start.",
  ],
} as const;
