import { notFound } from "next/navigation";
import { requireClientPortal } from "@/domain/client-portal/session";
import { prisma } from "@/lib/prisma";

export default async function PortalOrderDetail({params}:{params:Promise<{orderNumber:string}>}){
  const{context}=await requireClientPortal();const{orderNumber}=await params;
  const order=await prisma.order.findFirst({where:{orderNumber,userId:context.user.id},include:{items:true,statusHistory:{orderBy:{createdAt:"desc"}},shipments:true,addresses:true}});if(!order)notFound();
  return <div className="mx-auto max-w-5xl"><p className="text-xs font-bold uppercase tracking-widest text-sky-700">Order detail</p><h1 className="mt-1 text-3xl font-semibold">{order.orderNumber}</h1><p className="mt-2 text-sm text-slate-600">Placed {order.createdAt.toLocaleDateString("en-ZA")} · {order.status.replaceAll("_"," ")}</p><div className="mt-6 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><section className="rounded-xl border border-slate-200 bg-white shadow-sm"><h2 className="border-b p-5 text-lg font-semibold">Items</h2><div className="divide-y">{order.items.map(item=><div className="flex justify-between gap-4 p-5" key={item.id}><div><p className="font-semibold">{item.productName}</p><p className="text-sm text-slate-500">{item.sku} · Qty {item.quantity}</p></div><strong>R {Number(item.lineTotal).toLocaleString("en-ZA",{minimumFractionDigits:2})}</strong></div>)}</div><div className="flex justify-between border-t p-5 text-lg"><span>Total</span><strong>R {Number(order.grandTotal).toLocaleString("en-ZA",{minimumFractionDigits:2})}</strong></div></section><section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-semibold">Progress</h2><div className="mt-4 space-y-4">{order.statusHistory.map(event=><div className="border-l-2 border-sky-300 pl-4" key={event.id}><p className="text-sm font-semibold">{event.toStatus.replaceAll("_"," ")}</p><p className="text-xs text-slate-500">{event.createdAt.toLocaleString("en-ZA")}</p>{event.note?<p className="mt-1 text-sm text-slate-600">{event.note}</p>:null}</div>)}{!order.statusHistory.length?<p className="text-sm text-slate-500">Current status: {order.status.replaceAll("_"," ")}</p>:null}</div></section></div></div>;
}
