import { NextResponse } from "next/server";
import { z } from "zod";
import { AI_ORIGIN, aiIdentity } from "@/domain/ai-shopping/service";
import { getOrCreateCart } from "@/domain/cart/service";
import { isDailySpecial, supplierRetailPrice } from "@/domain/catalogue/retail-pricing";
import { pcPartCompatibility } from "@/domain/pc-projects/compatibility";
import { prisma } from "@/lib/prisma";

const schema=z.object({recommendationId:z.string().length(32),productIds:z.array(z.string().uuid()).min(1).max(15),kind:z.enum(["PRODUCT","PC_BUILD"])});
export async function POST(request:Request){
  const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"Invalid recommendation selection."},{status:400});const identity=await aiIdentity();
  const usage=await prisma.aIUsage.findFirst({where:{recommendationId:parsed.data.recommendationId,...(identity.userId?{userId:identity.userId}:{anonymousSessionId:identity.anonymousSessionId}),requestStatus:"SUCCESS"}});if(!usage)return NextResponse.json({error:"This recommendation is no longer available."},{status:404});
  const metadata=usage.metadata&&typeof usage.metadata==="object"&&!Array.isArray(usage.metadata)?usage.metadata as Record<string,unknown>:{},allowed=Array.isArray(metadata.recommendedProductIds)?metadata.recommendedProductIds.filter((id):id is string=>typeof id==="string"):[];if(!parsed.data.productIds.every(id=>allowed.includes(id))||parsed.data.kind!==usage.intentType)return NextResponse.json({error:"This selection does not belong to the verified recommendation."},{status:400});
  const ids=[...new Set(parsed.data.productIds)],products=await prisma.supplierCatalogueProduct.findMany({where:{id:{in:ids},active:true,availability:"IN_STOCK",stock:{gt:0},costPrice:{gt:0}}});if(products.length!==ids.length)return NextResponse.json({error:"Price or stock changed. Please request a fresh recommendation."},{status:409});
  if(parsed.data.kind==="PC_BUILD"){const selected:Record<string,(typeof products)[number]>={};for(const product of products){const text=`${product.categoryPath??""} ${product.name}`.toLowerCase(),key=text.includes("motherboard")?"motherboard":text.includes("cpu/")||text.includes("processor")?"cpu":text.includes("memory")?"memory":text.includes("solid state")||text.includes("hard disk")||text.includes("storage")?"storage":text.includes("graphics")?"graphics":text.includes("power suppl")?"power":text.includes("chassis")||text.includes("case")?"case":undefined;if(key)selected[key]=product}for(const[key,product]of Object.entries(selected)){if(pcPartCompatibility(key,product,selected).kind==="bad")return NextResponse.json({error:"A component compatibility check changed. Please request a fresh build."},{status:409})}}
  const summary=products.map(product=>{const price=supplierRetailPrice({costPrice:product.costPrice!,recommendedRetail:product.recommendedRetail,promotionalPrice:product.promotionalPrice,promotionStartsAt:product.promotionStartsAt,promotionEndsAt:product.promotionEndsAt,special:isDailySpecial(product.id)});return{id:product.id,name:product.name,price:Number(price.salePrice??price.regularPrice)}}),cart=await getOrCreateCart();
  await prisma.$transaction(async tx=>{await tx.cart.update({where:{id:cart.id},data:{origin:AI_ORIGIN,aiRecommendationId:parsed.data.recommendationId,aiSummary:{kind:parsed.data.kind,products:summary}}});for(const product of products)await tx.supplierCartItem.upsert({where:{cartId_supplierId_supplierProductId:{cartId:cart.id,supplierId:product.supplierId,supplierProductId:product.supplierProductId}},create:{cartId:cart.id,supplierId:product.supplierId,supplierProductId:product.supplierProductId,supplierSku:product.supplierSku,quantity:1},update:{quantity:1}});await tx.aIUsage.update({where:{id:usage.id},data:{cartCreated:true}});await tx.recommendationEvent.createMany({data:products.map(product=>({userId:identity.userId,sessionId:identity.userId?`user:${identity.userId}`:identity.anonymousSessionId!,eventType:"AI_ADD_TO_CART",entityType:"SUPPLIER_PRODUCT",entityId:product.id,category:product.category,brand:product.brand,recommendationId:parsed.data.recommendationId,context:"ai-shopping"}))})});
  return NextResponse.json({ok:true,redirect:"/cart?status=ai-added"});
}
