import type { EmailMessage } from "./provider";

const siteUrl = () => (process.env.NEXT_PUBLIC_SITE_URL ?? "https://shop.innozanzi.co.za").replace(/\/$/, "");
const escape = (value: string) => value.replace(/[&<>'"]/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[char]!);

function template(title: string, preview: string, content: string) {
  return `<!doctype html><html><body style="margin:0;background:#eef1f4;font-family:Arial,sans-serif;color:#172b3a"><div style="display:none;max-height:0;overflow:hidden">${escape(preview)}</div><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding:32px 16px"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:620px;background:#fff;border:1px solid #d5dadd"><tr><td style="padding:22px 28px;background:#071b33;color:#fff"><div style="font-size:20px;font-weight:700">INNOZANZI</div><div style="margin-top:4px;font-size:12px;color:#b8d8f2">ICT procurement & technology solutions</div></td></tr><tr><td style="padding:30px 28px"><h1 style="margin:0 0 16px;font-size:24px;color:#172b3a">${escape(title)}</h1>${content}</td></tr><tr><td style="padding:18px 28px;background:#f5f7f8;font-size:12px;color:#667085">Innozanzi Shop · South Africa<br>This is an automated transactional message.</td></tr></table></td></tr></table></body></html>`;
}
const button = (label: string, href: string) => `<p style="margin:24px 0"><a href="${escape(href)}" style="display:inline-block;background:#0a6ed1;color:#fff;text-decoration:none;padding:12px 20px;font-weight:700">${escape(label)}</a></p>`;
const money = (value: string | number) => `R ${Number(value).toLocaleString("en-ZA", { minimumFractionDigits: 2 })}`;

export const emailTemplates = {
  verifyEmail: (to:string, name:string, token:string):EmailMessage => { const url=`${siteUrl()}/verify-email?email=${encodeURIComponent(to)}&token=${encodeURIComponent(token)}`;return{to,subject:"Verify your Innozanzi account",text:`Hello ${name}, verify your account: ${url}`,html:template("Verify your email","Complete your Innozanzi registration",`<p>Hello ${escape(name)},</p><p>Confirm your email address to activate your account.</p>${button("Verify email",url)}<p style="font-size:13px;color:#667085">This link expires in 24 hours.</p>`),idempotencyKey:`verify:${to}:${token.slice(-12)}`}},
  passwordReset: (to:string, token:string):EmailMessage => {const url=`${siteUrl()}/reset-password?email=${encodeURIComponent(to)}&token=${encodeURIComponent(token)}`;return{to,subject:"Reset your Innozanzi password",text:`Reset your password: ${url}`,html:template("Reset your password","Your secure password-reset link",`<p>We received a password reset request for your account.</p>${button("Choose a new password",url)}<p style="font-size:13px;color:#667085">This link expires in one hour. Ignore this message if you did not request it.</p>`),idempotencyKey:`password-reset:${to}:${token.slice(-12)}`}},
  quotationRequest: (to:string,name:string,reference:string):EmailMessage => ({to,subject:`Quotation request ${reference} received`,text:`Hello ${name}, we received quotation request ${reference}.`,html:template("Quotation request received",`We are reviewing request ${reference}`,`<p>Hello ${escape(name)},</p><p>Our sales team has received your requirements and will prepare a quotation.</p><p><strong>Reference:</strong> ${escape(reference)}</p>`),idempotencyKey:`quotation-request:${reference}`}),
  quotationIssued: (to:string,name:string,number:string,total:string):EmailMessage => ({to,subject:`Your final quotation ${number}`,text:`Hello ${name}, quotation ${number} for ${money(total)} has been approved and is ready.`,html:template("Your quotation is ready",`Final quotation ${number}`,`<p>Hello ${escape(name)},</p><p>Your quotation has completed internal review and is now final.</p><p><strong>Quotation:</strong> ${escape(number)}<br><strong>Total:</strong> ${money(total)}</p>${button("Sign in to your account",`${siteUrl()}/account`)}`),idempotencyKey:`quotation-issued:${number}`}),
  invoiceCreated: (to:string,name:string,number:string,total:string,due:Date):EmailMessage => ({to,subject:`Invoice ${number} created`,text:`Hello ${name}, invoice ${number} for ${money(total)} is due ${due.toLocaleDateString("en-ZA")}.`,html:template("Invoice created",`Invoice ${number}`,`<p>Hello ${escape(name)},</p><p>Your invoice has been created from the accepted quotation.</p><p><strong>Invoice:</strong> ${escape(number)}<br><strong>Total:</strong> ${money(total)}<br><strong>Due:</strong> ${due.toLocaleDateString("en-ZA")}</p>`),idempotencyKey:`invoice-created:${number}`}),
  orderCreated: (to:string,number:string,total:string):EmailMessage => ({to,subject:`Sales order ${number} created`,text:`Your sales order ${number} for ${money(total)} has been created.`,html:template("Sales order created",`Order ${number}`,`<p>Your accepted quotation has been converted into sales order <strong>${escape(number)}</strong>.</p><p><strong>Total:</strong> ${money(total)}</p>${button("View your account",`${siteUrl()}/account`)}`),idempotencyKey:`order-created:${number}`}),
  orderStatus: (to:string,number:string,status:string):EmailMessage => ({to,subject:`Order ${number}: ${status.replaceAll("_"," ")}`,text:`Your order ${number} is now ${status.replaceAll("_"," ").toLowerCase()}.`,html:template("Order status updated",`Order ${number}`,`<p>Your order <strong>${escape(number)}</strong> is now:</p><p style="font-size:18px;font-weight:700;color:#0a6ed1">${escape(status.replaceAll("_"," "))}</p>${button("View your account",`${siteUrl()}/account`)}`),idempotencyKey:`order-status:${number}:${status}`}),
  paymentReceived: (to:string,order:string,total:string):EmailMessage => ({to,subject:`Payment received for ${order}`,text:`Payment of ${money(total)} was received for order ${order}.`,html:template("Payment received",`Payment confirmed for ${order}`,`<p>We received your payment for order <strong>${escape(order)}</strong>.</p><p><strong>Amount:</strong> ${money(total)}</p><p>Our team will continue processing your order.</p>`),idempotencyKey:`payment-received:${order}`}),
  paymentReview: (to:string,order:string,status:string):EmailMessage => ({to,subject:`Payment proof ${status.toLowerCase()} for ${order}`,text:`Your payment proof for ${order} was ${status.toLowerCase()}.`,html:template("Payment proof reviewed",`Payment update for ${order}`,`<p>Your payment proof for order <strong>${escape(order)}</strong> was <strong>${escape(status.toLowerCase())}</strong>.</p>`),idempotencyKey:`payment-proof:${order}:${status}`}),
};
