import type { EmailMessage } from "./provider";
import { createHmac } from "node:crypto";

const siteUrl = () => (process.env.NEXT_PUBLIC_SITE_URL ?? "https://shop.innozanzi.co.za").replace(/\/$/, "");
const escape = (value: string) => value.replace(/[&<>'"]/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[char]!);

function template(title: string, preview: string, content: string) {
  const logo=process.env.EMAIL_DARK_HEADER_LOGO_URL??"https://jhfbsdlpkxppujpvbpxf.supabase.co/storage/v1/object/public/uploads/brand/email-logo-white.png";
  return `<!doctype html><html><body style="margin:0;background:#eef1f4;font-family:Arial,sans-serif;color:#172b3a"><div style="display:none;max-height:0;overflow:hidden">${escape(preview)}</div><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding:32px 16px"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:620px;background:#fff;border:1px solid #d5dadd"><tr><td style="padding:20px 28px;background:#071b33"><img src="${escape(logo)}" width="190" alt="Innozanzi Shop" style="display:block;max-width:190px;height:auto"><div style="margin-top:8px;font-size:12px;color:#b8d8f2">ICT procurement & technology solutions</div></td></tr><tr><td style="padding:30px 28px"><h1 style="margin:0 0 16px;font-size:24px;color:#172b3a">${escape(title)}</h1>${content}</td></tr><tr><td style="padding:18px 28px;background:#f5f7f8;font-size:12px;color:#667085">Innozanzi Shop · South Africa · support@innozanzi.co.za<br>This is an automated message from our support team.</td></tr></table></td></tr></table></body></html>`;
}
const button = (label: string, href: string) => `<p style="margin:24px 0"><a href="${escape(href)}" style="display:inline-block;background:#0a6ed1;color:#fff;text-decoration:none;padding:12px 20px;font-weight:700">${escape(label)}</a></p>`;
const money = (value: string | number) => `R ${Number(value).toLocaleString("en-ZA", { minimumFractionDigits: 2 })}`;
export const newsletterToken=(email:string)=>createHmac("sha256",process.env.EMAIL_UNSUBSCRIBE_SECRET??process.env.OPENAI_ROUTE_SECRET??"local-development-only").update(email.toLowerCase()).digest("hex");

export const emailTemplates = {
  userInvitation: (to:string,name:string,tempPassword:string,role:string,accountType:string,company:string,token:string,expires:Date):EmailMessage => {const url=`${siteUrl()}/activate-account?token=${encodeURIComponent(token)}&email=${encodeURIComponent(to)}`;return{to,subject:"Your Innozanzi account invitation",text:`Hello ${name}, you were invited as ${role} (${accountType}) for ${company}. Sign in with ${to} and temporary password ${tempPassword}, then change it before ${expires.toLocaleString("en-ZA")}. Activation: ${url}`,html:template("Youâ€™re invited","Activate your Innozanzi account",`<p>Hello ${escape(name)},</p><p>An authorised user created an Innozanzi account for you.</p><p><strong>Email:</strong> ${escape(to)}<br><strong>Temporary password:</strong> <code>${escape(tempPassword)}</code><br><strong>Role:</strong> ${escape(role)}<br><strong>Account type:</strong> ${escape(accountType.replaceAll("_"," "))}<br><strong>Company:</strong> ${escape(company)}</p><p>You must change this temporary password before you can access any protected area. It expires ${expires.toLocaleString("en-ZA")}.</p>${button("Activate account",url)}`),idempotencyKey:`user-invitation:${to}:${token.slice(-12)}`}},
  userActivated: (name:string,email:string,accountType:string,role:string,company:string,department:string,inviter:string,invitedAt:Date,activatedAt:Date,userId:string):EmailMessage => ({to:process.env.USER_ACTIVATION_NOTIFICATION_EMAIL??"support@emails.co.za",subject:`New ${role} account activated`,text:`${name} (${email}) activated a ${accountType} account. Role: ${role}. Company: ${company}. Department: ${department}. Invited by ${inviter} on ${invitedAt.toISOString()}; activated ${activatedAt.toISOString()}.`,html:template("User account activated",`A new ${role} account is active`,`<p><strong>Name:</strong> ${escape(name)}<br><strong>Email:</strong> ${escape(email)}<br><strong>Account type:</strong> ${escape(accountType.replaceAll("_"," "))}<br><strong>Role:</strong> ${escape(role)}<br><strong>Company:</strong> ${escape(company)}<br><strong>Department:</strong> ${escape(department)}<br><strong>Invited by:</strong> ${escape(inviter)}<br><strong>Invitation date:</strong> ${invitedAt.toLocaleString("en-ZA")}<br><strong>Activation date:</strong> ${activatedAt.toLocaleString("en-ZA")}</p>${button("View user",`${siteUrl()}/admin/access-control?user=${encodeURIComponent(userId)}`)}`),idempotencyKey:`user-activated:${userId}`}),
  verifyEmail: (to:string, name:string, token:string):EmailMessage => { const url=`${siteUrl()}/verify-email?email=${encodeURIComponent(to)}&token=${encodeURIComponent(token)}`;return{to,subject:"Verify your Innozanzi account",text:`Hello ${name}, verify your account: ${url}`,html:template("Verify your email","Complete your Innozanzi registration",`<p>Hello ${escape(name)},</p><p>Confirm your email address to activate your account.</p>${button("Verify email",url)}<p style="font-size:13px;color:#667085">This link expires in 24 hours.</p>`),idempotencyKey:`verify:${to}:${token.slice(-12)}`}},
  welcome: (to:string,name:string):EmailMessage => ({to,subject:"Welcome to Innozanzi",text:`Welcome ${name}. Your Innozanzi customer account is ready.`,html:template("Welcome to Innozanzi","Your customer account is ready",`<p>Hello ${escape(name)},</p><p>Your customer account is active. You can now manage quote requests, documents and orders.</p>${button("Open your account",`${siteUrl()}/account`)}`),idempotencyKey:`welcome:${to}`}),
  passwordReset: (to:string, token:string):EmailMessage => {const url=`${siteUrl()}/reset-password?email=${encodeURIComponent(to)}&token=${encodeURIComponent(token)}`;return{to,subject:"Reset your Innozanzi password",text:`Reset your password: ${url}`,html:template("Reset your password","Your secure password-reset link",`<p>We received a password reset request for your account.</p>${button("Choose a new password",url)}<p style="font-size:13px;color:#667085">This link expires in one hour. Ignore this message if you did not request it.</p>`),idempotencyKey:`password-reset:${to}:${token.slice(-12)}`}},
  passwordChanged: (to:string):EmailMessage => ({to,subject:"Your Innozanzi password was changed",text:"Your customer account password was changed. Contact support immediately if this was not you.",html:template("Password changed","Your account password was updated",`<p>Your customer account password was changed.</p><p>If this was not you, contact <a href="mailto:support@innozanzi.co.za">support@innozanzi.co.za</a> immediately.</p>`),idempotencyKey:`password-changed:${to}:${Date.now()}`}),
  quotationRequest: (to:string,name:string,reference:string):EmailMessage => ({to,subject:`Quotation request ${reference} received`,text:`Hello ${name}, we received quotation request ${reference}.`,html:template("Quotation request received",`We are reviewing request ${reference}`,`<p>Hello ${escape(name)},</p><p>Our sales team has received your requirements and will prepare a quotation.</p><p><strong>Reference:</strong> ${escape(reference)}</p>`),idempotencyKey:`quotation-request:${reference}`}),
  quotationSupportAlert: (reference:string,name:string,email:string,requirements:string):EmailMessage => ({to:process.env.SUPPORT_EMAIL??"support@innozanzi.co.za",subject:`New quotation request ${reference}`,text:`New request ${reference} from ${name} (${email}). ${requirements}`,html:template("New quotation request",`${reference} requires sales review`,`<p><strong>Reference:</strong> ${escape(reference)}<br><strong>Customer:</strong> ${escape(name)}<br><strong>Email:</strong> ${escape(email)}</p><p>${escape(requirements)}</p>${button("Open quote pipeline",`${siteUrl()}/admin/quotations`)}`),idempotencyKey:`quotation-support:${reference}`}),
  quotationIssued: (to:string,name:string,number:string,total:string):EmailMessage => ({to,subject:`Your final quotation ${number}`,text:`Hello ${name}, quotation ${number} for ${money(total)} has been approved and is ready.`,html:template("Your quotation is ready",`Final quotation ${number}`,`<p>Hello ${escape(name)},</p><p>Your quotation has completed internal review and is now final.</p><p><strong>Quotation:</strong> ${escape(number)}<br><strong>Total:</strong> ${money(total)}</p>${button("Sign in to your account",`${siteUrl()}/account`)}`),idempotencyKey:`quotation-issued:${number}`}),
  provisionalQuotation: (to:string,name:string,number:string,total:string,expires:Date,pdf:Buffer):EmailMessage => ({to,subject:`Provisional quotation ${number}`,text:`Hello ${name}, your provisional quotation ${number} totals ${money(total)} and expires ${expires.toLocaleDateString("en-ZA")}. It remains subject to business review and is not a request for payment.`,html:template("Provisional quotation prepared",`${number} is awaiting business review`,`<p>Hello ${escape(name)},</p><p>We prepared the attached provisional quotation from your requested products and quantities.</p><p><strong>Quotation:</strong> ${escape(number)}<br><strong>Provisional total:</strong> ${money(total)}<br><strong>Expires:</strong> ${expires.toLocaleDateString("en-ZA")}</p><p><strong>Do not make payment yet.</strong> This document is subject to business review. We will send a final quotation if approved.</p>${button("View quotation progress",`${siteUrl()}/account/quotations`)}`),idempotencyKey:`quotation-provisional:${number}`,attachments:[{filename:`${number}-provisional.pdf`,content:pdf,contentType:"application/pdf"}]}),
  finalQuotation: (to:string,name:string,number:string,total:string,expires:Date,reference:string,pdf:Buffer):EmailMessage => ({to,subject:`Final quotation ${number}`,text:`Hello ${name}, final quotation ${number} for ${money(total)} expires ${expires.toLocaleDateString("en-ZA")}. Use payment reference ${reference}, then upload proof of payment in your account. Processing starts only after verification.`,html:template("Final quotation approved",`${number} is ready for payment`,`<p>Hello ${escape(name)},</p><p>Your final quotation is attached.</p><p><strong>Amount payable:</strong> ${money(total)}<br><strong>Expiry date:</strong> ${expires.toLocaleDateString("en-ZA")}<br><strong>Payment reference:</strong> ${escape(reference)}</p><p>Use the banking instructions in the PDF. Your order will only be created and processed after our team verifies your proof of payment.</p>${button("Upload proof of payment",`${siteUrl()}/account/quotations`)}`),idempotencyKey:`quotation-final:${number}:${expires.toISOString()}`,attachments:[{filename:`${number}-final.pdf`,content:pdf,contentType:"application/pdf"}]}),
  paymentSubmitted: (to:string,number:string):EmailMessage => ({to,subject:`Payment proof received for ${number}`,text:`We received your proof of payment for quotation ${number}. Verification is pending and no order has been activated yet.`,html:template("Proof of payment received",`Verification pending for ${number}`,`<p>We received your proof of payment for quotation <strong>${escape(number)}</strong>.</p><p>Our finance team must verify it before an order is created or fulfilment begins.</p>${button("View quotation progress",`${siteUrl()}/account/quotations`)}`),idempotencyKey:`payment-submitted:${number}:${Date.now()}`}),
  paymentDecision: (to:string,number:string,status:string,reason:string|undefined,orderNumber?:string):EmailMessage => ({to,subject:`Payment ${status.toLowerCase()} for ${number}`,text:`Your payment for ${number} was ${status.toLowerCase()}.${reason?` ${reason}`:""}${orderNumber?` Order ${orderNumber} is now active.`:""}`,html:template("Payment verification update",`${number}: ${status.replaceAll("_"," ")}`,`<p>Your payment for quotation <strong>${escape(number)}</strong> is <strong>${escape(status.replaceAll("_"," ").toLowerCase())}</strong>.</p>${reason?`<p><strong>Next step:</strong> ${escape(reason)}</p>`:""}${orderNumber?`<p>Your order <strong>${escape(orderNumber)}</strong> is now active.</p>${button("Track your order",`${siteUrl()}/account/orders/${encodeURIComponent(orderNumber)}`)}`:""}`),idempotencyKey:`payment-decision:${number}:${status}:${Date.now()}`}),
  invoiceCreated: (to:string,name:string,number:string,total:string,due:Date):EmailMessage => ({to,subject:`Invoice ${number} created`,text:`Hello ${name}, invoice ${number} for ${money(total)} is due ${due.toLocaleDateString("en-ZA")}.`,html:template("Invoice created",`Invoice ${number}`,`<p>Hello ${escape(name)},</p><p>Your invoice has been created from the accepted quotation.</p><p><strong>Invoice:</strong> ${escape(number)}<br><strong>Total:</strong> ${money(total)}<br><strong>Due:</strong> ${due.toLocaleDateString("en-ZA")}</p>`),idempotencyKey:`invoice-created:${number}`}),
  orderCreated: (to:string,number:string,total:string):EmailMessage => ({to,subject:`Sales order ${number} created`,text:`Your sales order ${number} for ${money(total)} has been created.`,html:template("Sales order created",`Order ${number}`,`<p>Your accepted quotation has been converted into sales order <strong>${escape(number)}</strong>.</p><p><strong>Total:</strong> ${money(total)}</p>${button("View your account",`${siteUrl()}/account`)}`),idempotencyKey:`order-created:${number}`}),
  orderStatus: (to:string,number:string,status:string):EmailMessage => ({to,subject:`Order ${number}: ${status.replaceAll("_"," ")}`,text:`Your order ${number} is now ${status.replaceAll("_"," ").toLowerCase()}.`,html:template("Order status updated",`Order ${number}`,`<p>Your order <strong>${escape(number)}</strong> is now:</p><p style="font-size:18px;font-weight:700;color:#0a6ed1">${escape(status.replaceAll("_"," "))}</p>${button("View your account",`${siteUrl()}/account`)}`),idempotencyKey:`order-status:${number}:${status}`}),
  paymentReceived: (to:string,order:string,total:string):EmailMessage => ({to,subject:`Payment received for ${order}`,text:`Payment of ${money(total)} was received for order ${order}.`,html:template("Payment received",`Payment confirmed for ${order}`,`<p>We received your payment for order <strong>${escape(order)}</strong>.</p><p><strong>Amount:</strong> ${money(total)}</p><p>Our team will continue processing your order.</p>`),idempotencyKey:`payment-received:${order}`}),
  paymentReview: (to:string,order:string,status:string):EmailMessage => ({to,subject:`Payment proof ${status.toLowerCase()} for ${order}`,text:`Your payment proof for ${order} was ${status.toLowerCase()}.`,html:template("Payment proof reviewed",`Payment update for ${order}`,`<p>Your payment proof for order <strong>${escape(order)}</strong> was <strong>${escape(status.toLowerCase())}</strong>.</p>`),idempotencyKey:`payment-proof:${order}:${status}`}),
  newsletterWelcome: (to:string,name:string,subscriptionAttempt="initial"):EmailMessage => {const unsubscribe=`${siteUrl()}/unsubscribe?email=${encodeURIComponent(to)}&token=${newsletterToken(to)}`;return{to,subject:"Welcome to Innozanzi updates",text:`Hello ${name}, you are subscribed to Innozanzi updates.\n\nUnsubscribe: ${unsubscribe}`,html:template("You’re subscribed","Useful ICT offers and advice",`<p>Hello ${escape(name)},</p><p>You’ll receive selected ICT offers, new arrivals and practical technology guidance—without the noise.</p>${button("Explore the shop",`${siteUrl()}/shop`)}<hr style="margin:28px 0;border:0;border-top:1px solid #e5e7eb"><p style="font-size:12px;color:#667085">Changed your mind? <a href="${escape(unsubscribe)}">Unsubscribe and remove your email</a>.</p>`),idempotencyKey:`newsletter-welcome:${to}:${subscriptionAttempt}`}},
  helpDeskReceived: (to:string,name:string,ticket:string):EmailMessage => ({to,subject:`Support request ${ticket} received`,text:`Hello ${name}, we received your support request ${ticket}.`,html:template("We’re on it",`Support ticket ${ticket}`,`<p>Hello ${escape(name)},</p><p>Our support team received your request.</p><p><strong>Ticket:</strong> ${escape(ticket)}</p>`),idempotencyKey:`helpdesk-received:${ticket}`}),
  helpDeskSupportAlert: (ticket:string,name:string,email:string,subject:string,message:string):EmailMessage => ({to:process.env.SUPPORT_EMAIL??"support@innozanzi.co.za",subject:`Help desk ${ticket}: ${subject}`,text:`${ticket} from ${name} (${email}): ${message}`,html:template("New help-desk ticket",`${ticket}: ${subject}`,`<p><strong>Customer:</strong> ${escape(name)}<br><strong>Email:</strong> ${escape(email)}<br><strong>Subject:</strong> ${escape(subject)}</p><p>${escape(message)}</p>${button("Open help desk",`${siteUrl()}/admin/help-desk`)}`),idempotencyKey:`helpdesk-support:${ticket}`}),
  helpDeskUpdated: (to:string,ticket:string,status:string,message:string):EmailMessage => ({to,subject:`Support ticket ${ticket}: ${status.replaceAll("_"," ")}`,text:`Your support ticket ${ticket} is ${status.replaceAll("_"," ").toLowerCase()}. ${message}`,html:template("Support ticket updated",`${ticket}: ${status.replaceAll("_"," ")}`,`<p>Your support ticket <strong>${escape(ticket)}</strong> is now <strong>${escape(status.replaceAll("_"," ").toLowerCase())}</strong>.</p><p>${escape(message)}</p>${button("View support tickets",`${siteUrl()}/account/support`)}`),idempotencyKey:`helpdesk-update:${ticket}:${status}:${Date.now()}`}),
  serviceTaskAssigned: (to:string,title:string,ticket:string|undefined,dueAt:Date|undefined):EmailMessage => ({to,subject:`Task assigned: ${title}`,text:`You were assigned: ${title}.${ticket?` Ticket ${ticket}.`:""}${dueAt?` Due ${dueAt.toLocaleString("en-ZA")}.`:""}`,html:template("Service task assigned",title,`<p><strong>Task:</strong> ${escape(title)}${ticket?`<br><strong>Ticket:</strong> ${escape(ticket)}`:""}${dueAt?`<br><strong>Due:</strong> ${dueAt.toLocaleString("en-ZA")}`:""}</p>${button("Open service workspace",`${siteUrl()}/admin/help-desk`)}`),idempotencyKey:`service-task:${to}:${title}:${dueAt?.toISOString()??"none"}`}),
  partnershipApplication: (to:string,name:string,reference:string,status:string,note?:string):EmailMessage => ({to,subject:`Partnership application ${reference}: ${status.replaceAll("_"," ")}`,text:`Hello ${name}, your partnership application ${reference} is ${status.replaceAll("_"," ").toLowerCase()}.${note?` ${note}`:""}`,html:template("Partnership application update",`${reference}: ${status.replaceAll("_"," ")}`,`<p>Hello ${escape(name)},</p><p>Your partnership application <strong>${escape(reference)}</strong> is now <strong>${escape(status.replaceAll("_"," ").toLowerCase())}</strong>.</p>${note?`<p>${escape(note)}</p>`:""}${button("View application",`${siteUrl()}/account/partnership`)}`),idempotencyKey:`partnership-application:${reference}:${status}:${Date.now()}`}),
  partnershipAdminAlert: (reference:string,name:string,track:string):EmailMessage => ({to:process.env.SUPPORT_EMAIL??"support@innozanzi.co.za",subject:`Partnership application ${reference} submitted`,text:`${reference} from ${name} for ${track} requires review.`,html:template("Partnership application submitted",`${reference} requires review`,`<p><strong>Applicant:</strong> ${escape(name)}<br><strong>Track:</strong> ${escape(track)}<br><strong>Reference:</strong> ${escape(reference)}</p>${button("Review application",`${siteUrl()}/admin/partnerships/applications`)}`),idempotencyKey:`partnership-admin:${reference}`}),
  partnerRequestUpdate: (to:string,reference:string,status:string,note?:string):EmailMessage => ({to,subject:`Partner request ${reference}: ${status.replaceAll("_"," ")}`,text:`Partner request ${reference} is ${status.replaceAll("_"," ").toLowerCase()}.${note?` ${note}`:""}`,html:template("Partner request update",`${reference}: ${status.replaceAll("_"," ")}`,`<p>Your partner request <strong>${escape(reference)}</strong> is now <strong>${escape(status.replaceAll("_"," ").toLowerCase())}</strong>.</p>${note?`<p>${escape(note)}</p>`:""}${button("Open Partner Workspace",`${siteUrl()}/account/partner`)}`),idempotencyKey:`partner-request:${reference}:${status}:${Date.now()}`}),
  campaign: (to:string,subject:string,preview:string,content:string,campaignId:string):EmailMessage => {const unsubscribe=`${siteUrl()}/unsubscribe?email=${encodeURIComponent(to)}&token=${newsletterToken(to)}`;return{to,subject,text:`${preview}\n\n${content.replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim()}\n\nUnsubscribe: ${unsubscribe}`,html:template(subject,preview,`${content}<hr style="margin:28px 0;border:0;border-top:1px solid #e5e7eb"><p style="font-size:12px;color:#667085">You received this because you subscribed to Innozanzi updates. <a href="${escape(unsubscribe)}">Unsubscribe</a>.</p>`),idempotencyKey:`campaign:${campaignId}:${to}`}},
};
