import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, CheckCircle2, Code2, Compass, Gamepad2, HeartHandshake, Lightbulb, PackageCheck, ShieldCheck, Sparkles, Wrench } from "lucide-react";
import { brand, companyIdentity } from "@/config/brand";
import { entityMetadata } from "@/domain/marketing/seo";

export async function generateMetadata():Promise<Metadata>{return entityMetadata({entityType:"STATIC_PAGE",entityId:"about",path:"/about",title:"About Innozanzi | Technology, Made Easier",description:"Discover why Simukelo Ntshaba founded Innozanzi and how specialist products, intelligent software and hands-on service make buying technology easier in South Africa.",keywords:["about Innozanzi","Simukelo Ntshaba","South African technology company","custom PC specialists","technology shop South Africa"]})}

const approach=[
  {icon:Compass,title:"Understand the need",body:"We begin with what you want the technology to accomplish—not with the most expensive product."},
  {icon:Code2,title:"Build useful software",body:"Our engineering background helps us turn compatibility, discovery and order visibility into clearer digital experiences."},
  {icon:PackageCheck,title:"Care for the order",body:"Payment is one step. We remain responsible through sourcing, communication, fulfilment and delivery."},
] as const;

export default function AboutPage(){return <main className="bg-white text-slate-950">
  <section className="overflow-hidden border-b border-slate-800 bg-[#071b33] text-white"><div className="mx-auto grid max-w-7xl gap-12 px-4 py-16 sm:px-6 sm:py-24 lg:grid-cols-[1.15fr_.85fr] lg:items-end lg:px-8"><div><p className="text-xs font-black uppercase tracking-[.22em] text-sky-300">About Innozanzi</p><h1 className="mt-5 max-w-4xl text-4xl font-black leading-[1.05] tracking-tight sm:text-6xl">Technology should empower you, not intimidate you.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-300">Innozanzi combines technology retail, software engineering and human service to make choosing, buying and receiving technology clearer.</p><div className="mt-9 flex flex-wrap gap-3"><Link className="inline-flex min-h-12 items-center gap-2 rounded-lg bg-sky-400 px-6 font-black text-slate-950" href="/shop">Explore technology<ArrowRight className="size-4"/></Link><Link className="inline-flex min-h-12 items-center gap-2 rounded-lg border border-slate-600 px-6 font-bold text-white hover:border-sky-300" href="/build-a-pc">Build your PC<Wrench className="size-4"/></Link></div></div><aside className="border-l border-slate-700 pl-6 sm:pl-8"><p className="text-sm font-bold text-sky-300">Our purpose</p><p className="mt-3 text-2xl font-black leading-9">{companyIdentity.purpose}</p><p className="mt-7 text-sm font-bold text-sky-300">The simple expression</p><p className="mt-2 text-xl font-bold">{brand.tagline}</p></aside></div></section>

  <section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 sm:py-20 lg:px-8"><div className="grid gap-10 lg:grid-cols-[.72fr_1.28fr]"><div><p className="text-xs font-black uppercase tracking-[.18em] text-sky-700">Why we started</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">A better way to buy technology needed to be built.</h2></div><div className="space-y-5 text-base leading-8 text-slate-600"><p>Technology has become essential to work, study, creativity, business and entertainment. Yet buying it can still mean navigating model numbers, unclear specifications and expensive compatibility mistakes without enough useful guidance.</p><p>That problem is especially clear when building a PC. A processor, motherboard, memory kit, power supply or case can look right on its own and still be wrong for the complete machine. Innozanzi was created to reduce that uncertainty—not merely to place more products in front of people.</p><p>Our goal is to help customers understand what they need, choose with confidence, pay securely and know what is happening until the order reaches them.</p></div></div><div className="mt-14 grid gap-px overflow-hidden rounded-2xl border border-slate-200 bg-slate-200 md:grid-cols-3">{approach.map(({icon:Icon,title,body},index)=><article className="bg-white p-6 sm:p-8" key={title}><span className="text-xs font-black text-slate-400">0{index+1}</span><Icon className="mt-6 size-7 text-sky-700"/><h3 className="mt-4 text-xl font-black">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{body}</p></article>)}</div></section>

  <section className="bg-slate-50"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 sm:py-20 lg:px-8"><div className="max-w-3xl"><p className="text-xs font-black uppercase tracking-[.18em] text-sky-700">What we are building</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">More useful than a catalogue.</h2><p className="mt-5 text-lg leading-8 text-slate-600">The product matters. So does every experience surrounding it.</p></div><div className="mt-10 grid gap-5 md:grid-cols-2"><article className="rounded-2xl border border-slate-200 bg-white p-7"><Wrench className="size-8 text-sky-700"/><h3 className="mt-5 text-2xl font-black">Build a PC</h3><p className="mt-3 leading-7 text-slate-600">A customer-owned workspace for choosing real components, reviewing a complete build and purchasing the machine together or progressively. It expresses our belief that software should remove purchasing friction.</p><Link className="mt-5 inline-flex items-center gap-2 font-bold text-sky-700" href="/build-a-pc">Enter the PC Workshop<ArrowRight className="size-4"/></Link></article><article className="rounded-2xl border border-slate-200 bg-white p-7"><Gamepad2 className="size-8 text-sky-700"/><h3 className="mt-5 text-2xl font-black">Gaming discovery</h3><p className="mt-3 leading-7 text-slate-600">A focused route through gaming machines, performance levels and meaningful upgrades—designed around what players want to experience rather than an unstructured wall of products.</p><Link className="mt-5 inline-flex items-center gap-2 font-bold text-sky-700" href="/gaming">Explore Gaming<ArrowRight className="size-4"/></Link></article></div></div></section>

  <section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 sm:py-20 lg:px-8"><div className="grid gap-6 lg:grid-cols-3"><article className="rounded-2xl bg-[#071b33] p-7 text-white"><Lightbulb className="size-8 text-sky-300"/><p className="mt-5 text-xs font-black uppercase tracking-[.18em] text-sky-300">Purpose</p><p className="mt-3 text-xl font-bold leading-8">{companyIdentity.purpose}</p></article><article className="rounded-2xl border border-slate-200 p-7"><Compass className="size-8 text-sky-700"/><p className="mt-5 text-xs font-black uppercase tracking-[.18em] text-sky-700">Mission</p><p className="mt-3 leading-7 text-slate-700">{companyIdentity.mission}</p></article><article className="rounded-2xl border border-slate-200 p-7"><Sparkles className="size-8 text-sky-700"/><p className="mt-5 text-xs font-black uppercase tracking-[.18em] text-sky-700">Vision</p><p className="mt-3 leading-7 text-slate-700">{companyIdentity.vision}</p></article></div></section>

  <section className="border-y border-slate-200 bg-slate-50"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 sm:py-20 lg:px-8"><div className="max-w-3xl"><p className="text-xs font-black uppercase tracking-[.18em] text-sky-700">Our values</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Principles for real decisions.</h2><p className="mt-4 leading-7 text-slate-600">These are not slogans for a wall. They guide how we recommend products, communicate problems, build software and care for orders.</p></div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{companyIdentity.values.map((value,index)=><article className="rounded-2xl border border-slate-200 bg-white p-6" key={value.name}><span className="text-xs font-black text-sky-700">0{index+1}</span><h3 className="mt-3 text-xl font-black">{value.name}</h3><p className="mt-2 font-semibold text-slate-700">{value.summary}</p><p className="mt-3 text-sm leading-6 text-slate-600">{value.detail}</p></article>)}</div></div></section>

  <section className="mx-auto grid max-w-7xl gap-10 px-4 py-16 sm:px-6 sm:py-20 lg:grid-cols-2 lg:px-8"><div><p className="text-xs font-black uppercase tracking-[.18em] text-sky-700">What we believe</p><h2 className="mt-3 text-3xl font-black">Technology works better with clarity and care.</h2><div className="mt-7 space-y-4">{companyIdentity.beliefs.map(item=><p className="flex gap-3 leading-7 text-slate-600" key={item}><CheckCircle2 className="mt-1 size-5 shrink-0 text-sky-700"/>{item}</p>)}</div></div><aside className="h-fit rounded-2xl bg-[#071b33] p-7 text-white sm:p-9"><HeartHandshake className="size-9 text-sky-300"/><p className="mt-6 text-xs font-black uppercase tracking-[.18em] text-sky-300">Our customer promise</p><blockquote className="mt-4 text-2xl font-black leading-9">“{companyIdentity.customerPromise}”</blockquote><p className="mt-6 leading-7 text-slate-300">Suppliers, couriers and technology can create unexpected problems. Our promise is not that nothing can go wrong. It is that we communicate, take ownership, look for solutions and do not disappear after payment.</p></aside></section>

  <section className="bg-[#071b33] text-white"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-16 sm:px-6 sm:py-20 lg:grid-cols-[.78fr_1.22fr] lg:px-8"><div><p className="text-xs font-black uppercase tracking-[.18em] text-sky-300">The founder story</p><h2 className="mt-3 text-3xl font-black">{brand.founder.name}</h2><p className="mt-2 font-semibold text-slate-300">{brand.founder.title}</p></div><div className="space-y-5 text-base leading-8 text-slate-300"><p>Innozanzi grew from Simukelo’s experience as a software developer, senior software developer, technology enthusiast and technology customer. It was not created simply because technology products sell.</p><p>Building software shaped the belief that frustrating purchasing processes do not always need to be accepted—they can be redesigned. Buying and using technology personally made the compatibility problems, unclear choices and weak post-payment experiences impossible to ignore.</p><p>That combination became the foundation of Innozanzi: understand technology, build technology and sell technology in a way that makes the entire experience easier for the people and businesses depending on it.</p></div></div></section>

  <section className="mx-auto max-w-7xl px-4 py-16 text-center sm:px-6 sm:py-20 lg:px-8"><ShieldCheck className="mx-auto size-9 text-sky-700"/><p className="mt-5 text-xs font-black uppercase tracking-[.18em] text-sky-700">Where we are going</p><h2 className="mx-auto mt-3 max-w-4xl text-3xl font-black tracking-tight sm:text-4xl">A trusted place to understand what technology you need—and obtain it with confidence.</h2><p className="mx-auto mt-5 max-w-3xl leading-8 text-slate-600">Our ambition reaches beyond operating another online store. We are building a South African technology company where useful software, carefully chosen products and accountable human service strengthen one another.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><Link className="inline-flex min-h-12 items-center gap-2 rounded-lg bg-[#071b33] px-6 font-black text-white" href="/shop">Start shopping<ArrowRight className="size-4"/></Link><Link className="inline-flex min-h-12 items-center gap-2 rounded-lg border border-slate-300 px-6 font-bold" href="/contact">Talk to Innozanzi</Link></div></section>
</main>}
