import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Boxes, Gamepad2, HeartHandshake, Laptop, Server, Wrench } from "lucide-react";
import { brand } from "@/config/brand";
import { entityMetadata } from "@/domain/marketing/seo";

export async function generateMetadata():Promise<Metadata>{return entityMetadata({entityType:"STATIC_PAGE",entityId:"about",path:"/about",title:"About Innozanzi | South African Technology Specialists",description:"Meet Innozanzi, a South African specialist technology store for computers, laptops, custom PCs, gaming, servers and practical support.",keywords:["about Innozanzi","South African computer specialists","custom PC experts","technology shop South Africa"]})}

const specialties=[
  {icon:Laptop,title:"Computers & laptops",body:"Focused products for work, study, creation and everyday use."},
  {icon:Wrench,title:"Build your own PC",body:"A guided workspace for choosing components, checking your build and buying it all—or building it over time."},
  {icon:Gamepad2,title:"Gaming",body:"A dedicated experience for gaming machines, upgrades, components and complete setups."},
  {icon:Server,title:"Serious technology",body:"Servers, networking, storage, power and the tools that keep homes and teams connected."},
] as const;

export default function AboutPage(){return <main className="bg-white text-slate-950">
  <section className="border-b border-slate-200 bg-[#071b33] text-white"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 sm:py-24 lg:px-8"><p className="text-xs font-black uppercase tracking-[.2em] text-sky-300">About Innozanzi</p><h1 className="mt-4 max-w-4xl text-4xl font-black leading-tight sm:text-6xl">We live technology.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-300">We do not try to sell everything. We focus on computers, laptops, PC components, gaming, servers and the technology around them—because specialist knowledge makes buying technology easier.</p><div className="mt-8 flex flex-wrap gap-3"><Link className="inline-flex min-h-12 items-center gap-2 rounded-lg bg-sky-400 px-6 font-black text-slate-950" href="/shop">Shop technology<ArrowRight className="size-4"/></Link><Link className="inline-flex min-h-12 items-center gap-2 rounded-lg border border-slate-600 px-6 font-bold text-white" href="/build-a-pc">Build your PC<Wrench className="size-4"/></Link></div></div></section>
  <section className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-black uppercase tracking-[.18em] text-sky-700">Why we exist</p><h2 className="mt-3 text-3xl font-black">Technology should feel understandable.</h2></div><div className="space-y-5 text-base leading-8 text-slate-600"><p>Buying a computer can become a wall of model numbers, compatibility questions and unclear choices. Innozanzi exists to turn that into a clear journey: discover the right product, understand what it does, pay securely and follow the order through delivery.</p><p>Our PC Builder takes that belief further. Your build becomes a project attached to your account. You can choose real components, return later, buy selected parts over time and keep track of what remains.</p></div></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{specialties.map(({icon:Icon,title,body})=><article className="rounded-2xl border border-slate-200 p-5" key={title}><Icon className="size-7 text-sky-700"/><h3 className="mt-4 text-lg font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{body}</p></article>)}</div></section>
  <section className="bg-slate-50"><div className="mx-auto grid max-w-7xl gap-8 px-4 py-14 sm:px-6 lg:grid-cols-2 lg:px-8"><article className="rounded-2xl bg-white p-7 shadow-sm"><HeartHandshake className="size-8 text-sky-700"/><h2 className="mt-5 text-2xl font-black">People who speak computer</h2><p className="mt-3 leading-7 text-slate-600">Our role is not to add noise. It is to help customers make a confident decision, provide a dependable buying process and remain available when the technology needs support.</p></article><article className="rounded-2xl bg-[#071b33] p-7 text-white"><Boxes className="size-8 text-sky-300"/><p className="mt-5 text-xs font-bold uppercase tracking-[.18em] text-sky-300">Founder</p><h2 className="mt-2 text-2xl font-black">{brand.founder.name}</h2><p className="mt-1 text-sm font-semibold text-slate-300">{brand.founder.title}, {brand.legalName}</p><p className="mt-4 leading-7 text-slate-300">Innozanzi was built from a practical love of computers and software: create a specialist technology store where the product, guidance and digital experience work together.</p></article></div></section>
</main>}
