import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { requireUser } from "@/domain/auth/session";
import { startQuotationPaystackPayment, submitPaymentProof } from "@/domain/payments/actions";
import { formatZar } from "@/lib/money";

const input="mt-1 min-h-11 w-full rounded-lg border border-slate-300 px-3";

export default async function CustomerQuotations({searchParams}:{searchParams:Promise<{submitted?:string;payment?:string;online?:string}>}){
  const ctx=await requireUser();const params=await searchParams;
  const quotes=await prisma.quotation.findMany({where:{customerId:ctx.user.id},include:{items:true,paymentSubmissions:{orderBy:{submittedAt:"desc"},take:1}},orderBy:{createdAt:"desc"}});
  const notice=params.online==="paid"?"Your Paystack payment was verified. Your order is now active.":params.online==="verification-failed"?"We could not verify the returned payment. If funds were deducted, the secure webhook will still update your order.":params.payment?"Proof received. Payment verification is pending.":params.submitted?`Quotation request ${params.submitted} was submitted.`:null;
  return <main className="mx-auto max-w-6xl px-4 py-10">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-black">Your quotations</h1><p className="mt-2 text-slate-600">Follow provisional review, final quotation and payment progress.</p></div><Link className="rounded-lg bg-sky-600 px-5 py-3 font-bold text-white" href="/shop">Start another request</Link></div>
    {notice?<p className={`mt-5 rounded-lg p-4 ${params.online==="verification-failed"?"bg-amber-50 text-amber-900":"bg-emerald-50 text-emerald-800"}`}>{notice}</p>:null}
    <div className="mt-7 space-y-5">{quotes.map(q=>{const canPay=q.kind==="FINAL"&&["FINAL_APPROVED","SENT"].includes(q.status)&&q.validUntil>new Date();const canUpload=q.kind==="FINAL"&&["FINAL_APPROVED","SENT","PAYMENT_REJECTED"].includes(q.status)&&q.validUntil>new Date()&&!q.convertedOrderId;return <article className="rounded-xl border bg-white p-5 shadow-sm" key={q.id}>
      <div className="flex flex-wrap justify-between gap-4"><div><p className="text-xs font-bold uppercase text-sky-700">{q.kind} quotation</p><h2 className="mt-1 text-xl font-bold">{q.quotationNumber} · v{q.version}</h2><p className="mt-1 text-sm text-slate-500">Expires {q.validUntil.toLocaleDateString("en-ZA")}</p></div><div className="text-right"><p className="rounded bg-slate-100 px-3 py-1 text-xs font-bold">{q.status.replaceAll("_"," ")}</p><p className="mt-2 text-xl font-black">{formatZar(q.grandTotal.toString())}</p></div></div>
      <div className="mt-4 divide-y rounded-lg border">{q.items.map(i=><div className="flex justify-between gap-4 p-3 text-sm" key={i.id}><span>{i.productName} × {i.quantity}</span><strong>{formatZar(i.lineTotal.toString())}</strong></div>)}</div>
      <div className="mt-4 flex flex-wrap items-center gap-3"><Link className="font-semibold text-sky-700 underline" href={`/api/quotations/${q.quotationNumber}/pdf`} target="_blank">Open PDF</Link>{canPay?<form action={startQuotationPaystackPayment}><input name="quotationId" type="hidden" value={q.id}/><button className="rounded-lg bg-emerald-700 px-5 py-3 font-bold text-white">Pay securely online</button></form>:null}{q.convertedOrderId?<Link className="font-semibold text-sky-700 underline" href="/account/orders">Track active order</Link>:null}</div>
      {q.kind==="PROVISIONAL"?<p className="mt-4 rounded-lg bg-amber-50 p-3 text-sm text-amber-900">This is provisional. Do not pay until a final quotation is approved and sent.</p>:null}
      {canUpload?<details className="mt-5 rounded-lg bg-slate-50 p-4"><summary className="cursor-pointer font-bold">Pay by EFT and upload proof</summary><form action={submitPaymentProof} className="mt-4 grid gap-3 sm:grid-cols-2"><input type="hidden" name="quotationId" value={q.id}/><label>Amount paid<input className={input} name="amount" type="number" min="0.01" step="0.01" defaultValue={q.grandTotal.toString()} required/></label><label>Payment date<input className={input} name="paymentDate" type="date" required/></label><label>Payment reference<input className={input} name="paymentReference" defaultValue={q.paymentReference??q.quotationNumber} required/></label><label>Proof document<input className={`${input} py-2`} name="proof" type="file" accept=".pdf,image/jpeg,image/png,image/webp" required/></label><label className="sm:col-span-2">Optional note<textarea className={`${input} min-h-20 py-2`} name="customerNote"/></label><button className="rounded-lg bg-[#071b33] px-5 py-3 font-bold text-white sm:col-span-2">Submit proof for verification</button></form></details>:null}
      {q.paymentSubmissions[0]?<p className="mt-4 text-sm"><strong>Latest payment submission:</strong> {q.paymentSubmissions[0].status.replaceAll("_"," ")}{q.paymentSubmissions[0].rejectionReason?` — ${q.paymentSubmissions[0].rejectionReason}`:""}</p>:null}
    </article>})}{!quotes.length?<p className="rounded-xl border border-dashed p-10 text-center text-slate-500">No quotation requests yet.</p>:null}</div>
  </main>;
}
