import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminPage,Panel,StatusBadge,buttonClass,inputClass,secondaryButtonClass,tableClass } from "@/components/admin/admin-ui";
import { requirePermission } from "@/domain/auth/session";
import { recordInvoicePayment,updateInvoiceStatus } from "@/domain/documents/actions";
import { prisma } from "@/lib/prisma";

export default async function InvoiceDetail({params}:{params:Promise<{id:string}>}){
  await requirePermission("quotations.manage");const invoice=await prisma.invoice.findUnique({where:{id:(await params).id},include:{items:{orderBy:{sortOrder:"asc"}},payments:{orderBy:{paidAt:"desc"}},createdBy:{select:{name:true,email:true}},order:true,quotation:true}});if(!invoice)notFound();
  return <AdminPage title={invoice.invoiceNumber} description={`${invoice.origin} invoice · ${invoice.companyName??invoice.customerName}`} actions={<><Link className={secondaryButtonClass} href="/admin/invoices">Back</Link><a className={buttonClass} href={`/api/invoices/${invoice.invoiceNumber}/pdf`} target="_blank">Open PDF</a><StatusBadge value={invoice.status}/></>}>
    <div className="grid gap-4 xl:grid-cols-[1.5fr_.7fr]"><div className="space-y-4"><Panel><dl className="mb-4 grid gap-3 text-sm sm:grid-cols-3"><div><dt className="font-bold">Customer</dt><dd>{invoice.customerName}<br/>{invoice.customerEmail}</dd></div><div><dt className="font-bold">Source</dt><dd>{invoice.order?.orderNumber??invoice.quotation?.quotationNumber??"Standalone"}</dd></div><div><dt className="font-bold">Due</dt><dd>{invoice.dueAt.toLocaleDateString("en-ZA")}</dd></div></dl><table className={tableClass}><thead><tr><th>Description</th><th>Qty</th><th>Unit</th><th>VAT</th><th>Total</th></tr></thead><tbody>{invoice.items.map(x=><tr key={x.id}><td>{x.description}</td><td>{x.quantity}</td><td>R {Number(x.unitPrice).toFixed(2)}</td><td>R {Number(x.vatTotal).toFixed(2)}</td><td>R {Number(x.lineTotal).toFixed(2)}</td></tr>)}</tbody></table><div className="ml-auto mt-5 max-w-sm space-y-2 border-t pt-4 text-sm"><p className="flex justify-between"><span>Total</span><strong>R {Number(invoice.grandTotal).toFixed(2)}</strong></p><p className="flex justify-between"><span>Paid</span><strong>R {Number(invoice.amountPaid).toFixed(2)}</strong></p><p className="flex justify-between text-lg"><span>Balance</span><strong>R {Number(invoice.balanceDue).toFixed(2)}</strong></p></div></Panel><Panel title="Payment history">{invoice.payments.length?<table className={tableClass}><thead><tr><th>Date</th><th>Method</th><th>Reference</th><th>Amount</th></tr></thead><tbody>{invoice.payments.map(x=><tr key={x.id}><td>{x.paidAt.toLocaleDateString("en-ZA")}</td><td>{x.method}</td><td>{x.reference??"—"}</td><td>R {Number(x.amount).toFixed(2)}</td></tr>)}</tbody></table>:<p className="text-sm text-slate-500">No payments recorded.</p>}</Panel></div>
    <aside className="space-y-4"><Panel title="Document status"><form action={updateInvoiceStatus} className="space-y-3"><input type="hidden" name="invoiceId" value={invoice.id}/><select className={inputClass} name="status" defaultValue={invoice.status}>{["DRAFT","ISSUED","SENT","OVERDUE","VOID","CANCELLED","CREDITED"].map(x=><option key={x}>{x.replaceAll("_"," ")}</option>)}</select><button className={buttonClass}>Update status</button></form></Panel>{!["PAID","VOID","CANCELLED","CREDITED"].includes(invoice.status)?<Panel title="Record payment"><form action={recordInvoicePayment} className="space-y-3"><input type="hidden" name="invoiceId" value={invoice.id}/><input className={inputClass} name="amount" type="number" min=".01" max={invoice.balanceDue.toString()} step=".01" placeholder="Amount" required/><input className={inputClass} name="paidAt" type="date" required/><select className={inputClass} name="method"><option>EFT</option><option>MANUAL</option><option>PAYSTACK</option><option>YOCO</option></select><input className={inputClass} name="reference" placeholder="Payment reference"/><textarea className={`${inputClass} min-h-20`} name="note" placeholder="Internal note"/><button className={buttonClass}>Record payment</button></form></Panel>:null}<Panel title="Audit summary"><p className="text-sm">Created by {invoice.createdBy?.name??invoice.createdBy?.email??"System"} on {invoice.createdAt.toLocaleString("en-ZA")}.</p></Panel></aside></div>
  </AdminPage>;
}
