import { createPortalQuotationRequest } from "@/domain/client-portal/actions";
import { requireClientPortal } from "@/domain/client-portal/session";
import { prisma } from "@/lib/prisma";

const input="mt-1 w-full rounded-md border border-slate-300 bg-white px-3 py-2.5 text-sm";
export default async function NewPortalRequestPage({searchParams}:{searchParams:Promise<{product?:string}>}){
  await requireClientPortal();const{product}=await searchParams;
  const products=await prisma.product.findMany({where:{status:"PUBLISHED",deletedAt:null},select:{id:true,name:true,sku:true,stockStatus:true},orderBy:{name:"asc"},take:250});
  return <div className="mx-auto max-w-5xl"><p className="text-xs font-bold uppercase tracking-widest text-sky-700">Procurement request</p><h1 className="mt-1 text-3xl font-semibold">Request a quotation</h1><p className="mt-2 text-sm text-slate-600">Combine catalogue items and products we do not currently list. Our team will confirm availability, sourcing and business pricing.</p>
    <form action={createPortalQuotationRequest} className="mt-6 space-y-5">
      <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-semibold">Catalogue products</h2><p className="text-sm text-slate-500">Out-of-stock items are welcome—we will check suppliers.</p><div className="mt-4 space-y-3">{Array.from({length:4},(_,index)=><div className="grid gap-3 sm:grid-cols-[1fr_120px]" key={index}><select className={input} defaultValue={index===0?product??"":""} name={`productId:${index}`}><option value="">Select a product (optional)</option>{products.map(item=><option key={item.id} value={item.id}>{item.name} · {item.sku} · {item.stockStatus.replaceAll("_"," ")}</option>)}</select><input className={input} min="1" name={`productQuantity:${index}`} placeholder="Qty" type="number"/></div>)}</div></section>
      <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-semibold">Products not in our catalogue</h2><p className="text-sm text-slate-500">Give us a product name plus any brand, model or technical requirements.</p><div className="mt-4 space-y-4">{Array.from({length:4},(_,index)=><div className="grid gap-3 rounded-lg bg-slate-50 p-3 sm:grid-cols-[1fr_100px_1.4fr]" key={index}><input className={input} name={`requestedName:${index}`} placeholder="Product name"/><input className={input} min="1" name={`requestedQuantity:${index}`} placeholder="Qty" type="number"/><input className={input} name={`requestedNotes:${index}`} placeholder="Brand, model, specifications or equivalent"/></div>)}</div></section>
      <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-semibold">Delivery and request details</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Required by<input className={input} name="targetDeliveryDate" type="date"/></label><label className="text-sm font-semibold">Contact phone<input className={input} name="phone" type="tel"/></label></div><label className="mt-4 block text-sm font-semibold">Overall requirements<textarea className={input} name="requirements" placeholder="Delivery location, use case, required specifications, preferred alternatives…" rows={4}/></label><label className="mt-4 block text-sm font-semibold">Additional notes<textarea className={input} name="customerNotes" rows={3}/></label></section>
      <button className="rounded-md bg-sky-700 px-6 py-3 text-sm font-bold text-white hover:bg-sky-800" type="submit">Submit quotation request</button>
    </form>
  </div>;
}
