import Link from "next/link";
import { notFound } from "next/navigation";
import { OrderProgress } from "@/components/orders/order-progress";
import { requireUser } from "@/domain/auth/session";
import { orderCompletionWindowDays, returnWindowEnd } from "@/domain/orders/settings";
import { formatZar } from "@/lib/money";
import { prisma } from "@/lib/prisma";

export default async function TrackOrder({params,searchParams}:{params:Promise<{orderNumber:string}>,searchParams:Promise<{quotation?:string}>}) {
  const ctx=await requireUser(); const {orderNumber}=await params; const {quotation}=await searchParams;
  const [order,completionDays]=await Promise.all([prisma.order.findFirst({where:{userId:ctx.user.id,...(orderNumber==="by-quotation"&&quotation?{convertedQuotation:{quotationNumber:quotation}}:{orderNumber})},include:{items:true,deliveryEvents:{orderBy:{occurredAt:"asc"}},shipments:{orderBy:{createdAt:"desc"}},procurements:{select:{orderedAt:true,confirmedAt:true},orderBy:{createdAt:"asc"}},returnCases:{select:{id:true,status:true}}}}),orderCompletionWindowDays()]);
  if(!order)notFound(); const shipment=order.shipments[0];
  const supplierOrderedAt=order.procurements.map(item=>item.orderedAt).filter((date):date is Date=>Boolean(date)).sort((a,b)=>a.getTime()-b.getTime())[0]??null;
  const supplierConfirmedAt=order.procurements.map(item=>item.confirmedAt).filter((date):date is Date=>Boolean(date)).sort((a,b)=>a.getTime()-b.getTime())[0]??null;
  const returnWindowEndsAt=shipment?.deliveredAt?returnWindowEnd(shipment.deliveredAt,completionDays):null;
  return <main className="mx-auto min-w-0 max-w-5xl px-4 py-7 sm:py-10">
    <p className="text-xs font-bold uppercase tracking-wider text-sky-700">Delivery tracking</p>
    <div className="mt-2 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div className="min-w-0"><h1 className="break-words text-2xl font-black sm:text-3xl">Order {order.orderNumber}</h1><p className="mt-2 text-sm text-slate-600 sm:text-base">Follow every verified fulfilment and delivery update.</p></div><div className="grid grid-cols-2 gap-2 sm:flex"><a className="inline-flex min-h-11 items-center justify-center rounded-lg border px-3 text-center text-sm font-bold text-sky-700" href={`/api/orders/${order.orderNumber}/delivery-note`} target="_blank">Delivery note</a><Link className="inline-flex min-h-11 items-center justify-center rounded-lg bg-sky-700 px-3 text-center text-sm font-bold text-white" href={`/account/returns/new?order=${order.orderNumber}`}>Get product help</Link></div></div>
    <section className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-6"><div className="mb-5"><p className="text-xs font-bold uppercase tracking-wider text-sky-700">Current fulfilment stage</p><h2 className="mt-1 text-xl font-black">Your order’s journey</h2></div><OrderProgress status={order.status} details={{placedAt:order.placedAt,estimatedDeliveryAt:shipment?.estimatedDeliveryAt,deliveredAt:shipment?.deliveredAt,returnWindowEndsAt,supplierOrderedAt,supplierConfirmedAt,events:order.deliveryEvents}}/></section>
    {order.status==="DELIVERED"&&returnWindowEndsAt?<section className="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-950"><strong>Delivered successfully</strong><p className="mt-1">Your order remains open for returns or refund requests until {returnWindowEndsAt.toLocaleString("en-ZA",{dateStyle:"long",timeStyle:"short"})}. An open request prevents automatic closure.</p></section>:null}
    {shipment?<section className="mt-4 grid gap-4 rounded-xl border border-sky-200 bg-sky-50 p-4 text-sm sm:grid-cols-3"><div><strong>Delivery company</strong><p className="mt-1 break-words">{shipment.deliveryCompany??"Being arranged"}</p></div><div><strong>Estimated delivery</strong><p className="mt-1">{shipment.estimatedDeliveryAt?.toLocaleString("en-ZA")??"To be confirmed"}</p></div><div><strong>Courier tracking</strong><p className="mt-1 break-all">{shipment.trackingUrl?<a className="text-sky-700 underline" href={shipment.trackingUrl} target="_blank">{shipment.trackingNumber??"Open courier tracking"}</a>:shipment.trackingNumber??"Not available yet"}</p></div></section>:null}
    <div className="mt-6 grid min-w-0 gap-5 md:grid-cols-[minmax(0,1fr)_minmax(16rem,.8fr)]"><section className="min-w-0 rounded-xl border bg-white p-4 sm:p-5"><h2 className="font-bold">Verified updates</h2><div className="mt-5">{order.deliveryEvents.map((event,index)=><div className="relative border-l-2 border-sky-500 pb-7 pl-5 last:pb-0" key={event.id}><span className="absolute -left-[7px] top-0 size-3 rounded-full bg-sky-600"/><p className="font-semibold">{event.status.replaceAll("_"," ")}</p><p className="text-xs text-slate-500">{event.occurredAt.toLocaleString("en-ZA")}</p>{event.publicNote?<p className="mt-1 text-sm leading-6 text-slate-700">{event.publicNote}</p>:null}{index===order.deliveryEvents.length-1?<span className="mt-2 inline-block rounded bg-sky-50 px-2 py-1 text-xs font-bold text-sky-800">Latest update</span>:null}</div>)}</div></section><aside className="h-fit min-w-0 rounded-xl bg-slate-900 p-5 text-white"><h2 className="font-bold">Order summary</h2><p className="mt-2 text-2xl font-black">{formatZar(order.grandTotal.toString())}</p><div className="mt-4 divide-y divide-slate-700">{order.items.map(item=><div className="flex min-w-0 justify-between gap-3 py-3 text-sm" key={item.id}><span className="min-w-0 break-words">{item.productName}</span><span className="shrink-0">× {item.quantity}</span></div>)}</div></aside></div>
  </main>;
}
