import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { requestSupplierProductQuotation } from "@/domain/catalogue/supplier-quotation-actions";
import { prisma } from "@/lib/prisma";
export const dynamic="force-dynamic";
export default async function SupplierProductPage({params}:{params:Promise<{slug:string}>}){
  const product=await prisma.supplierCatalogueProduct.findFirst({where:{slug:(await params).slug,active:true},include:{supplier:{select:{companyName:true}}}});if(!product)notFound();
  const specs=product.specifications&&typeof product.specifications==="object"&&!Array.isArray(product.specifications)?Object.entries(product.specifications as Record<string,unknown>):[];
  return <main className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><nav className="mb-6 text-sm text-slate-500"><Link href="/shop">Products</Link> / {product.category??"Catalogue"} / {product.name}</nav><div className="grid gap-10 lg:grid-cols-2"><section><div className="relative aspect-square overflow-hidden rounded-3xl bg-slate-50">{product.images[0]?<Image src={product.images[0]} alt={product.name} fill sizes="50vw" className="object-contain p-8" priority/>:<div className="grid h-full place-items-center text-slate-500">Image unavailable</div>}</div></section><section><p className="text-sm font-semibold uppercase tracking-wider text-sky-700">{product.brand??product.category??product.supplier.companyName}</p><h1 className="mt-2 text-3xl font-bold sm:text-4xl">{product.name}</h1><p className="mt-2 text-sm text-slate-500">SKU {product.supplierSku}</p><div className="mt-6 rounded-xl border border-sky-200 bg-sky-50 p-4"><p className="font-bold">Pricing is prepared by quotation</p><p className="mt-1 text-sm text-slate-600">We will confirm current availability, delivery and your approved business price.</p></div><p className="mt-6 text-sm font-semibold text-slate-700">{product.availability==="IN_STOCK"?"Available from supplier":"Availability confirmed during quotation"}</p><form action={requestSupplierProductQuotation} className="mt-6 flex gap-3"><input type="hidden" name="productId" value={product.id}/><input aria-label="Requested quantity" className="w-28 rounded-lg border px-3" name="quantity" type="number" min="1" max="999" defaultValue="1"/><button className="flex-1 rounded-lg bg-sky-700 px-6 py-3 font-semibold text-white">Request a quotation</button></form>{product.shortDescription?<div className="mt-7 leading-7 text-slate-700" dangerouslySetInnerHTML={{__html:product.shortDescription}}/>:null}</section></div>{product.description?<section className="prose mt-14 max-w-4xl border-t pt-10" dangerouslySetInnerHTML={{__html:product.description}}/>:null}{specs.length?<section className="mt-10 max-w-4xl"><h2 className="text-2xl font-bold">Specifications</h2><dl className="mt-4 divide-y rounded-xl border">{specs.map(([name,value])=><div className="grid grid-cols-2 gap-4 p-4" key={name}><dt className="font-medium">{name.replaceAll("-"," ")}</dt><dd className="text-slate-600">{String(value)}</dd></div>)}</dl></section>:null}</main>
}
