/* eslint-disable react-hooks/purity */
import Link from "next/link";
import { notFound } from "next/navigation";
import { requestSupplierProductQuotation } from "@/domain/catalogue/supplier-quotation-actions";
import { prisma } from "@/lib/prisma";
import { ProductGallery } from "@/components/store/product-gallery";
import { ProductCard } from "@/components/store/product-card";
import { safeSupplierHtml } from "@/lib/safe-supplier-html";
import type { Metadata } from "next";
import { entityMetadata } from "@/domain/marketing/seo";
export const dynamic="force-dynamic";
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{
  const product=await prisma.supplierCatalogueProduct.findFirst({where:{slug:(await params).slug,active:true}});
  if(!product)return{robots:{index:false,follow:false}};
  const plain=(product.shortDescription??product.description??"").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim();
  return entityMetadata({entityType:"SUPPLIER_PRODUCT",entityId:product.id,path:`/supplier-products/${product.slug}`,title:`${product.name} | Business quotation`,description:plain.slice(0,160)||`Request a business quotation for ${product.name}. Innozanzi confirms availability, delivery and support across South Africa.`,image:product.images[0],keywords:[product.name,product.supplierSku,product.manufacturerSku??"",product.brand??"",product.category??"","South Africa"]});
}
export default async function SupplierProductPage({params}:{params:Promise<{slug:string}>}){
  const product=await prisma.supplierCatalogueProduct.findFirst({where:{slug:(await params).slug,active:true},include:{supplier:{select:{companyName:true}}}});if(!product)notFound();
  const specs=product.specifications&&typeof product.specifications==="object"&&!Array.isArray(product.specifications)?Object.entries(product.specifications as Record<string,unknown>):[];
  const related=await prisma.supplierCatalogueProduct.findMany({where:{active:true,id:{not:product.id},category:product.category,images:{isEmpty:false}},take:4,orderBy:{stock:"desc"},select:{id:true,name:true,slug:true,supplierSku:true,availability:true,brand:true,category:true,images:true}});
  return <main className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><nav className="mb-6 text-sm text-slate-500"><Link href="/shop">Products</Link> / {product.category??"Catalogue"} / {product.name}</nav><div className="grid gap-10 lg:grid-cols-2"><ProductGallery images={product.images} name={product.name}/><section>{product.sourceUpdatedAt&&Date.now()-product.sourceUpdatedAt.getTime()<30*86400000?<span className="rounded-full bg-sky-100 px-3 py-1 text-xs font-bold text-sky-800">NEW / UPDATED</span>:null}<p className="mt-3 text-sm font-semibold uppercase tracking-wider text-sky-700">{product.brand??product.category??product.supplier.companyName}</p><h1 className="mt-2 text-3xl font-bold sm:text-4xl">{product.name}</h1><p className="mt-2 text-sm text-slate-500">SKU {product.supplierSku}{product.manufacturerSku?` · MPN ${product.manufacturerSku}`:""}</p><div className="mt-6 rounded-xl border border-sky-200 bg-sky-50 p-4"><p className="font-bold">Pricing is prepared by quotation</p><p className="mt-1 text-sm text-slate-600">We confirm availability, delivery and an approved business price.</p></div><p className="mt-6 font-semibold">{product.availability==="IN_STOCK"?"Available from supplier":product.nextShipmentAt?`Incoming stock expected ${product.nextShipmentAt.toLocaleDateString("en-ZA")}`:"Availability confirmed during quotation"}</p><form action={requestSupplierProductQuotation} className="mt-6 flex gap-3"><input type="hidden" name="productId" value={product.id}/><input aria-label="Requested quantity" className="w-28 rounded-lg border px-3" name="quantity" type="number" min="1" max="999" defaultValue="1"/><button className="flex-1 rounded-lg bg-sky-700 px-6 py-3 font-semibold text-white">Add to quotation request</button></form>{product.shortDescription?<div className="mt-7 leading-7 text-slate-700" dangerouslySetInnerHTML={{__html:safeSupplierHtml(product.shortDescription)}}/>:null}</section></div>{product.description?<section className="prose mt-14 max-w-4xl border-t pt-10" dangerouslySetInnerHTML={{__html:safeSupplierHtml(product.description)}}/>:null}{specs.length?<section className="mt-10 max-w-4xl"><h2 className="text-2xl font-bold">Specifications</h2><dl className="mt-4 divide-y rounded-xl border">{specs.map(([name,value])=><div className="grid grid-cols-2 gap-4 p-4" key={name}><dt className="font-medium">{name.replaceAll("-"," ")}</dt><dd className="text-slate-600">{String(value)}</dd></div>)}</dl></section>:null}{related.length?<section className="mt-14"><h2 className="text-2xl font-bold">Related products</h2><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{related.map(p=><ProductCard key={p.id} product={{id:p.id,name:p.name,slug:p.slug,sku:p.supplierSku,stockStatus:p.availability,brand:p.brand?{name:p.brand,slug:p.brand}:null,category:{name:p.category??"Catalogue",slug:p.category??"catalogue"},images:p.images.slice(0,1).map(path=>({path,altText:p.name})),source:"supplier"}}/>)}</div></section>:null}</main>
}
