import Link from "next/link";
import { AdminPage,Panel,buttonClass,inputClass,secondaryButtonClass } from "@/components/admin/admin-ui";
import { requirePermission } from "@/domain/auth/session";
import { saveComboCampaign } from "@/domain/combos/actions";
import { prisma } from "@/lib/prisma";

export default async function NewCombo(){
  await requirePermission("combos.create");
  const products=await prisma.product.findMany({where:{status:"PUBLISHED",deletedAt:null,isTestData:false},include:{inventory:true,suppliers:{where:{isPreferred:true},take:1}},orderBy:{name:"asc"}});
  return <AdminPage title="Create Product Combo" description="Select two to five existing products. Prices, costs and stock are revalidated on the server." actions={<Link className={secondaryButtonClass} href="/admin/marketing/combos">Cancel</Link>}>
    <form action={saveComboCampaign} className="space-y-5"><input type="hidden" name="id" value=""/>
      <Panel title="1. Campaign details"><div className="grid gap-3 md:grid-cols-2"><F name="name" label="Campaign name"/><F name="headline" label="Promotional headline"/><label>Type<select className={`${inputClass} mt-1 w-full`} name="type">{["DAILY","WEEKLY","MONTHLY","CUSTOM"].map(x=><option key={x}>{x}</option>)}</select></label><F name="targetAudience" label="Target audience" value="Small businesses"/><F name="startsAt" label="Starts" type="datetime-local"/><F name="endsAt" label="Ends" type="datetime-local"/><label className="md:col-span-2">Description<textarea className={`${inputClass} mt-1 min-h-28 w-full`} name="description" required/></label><label className="md:col-span-2">Benefits<textarea className={`${inputClass} mt-1 min-h-20 w-full`} name="benefits"/></label></div></Panel>
      <Panel title="2. Select products" description="Availability and preferred supplier or catalogue cost are checked when saved."><div className="space-y-3">{Array.from({length:5},(_,index)=><div className="grid gap-2 md:grid-cols-[1fr_140px]" key={index}><select className={inputClass} name={`product_${index}`} required={index<2}><option value="">Select product {index+1}</option>{products.map(p=><option value={p.id} key={p.id}>{p.name} · {p.sku} · {p.inventory.reduce((n,x)=>n+Math.max(0,x.onHand-x.reserved),0)} available · R {Number(p.salePrice??p.regularPrice).toFixed(2)}</option>)}</select><input className={inputClass} name={`quantity_${index}`} type="number" min="1" defaultValue="1"/></div>)}</div></Panel>
      <Panel title="3. Pricing and profitability"><div className="grid gap-3 md:grid-cols-4"><F name="comboPrice" label="Combo price" type="number"/><F name="serviceCost" label="Service costs" type="number" value="0"/><F name="deliveryCost" label="Delivery costs" type="number" value="0"/><F name="paymentCost" label="Payment costs" type="number" value="0"/></div><p className="mt-3 text-xs text-slate-500">Normal price, discount, total cost, gross profit and margin are calculated from authoritative product data. Unsafe campaigns remain drafts.</p></Panel>
      <Panel title="4–5. Marketing and distribution"><div className="grid gap-3 md:grid-cols-2"><F name="imageUrl" label="Campaign image URL" required={false}/><F name="mobileImageUrl" label="Mobile image URL" required={false}/><label>Call to action<select className={`${inputClass} mt-1 w-full`} name="callToAction">{["Request a Quote","Get a Quick Quote","Speak to Sales","Order Now"].map(x=><option key={x}>{x}</option>)}</select></label><F name="emailSubject" label="Email subject" required={false}/><F name="emailPreview" label="Email preview" required={false}/><F name="sliderHeadline" label="Slider headline" required={false}/><label className="md:col-span-2">Email body<textarea className={`${inputClass} mt-1 min-h-24 w-full`} name="emailBody"/></label><label className="md:col-span-2">Slider supporting text<textarea className={`${inputClass} mt-1 min-h-20 w-full`} name="sliderText"/></label><label className="md:col-span-2">Social caption<textarea className={`${inputClass} mt-1 min-h-20 w-full`} name="socialCaption"/></label></div></Panel>
      <button className={`${buttonClass} w-full`}>Create protected draft</button>
    </form>
  </AdminPage>;
}
function F({name,label,type="text",value,required=true}:{name:string;label:string;type?:string;value?:string;required?:boolean}){return <label>{label}<input className={`${inputClass} mt-1 w-full`} name={name} type={type} step={type==="number"?".01":undefined} min={type==="number"?"0":undefined} defaultValue={value} required={required}/></label>}
