import Image from "next/image";
import Link from "next/link";
import { AdminPage, EmptyState, Panel, buttonClass, inputClass } from "@/components/admin/admin-ui";
import { requirePermission } from "@/domain/auth/session";
import { generateSocialContentNow } from "@/domain/marketing/social-actions";
import { DAILY_SOCIAL_TYPES, socialGenerationReadiness } from "@/domain/marketing/social-content";
import { prisma } from "@/lib/prisma";

const labels:Record<string,string>={PRODUCT:"Product spotlight",SPECIAL:"Legacy special",PC_BUILDER:"Build a PC",GAMING:"Gaming",INSIGHT:"Blog insight"};
const failures:Record<string,string>={CATALOGUE:"The system could not select a valid catalogue product for today’s posts.",COPY:"OpenAI could not create the three captions. Check API access, model availability or billing, then retry.",PRODUCT_ARTWORK:"A supplier product image could not be downloaded or composed.",FEATURE_ARTWORK:"High-quality feature artwork generation failed. Check image-model access or billing, then retry.",STORAGE:"The generated artwork could not be saved to storage.",EMAIL:"The posts were created, but background delivery failed. Retry to process the existing content.",INTERNAL:"An internal generation step failed. Retry once; if it persists, review the server log."};

export default async function SocialMarketingPage({searchParams}:{searchParams:Promise<{result?:string;stage?:string;type?:string;date?:string;search?:string}>}) {
  await requirePermission("marketing.content.view");
  const {result,stage,type,date,search}=await searchParams;
  const selectedType=type&&[...DAILY_SOCIAL_TYPES,"INSIGHT","SPECIAL"].includes(type)?type:"ALL";
  const selectedDate=/^\d{4}-\d{2}-\d{2}$/.test(date??"")?date:"";
  const query=(search??"").trim().slice(0,100);
  const [items,readiness]=await Promise.all([
    prisma.socialContent.findMany({where:{contentType:selectedType==="ALL"?undefined:selectedType,contentDate:selectedDate?new Date(`${selectedDate}T00:00:00.000Z`):undefined,OR:query?[{title:{contains:query,mode:"insensitive"}},{caption:{contains:query,mode:"insensitive"}}]:undefined},orderBy:[{contentDate:"desc"},{createdAt:"desc"}],take:80}),
    socialGenerationReadiness(),
  ]);
  return <AdminPage title="Social media" description="Three concise, high-quality product and feature posts are prepared each day for South African customers." actions={<Link className="text-sm font-semibold text-sky-700" href="/admin/marketing/settings">Settings</Link>}>
    {result==="generated"?<p className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">Today’s three posts were created successfully.</p>:null}
    {result==="already-generated"?<p className="rounded-lg bg-sky-50 p-3 text-sm text-sky-800">Today’s three posts already exist, so nothing was repeated.</p>:null}
    {result==="failed"?<p className="rounded-lg bg-red-50 p-3 text-sm text-red-800"><strong>Generation failed at {stage?.replaceAll("_"," ").toLowerCase()??"an internal step"}.</strong> {failures[stage??"INTERNAL"]??failures.INTERNAL}</p>:null}
    <Panel title="Generation services" description="Only the services needed to create captions and full-size artwork are shown here."><div className="grid gap-2 sm:grid-cols-2">{Object.entries({"Caption generation":readiness.openai,"Image storage":readiness.storage}).map(([label,ready])=><div className={`rounded-lg border p-3 text-sm font-bold ${ready?"border-emerald-200 bg-emerald-50 text-emerald-800":"border-red-200 bg-red-50 text-red-800"}`} key={label}>{label}: {ready?"Ready":"Missing"}</div>)}</div></Panel>
    <Panel title="Daily content plan" description="One real catalogue product and two useful Innozanzi shopping features. Product subjects rotate to keep the feed fresh."><div className="grid gap-3 sm:grid-cols-3">{["Product spotlight","Build a PC","Gaming"].map((label,index)=><div className="rounded-lg border border-slate-200 p-4" key={label}><span className="text-xs font-black text-sky-700">POST {index+1}</span><h3 className="mt-1 font-bold">{label}</h3><p className="mt-1 text-xs text-slate-500">Short caption · local hashtags · 1080 × 1350 artwork</p></div>)}</div><form action={generateSocialContentNow} className="mt-5"><button className={buttonClass}>Generate today’s three posts</button></form></Panel>
    <Panel title="Find content" description="Filter the saved library without exposing background email or delivery processing."><form className="grid gap-3 sm:grid-cols-[1fr_180px_180px_auto]" method="get"><input className={inputClass} name="search" defaultValue={query} placeholder="Search titles or captions"/><select className={inputClass} name="type" defaultValue={selectedType}><option value="ALL">All content</option>{[...DAILY_SOCIAL_TYPES,"INSIGHT","SPECIAL"].map(value=><option value={value} key={value}>{labels[value]??value}</option>)}</select><input className={inputClass} type="date" name="date" defaultValue={selectedDate}/><button className={buttonClass}>Apply filters</button></form>{query||selectedDate||selectedType!=="ALL"?<Link href="/admin/marketing/social" className="mt-3 inline-block text-sm font-bold text-sky-700">Clear filters</Link>:null}</Panel>
    <Panel title="Content library" description={`${items.length} matching post${items.length===1?"":"s"}.`}>{items.length?<div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{items.map(item=><article className="overflow-hidden rounded-xl border border-slate-200 bg-white" key={item.id}><div className="relative aspect-[4/5] bg-slate-100"><Image src={item.imageUrl} alt={item.imageAlt} fill sizes="(max-width: 768px) 100vw, 33vw" className="object-cover"/></div><div className="p-4"><span className="text-xs font-black uppercase text-sky-700">{labels[item.contentType]??item.contentType}</span><h3 className="mt-2 font-bold">{item.title}</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-600">{item.caption}</p><div className="mt-4 flex items-center justify-between text-xs text-slate-500"><span>{item.contentDate.toLocaleDateString("en-ZA")}</span><a className="font-semibold text-sky-700" href={item.imageUrl} target="_blank" rel="noreferrer" download>Download image</a></div></div></article>)}</div>:<EmptyState title="No matching social content" description="Change the filters or generate today’s three posts."/>}</Panel>
  </AdminPage>;
}
