import Image from "next/image";
import Link from "next/link";
import { AdminPage, EmptyState, Panel, StatusBadge, buttonClass } from "@/components/admin/admin-ui";
import { requirePermission } from "@/domain/auth/session";
import { generateSocialContentNow } from "@/domain/marketing/social-actions";
import { socialGenerationReadiness } from "@/domain/marketing/social-content";
import { prisma } from "@/lib/prisma";
const labels: Record<string, string> = { PRODUCT: "Product spotlight", SPECIAL: "Product special", PC_BUILDER: "Build a PC", GAMING: "Gaming", INSIGHT: "Blog insight" };

const failures:Record<string,string>={CATALOGUE:"The system could not select valid catalogue products for today’s posts.",COPY:"OpenAI could not create the four captions. Check API access, model availability or billing, then retry.",PRODUCT_ARTWORK:"A supplier product image could not be downloaded or composed.",FEATURE_ARTWORK:"OpenAI image generation failed. Check image-model access or billing, then retry.",STORAGE:"The generated artwork could not be saved to storage.",EMAIL:"The posts were created, but email delivery failed. Retry to send the existing content.",INTERNAL:"An internal generation step failed. Retry once; if it persists, review the server log."};
export default async function SocialMarketingPage({ searchParams }: { searchParams: Promise<{ result?: string;stage?:string }> }) {
  await requirePermission("marketing.content.view"); const { result,stage } = await searchParams;
  const [items,readiness] = await Promise.all([prisma.socialContent.findMany({ orderBy: [{ contentDate: "desc" }, { createdAt: "desc" }], take: 80 }),socialGenerationReadiness()]);
  return <AdminPage title="Social media" description="Four branded, human-sounding posts are prepared every day and emailed for manual publishing." actions={<Link className="text-sm font-semibold text-sky-700" href="/admin/marketing/settings">Settings</Link>}>
    {result === "generated" ? <p className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">Today’s four posts were created and emailed.</p> : null}
    {result === "already-generated" ? <p className="rounded-lg bg-sky-50 p-3 text-sm text-sky-800">Today’s content already exists, so nothing was repeated.</p> : null}
    {result === "failed" ? <p className="rounded-lg bg-red-50 p-3 text-sm text-red-800"><strong>Generation failed at {stage?.replaceAll("_"," ").toLowerCase()??"an internal step"}.</strong> {failures[stage??"INTERNAL"]??failures.INTERNAL}</p> : null}
    <Panel title="Generation readiness" description="Credentials remain server-side; this only confirms whether each required setting is present."><div className="grid gap-2 sm:grid-cols-4">{Object.entries({Recipient:readiness.recipient,OpenAI:readiness.openai,Storage:readiness.storage,Email:readiness.email}).map(([label,ready])=><div className={`rounded-lg border p-3 text-sm font-bold ${ready?"border-emerald-200 bg-emerald-50 text-emerald-800":"border-red-200 bg-red-50 text-red-800"}`} key={label}>{label}: {ready?"Ready":"Missing"}</div>)}</div></Panel>
    <Panel title="Daily content plan" description="The system always creates one useful post in each category. Product sources are rotated so recent subjects are not needlessly repeated."><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{["Product spotlight", "Current special", "Build a PC", "Gaming"].map((label, index) => <div className="rounded-lg border border-slate-200 p-4" key={label}><span className="text-xs font-black text-sky-700">POST {index + 1}</span><h3 className="mt-1 font-bold">{label}</h3></div>)}</div><form action={generateSocialContentNow} className="mt-5"><button className={buttonClass}>Generate today’s posts now</button></form></Panel>
    <Panel title="Content history" description="Every generated image and caption is saved here, including extra social posts created for blog insights.">{items.length ? <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{items.map(item => <article className="overflow-hidden rounded-xl border border-slate-200 bg-white" key={item.id}><div className="relative aspect-square bg-slate-100"><Image src={item.imageUrl} alt={item.imageAlt} fill sizes="(max-width: 768px) 100vw, 33vw" className="object-cover"/></div><div className="p-4"><div className="flex items-center justify-between gap-2"><span className="text-xs font-black uppercase text-sky-700">{labels[item.contentType] ?? item.contentType}</span><StatusBadge value={item.emailStatus}/></div><h3 className="mt-2 font-bold">{item.title}</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-600">{item.caption}</p><div className="mt-4 flex items-center justify-between text-xs text-slate-500"><span>{item.contentDate.toLocaleDateString("en-ZA")}</span><a className="font-semibold text-sky-700" href={item.imageUrl} target="_blank" rel="noreferrer">Full-size image</a></div></div></article>)}</div> : <EmptyState title="No social content yet" description="Configure the recipient, then generate the first four posts."/>}</Panel>
  </AdminPage>;
}
