"use server";
import { randomUUID } from "crypto";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { requirePermission } from "@/domain/auth/session";
import { prisma } from "@/lib/prisma";
import { createSupabaseAdmin } from "@/lib/supabase";

const text=(max=1000)=>z.string().trim().max(max).optional();
const optionalDate=z.preprocess(value=>value===""||value===null||value===undefined?undefined:value,z.coerce.date().optional());
export async function saveGlobalSeo(formData:FormData){
  const ctx=await requirePermission("marketing.seo.edit");const schema=z.object({siteTitle:z.string().trim().min(3).max(120),titleTemplate:z.string().trim().min(3).max(120),description:z.string().trim().min(40).max(320),businessName:z.string().trim().min(2).max(120),siteUrl:z.string().url(),defaultImage:z.string().min(1),logo:z.string().min(1),twitter:text(200),facebook:text(300),linkedin:text(300),instagram:text(300),phone:text(60),email:z.string().email(),address:text(500),serviceAreas:text(500),googleVerification:text(300),bingVerification:text(300)});const data=schema.parse(Object.fromEntries(formData));await prisma.$transaction(async tx=>{for(const[key,value]of Object.entries(data))await tx.marketingSetting.upsert({where:{key:`seo.${key}`},update:{value,updatedById:ctx.user.id},create:{key:`seo.${key}`,value,updatedById:ctx.user.id}});await tx.auditLog.create({data:{actorId:ctx.user.id,action:"marketing.seo.global.update",entityType:"MarketingSetting",entityId:"global",after:data}})});revalidatePath("/", "layout");revalidatePath("/admin/marketing");
}

export async function saveEntitySeo(formData:FormData){
  const ctx=await requirePermission("marketing.seo.edit");const data=z.object({entityType:z.string().trim().min(2).max(50),entityId:z.string().trim().min(1).max(200),path:z.string().trim().startsWith("/"),title:text(120),description:text(320),canonicalUrl:text(500),openGraphTitle:text(120),openGraphDescription:text(320),openGraphImage:text(1000),twitterTitle:text(120),twitterDescription:text(320),twitterImage:text(1000),primaryKeyword:text(120),secondaryKeywords:text(1000),structuredDataType:text(80),sitemapPriority:z.coerce.number().min(0).max(1)}).parse(Object.fromEntries(formData));const flags={indexable:formData.get("indexable")==="on",followLinks:formData.get("followLinks")==="on",includeInSitemap:formData.get("includeInSitemap")==="on"};const previous=await prisma.seoRecord.findUnique({where:{entityType_entityId:{entityType:data.entityType,entityId:data.entityId}}});const record=await prisma.seoRecord.upsert({where:{entityType_entityId:{entityType:data.entityType,entityId:data.entityId}},update:{...data,...flags,title:data.title||null,description:data.description||null,canonicalUrl:data.canonicalUrl||null,openGraphTitle:data.openGraphTitle||null,openGraphDescription:data.openGraphDescription||null,openGraphImage:data.openGraphImage||null,twitterTitle:data.twitterTitle||null,twitterDescription:data.twitterDescription||null,twitterImage:data.twitterImage||null,primaryKeyword:data.primaryKeyword||null,secondaryKeywords:data.secondaryKeywords?.split(",").map(x=>x.trim()).filter(Boolean)??[],structuredDataType:data.structuredDataType||null,updatedById:ctx.user.id},create:{...data,...flags,title:data.title||null,description:data.description||null,canonicalUrl:data.canonicalUrl||null,openGraphTitle:data.openGraphTitle||null,openGraphDescription:data.openGraphDescription||null,openGraphImage:data.openGraphImage||null,twitterTitle:data.twitterTitle||null,twitterDescription:data.twitterDescription||null,twitterImage:data.twitterImage||null,primaryKeyword:data.primaryKeyword||null,secondaryKeywords:data.secondaryKeywords?.split(",").map(x=>x.trim()).filter(Boolean)??[],structuredDataType:data.structuredDataType||null,createdById:ctx.user.id,updatedById:ctx.user.id}});await prisma.auditLog.create({data:{actorId:ctx.user.id,action:"marketing.seo.entity.update",entityType:"SeoRecord",entityId:record.id,before:previous?{title:previous.title,description:previous.description,indexable:previous.indexable}:undefined,after:{entityType:data.entityType,entityId:data.entityId,title:data.title,indexable:flags.indexable}}});revalidatePath(data.path);revalidatePath("/sitemap.xml");
}

function validPath(value:string){if(!value.startsWith("/")||value.startsWith("//")||value.includes("://")||value.startsWith("/admin")||value.startsWith("/account")||value.startsWith("/api"))throw new Error("Use a safe public path beginning with /.");return value}
export async function createRedirect(formData:FormData){const ctx=await requirePermission("marketing.redirects.manage");const data=z.object({sourcePath:z.string(),targetPath:z.string(),type:z.enum(["PERMANENT","TEMPORARY"])}).parse(Object.fromEntries(formData));const sourcePath=validPath(data.sourcePath);const targetPath=validPath(data.targetPath);if(sourcePath===targetPath)throw new Error("A redirect cannot point to itself.");const reverse=await prisma.redirectRule.findFirst({where:{sourcePath:targetPath,targetPath:sourcePath,isActive:true}});if(reverse)throw new Error("This redirect would create a loop.");const redirect=await prisma.redirectRule.upsert({where:{sourcePath},update:{targetPath,type:data.type,isActive:true,updatedById:ctx.user.id},create:{sourcePath,targetPath,type:data.type,createdById:ctx.user.id,updatedById:ctx.user.id}});await prisma.auditLog.create({data:{actorId:ctx.user.id,action:"marketing.redirect.save",entityType:"RedirectRule",entityId:redirect.id,after:{sourcePath,targetPath,type:data.type}}});revalidatePath("/admin/marketing/redirects")}
export async function toggleRedirect(formData:FormData){const ctx=await requirePermission("marketing.redirects.manage");const id=z.string().uuid().parse(formData.get("id"));const row=await prisma.redirectRule.findUniqueOrThrow({where:{id}});await prisma.redirectRule.update({where:{id},data:{isActive:!row.isActive,updatedById:ctx.user.id}});revalidatePath("/admin/marketing/redirects")}

export async function saveMarketingBlock(formData:FormData){const ctx=await requirePermission("marketing.content.edit");const data=z.object({id:z.string().uuid().optional().or(z.literal("")),key:z.string().trim().regex(/^[a-z0-9-]+$/),location:z.enum(["HOMEPAGE_TOP","HOMEPAGE_CONTENT","ANNOUNCEMENT"]),type:z.enum(["HERO","ANNOUNCEMENT","CTA","RICH_TEXT"]),title:text(160),heading:z.string().trim().min(3).max(160),body:z.string().trim().min(3).max(2000),buttonLabel:text(60),buttonLink:text(500),desktopImage:text(1000),mobileImage:text(1000),altText:text(300),displayOrder:z.coerce.number().int().min(0).max(1000),startsAt:optionalDate,endsAt:optionalDate,status:z.enum(["DRAFT","IN_REVIEW","APPROVED","SCHEDULED","PUBLISHED","EXPIRED","ARCHIVED"])}).parse(Object.fromEntries(formData));if(["APPROVED","SCHEDULED","PUBLISHED"].includes(data.status))await requirePermission("marketing.content.publish");if(data.buttonLink)validPath(data.buttonLink);const content={heading:data.heading,body:data.body,buttonLabel:data.buttonLabel||null,buttonLink:data.buttonLink||null,desktopImage:data.desktopImage||null,mobileImage:data.mobileImage||null,altText:data.altText||data.heading};await prisma.$transaction(async tx=>{const existing=data.id?await tx.marketingBlock.findUnique({where:{id:data.id}}):null;const block=existing?await tx.marketingBlock.update({where:{id:existing.id},data:{key:data.key,location:data.location,type:data.type,title:data.title||null,content,status:data.status,displayOrder:data.displayOrder,startsAt:data.startsAt,endsAt:data.endsAt,publishedAt:data.status==="PUBLISHED"?new Date():existing.publishedAt,updatedById:ctx.user.id}}):await tx.marketingBlock.create({data:{key:data.key,location:data.location,type:data.type,title:data.title||null,content,status:data.status,displayOrder:data.displayOrder,startsAt:data.startsAt,endsAt:data.endsAt,publishedAt:data.status==="PUBLISHED"?new Date():null,createdById:ctx.user.id,updatedById:ctx.user.id}});const version=await tx.marketingBlockVersion.count({where:{marketingBlockId:block.id}})+1;await tx.marketingBlockVersion.create({data:{marketingBlockId:block.id,version,snapshot:JSON.parse(JSON.stringify({content,status:data.status,displayOrder:data.displayOrder})),createdById:ctx.user.id}});await tx.auditLog.create({data:{actorId:ctx.user.id,action:"marketing.block.save",entityType:"MarketingBlock",entityId:block.id,before:existing?{status:existing.status,content:existing.content}:undefined,after:{status:data.status,content}}})});revalidatePath("/");revalidatePath("/admin/marketing/homepage")}

export async function uploadMarketingMedia(formData:FormData){const ctx=await requirePermission("marketing.media.manage");const data=z.object({altText:z.string().trim().min(3).max(300),title:text(150),caption:text(500),isSocialImage:z.string().optional()}).parse(Object.fromEntries(formData));const file=formData.get("file");if(!(file instanceof File)||!file.size||file.size>8*1024*1024||!["image/jpeg","image/png","image/webp","image/svg+xml"].includes(file.type))throw new Error("Upload a JPG, PNG, WebP or SVG smaller than 8 MB.");const bucket=process.env.SUPABASE_PUBLIC_BUCKET??"product-images";const supabase=createSupabaseAdmin();if(!(await supabase.storage.getBucket(bucket)).data){const made=await supabase.storage.createBucket(bucket,{public:true,fileSizeLimit:8*1024*1024});if(made.error)throw made.error}const safe=file.name.toLowerCase().replace(/[^a-z0-9._-]/g,"-");const path=`marketing/${new Date().getFullYear()}/${randomUUID()}-${safe}`;const uploaded=await supabase.storage.from(bucket).upload(path,file,{contentType:file.type,upsert:false});if(uploaded.error)throw uploaded.error;const publicUrl=supabase.storage.from(bucket).getPublicUrl(path).data.publicUrl;await prisma.mediaAsset.create({data:{bucket,path,publicUrl,title:data.title||null,altText:data.altText,caption:data.caption||null,mimeType:file.type,size:file.size,isSocialImage:data.isSocialImage==="on",createdById:ctx.user.id}});revalidatePath("/admin/marketing/media")}
