import { brand } from "@/config/brand";

export type MarketingResource={slug:string;title:string;summary:string;audience:string;sections:Array<{heading:string;body:string;points?:string[]}>};

export const marketingResources:MarketingResource[]=[
  {slug:"brand-standards",title:"Innozanzi Brand Standards",summary:"The identity, logo, colours, voice and non-negotiable brand rules.",audience:"Designers, agencies, employees and marketing partners",sections:[
    {heading:"Brand idea",body:brand.positioning,points:["Official customer-facing name: Innozanzi Shop","Legal name: Innozanzi (Pty) Ltd","Primary domain: shop.innozanzi.co.za","Core line: Technology people who listen"]},
    {heading:"Visual identity",body:"Use the supplied Innozanzi logo without redrawing, stretching, recolouring or placing it on a background that reduces contrast.",points:["Primary navy: #071B33","Commerce blue: #0A6ED1","Sky accent: #38BDF8","White: #FFFFFF","Body slate: #475569","Keep clear space around the logo equal to the height of the I symbol"]},
    {heading:"Voice",body:"Sound knowledgeable, direct and human. Explain what the product does and help the customer move forward.",points:["Talk about products before company claims","Use short sentences and specific actions","Never invent specifications, discounts, stock, delivery dates or performance","Avoid unsupported best, biggest, unbeatable and competitor comparisons","Never sound like a generic everything-store"]},
  ]},
  {slug:"company-story-positioning",title:"Company Story & Positioning",summary:"Who Innozanzi is, why it exists and why customers should choose it.",audience:"Marketing, media, partners and new employees",sections:[
    {heading:"Who we are",body:"Innozanzi is a South African specialist technology store for computers, laptops, PC components, gaming gear, servers, networking, storage, power and useful connected technology."},
    {heading:"Why we exist",body:"Technology buying becomes difficult when customers face model numbers, compatibility questions and unclear choices. We turn that into a guided journey from discovery to secure checkout and delivery tracking."},
    {heading:"What makes us different",body:"Our differentiation is specialist focus plus software-led shopping.",points:["A focused technology catalogue—not an everything-store","A guided Build a PC workspace using real products","Customer-owned PC projects that can continue over time","A dedicated gaming discovery experience","Human product and after-sales support","Secure online payment, bank transfer and order tracking"]},
    {heading:"Founder statement",body:`${brand.founder.name}, ${brand.founder.title}: Innozanzi was built from a practical love of computers and software. The goal is a specialist store where the product, guidance and digital experience work together.`},
  ]},
  {slug:"product-experience-playbook",title:"Product & Experience Playbook",summary:"What we sell and how to communicate the shop, Gaming and Build a PC experiences.",audience:"Sales, content, performance marketing and customer care",sections:[
    {heading:"Core product worlds",body:"Lead with the customer need, then the category.",points:["Computers and laptops: work, study, creation and everyday use","PC components: processors, motherboards, memory, storage, graphics, power, cooling and cases","Gaming: machines, upgrades, displays, peripherals and complete setups","Infrastructure: servers, networking, security, storage and backup power","Everyday technology: mobile accessories, smart devices, cables and practical electronics"]},
    {heading:"Build a PC",body:"Market this as a guided project—not a parts filter.",points:["Name and save a build to a customer account","Choose components step by step","See current customer pricing and availability","Review the complete machine","Buy the full build or selected components over time","Return to the project and track what remains"]},
    {heading:"Gaming",body:"Gaming is its own focused discovery zone while remaining recognisably Innozanzi. Sell outcomes: smoother play, the right performance tier, useful upgrades and a complete setup."},
    {heading:"Catalogue discipline",body:"A product belongs in a campaign when it fits the audience, has a clear image, accurate product facts, current availability and a useful reason to buy. Do not advertise weak products merely because they exist in the feed."},
  ]},
  {slug:"marketing-manager-brief",title:"Marketing Manager Brief",summary:"The commercial mandate, priorities, measures and working rules for whoever owns growth.",audience:"Marketing manager, agency lead or growth partner",sections:[
    {heading:"Mandate",body:"Grow qualified traffic and completed sales by making Innozanzi the specialist technology destination customers remember when they need a computer, laptop, PC build, gaming setup or supporting technology."},
    {heading:"Priority campaigns",body:"Focus investment where the store is most differentiated.",points:["Build your own PC and progressive PC projects","Gaming computers, components and complete setups","Laptops and ready-built computers","High-intent component and upgrade searches","Supplier promotions, unboxed and last-chance collections","Servers, networking, storage and backup power for specialist demand"]},
    {heading:"Success measures",body:"Report by channel and campaign every week.",points:["Qualified sessions and product-detail views","Search-to-product engagement","Add-to-cart and checkout-start rate","Completed and paid orders","Customer acquisition cost and return on ad spend","PC projects created, resumed and converted","Email revenue and unsubscribe rate","Organic impressions, ranking pages and non-brand clicks"]},
    {heading:"Operating rules",body:"Use real catalogue data and approved assets. Confirm landing pages, stock, price, tracking and mobile quality before launch. Pause campaigns that send customers to unavailable or irrelevant products."},
  ]},
  {slug:"channel-campaign-guide",title:"Paid & Social Channel Guide",summary:"How Facebook, Instagram, TikTok and Google should work together.",audience:"Paid media, social media and creative teams",sections:[
    {heading:"Google",body:"Capture existing intent.",points:["Search campaigns for computers, laptops, components, gaming PCs and Build a PC","Shopping/product ads only where feed data, prices and availability are current","Dedicated landing pages matching every ad group","Brand search protection and remarketing to product or project visitors"]},
    {heading:"Facebook & Instagram",body:"Create desire and bring customers back.",points:["Carousel collections for promotions and categories","Short Build a PC demonstrations","Gaming setup and upgrade stories","Dynamic retargeting for viewed products and abandoned carts","Use clean product imagery and one action per advert"]},
    {heading:"TikTok",body:"Teach and entertain quickly.",points:["Build progress and component-selection clips","Simple comparisons without attacking competitors","What this upgrade changes","Gaming performance tiers explained","Founder and team knowledge in a natural human voice"]},
    {heading:"Campaign safety",body:"Never advertise an unverified price, specification, discount, delivery promise or stock quantity. Use UTM parameters, conversion events and campaign naming consistently."},
  ]},
  {slug:"seo-content-framework",title:"SEO & Content Framework",summary:"The search themes, page intent and editorial standards for organic growth.",audience:"SEO, editorial, merchandising and development teams",sections:[
    {heading:"Primary search themes",body:"Own specialist technology intent in South Africa.",points:["computer shop South Africa","buy laptops online South Africa","custom PC builder South Africa","gaming PC and gaming components","computer components and upgrades","servers and networking equipment","backup power and storage"]},
    {heading:"Page roles",body:"Every indexed page needs one clear job.",points:["Homepage: establish specialist positioning and route demand","Category: satisfy a product family intent","Product: answer product-specific purchase questions","Build a PC: convert custom-build intent","Gaming: convert gaming discovery intent","Guides: answer questions and link to the next commercial action","About: establish expertise, trust and company story"]},
    {heading:"Editorial standard",body:"Use accurate product names, descriptive headings, internal links, useful alt text and concise South African context. Avoid keyword stuffing, duplicated copy and claims that cannot be proven."},
  ]},
];

const escape=(value:string)=>value.replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char]!);
export function renderMarketingResource(resource:MarketingResource){const date=new Date().toLocaleDateString("en-ZA",{day:"2-digit",month:"long",year:"numeric"});return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${escape(resource.title)}</title><style>@page{margin:18mm}*{box-sizing:border-box}body{margin:0;font-family:Arial,sans-serif;color:#172b3a;line-height:1.55}header{border-bottom:4px solid #0a6ed1;padding:0 0 22px}header img{width:190px;height:auto}h1{font-size:30px;margin:28px 0 8px;color:#071b33}h2{font-size:19px;margin:28px 0 8px;color:#071b33}p,li{font-size:13px}.meta{color:#64748b}.summary{font-size:16px;max-width:720px}section{break-inside:avoid}li{margin:6px 0}.signature{margin-top:42px;border-top:1px solid #cbd5e1;padding-top:18px}.signature strong{display:block;color:#071b33}footer{margin-top:40px;padding-top:14px;border-top:1px solid #cbd5e1;color:#64748b;font-size:11px}@media print{a{color:inherit;text-decoration:none}}</style></head><body><header><img src="${escape(`${brand.siteUrl}/brand/innozanzi-shop-logo-header-v2.png`)}" alt="Innozanzi Shop"><h1>${escape(resource.title)}</h1><p class="summary">${escape(resource.summary)}</p><p class="meta">Audience: ${escape(resource.audience)} · Updated ${escape(date)}</p></header>${resource.sections.map(section=>`<section><h2>${escape(section.heading)}</h2><p>${escape(section.body)}</p>${section.points?.length?`<ul>${section.points.map(point=>`<li>${escape(point)}</li>`).join("")}</ul>`:""}</section>`).join("")}<div class="signature"><strong>${escape(brand.founder.name)}</strong><span>${escape(brand.founder.title)}<br>${escape(brand.legalName)}</span></div><footer>${escape(brand.shopName)} · ${escape(brand.siteUrl)} · ${escape(brand.contact.email)}<br>Controlled marketing resource. Verify product, price and availability data before publishing.</footer></body></html>`}
