import { brand, companyIdentity } from "@/config/brand";

export type MarketingResource={slug:string;title:string;summary:string;audience:string;sections:Array<{heading:string;body:string;points?:string[]}>};

export const marketingResources:MarketingResource[]=[
  {slug:"brand-standards",title:"Innozanzi Brand Standards",summary:"The identity, logo, colours, voice and non-negotiable brand rules.",audience:"Designers, agencies, employees and marketing partners",sections:[
    {heading:"Brand foundation",body:brand.positioning,points:["Official customer-facing name: Innozanzi Shop","Legal name: Innozanzi (Pty) Ltd","Primary domain: shop.innozanzi.co.za",`Core expression: ${brand.tagline}`,`Purpose: ${companyIdentity.purpose}`]},
    {heading:"Visual identity",body:"Use the supplied Innozanzi logo without redrawing, stretching, recolouring or placing it on a background that reduces contrast.",points:["Primary navy: #071B33","Commerce blue: #0A6ED1","Sky accent: #38BDF8","White: #FFFFFF","Body slate: #475569","Keep clear space around the logo equal to the height of the I symbol"]},
    {heading:"Voice",body:"Sound knowledgeable, direct and human. Explain what the product does and help the customer move forward.",points:["Talk about products before company claims","Use short sentences and specific actions","Never invent specifications, discounts, stock, delivery dates or performance","Avoid unsupported best, biggest, unbeatable and competitor comparisons","Never sound like a generic everything-store"]},
    {heading:"Brand personality",body:"Every touchpoint should feel modern, technical, clean, confident, premium, human and accessible.",points:["Knowledgeable without making customers feel inexperienced","Confident without exaggerated claims","Modern because the experience is useful—not because it uses fashionable effects","Technical while remaining understandable","Fast, but never careless with facts or customer money","Ambitious while disciplined about trust and execution"]},
    {heading:"Message hierarchy",body:"Begin with the customer need, explain the useful difference, then offer one clear next action.",points:["Need: what the customer is trying to accomplish","Proof: the product, software experience or service that helps","Trust: current price, availability, payment and fulfilment clarity","Action: shop, build, compare, ask or continue an order","Never repeat the same company paragraph across every campaign"]},
    {heading:"Accessibility and consistency",body:"Brand quality includes how easily people can read, navigate and understand the material.",points:["Maintain strong contrast and readable type sizes","Keep logo proportions and clear space intact","Use accurate headings and descriptive link labels","Design mobile-first, then strengthen larger layouts","Use the same legal name, founder name, purpose and promise from the controlled brand source"]},
  ]},
  {slug:"company-story-positioning",title:"Company Story & Positioning",summary:"Who Innozanzi is, why it exists and why customers should choose it.",audience:"Marketing, media, partners and new employees",sections:[
    {heading:"Who we are",body:"Innozanzi is a South African technology company combining specialist retail, software engineering and hands-on service. We serve people and businesses buying computers, laptops, components, gaming technology, servers, networking, storage, power and useful connected products."},
    {heading:"Why we exist",body:companyIdentity.purpose,points:["Technology is essential but purchasing it can still be confusing","Compatibility mistakes are expensive and avoidable","Customers deserve useful advice before payment and clear communication afterwards","A catalogue should help people reach an outcome rather than overwhelm them with products"]},
    {heading:"Founder story",body:`${brand.founder.name} founded Innozanzi after years in software development, progressing to senior software developer while remaining a technology enthusiast and customer. That combination revealed an opportunity: use engineering thinking to improve the problems people experience when choosing and buying technology.`},
    {heading:"The problem we are solving",body:"A processor, motherboard, memory kit, power supply or case can look right independently and still fail as part of a complete build. The same uncertainty appears when choosing a development laptop, business infrastructure or a meaningful upgrade. Innozanzi helps customers understand the decision before committing their money."},
    {heading:"What makes our approach different",body:"Products can be copied. The experience surrounding them is harder to copy.",points:["Specialist product selection with clearer paths into each need","A guided Build a PC workspace using real products","Customer-owned PC projects that can continue over time","A dedicated gaming discovery experience","Intelligent product discovery and practical explanations","Secure Paystack and bank-transfer options","Order visibility and human support beyond payment"]},
    {heading:"Purpose, mission and vision",body:companyIdentity.mission,points:[`Purpose: ${companyIdentity.purpose}`,`Vision: ${companyIdentity.vision}`,`Customer promise: ${companyIdentity.customerPromise}`]},
    {heading:"Service philosophy",body:"Every order represents a person or business trusting Innozanzi with money and an important need. Success is not only how many orders arrive; it is how well each order is handled through sourcing, communication, fulfilment and delivery."},
    {heading:"The next technology cycle",body:"AI is changing what developers, creators, students, businesses and everyday customers need from computers. Innozanzi can become a place where people understand whether a machine can support their work, which upgrade matters and what infrastructure fits—then obtain it through the same experience."},
  ]},
  {slug:"product-experience-playbook",title:"Product & Experience Playbook",summary:"What we sell and how to communicate the shop, Gaming and Build a PC experiences.",audience:"Sales, content, performance marketing and customer care",sections:[
    {heading:"Core product worlds",body:"Lead with the customer need, then the category.",points:["Computers and laptops: work, study, creation and everyday use","PC components: processors, motherboards, memory, storage, graphics, power, cooling and cases","Gaming: machines, upgrades, displays, peripherals and complete setups","Infrastructure: servers, networking, security, storage and backup power","Everyday technology: mobile accessories, smart devices, cables and practical electronics"]},
    {heading:"Build a PC",body:"Market this as a guided project—not a parts filter.",points:["Name and save a build to a customer account","Choose components step by step","See current customer pricing and availability","Review the complete machine","Buy the full build or selected components over time","Return to the project and track what remains"]},
    {heading:"Gaming",body:"Gaming is its own focused discovery zone while remaining recognisably Innozanzi. Sell outcomes: smoother play, the right performance tier, useful upgrades and a complete setup."},
    {heading:"Catalogue discipline",body:"A product belongs in a campaign when it fits the audience, has a clear image, accurate product facts, current availability and a useful reason to buy. Do not advertise weak products merely because they exist in the feed."},
    {heading:"Customer decision framework",body:"Translate specifications into the decision a customer needs to make.",points:["Work and study: portability, battery, memory and everyday reliability","Development and AI: processor, memory, graphics capability, storage and upgrade path","Gaming: target resolution, performance tier, display and balanced components","Business infrastructure: workload, scale, continuity, security and support","Upgrades: compatibility, measurable benefit and whether replacement is better value"]},
    {heading:"Service after selection",body:"The product journey continues after Add to cart.",points:["Show the complete price and applicable delivery fee before payment","Recheck supplier availability when the order is placed","Notify customers when the order stage changes","Escalate exceptions early and communicate what happens next","Keep returns, assistance and order tracking easy to find"]},
  ]},
  {slug:"marketing-manager-brief",title:"Marketing Manager Brief",summary:"The commercial mandate, priorities, measures and working rules for whoever owns growth.",audience:"Marketing manager, agency lead or growth partner",sections:[
    {heading:"Mandate",body:"Grow qualified traffic and completed sales by making Innozanzi the specialist technology destination customers remember when they need a computer, laptop, PC build, gaming setup or supporting technology."},
    {heading:"Priority campaigns",body:"Focus investment where the store is most differentiated.",points:["Build your own PC and progressive PC projects","Gaming computers, components and complete setups","Laptops and ready-built computers","High-intent component and upgrade searches","Supplier promotions, unboxed and last-chance collections","Servers, networking, storage and backup power for specialist demand"]},
    {heading:"Success measures",body:"Report by channel and campaign every week.",points:["Qualified sessions and product-detail views","Search-to-product engagement","Add-to-cart and checkout-start rate","Completed and paid orders","Customer acquisition cost and return on ad spend","PC projects created, resumed and converted","Email revenue and unsubscribe rate","Organic impressions, ranking pages and non-brand clicks"]},
    {heading:"Operating rules",body:"Use real catalogue data and approved assets. Confirm landing pages, stock, price, tracking and mobile quality before launch. Pause campaigns that send customers to unavailable or irrelevant products."},
    {heading:"First 90 days",body:"Build a measurable acquisition foundation before increasing spend.",points:["Weeks 1–2: validate analytics, conversion events, catalogue health and landing pages","Weeks 3–4: launch narrow high-intent search and remarketing tests","Month 2: expand winning product, PC Build and gaming themes","Month 3: strengthen lifecycle email, organic guides and returning-customer campaigns","Document each test, result, decision and next action"]},
    {heading:"Customer and brand safeguards",body:"Growth never outranks trust.",points:["Do not promote unavailable products simply to attract traffic","Do not disguise supplier offers as Innozanzi-created discounts","Do not publish AI-written facts without human verification","Do not use urgency unless the promotion or stock evidence supports it","Do not collect customer data without a clear purpose and lawful handling"]},
    {heading:"Weekly commercial review",body:"The marketing owner should connect channel data to actual customer and operational outcomes.",points:["Which campaigns produced paid orders—not only clicks?","Which searches ended without a useful result?","Which product pages converted or lost customers?","Were promoted orders fulfilled well and on time?","What did support questions reveal about unclear content?","What should be stopped, improved or scaled next week?"]},
  ]},
  {slug:"channel-campaign-guide",title:"Paid & Social Channel Guide",summary:"How Facebook, Instagram, TikTok and Google should work together.",audience:"Paid media, social media and creative teams",sections:[
    {heading:"Google",body:"Capture existing intent.",points:["Search campaigns for computers, laptops, components, gaming PCs and Build a PC","Shopping/product ads only where feed data, prices and availability are current","Dedicated landing pages matching every ad group","Brand search protection and remarketing to product or project visitors"]},
    {heading:"Facebook & Instagram",body:"Create desire and bring customers back.",points:["Carousel collections for promotions and categories","Short Build a PC demonstrations","Gaming setup and upgrade stories","Dynamic retargeting for viewed products and abandoned carts","Use clean product imagery and one action per advert"]},
    {heading:"TikTok",body:"Teach and entertain quickly.",points:["Build progress and component-selection clips","Simple comparisons without attacking competitors","What this upgrade changes","Gaming performance tiers explained","Founder and team knowledge in a natural human voice"]},
    {heading:"Campaign safety",body:"Never advertise an unverified price, specification, discount, delivery promise or stock quantity. Use UTM parameters, conversion events and campaign naming consistently."},
    {heading:"Creative system",body:"Use campaigns that are visually consistent but adapted to the reason someone uses each channel.",points:["Lead with one strong product family, problem or outcome","Use supplier assets only when they are clear, current and properly licensed","Create collection artwork for broad promotions rather than forcing a low-value single product into a hero","Keep logo placement, typography and action labels consistent","Build desktop, square, portrait and story variants from the same approved message"]},
    {heading:"Lifecycle and retargeting",body:"A customer should receive a useful next step rather than the same advert repeatedly.",points:["Product viewer: return to the product or see a relevant alternative","Cart starter: resume checkout with current price and stock context","PC project owner: continue the saved build","Gaming visitor: explore the matching performance tier","Past customer: accessories, upgrades, support or replenishment based on the purchase"]},
    {heading:"Channel measurement",body:"Use comparable definitions across every platform.",points:["Track view, search, product engagement, add to cart, checkout, payment and order completion","Report spend, revenue, acquisition cost and return by campaign","Separate new and returning customers","Review assisted conversions instead of crediting only the last click","Investigate tracking gaps before making budget decisions"]},
  ]},
  {slug:"seo-content-framework",title:"SEO & Content Framework",summary:"The search themes, page intent and editorial standards for organic growth.",audience:"SEO, editorial, merchandising and development teams",sections:[
    {heading:"Primary search themes",body:"Own specialist technology intent in South Africa.",points:["computer shop South Africa","buy laptops online South Africa","custom PC builder South Africa","gaming PC and gaming components","computer components and upgrades","servers and networking equipment","backup power and storage"]},
    {heading:"Page roles",body:"Every indexed page needs one clear job.",points:["Homepage: establish specialist positioning and route demand","Category: satisfy a product family intent","Product: answer product-specific purchase questions","Build a PC: convert custom-build intent","Gaming: convert gaming discovery intent","Guides: answer questions and link to the next commercial action","About: establish expertise, trust and company story"]},
    {heading:"Editorial standard",body:"Use accurate product names, descriptive headings, internal links, useful alt text and concise South African context. Avoid keyword stuffing, duplicated copy and claims that cannot be proven."},
    {heading:"Content pillars",body:"Publish content that answers a real purchasing or ownership question.",points:["How to choose a laptop for work, study, development or creation","PC compatibility and step-by-step component selection","Gaming performance tiers and sensible upgrade paths","RAM, storage, graphics and power explained clearly","Servers, networking, backup power and continuity for growing teams","Order, delivery, returns and after-sales guidance"]},
    {heading:"Search and catalogue quality",body:"Search should help customers recover from imperfect wording rather than end the journey.",points:["Use product names, brands, SKUs, categories, specifications and common synonyms","Offer close alternatives when an exact product is unavailable","Prevent unrelated products from appearing under misleading category headings","Keep canonical URLs, structured data, social metadata and sitemap entries current","Remove or redirect obsolete pages deliberately rather than creating dead ends"]},
    {heading:"Editorial workflow",body:"Every article and landing page requires a clear owner and review date.",points:["Confirm the customer question and search intent","Use verified product and technical sources","Write a concise answer before expanding detail","Link to the relevant product, category, PC Build or support action","Review claims, spelling, mobile layout and metadata before publishing","Refresh or retire content when products and technology change"]},
  ]},
];

const escape=(value:string)=>value.replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char]!);
export function renderMarketingResource(resource:MarketingResource){const date=new Date().toLocaleDateString("en-ZA",{day:"2-digit",month:"long",year:"numeric"});return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${escape(resource.title)}</title><style>@page{size:A4;margin:16mm 17mm}*{box-sizing:border-box}body{margin:0;font-family:Arial,Helvetica,sans-serif;color:#172b3a;line-height:1.65;background:#fff}header{border-top:8px solid #071b33;border-bottom:3px solid #0a6ed1;padding:24px 0 28px}header img{display:block;width:205px;max-height:62px;object-fit:contain;object-position:left center}h1{font-size:31px;line-height:1.18;margin:30px 0 10px;color:#071b33;letter-spacing:-.4px}h2{font-size:20px;line-height:1.3;margin:0 0 10px;color:#071b33}p,li{font-size:14px}.meta{margin-top:16px;color:#64748b;font-size:12px}.summary{font-size:17px;line-height:1.6;max-width:720px;color:#334155}section{break-inside:avoid;border-bottom:1px solid #e2e8f0;padding:24px 0 20px}section p{margin:0;color:#334155}ul{margin:12px 0 0;padding-left:22px}li{margin:8px 0;padding-left:3px}.signature{margin-top:36px;border-left:4px solid #0a6ed1;background:#f8fafc;padding:18px 20px}.signature strong{display:block;font-size:15px;color:#071b33}.signature span{font-size:12px;color:#475569}footer{margin-top:34px;padding-top:14px;border-top:1px solid #cbd5e1;color:#64748b;font-size:11px}@media screen{body{max-width:850px;margin:24px auto;padding:0 38px;box-shadow:0 10px 35px rgba(7,27,51,.12)}}@media(max-width:640px){body{margin:0;padding:0 20px;box-shadow:none}h1{font-size:27px}header img{width:180px}}@media print{a{color:inherit;text-decoration:none}}</style></head><body><header><img src="${escape(`${brand.siteUrl}/brand/innozanzi-shop-logo-header-v2.png`)}" alt="Innozanzi Shop"><h1>${escape(resource.title)}</h1><p class="summary">${escape(resource.summary)}</p><p class="meta">Audience: ${escape(resource.audience)} · Updated ${escape(date)}</p></header>${resource.sections.map(section=>`<section><h2>${escape(section.heading)}</h2><p>${escape(section.body)}</p>${section.points?.length?`<ul>${section.points.map(point=>`<li>${escape(point)}</li>`).join("")}</ul>`:""}</section>`).join("")}<div class="signature"><strong>${escape(brand.founder.name)}</strong><span>${escape(brand.founder.title)}<br>${escape(brand.legalName)}</span></div><footer>${escape(brand.shopName)} · ${escape(brand.siteUrl)} · ${escape(brand.contact.email)}<br>Controlled marketing resource. Verify product, price and availability data before publishing.</footer></body></html>`}
