import { setProductTesterAccess } from "@/domain/mobile-admin/tester-actions";
import { requireMobileAdmin } from "@/domain/auth/session";
import { prisma } from "@/lib/prisma";

export default async function MobileTesters({searchParams}:{searchParams:Promise<{q?:string}>}){
  await requireMobileAdmin();
  const query=(await searchParams).q?.trim()??"";
  const users=await prisma.user.findMany({where:{deletedAt:null,...(query?{OR:[{name:{contains:query,mode:"insensitive"}},{email:{contains:query,mode:"insensitive"}}]}:{})},select:{id:true,name:true,email:true,accountType:true,status:true,roles:{where:{role:{slug:"product-tester"}},select:{roleId:true}}},orderBy:[{name:"asc"},{email:"asc"}],take:100});
  return <><h1 className="text-3xl font-black text-[#071b33]">Product testers</h1><p className="mt-1 text-sm leading-6 text-slate-500">Grant selected clients or team members access to private testing products. This does not give them admin access.</p><form className="mt-5 flex gap-2"><input className="min-h-12 min-w-0 flex-1 rounded-xl border border-slate-300 bg-white px-4" defaultValue={query} name="q" placeholder="Search name or email"/><button className="min-h-12 rounded-xl bg-[#071b33] px-5 text-sm font-bold text-white">Search</button></form><div className="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{users.length?users.map(user=>{const enabled=user.roles.length>0;return <div className="flex items-center justify-between gap-3 border-b border-slate-100 p-4 last:border-0" key={user.id}><div className="min-w-0"><p className="truncate text-sm font-bold text-slate-900">{user.name??"Unnamed user"}</p><p className="truncate text-xs text-slate-500">{user.email}</p><p className="mt-1 text-[10px] font-bold uppercase text-slate-400">{user.accountType.replaceAll("_"," ")} · {user.status.replaceAll("_"," ")}</p></div><form action={setProductTesterAccess}><input name="userId" type="hidden" value={user.id}/><input name="enabled" type="hidden" value={String(!enabled)}/><button className={`min-h-11 shrink-0 rounded-xl px-4 text-xs font-black ${enabled?"border border-rose-200 bg-rose-50 text-rose-700":"bg-sky-700 text-white"}`}>{enabled?"Remove":"Grant access"}</button></form></div>}):<p className="p-6 text-center text-sm text-slate-500">No users match this search.</p>}</div></>;
}
