ALTER TABLE "PcProject"
ADD COLUMN "intendedUse" TEXT NOT NULL DEFAULT 'BALANCED',
ADD COLUMN "performanceTarget" TEXT NOT NULL DEFAULT 'SMOOTH',
ADD COLUMN "gamePreferences" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
