import Link from "next/link";
import type { QuotationOrigin } from "@/generated/prisma/enums";
import { AdminPage, MetricCard, Panel, StatusBadge, buttonClass, inputClass, secondaryButtonClass, tableClass } from "@/components/admin/admin-ui";
import { requirePermission } from "@/domain/auth/session";
import { createQuotation, setDefaultQuotationMarkup } from "@/domain/quotations/actions";
import { prisma } from "@/lib/prisma";

export default async function Page({ searchParams }: { searchParams: Promise<{ origin?: string; status?: string; q?: string }> }) {
  await requirePermission("quotations.manage");
  const params = await searchParams;
  const origins: QuotationOrigin[] = ["CUSTOMER_REQUEST","MANUAL","PARTNER"];
  const origin = origins.includes(params.origin as QuotationOrigin) ? params.origin as QuotationOrigin : undefined;
  const query = params.q?.trim() ?? "";
  const [quotes, unprepared, setting] = await Promise.all([
    prisma.quotation.findMany({ where: { ...(origin?{origin}:{}), ...(params.status?{status:params.status as never}:{}), ...(query?{OR:[{quotationNumber:{contains:query,mode:"insensitive"}},{quotationRequest:{email:{contains:query,mode:"insensitive"}}},{quotationRequest:{companyName:{contains:query,mode:"insensitive"}}}]}:{}) }, include: { quotationRequest: true, _count: { select: { items: true } } }, orderBy: { createdAt: "desc" }, take: 150 }),
    prisma.quotationRequest.findMany({ where: { quotations: { none: {} } }, include: { _count: { select: { items: true } } }, orderBy: { createdAt: "desc" }, take: 30 }),
    prisma.siteSetting.findUnique({ where: { key: "quotation.defaultMarkupPercent" } }),
  ]);
  return <AdminPage title="Quotation operations" description="One register for customer, partner and manually captured quotations from preparation through payment." actions={<Link className={buttonClass} href="/admin/quotations/new">Create manual quotation</Link>}>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Customer generated" value={quotes.filter(x=>x.origin==="CUSTOMER_REQUEST").length}/><MetricCard label="Manual" value={quotes.filter(x=>x.origin==="MANUAL").length}/><MetricCard label="Awaiting review" value={quotes.filter(x=>["PROVISIONAL_GENERATED","PENDING_APPROVAL","UNDER_REVIEW"].includes(x.status)).length}/><MetricCard label="Awaiting payment" value={quotes.filter(x=>x.status==="SENT").length}/></div>
    <Panel title="Find quotations"><form className="flex flex-wrap items-end gap-3"><label className="min-w-64 flex-1 text-xs font-semibold">Search<input className={`${inputClass} mt-1 w-full`} name="q" defaultValue={query} placeholder="Quotation, company or email"/></label><label className="text-xs font-semibold">Origin<select className={`${inputClass} mt-1`} name="origin" defaultValue={origin??""}><option value="">All origins</option>{origins.map(x=><option key={x}>{x}</option>)}</select></label><label className="text-xs font-semibold">Status<select className={`${inputClass} mt-1`} name="status" defaultValue={params.status??""}><option value="">All statuses</option>{["PROVISIONAL_GENERATED","PENDING_APPROVAL","UNDER_REVIEW","SENT","PAYMENT_SUBMITTED","PAYMENT_VERIFIED","ACCEPTED","REJECTED","EXPIRED","CANCELLED"].map(x=><option key={x}>{x}</option>)}</select></label><button className={buttonClass}>Filter</button><Link className={secondaryButtonClass} href="/admin/quotations">Clear</Link></form></Panel>
    {unprepared.length?<Panel title="Requests needing a provisional quotation" description="Customer requests appear here until pricing is prepared."><div className="space-y-2">{unprepared.map(request=><div className="flex flex-wrap items-center justify-between gap-3 border-b py-2" key={request.id}><p className="text-sm"><strong>{request.requestNumber}</strong> · {request.companyName??request.contactName} · {request._count.items} item(s)</p><form action={createQuotation} className="flex gap-2"><input type="hidden" name="requestId" value={request.id}/><input className={`${inputClass} w-20`} name="markupPercent" type="number" defaultValue="5"/><button className={buttonClass}>Prepare provisional</button></form></div>)}</div></Panel>:null}
    <Panel title="Quotation register"><div className="-mx-4 overflow-x-auto"><table className={tableClass}><thead><tr><th>Quotation</th><th>Origin</th><th>Customer</th><th>Items</th><th>Total</th><th>Status</th><th></th></tr></thead><tbody>{quotes.map(quote=><tr key={quote.id}><td><strong>{quote.quotationNumber}</strong><br/><span className="text-xs text-slate-500">v{quote.version} · {quote.createdAt.toLocaleDateString("en-ZA")}</span></td><td><span className="text-xs font-bold">{quote.origin.replaceAll("_"," ")}</span></td><td>{quote.quotationRequest?.companyName??quote.quotationRequest?.contactName??"Customer"}<br/><span className="text-xs text-slate-500">{quote.quotationRequest?.email}</span></td><td>{quote._count.items}</td><td className="font-semibold">R {Number(quote.grandTotal).toLocaleString("en-ZA",{minimumFractionDigits:2})}</td><td><StatusBadge value={quote.status}/></td><td><Link className="font-semibold text-sky-700" href={`/admin/quotations/${quote.id}`}>View</Link></td></tr>)}</tbody></table></div></Panel>
    <Panel title="Provisional pricing setting"><form action={setDefaultQuotationMarkup} className="flex flex-wrap items-end gap-3"><label className="text-sm font-semibold">Default markup %<input className={`${inputClass} mt-1 w-32`} name="markupPercent" type="number" min="0" max="500" step="0.1" defaultValue={typeof setting?.value==="number"?setting.value:5}/></label><button className={buttonClass}>Save setting</button></form></Panel>
  </AdminPage>;
}
