import Image from "next/image";
import { notFound } from "next/navigation";
import { requestComboQuotation } from "@/domain/combos/actions";
import { prisma } from "@/lib/prisma";

export const dynamic="force-dynamic";
export default async function ComboDetail({params}:{params:Promise<{slug:string}>}){
  const now=new Date(),slug=(await params).slug;
  const campaign=await prisma.comboCampaign.findFirst({where:{slug,status:"ACTIVE",startsAt:{lte:now},endsAt:{gt:now},isTestData:false},include:{items:{include:{product:{include:{images:true,inventory:true}},supplierCatalogueProduct:true}}}});
  if(!campaign)notFound();
  await prisma.comboCampaignEvent.create({data:{campaignId:campaign.id,type:"VIEW",channel:"WEBSITE"}}).catch(()=>undefined);
  const saving=Number(campaign.normalPrice)-Number(campaign.comboPrice);
  const available=campaign.items.every(x=>x.supplierCatalogueProduct?x.supplierCatalogueProduct.active&&x.supplierCatalogueProduct.stock>=x.quantity:Boolean(x.product&&x.product.status==="PUBLISHED"&&x.product.inventory.reduce((n,i)=>n+Math.max(0,i.onHand-i.reserved),0)>=x.quantity));
  return <main className="mx-auto max-w-6xl px-4 py-10 sm:px-6"><div className="grid gap-8 lg:grid-cols-2"><div className="relative aspect-[4/3] overflow-hidden rounded-2xl bg-slate-100">{campaign.imageUrl?<Image src={campaign.imageUrl} alt={campaign.headline} fill sizes="50vw" className="object-contain p-6"/>:<div className="grid h-full place-items-center text-slate-500">Campaign artwork coming soon</div>}</div><section><p className="text-xs font-bold uppercase tracking-widest text-sky-700">{campaign.type} COMBO</p><h1 className="mt-2 text-4xl font-black text-[#071b33]">{campaign.headline}</h1><p className="mt-4 leading-7 text-slate-600">{campaign.description}</p><div className="mt-6 rounded-xl border border-sky-200 bg-sky-50 p-5"><p className="text-sm text-slate-500">Normal combined price <s>R {Number(campaign.normalPrice).toFixed(2)}</s></p><p className="mt-1 text-3xl font-black text-sky-800">R {Number(campaign.comboPrice).toFixed(2)}</p><p className="mt-1 font-semibold text-emerald-700">Save R {saving.toFixed(2)} ({(saving/Number(campaign.normalPrice)*100).toFixed(1)}%)</p></div><p className={`mt-4 font-semibold ${available?"text-emerald-700":"text-amber-700"}`}>{available?"Available — rechecked before quotation":"Availability requires confirmation"}</p><p className="mt-2 text-sm text-slate-500">Offer ends {campaign.endsAt.toLocaleString("en-ZA")}. No false stock reservation is made until payment approval.</p><form action={requestComboQuotation} className="mt-6"><input type="hidden" name="id" value={campaign.id}/><button disabled={!available} className="min-h-12 w-full rounded-lg bg-sky-600 px-6 font-bold text-white disabled:bg-slate-400">{campaign.callToAction}</button></form></section></div><section className="mt-12"><h2 className="text-2xl font-bold">What is included</h2><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{campaign.items.map(x=>{const manualImage=x.product?.images.find(i=>i.isPrimary)??x.product?.images[0];const image=manualImage?.path??x.supplierCatalogueProduct?.images[0];return <article className="rounded-xl border p-4" key={x.id}>{image?<div className="relative aspect-video bg-slate-50"><Image src={image} alt={manualImage?.altText??x.productName} fill sizes="33vw" className="object-contain"/></div>:null}<h3 className="mt-3 font-bold">{x.productName}</h3><p className="text-sm text-slate-500">{x.sku} · Quantity {x.quantity}</p></article>})}</div></section></main>;
}
